### ISSUE TITLE
`prefetch` initiator appears to be unused

### ISSUE THREAD

**Issue by bakkot** [whatwg/fetch#1008]
[This part of the fetch spec](https://fetch.spec.whatwg.org/#concept-request-initiator) says that requests have an associated initiator, for which one of the possible values is `prefetch` (added in https://github.com/whatwg/fetch/pull/659, so cc @yoavweiss and @annevk as the most likely people to know abou this). A table shortly below it says that `prefetch` initiator is used for "HTML’s &lt;link rel=prefetch>". But neither the [HTML spec](https://html.spec.whatwg.org/multipage/) nor the [resource hints spec](https://w3c.github.io/resource-hints/) (the only other place I could think where it would be defined) make any mention of this. The resource hints spec doesn't even mention initiators at all.

Is there somewhere else I should be looking?

**Comment by yoavweiss** [comment]
It's used in https://github.com/whatwg/html/pull/4115, which never landed, but which we should get back to.

/cc @domfarolino

**Comment by annevk** [comment]
https://w3c.github.io/webappsec-csp/ uses it as well.

**Comment by bakkot** [comment]
@annevk Sorry, by "uses" I meant that nothing creates such requests. CSP switches on request having an initiator of `prefetch`, but since nothing creates such request that part of the specification is effectively dead. (That's actually how this came up; I was trying to figure out what that part of the CSP spec did.)

**Comment by annevk** [comment]
Ah okay, so in part the history here is that browsers shipped a bunch of things without standardizing them properly and we've been slowly trying to fix that. (Another large hole here is that CSS doesn't really call into fetch.)

**Comment by annevk** [comment]
cc @noamr

**Comment by noamr** [comment]
https://github.com/whatwg/html/pull/8111 fixes this.
