### ISSUE TITLE
Inconsistent handling of response

### ISSUE THREAD

**Issue by ayZagen** [whatwg/fetch#1014]
Please have a look at the example below

```js
fetch('https://httpstat.us/500', {
    cache: 'no-cache',
    headers: {
      "AnyHeader": "value"
    }
  })
  .then(function(response) {
    if (!response.ok) {
      throw Error(response.statusText);
    }
    return response;
  }).then(function(response) {
    console.log('ok');
  }).catch(function(error) {
    // Promise rejected with TypeError: Failed to fetch
    console.log(error);
  });
```
If we remove the `AnyHeader` header the promise will not be rejected.

**Comment by ayZagen** [comment]
Sorry wrong place for the issue

**Comment by annevk** [comment]
I suspect the server does not support CORS preflights (or does not support that particular header). When all browsers behave the same, the place to go is StackOverflow generally. If they don't, please do come here!

**Comment by ayZagen** [comment]
Actually it supports CORS and if you have tried the example with and without the headers you would have see the difference. The behavior is the same when we add `mode: 'cors'` option. Even if the server doesn't support the CORS why would the handling of the request vary because of the change in headers? I believe this is clearly an error.

**Comment by annevk** [comment]
It sends CORS response headers, yes, but it doesn't deal with a CORS preflight. And yes, adding a header can be enough to require a preflight.
