### ISSUE TITLE
Error Handle Chinese character for Charset=UTF-8

### ISSUE THREAD

**Issue by camsong** [whatwg/fetch#102]
I'm using Chrome(45.0.2454.15 beta (64-bit)) and Firefox(33.1.1) on Mac OS X 10.10.4. Both support `fetch` API. but I got messy code when the server response text has Chinese characters.

This is steps you may reproduce:
1. open http://xueqiu.com/
2. Open devtool console and type: 

```
var url = 'http://xueqiu.com/imgroups/search.json?q=%E5%A4%A7%E5%8A%9B&count=3&sg=1';
fetch(url, { method: 'get', credentials: 'include' }).then(function (res) {
  return res.json();
}).then(function (json) {
  return console.log('receive: ' + JSON.stringify(json));
});
```

Here is the response headers:
![image](https://cloud.githubusercontent.com/assets/948896/9077282/f432b638-3b5e-11e5-8228-677cf10a83ce.png)

response text in preview:
![image](https://cloud.githubusercontent.com/assets/948896/9077286/065d822a-3b5f-11e5-9877-7b45b3775c3b.png)

Result in console, oops, I got messy code

![image](https://cloud.githubusercontent.com/assets/948896/9077388/2551fc96-3b60-11e5-8610-7e65c48928d8.png)

response I got **å¤§å**  which should be **大力**。This should not be an issue of server response, since it works when using `XMLHTTPRequest`.
￼

**Comment by yutakahirano** [comment]
Thanks for the report, but if it is a user-agent problem, issue trackers for them is more suitable, I think.
https://crbug.com/ for Chrome, https://bugzilla.mozilla.org/ for Firefox.

**Comment by camsong** [comment]
Reported, thanks

**Comment by wanderview** [comment]
FWIW, I seem to get the correct characters on FF nightly 42.
