### ISSUE TITLE
How should the ReadableStream from response.body work when it's multipart?

### ISSUE THREAD

**Issue by dalecurtis** [whatwg/fetch#1021]
Opening here at the request of @domenic -- while looking into providing an [ImageDecoder API](https://github.com/dalecurtis/image-decoder-api/blob/master/explainer.md) I've hit an issue with streaming multipart MJPEG resources and the ReadableStream returned by response.body.

Downstream streams don't know the multipart boundary specified in the Content-Type header, so they can't parse headers out of the ReadableStream to get at the binary data. E.g., Using [cam2web](https://github.com/cvsandbox/cam2web/), the multipart Content-Type is:

> Content-Type=multipart/x-mixed-replace; boundary=--myboundary

And each chunk of the response looks like this:

> '--myboundary\r\nContent-Type: image/jpeg\r\nContent-Length: $SIZE\r\n\r\n$JPEG_DATA'

So multipart ReadableStreams today require a user supplied TransformStream to reform the data into contiguous blocks. @domenic indicated there may be some interest in providing a browser-supplied solution to this, so opening this issue for discussion. Thanks!

**Comment by dalecurtis** [comment]
Here's an example of what that TransformStream looks like (warning my Streams-fu is weak):
```
class MultipartParser {
  constructor(boundary) {
    this.boundary = boundary;
    this.onChunk = null;
    this.onClose = null;

    this.first = null;
    this.lastImage = null;
    this.lastImageLen = 0;
    this.nextType = ParseState.BOUNDARY;
    this.contentLength = -1;
  }

  addBinaryData(incoming_data) {
    this.data = incoming_data;
    this.checkForImages();
  }

  emitImage() {
    this.nextType = ParseState.BOUNDARY;
    if (this.lastImageLen > 0)
      this.onChunk(this.lastImage);
    this.lastImage = null;
    this.lastImageLen = 0;
  }

  checkForImages() {
    var dataIndex = 0;
    while (dataIndex < this.data.length) {
      var subdata = this.data.slice(dataIndex);
      switch (this.nextType) {
        case ParseState.DATA:
          var sum = subdata.length + this.lastImageLen;
          if (sum == this.contentLength) {
            this.lastImage = subdata;
            this.lastImageLen += subdata.length;
            this.emitImage();
            dataIndex += subdata.length;
            this.nextType = ParseState.BOUNDARY;
          } else if (sum > this.contentLength) {
            var remainingImage = this.contentLength - this.lastImage.length;
            this.lastImage.set(
                subdata.slice(0, remainingImage), this.lastImageLen);
            this.lastImageLen += remainingImage;
            this.emitImage();
            dataIndex += remainingImage;
            this.nextType = ParseState.BOUNDARY;
          } else {
            this.lastImage.set(subdata, this.lastImageLen);
            this.lastImageLen += subdata.length;
            dataIndex += subdata.length;
          }
          break;
        case ParseState.CONTENT_TYPE:
          if (subdata.length == 2 && subdata.toString() == "\r\n")
            this.nextType = ParseState.BOUNDARY;
          else
            this.nextType = ParseState.CONTENT_LEN;
          dataIndex += subdata.indexOf(10) + 1;
          break;
        case ParseState.CONTENT_LEN:
          var cl = new TextDecoder("utf-8").decode(
              subdata.slice(0, subdata.indexOf(10)));
          this.contentLength = parseInt(
              cl.toLowerCase().split("content-length:")[1].trim());
          this.nextType = ParseState.BLANK_LINE;
          this.lastImage = new Uint8Array(this.contentLength);
          this.lastImageLen = 0;
          dataIndex += subdata.indexOf(10) + 1;
          break;
        case ParseState.BOUNDARY:
          this.nextType = ParseState.CONTENT_TYPE;
          dataIndex += subdata.indexOf(10) + 1;
          break;
        case ParseState.BLANK_LINE:
          this.nextType = ParseState.DATA;
          dataIndex += subdata.indexOf(10) + 1;
          break;
      }
    }
  }
}

var parser;
class MultipartTransformStream {
  constructor(boundary) {
    parser = new MultipartParser(boundary);

    this.readable = new ReadableStream({
      start(controller) {
        parser.onChunk = chunk => controller.enqueue(chunk);
        parser.onClose = () => controller.close();
      }
    });

    this.writable = new WritableStream({
      write(incoming_data) {
        parser.addBinaryData(incoming_data);
      }
    });
  }
}
```

**Comment by domenic** [comment]
/cc @ricea 

> And each chunk of the response looks like this:

I imagine this is an implementation artifact; in the specification doesn't mandate any correspondence between `ReadableStream` chunks and multipark chunks. So robust code that handles that would be even trickier to write than your above.

Is your idea for the TransformStream to be essentially splitting the `$JPEG_DATA` portion out and only emitting that? I guess doing that automatically would go against the purpose of fetch response bodies as "raw data", right?

**Comment by dalecurtis** [comment]
Yeah my implementation is half baked (it fails 1 out 2 times :), but you have the gist of it. Just emit the $JPEG_DATA chunks and strip everything else out.

**Comment by annevk** [comment]
I suspect this is equivalent/similar to the parser for `multipart/form-data`, right? (Which also isn't defined in sufficient detail.) Ideally we tackle all of that in one go.

**Comment by domenic** [comment]
Just to step back for a bit, can we confirm with @annevk as spec editors and/or with some implementers that emitting the raw data (including multipart boundaries) is the intended interpretation of the current spec? I wonder if the result of `.arrayBuffer()` also includes the boundaries, or if they get deleted from that?

**Comment by annevk** [comment]
I would expect all `multipart/*` to be emitted as-is. HTML will do something special with such responses in navigation and for images (maybe?) and `response.formData()` handles `multipart/form-data` specifically, but that's it.

**Comment by domenic** [comment]
Hmm, I tried to make a test case but browsers seem to instead get confused.

https://wooded-malleable-mine.glitch.me/ writes out the response body

```
--myboundary
Content-Type: text/plain
Content-Length: 4

aaaa--myboundary
Content-Type: text/plain
Content-Length: 4

bbbb--myboundary
Content-Type: text/plain
Content-Length: 4

cccc--myboundary
Content-Type: text/plain
Content-Length: 4

dddd
```

with header

```
content-type: multipart/x-mixed-replace; boundary=--myboundary
```

But when I head there and put the following in my console

```js
fetch("https://wooded-malleable-mine.glitch.me/").then(r => r.arrayBuffer()).then(console.log)
```

I get a zero-length ArrayBuffer. So either I set up my server wrong (code [here](https://glitch.com/edit/#!/wooded-malleable-mine?path=server.js)) or we have more foundational problems with the Fetch API + multipart/x-mixed-replace.

**Comment by ricea** [comment]
@domenic I haven't looked into this in detail, but I believe there should be a CRLF before `--myboundary`.

Chrome only supports multipart/x-mixed-replace for images, but I'm not sure that's relevant to this discussion.

**Comment by domenic** [comment]
After tweaking the demo a bit I'm getting a forever-pending `arrayBuffer()` promise. That's more like what I would expect. I guess then multipart is only observable through the `.body` property. And indeed, at least in Firefox and Chrome, that displays raw chunks. (Although I'm seeing skipped chunks... probably a bug in my server code or the CDN/proxy in front of Glitch.)

OK. So we can come back to the OP's question as to whether we want to expose any built-in helpers in fetch (e.g. a transform stream) that lets people parse `multipart/x-mixed-replace` responses...

**Comment by annevk** [comment]
Those seem like implementation bugs to me. From the perspective of Fetch the MIME type of a response has no bearing on how its body is exposed.

**Comment by annevk** [comment]
Is it okay to close this issue? I think it would be clearer if a new issue was opened if we specifically want to consider adding new utility streams or some such.

**Comment by annevk** [comment]
Closing this due to the lack of follow-up.
