### ISSUE TITLE
where is fetch source code?

### ISSUE THREAD

**Issue by anlexN** [whatwg/fetch#1025]
[Chaining promises](https://nodejs.dev/understanding-javascript-promises#chaining-promises) says Fetch API is a layer on top of the XMLHttpRequest API, where are fetch and XMLHttpRequest source code?

**Comment by jakearchibald** [comment]
This is the fetch spec, not an implementation. There are at least 4 independent implementations of fetch. One in Chrome, Safari, old Edge, and Firefox.

Besides, fetch is the lower level, and xmlhttprequest builds on top of fetch. You can see the references to fetch in the XHR spec

**Comment by anlexN** [comment]
1. fetch spec is living standard, why have different implementations?
2. i review [send method](https://xhr.spec.whatwg.org/#the-send()-method), where says xmlhttprequest builds on top of fetch?

**Comment by jakearchibald** [comment]
> fetch spec is living standard, why have different implementations?

So the web isn't controlled by a single vendor. For example, there are many implementations of the HTML spec.

> 2\. i review [send method](https://xhr.spec.whatwg.org/#the-send()-method), where says xmlhttprequest builds on top of fetch?

It calls out to fetch in step 11.4, whereas fetch does not call out to XMLHttpRequest.

**Comment by anlexN** [comment]
1. where is google implementation source code?

**Comment by jakearchibald** [comment]
> 1. where is google implementation source code?

https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/platform/loader/fetch/?originalUrl=https:%2F%2Fcs.chromium.org%2F

> 2. can you update [chaining-promises](https://nodejs.dev/understanding-javascript-promises#chaining-promises) docs?

Personally, no, but I have filed an issue https://github.com/nodejs/nodejs.dev/issues/674

**Comment by anlexN** [comment]
whatwg should give us readers many and many demoes so that better understand these standards, can you?

**Comment by jakearchibald** [comment]
There are a lot of docs out there for `fetch()`, including https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API.

But if you have a specific question I'm happy to answer it here.

**Comment by anlexN** [comment]
where is async/await source code? someone tell me async/await is based on fetch, it's right?

**Comment by jakearchibald** [comment]
Async/await is a JavaScript feature. It has nothing directly to do with fetch. https://developers.google.com/web/fundamentals/primers/async-functions

Fetch does return a promise though, so it can be used with async/await.

There are many implementations of JavaScript, the one in Chrome is V8 https://chromium.googlesource.com/v8/v8.git. I don't think you need to read the source of a JavaScript engine in order to use JavaScript.

**Comment by anlexN** [comment]
what do you think of nodejs don't use fetch? fetch source code can not merge into nodejs source code?

**Comment by jakearchibald** [comment]
https://github.com/nodejs/node/issues/19393 - they're discussing it. Although, the streams implementation that the web uses is different to node, so there'll need to either align, or have a compatibility layer.

Also, some of the security measures in fetch, such as CORS, don't really make sense for nodejs.
