### ISSUE TITLE
Add `json` to RequestDestination values

### ISSUE THREAD

**Issue by ayumi-cloud** [whatwg/fetch#1042]
Looking at the list of values for the spec found here on mdn: https://developer.mozilla.org/en-US/docs/Web/API/RequestDestination#Values

It would be great to have:

```
"json"
The target is json data.
```

Above is mentioning mdn and here is a link to the spec: https://fetch.spec.whatwg.org/#requestdestination

**Comment by annevk** [comment]
What would use this?

**Comment by ayumi-cloud** [comment]
@annevk 

hi,

I'm currently using [Google Workbox](https://github.com/GoogleChrome/workbox) and our [PWA](https://web.dev/progressive-web-apps/), uses `json` files for the **content and semantic** data files for our `web 3.0` stuff.

We want to increase performance and add a `cache-first` strategy for our content json files in our pwa.

A code example would look like this:

```
import { registerRoute } from "workbox-routing";
import { ExpirationPlugin } from "workbox-expiration";

registerRoute(
    ({ request }) => request.destination === "json",
    new CacheFirst({
        cacheName: "json",
        plugins: [
            new ExpirationPlugin({
                maxEntries: 60,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
        ],
    })
);
```

Link to more examples: https://developers.google.com/web/tools/workbox/guides/common-recipes

Hope that helps for an example use case.

**Comment by annevk** [comment]
How is the request constructed such that it ends up with that destination?
