### ISSUE TITLE
Structured Field Values (formerly Structured Headers) changes

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#1053]
Reportedly SFV is the final name of https://tools.ietf.org/html/draft-ietf-httpbis-header-structure, though the RFC is not yet published.

This would mean we have to change

* https://fetch.spec.whatwg.org/#concept-header-list-get-structured-header
* https://fetch.spec.whatwg.org/#concept-header-list-set-structured-header

though maybe keep using the old IDs for some stability.

The other change @domenic and I have been contemplating is that we do not distinguish between no header present and header fails to parse for the entirety of the web platform. This would mean changing step 5 of the first algorithm to return null instead. I don't believe this affects any existing callers as they all already do so, but please let me know if you have any concerns.

Standards impacted by these naming changes are HTML, https://w3c.github.io/webappsec-fetch-metadata/, https://w3c.github.io/webappsec-feature-policy/, https://w3c.github.io/reporting/, ...? From a quick check they all treat null and failure as equivalent already.

cc @whatwg/http @clelland @mikewest @domenic

**Comment by clelland** [comment]
This is three different changes, is that right?

1. Change step 4 of "get a structured header" (and step 1 of "set a structured header") to call the new algorithms correctly
2. Rename the two algorithms in Fetch to "get/set a structured field value"
3. Make "get a structured field value" return null on parser failure

(I'm trying to figure out if 2. is necessary; it's still OK to call a field value a "structured header value" if the context is restricted to HTTP headers, and not trailers.)

**Comment by annevk** [comment]
Yeah. Maybe @mnot can advice on 2, though I'd note that we'd use header lists for trailers too if we ever added trailers back in as a concept.

**Comment by clelland** [comment]
Makes sense; and "get/set a structured field value...from a header list" works grammatically as well, so maybe switching to that now would be easiest.

**Comment by mnot** [comment]
WFM

**Comment by mnot** [comment]
WRT changing step 5 - I think it's OK for headers defined by the web platform to avoid distinguishing between a parse error and a missing header, but developer code (once the API is exposed) might want to know the difference for legitimate reasons.

**Comment by annevk** [comment]
That's a fair point, though I suppose you could always use the "legacy" API to see the actual value. (And once they are objects end-to-end it shouldn't be possible to have a failure case.) API is #930 though I suspect it'd be good to wait a while to see what kind of adoption and patterns emerge from userland.
