### ISSUE TITLE
Allow streaming requests to follow 301/2 redirects if method is 'POST'

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/fetch#1058]
If I'm reading the spec correctly, we return an error if the body is a stream (it has no source) and we get a redirect that isn't 303 https://fetch.spec.whatwg.org/#concept-http-redirect-fetch (step 9).

It seems like we could allow 301/2 redirects if the method is POST, since the body is discarded (step 11).

**Comment by annevk** [comment]
Since this is a new feature and HTTP in general hasn't accepted that 301/302 with POST are a lost cause, I'm a little hesitant to allow do this as it would mean other clients would be forced to adopt the behavior of browsers rather than preserve the method and body in such cases.

cc @whatwg/http

**Comment by jakearchibald** [comment]
I don't feel really strongly about it btw, it's just something that confused me when reading the spec. Maybe a note is good enough.

**Comment by yoichio** [comment]
I don't think this issue is `upload-streaming-blocking`  but general HTTP issue as annevk mentions.

**Comment by jakearchibald** [comment]
Yeah, and it feels like this could be changed after shipping without much of a compatibility issue.

**Comment by annevk** [comment]
I would prefer having this settled before anyone ships, but it sounds like better documentation might be all that's needed here.

**Comment by MattMenke2** [comment]
+1 to getting a consensus here, and having tests for it.  If we don't want browsers to support following 301 redirects for these requests, I don't think we want to risk one browser accidentally supporting it, as that would lead to incompatibilities, and other browsers feeling pressure to follow suit.

**Comment by yoichio** [comment]
I added the test confirming fetch upload is prohibited on redirect except 303 See Other.
Any ambiguous point to discuss here?

**Comment by yoichio** [comment]
Ping?

**Comment by annevk** [comment]
Yeah, this can be closed. Thanks for writing the tests @yoichio!
