### ISSUE TITLE
Drafting the patches to HTML

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/fetch#106]
Given the recent confusion on navigation, now sounds like the right time to draft up a table, or patches for fetches.

Happy to do the work here, but @wanderview, you said you had a list of things that fetch to use as a starting point?

**Comment by jakearchibald** [comment]
Notes:

* I'm mapping "synchronous" to the blocking flag in the current html fetch algorithm, which may not be correct

## `<a ping>`

* *Current 'fetch' point*: https://html.spec.whatwg.org/#hyperlink-auditing:ping
* *client*: window containing the hyperlink
* *synchronous flag*: unclear, but I'd guess unset
* *skip-service-worker flag*: unset
* *mode*: no-cors
* *credentials mode*: include
* *cache mode*: no-store (unsure)
* *redirect mode*: follow

## Appacache Manifest check

* *Current 'fetch' point*: https://html.spec.whatwg.org/#downloading-or-updating-an-application-cache step 4
* *client*: the window that triggered the update
* *synchronous flag*: set
* *skip-service-worker flag*: set, I guess, but SW disables appcache
* *mode*: same-origin
* *credentials mode*: include
* *cache mode*: default
* *redirect mode*: error

## Appcache resource fetch

* *Current 'fetch' point*: https://html.spec.whatwg.org/#downloading-or-updating-an-application-cache step 17.3
* *client*: the window that triggered the update
* *synchronous flag*: set
* *skip-service-worker flag*: set, I guess, but SW disables appcache
* *mode*: no-cors
* *credentials mode*: include
* *cache mode*: default
* *redirect mode*: error

## CSP violation report

* *Current 'fetch' point*: https://w3c.github.io/webappsec/specs/CSP2/#send-violation-reports 3.2
* *client*: the client the report was generated against
* *synchronous flag*: unset
* *skip-service-worker flag*: unset
* *mode*: no-cors
* *credentials mode*: same-origin
* *cache mode*: no-store (unsure)
* *redirect mode*: error

## Navigation

Also applies to downloading, view-source.

* *Current 'fetch' point*: https://html.spec.whatwg.org/#navigating-across-documents 15
* *client*: null
* *synchronous flag*: set
* *skip-service-worker flag*: unset
* *mode*: same-origin
* *credentials mode*: include
* *cache mode*: default
* *redirect mode*: manual

More to come…

**Comment by horo-t** [comment]
How about Worker and SharedWorker?
https://html.spec.whatwg.org/#run-a-worker

**Comment by annevk** [comment]
I filed https://github.com/whatwg/html/issues/95 on HTML. I hope to work on this soonish, but it seems some more groundwork in Fetch is required first.

**Comment by annevk** [comment]
https://github.com/whatwg/html/pull/144 is a rewrite of the text in the HTML Standard. It also addresses workers. Review would be appreciated.

**Comment by annevk** [comment]
Note that #126 will change what we do for navigation requests @dstockwell.

I think this should be closed since it's no longer relevant. @jakearchibald?

**Comment by dstockwell** [comment]
It's amusing that github wants to give me credit for all blink commits, but that was actually @horo-t

**Comment by annevk** [comment]
Ah, @horo-t should probably add "horo@chromium.org" to his GitHub email addresses to rectify that.

**Comment by jakearchibald** [comment]
Happy to close this
