### ISSUE TITLE
A new Request(input, init) constructor step sounds weird.

### ISSUE THREAD

**Issue by yoichio** [whatwg/fetch#1061]
https://fetch.spec.whatwg.org/#dom-request
A step 38th states:
"38. If inputBody is body and input is disturbed or locked, then throw a TypeError."

However If input is string, asking if it is disturbed or locked doesn't make sense because [disturbed](https://fetch.spec.whatwg.org/#concept-body-disturbed) and locked are defined only on a Body mixin.
It should be 
"38. If inputBody is body and a Request object, and input is disturbed or locked, then throw a TypeError." ?

**Comment by annevk** [comment]
Well, _inputBody_ is only set to a non-null value if that is the case, no?

**Comment by yoichio** [comment]
Do you mean the case is "If inputBody is body" ? No, it can be both inputBody is null and body is null.

**Comment by yutakahirano** [comment]
Neither _body_ nor _inputBody_ can be a Request object. They are null or a [body](https://fetch.spec.whatwg.org/#concept-body). So 

```
inputBody is body and a Request object
```

 always returns false.

**Comment by annevk** [comment]
But disturbed/locked also does a non-null check so that part is covered, no? (We could make step 38 step 39.0 I suppose and assert that _input_'s body is non-null, but would that make it better?)

**Comment by yoichio** [comment]
@yutakahirano 
I missed. It should be
"If inputBody is body and input is a Request object, ..."

@annevk 
Disturbed/locked checks Body mixin's body is non-null but doesn't check Body's non-null.

**Comment by annevk** [comment]
@yoichio I don't follow. A `Request` object's body is Body mixin's body. Body itself is a mixin that Request includes, it cannot be null.

**Comment by yoichio** [comment]
> Body itself is a mixin that Request includes, it cannot be null.

Yes.

I feel discussion is going wrong. Back to the original question:
if _input_ is string and _init_["body"] doesn't exist, the 38th step is asking whether the _input_ is disturbed or locked.
That's strange.

**Comment by annevk** [comment]
I see, so yeah, moving step 38 to 39.0 would be the right approach here as we need to know that _body_/_inputBody_ are non-null.

**Comment by annevk** [comment]
I pushed a fix for this to #1152.
