### ISSUE TITLE
Allow strings or byte sequences as bodies?

### ISSUE THREAD

**Issue by domenic** [whatwg/fetch#1073]
This is several issues in one...

HTML always invokes Fetch with byte sequence request bodies. The two invocations are:

- https://html.spec.whatwg.org/#form-submission-algorithm:concept-request-body
- https://html.spec.whatwg.org/#hyperlink-auditing:concept-request-body

I think we should allow this, instead of requiring HTML or other callers to create new `ReadableStream` instances. Fetch could, very early in the Fetch algorithm, [construct a fixed ReadableStream instance](https://fetch.spec.whatwg.org/#concept-construct-fixed-readablestream).

HTML also has a few places where it wants to supply a string as a response body in a synthetic response:

- https://html.spec.whatwg.org/#the-iframe-element:concept-response-body
- https://html.spec.whatwg.org/#navigating-across-documents:concept-response-body

These are interesting because I know that Blink, at least, has a direct path for javascript: URLs and iframe srcdoc to set the resulting document's value as a string. Bytes never get involved, and the charset defined for the document is ignored. (I don't know if the HTML spec defines the charset of the produced documents very well for those cases...)

I'm not sure what we should do here. Maybe HTML's navigate algorithm should grow a new type of "resource", the string resource, since this seems very specific to that case? Or HTML could UTF-8 encode and created a fixed stream itself. Maybe with a helper defined in Fetch, like "created a fixed string body"?

I can't think of an easy way for Fetch to handle this in general, because we probably want to confine string-bodies to these navigation special cases; certainly any cases that might pass through service workers need to be stream-bodies.

Finally, HTML also treats script response bodies as byte sequences:

- https://html.spec.whatwg.org/#fetching-scripts:concept-response-body and 3 other very similar places.

But this is already covered in https://github.com/whatwg/fetch/issues/661, so we can ignore it for this issue.

**Comment by annevk** [comment]
Apart from `fetch()` and `XMLHttpRequest`, navigation is the only place that can produce request bodies in a browser. Is it hard for HTML to invoke https://fetch.spec.whatwg.org/#concept-bodyinit-extract similar to how `XMLHttpRequest` does it?

**Comment by domenic** [comment]
I guess it wouldn't be too bad to have HTML do this, if you really don't think other specs will have request bodies. (No specs want to ping a server?) "Extract" isn't a great fit as we don't want the MIME type, but maybe we can factor out some common primitive...

**Comment by annevk** [comment]
Hmm, maybe the Reporting API?

cc @clelland

**Comment by clelland** [comment]
Yep, Reporting creates POST requests with bodies -- it sets the MIME type, and provides a byte sequence to Fetch.

The byte sequence used is always the output of https://infra.spec.whatwg.org/#serialize-json-to-bytes, so it could probably use a string just as well, if the Fetch primitive were to be refactored.
