### ISSUE TITLE
The guard of headers created from no-cors request

### ISSUE THREAD

**Issue by yutakahirano** [whatwg/fetch#1074]
In https://fetch.spec.whatwg.org/#dom-request, we set request's headers guard to "request" if _init_ is empty, even when created from a no-cors request. This allows web developers to modify headers that are not CORS-safelisted.

This seems like a spec bug.

See also: #560

@youennf @annevk @jakearchibald

**Comment by annevk** [comment]
@jakearchibald do you want to fix this?

**Comment by jakearchibald** [comment]
Yeah I can take this

**Comment by jakearchibald** [comment]
PR https://github.com/whatwg/fetch/pull/1076
