### ISSUE TITLE
Request.headers is shared across Requests. Is it OK?

### ISSUE THREAD

**Issue by yutakahirano** [whatwg/fetch#1075]
```
const r1 = new Request('/');
const r2 = new Request(r1);
```

Because _r2_ is created without _init_ argument, _r2_'s associated request's header list is _r1_'s associated request's header list. Hence modification is shared.

```
r1.headers.set('x', 'y');
r2.headers.get('x') // => returns 'y'.
```

Is it OK? Or should we clone the header list?

This was introduced at #560 I think.

@youennf @annevk @jakearchibald

**Comment by jakearchibald** [comment]
Hm, it does feel like cloning is better. Sorry if I caused this.

**Comment by annevk** [comment]
Agreed that this should clone and that's also what browsers do (`r1.headers !== r2.headers` in at least Firefox and Chrome).

**Comment by annevk** [comment]
I looked at https://fetch.spec.whatwg.org/#dom-request and it seems that step 13 always copies the underlying header list and step 31 always creates a new `Headers` object. What am I missing?

**Comment by yutakahirano** [comment]
Oh I see. I was looking at 33.1 and I thought the copy there was critical, which was wrong.

Sorry for the noise.

**Comment by annevk** [comment]
No problem, thanks for verifying!
