### ISSUE TITLE
Handle blob URLs without a backing blob

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#1077]
Presumably these should result in a network error. The current specification doesn't state anything and it's not tested either.

See the README for instructions on where to add tests. In the specification the "blob" case of https://fetch.spec.whatwg.org/#scheme-fetch needs updating to handle current URL’s blob URL entry being null.

**Comment by M-ZubairAhmed** [comment]
@annevk can i look into this one, just trying to understand what needs to be done here

**Comment by annevk** [comment]
Hey @M-ZubairAhmed, there are basically two separate tasks:

1. Create test cases for `blob:` URLs not backed by a `Blob` object. E.g., trying to fetch `blob:not-backed-by-a-blob` would be such an example. Presumably this should result in a network error.
2. Update the specification to check for that condition as per OP.

Thanks for looking into it! Let me know if you have further questions, I'm also on IRC: https://whatwg.org/irc.

**Comment by Krishnaraj-shankar** [comment]
Hi @annevk ,Im a begginer . Would you guide me to solve this issue..
