### ISSUE TITLE
link BufferSource to definition

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#108]
While BufferSource is part of webidl, it looks like a separate interface.  It would be nice to link it to:

  http://heycam.github.io/webidl/#common-BufferSource

**Comment by annevk** [comment]
Terms part of IDL are the only ones that are not linked.

**Comment by annevk** [comment]
It seems that if we were to link `BufferSource` we would also have to link `any`, `USVString`, `DOMString`, `ByteString`, and I don't think that makes sense. Sorry.

**Comment by wanderview** [comment]
Ok, although it clearly confuses people (event spec authors):

  http://logs.glob.uno/?c=freenode%23whatwg&s=23+Mar+2015&e=23+Mar+2015&h=BufferSource#c941240

**Comment by domenic** [comment]
I think we should link all those terms too in theory. (As well as `long`, etc. etc.) @TabAtkins, thoughts? Bikeshed only includes "interface", which USVString/DOMString/etc. are not.

**Comment by annevk** [comment]
Note that Fetch is not yet in Bikeshed, but that would work for me.

**Comment by tabatkins** [comment]
They're *like* interfaces. Close enough, at least.  Same with `any`, etc.  When I finally Bikeshed WebIDL like I've been threatening to, they'll be marked up as such.  (Well, `any` is probably a typedef. Doesn't super matter; they're all linkable with the `{{idl}}` shorthand without having to know the type.)
