### ISSUE TITLE
TPAC 2020: Fetch Standard meeting interest

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#1082]
As discussed at https://github.com/whatwg/meta/issues/171 we have the option to participate in W3C's TPAC.

If you're interested in meeting with Fetch editors and the wider community please respond to this issue (or reach out privately) and indicate:

* Timezone preference: North America / Europe / Asia (other or a more detailed indication are okay too)
* Optional: topic you'd like to discuss.

E.g.,

* Timezone: Europe
* Topic: making progress on resolving issues.

**Comment by domenic** [comment]
Potential topic:

Timezone: we've got folks in North America, Tokyo, and Europe, so it's kind of hopeless.
Topic: [prerendering revamped](https://github.com/jeremyroman/alternate-loading-modes) fetch integrations

I think the plan is to discuss prerendering more generally [in WebPerf](https://docs.google.com/document/d/1inejuvPONXPOLKTCcUzOBhPh6QOckMcltnR-E3xyZVQ/edit), but if Fetch-adjacent folk are interested in having a more Fetch-focused discussion, we could do that separately.

I believe Fetch doesn't have any dedicated space on the TPAC schedule at this point, so this is mostly me hijacking the thread to give a heads-up that Chrome folks are happy to have a VC about prerendering + fetch if others would find that helpful. It's pretty early-stage though, so keeping things async is a good default.
