### ISSUE TITLE
Some browsers are reusing 'no-cache' cached images without revalidation

### ISSUE THREAD

**Issue by youennf** [whatwg/fetch#1088]
As discussed in https://bugs.webkit.org/show_bug.cgi?id=216048, it seems Chrome and Firefox are not always obeying 'Cache-Control: no-cache' directives, at least for image loads with directives like 'Cache-Control: public, max-age=31536000, no-cache'.
WebKit is currently revalidating such image loads which has a perf impact.
If both Chrome and Firefox are actually skipping revalidation in some cases, it might be worth documenting that in the fetch spec.

**Comment by mnot** [comment]
This sounds like the memory or image cache - see #590 and #354. All browsers currently will not reuse a response with `no-cache` even when it contains `max-age` -- see [test results](https://cache-tests.fyi/?id=cc-resp-no-cache#).

**Comment by youennf** [comment]
@yoavweiss mentioned this might be defined as part of https://html.spec.whatwg.org/#updating-the-image-data:list-of-available-images

**Comment by youennf** [comment]
WPT PR: https://github.com/web-platform-tests/wpt/pull/25380
Looking at the HTML spec, the cache is per document which does not seem to be what Chrome and Firefox are implementing.
Closing the issue since this might not end up in fetch spec land until we define the memory cache.

**Comment by annevk** [comment]
It's sorta-per-document as it can be reused across documents. Basically that needs to be revamped with a properly defined memory cache.
