### ISSUE TITLE
Referrer: Should request constructor fail when parsing referrer fails?

### ISSUE THREAD

**Issue by yutakahirano** [whatwg/fetch#109]
> The Request constructor must run these steps:
> ...
> 15. If init's referrer member is present, run these substeps:
>    1. Let referrer be init's referrer member.
>    2. If referrer is the empty string, set request's referrer to "no-referrer" and terminate these substeps.
>    3. Let parsedReferrer be the result of parsing referrer with baseURL.
>    4. If parsedReferrer's non-relative flag is set, scheme is "about", and path contains a single string "client", set request's referrer to "client" and terminate these substeps.
>    ...

When the parsing fails, what should we do? I think something such as throwing an error is needed here.

**Comment by annevk** [comment]
Thank you!
