### ISSUE TITLE
Question: Why don't constructed Response unpack?

### ISSUE THREAD

**Issue by jimmywarting** [whatwg/fetch#1090]
I was just wondering why isn't the response unpacked when content encoding is set when constructing and reading a Response?

Example code:
```js
// just to get a dummy gzip'ed blob
gz = new CompressionStream('gzip')
blob = new Blob(['a'.repeat(100)]).stream()
gzipBlob = await new Response(blob.pipeThrough(gz)).blob()

// read
headers = {'content-encoding': 'gzip'}
result = await new Response(gzipBlob, { headers }).blob()
result.size // 24 (maybe expected 100)
```

is it a bug or by design?
have it something to do with respondWith or that request and response share a common Body mixin?
or maybe the body isn't proper encoded? i have also tried deflate, didn't unpack either

**Comment by annevk** [comment]
Content codings are handled at the network layer, not below that.

**Comment by jimmywarting** [comment]
Okey, but why?
Was thinking maybe i could use `fetch(URL.createObjectURL(gzipBlob))` but just realized i can't set the response header for that.

So if i would do `fetchEvent.respondWith(new Response(gzipBlob, { headers }))` would it be unpacked then?

**Comment by annevk** [comment]
I don't think it was a conscious decision other than that it would take effort to move it around and it's not clear how compatible that would be at this point. Also, we shouldn't really add functionality around this until #716 is sorted I think. The underpinnings have too many unknowns.

**Comment by jimmywarting** [comment]
Alright, I'm fine with that decision.
I can just use DecompressionStream directly. i was mostly just curios why it didn't work below the network layer.
