### ISSUE TITLE
Referrer: Referer header value for "client" referrer

### ISSUE THREAD

**Issue by yutakahirano** [whatwg/fetch#110]
Just to confirm: In HTTP-network-or-cache fetch, "Referer: client" is appended if the referrer value is "client". Is that correct?

> Append `Referer`/empty byte sequence, if httpRequest's referrer is "no-referrer", and `Referer`/httpRequest's referrer, serialized and utf-8 encoded, otherwise, to httpRequest's header list.

"Referer: about:client" looks more reasonable to me.

**Comment by yutakahirano** [comment]
Sorry, I misundersood. "client" referrer should be replaced in Main fetch.

> If request's referrer is not "no-referrer", set request's referrer to the result of invoking determine request's referrer. [REFERRER]

and a non-url referrer is converted to a url.

**Comment by annevk** [comment]
Thank you. I decided to add a clarifying note.
