### ISSUE TITLE
[editorial] Link to `Content Security Policy objects` is broken

### ISSUE THREAD

**Issue by Malvoz** [whatwg/fetch#1110]
In https://fetch.spec.whatwg.org/#concept-response-csp-list:

> A [response](https://fetch.spec.whatwg.org/#concept-response) has an associated **CSP list**, which is a list of [Content Security Policy objects](https://w3c.github.io/webappsec-csp/#policy) for the [response](https://fetch.spec.whatwg.org/#concept-response). The list is empty unless otherwise specified. [[CSP]](https://fetch.spec.whatwg.org/#biblio-csp)

The link for "[Content Security Policy objects](https://w3c.github.io/webappsec-csp/#policy)" is broken.

**Comment by annevk** [comment]
Thanks, I created a PR, but might wait a bit with landing it to see if I can make some further improvements to how Fetch integrates with CSP that would prevent this from happening again (or at least silently happening again).
