### ISSUE TITLE
redirecting from same-origin to cross-origin CORS with userpass should fail

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#112]
Currently the redirect section of [HTTP Fetch](https://fetch.spec.whatwg.org/#http-fetch) step 5 says:

> If the CORS flag is set and either locationURL's username is not the empty string or locationURL's password is non-null, return a network error.

As far as I can tell, the only way for the CORS flag to be set is if we've previously already redirected through a CORS origin.  If the CORS location with userpass was reached from a same-origin URL redirecting, then the CORS flag is not set.

This is counter to how the existing gecko CORS infrastructure works.  It blocks userpass when redirecting to a CORS enabled server regardless of the originating origin doing the redirect.  Gecko code is here:

  https://dxr.mozilla.org/mozilla-central/source/dom/security/nsCORSListenerProxy.cpp?case=true&from=nsCORSListenerProxy.cpp#957

Which is correct?  It seems the gecko version is safer, but maybe its too conservative?

It seems whatever we decide here should also be applied to:

> If the CORS flag is set and locationURL's origin is not request's current url's origin, set request's origin to an opaque identifier. 

In both cases it seems perhaps we should be checking if the RequestMode is 'cors' instead of checking the CORS flag.

**Comment by annevk** [comment]
Thank you, fixed.

I ended up checking both the _CORS flag_ and the mode. Otherwise cross-origin to same-origin would not be covered.

**Comment by wanderview** [comment]
> I ended up checking both the CORS flag and the mode. Otherwise cross-origin to same-origin would not be covered.

Can you describe the case you are talking about here?  Wouldn't it be better to change this to use CORS mode as well?

> If the CORS flag is set and locationURL's origin is not same origin with request's current url's origin, set request's origin to an opaque identifier. 

Then there is no "cross-origin to same-origin" any more since you can't get "same-origin" to match the opaque identifier.

This is effectively what gecko does as well using a "have I ever been cross-origin" flag.  Again, this does not depend on being redirected from cross-origin to be set.  Its just the first time a cross-origin URL is evaluated regardless of the redirect source.

**Comment by annevk** [comment]
Talked about it on IRC: http://krijnhoetmer.nl/irc-logs/whatwg/20150820#l-286
