### ISSUE TITLE
Add `Promise<Document> document()` to `Response`

### ISSUE THREAD

**Issue by isiahmeadows** [whatwg/fetch#1124]
This one method would bring `fetch` to full parity with XHR regarding response types, and it'd be very useful for leveraging browsers' streaming parsers when fetching HTML to eventually either parse out (in user scripts) or display (in web pages). It wouldn't stream to the UI itself, however. In spirit, it'd mimic [the "set a document response" algorithm for XHRs](https://xhr.spec.whatwg.org/#document-response), and it'd likewise derive the MIME type from the response headers (specifically `response.headers.get('content-type')`).

**Comment by domenic** [comment]
Dupe of https://github.com/whatwg/fetch/issues/16 and its dupes.

**Comment by isiahmeadows** [comment]
👍
