### ISSUE TITLE
Why fetch does not redirect after a post request?

### ISSUE THREAD

**Issue by santimirandarp** [whatwg/fetch#1129]
Sorry, I'm a newbie and have been dealing with this for days, and having partial or wrong answers in stackoverflow.

I'm creating a login page, where I prevent the form default to deal with it using fetch, like this:
```
const fetchOptions = data => {
  return { 
    method: 'POST', 
    mode: 'cors', 
    cache: 'no-cache', 
    credentials: 'include', 
    headers: { 'Content-Type': 'application/json' },
    redirect: 'follow',
    referrerPolicy: 'no-referrer', 
    body: JSON.stringify(data)
  }}


form.addEventListener("submit", (e) => {
  e.preventDefault()
  fetch(uri, fetchOptions({
    "username":user.value, 
    "password":pwd.value 
  })).catch(e => console.log(e))
})
```

When the redirected response arrives (which I can see in the network tab), the page stays in `/login`.

Just for completeness, this is the redirect in pseudocode:
```
app.post("/login", (req,req)=>{
("if credentials correct")=>res.redirect(303, "/")
}
```

A [similar problem can be found here.](https://stackoverflow.com/questions/27202075/expressjs-res-redirect-not-working-as-expected) I've exhausted the MDN for answers, but no answer to this. Is this behaviour expected?

**Comment by annevk** [comment]
Why would the address bar change if you are doing a fetch and not a navigation? This is also the answer on StackOverflow so closing this.

**Comment by santimirandarp** [comment]
The first reason is because if we set `redirect:follow` shouldn't be followed automatically?

The second reason is that stackoverflow answer generates a new request, if you set

`window.location.href="/"` it runs a new GET.

**Comment by santimirandarp** [comment]
@annevk 
Can you just please tell me how am I wrong in what I'm saying? 

The approach you validates runs 2 requests, and is inefficient.

**Comment by annevk** [comment]
I'm not recommending that approach. I'm saying that if you want to navigate you should navigate and not expect that `fetch()` navigates. It just does a request. The `formdata` event might be what you're looking for, but I'm not sure where browser support is at.

To be clear though, this is a place to discuss issues with the Fetch standard. Questions such as these are best posed on StackOverflow or equivalent forum.

**Comment by santimirandarp** [comment]
@annevk 
Yeah I've done that, as well as asking on mozilla discourse. No one gave me an answer.

Thanks anyways.

**Comment by crustamet** [comment]
I agree with @ghost, im having the same issue, why the fetch does not follow the redirect and navigate once to the url that is present in the header ?

I cannot get around this issue only by returning a JSON response instead of a Redirect Response.

It should have an option that navigate as well to the new location.

**Comment by annevk** [comment]
If you want to navigate you should not be using fetch. Fetching is just a small subset of navigation. That will never change.
