### ISSUE TITLE
Determining MIME type of Request and Response objects

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#1135]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1684634 @evilpie found a discrepancy between Wasm's API and Fetch's API in how MIME types are determined for `Request` and `Response` objects.

https://webassembly.github.io/spec/web-api/#compile-a-potential-webassembly-response extracts a MIME type from the response directly, whereas Fetch uses the MIME type field. The MIME type field is not updated however when headers are set after the creation of the `Request` or `Response` object. I suggest we remove the MIME type field and always take changes to headers into account. The easiest change would be to change the MIME type field to a "get the MIME type" algorithm that both `Response` and `Request` define as extracting the MIME type from their current headers. Other suggestions welcome.

https://github.com/web-platform-tests/wpt/pull/27100 has some tests for this. Note that currently all implementations cache the MIME type so all would need to make changes, but it would make the overall situation more consistent and logical.

@youennf @cdumez @ricea @domenic does that seem reasonable?

**Comment by Ms2ger** [comment]
Agreed that the wasm-spec behaviour sounds more logical, though I don't think this case was considered in the decision. It seems like Chrome respects the late-set header, Firefox doesn't, and Safari doesn't ship the API. I'd probably consider it more important that wasm and fetch match, though, so I wouldn't object to changing wasm if we can't change fetch.

**Comment by wanderview** [comment]
I fixed chrome to match the spec last year.  Looking back at the change:

https://chromium-review.googlesource.com/c/chromium/src/+/2211949

It appears there is a WPT test validating the current spec behavior at:

https://github.com/web-platform-tests/wpt/blob/83fec7609709b94b8def0b17dbf0f067045c9655/service-workers/cache-storage/script-tests/cache-match.js#L381-L415

Just FYI for context.

**Comment by annevk** [comment]
@wanderview how do you feel about changing it again? I'm happy to update that test. Curiously @evilpie did not regress that test with his fix so maybe more is needed on Firefox's side.

**Comment by wanderview** [comment]
I don't feel strongly either way.  Its unlikely to be a priority to change chrome to the new behavior, though.

**Comment by domenic** [comment]
I also don't feel strongly either way.

Using the headers does seem more logical, but maybe there was a reason we have a specific MIME type field? Does anyone want to do some historical digging?

**Comment by wanderview** [comment]
Maybe some inheritance of blob.type design which seems to be immutable?

**Comment by evilpie** [comment]
> https://github.com/web-platform-tests/wpt/blob/83fec7609709b94b8def0b17dbf0f067045c9655/service-workers/cache-storage/script-tests/cache-match.js#L381-L415
> 
> Just FYI for context.

Thanks. Good to see that there are already tests for the current behavior at least. We now fail the assert: 
> original and overwritten response mime types should match

Sadly we were already failing the assert
> original and cached overwritten response mime types should match expected "text/html" but got "text/plain"

So the whole subtest "MIME type should be frozen at response construction." was marked as failing

**Comment by annevk** [comment]
It was added in 313cc37deb6346690a5f6a7dd096cb74afa19d03 because the mixin needed to get a MIME type from somewhere (as it still does, just need to make it a getter). I suspect it was an oversight. e058fe5a71556cebe7bb0961134a3f3e68af42c3 suggests so as well, at least to me.

I'll make this change as it seems bad that different APIs would be able to observe different sources of truth.

**Comment by wanderview** [comment]
If the header is missing and there is no mime type from headers, will we still preserve the mime type from other sources?  For example, if the body provided is a blob with a type, etc.

**Comment by annevk** [comment]
In that case a header gets set, right? Or do you mean if someone were to remove the header afterwards? In that case I would not expect it to be preserved.

**Comment by wanderview** [comment]
Ok.  I forgot a header was created.  Thanks.

**Comment by annevk** [comment]
I created #1137. I'll also work on adding some more tests as well as updating the cache tests.
