### ISSUE TITLE
Firefox deletes all cookies from fetch request!

### ISSUE THREAD

**Issue by h110m** [whatwg/fetch#1182]
I am referring to my SO question --> https://stackoverflow.com/questions/34815845/how-to-send-cookies-with-node-fetch

TL;DR

When I try to use the `credentials` flag with either `same-origin` or `include` it includes the right cookies within the headers of my fetch request. However this only works in chrome. When I try this in Firefox it deletes the headers even if I set them manually with the `header` option.

I am using fetch with react to make a call to my backend. For more info pls read the StackOverflow question that I pinned at the top.

Hope someone could help me. I am going nuts here bcs I can't figure out why this is only not working in firefox.

**Comment by annevk** [comment]
That question does not seem related to what you are stating here and this is also not a support forum. I recommend filing a bug against Firefox. Make sure to include a testcase of sorts.

**Comment by h110m** [comment]
> 
> 
> That question does not seem related to what you are stating here and this is also not a support forum. I recommend filing a bug against Firefox. Make sure to include a testcase of sorts.

Sorry, I accidentally copied the wrong link into my clipboard. Corrected it.
Besides that, I also just wanted to know if this is just happening on my browser or if anyone already had the same issue.
I mean I don't know if firefox is deleting the cookie or maybe it is related to the fetch package.

**Comment by annevk** [comment]
You are not supposed to be able to set Cookie headers, see https://fetch.spec.whatwg.org/#forbidden-header-name. If it actually works in Chrome that would be a security bug, but I suspect you might have already had the cookie set in some other way in that browser.

**Comment by h110m** [comment]
I didn't really mean that I can set the cookie header myself in chrome. I just wanted to say that the cookies are sent with the fetch request in chrome as they should be because of `credentials: 'same-origin'`. I still can't set the cookie header myself in chrome. But at least it works with the credentials flag. Also when I don't include the credentials flag in chrome it sends the cookies with the request and this should happen since I read that it is set to 'same-origin' by default. But like I said in Firefox none of the values for the 'credentials' flag works and I don't know why. I mean like I said it would be nice if someone could test this so that I know that this is not specific because I am using fetch wrong or something.

**Comment by annevk** [comment]
I'm pretty sure that if Firefox actually did that a lot of the web would be broken and that isn't the case, so I suspect you are doing something wrong. In any event, this repository is for developing the Fetch Standard.

**Comment by h110m** [comment]
Oh ok
So where can i open an issue then?

**Comment by wanderview** [comment]
> So where can i open an issue then?

https://bugzilla.mozilla.org/enter_bug.cgi

Also, try testing in firefox safe mode as you might have an extension or other setting causing the behavior:

https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode

**Comment by h110m** [comment]
Thanks a lot for the `safe mode` suggestion. I tried it and it works but idk why. Anyway thanks a lot. it works now

**Comment by 556677152** [comment]
https://github.com/whatwg/fetch/issues/1182#issue-818259818
