### ISSUE TITLE
New Resource Timing issues

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#1201]
@noamr when looking at https://github.com/whatwg/xhr/pull/319 I started looking at `fetch()` again and I don't understand a couple things. Let's start with this bit:

> Let handleFetchDone be to finalize and report timing with response, globalObject, and "fetch".

Where does _response_ come from here? I guess https://fetch.spec.whatwg.org/#finalize-response has to pass it on.

How does this interact with callers of HTTP-network fetch that might take this response and determine to return a network error to the caller of fetch?

Another problem here is that this might not be the final response. We end up calling these things for redirects and such too.

One way to potentially solve this is that in "fetch finale" we declare that this response is the one we need to hear about in terms of a done callback.

I suppose if "fetch finale" got a network error we could at that point invoke "done" as well, if it should happen for network errors. Do you get an entry if there's a CORS failure? I'm not sure that's currently adequately covered.

**Comment by noamr** [comment]
In "fetch finale" we attach the timing info to the response. Intermediate redirect responses don't get that, so their `timing info` is null, and gets discarded when the `fetch params` are gone, so `report and finalize` will be a noop.

But I do see what you're saying, that `responseDone` is reported for intermediate responses - it should only be reported for responses with an attached `timing info` (we can make that more explicit with a flag)

**Comment by annevk** [comment]
From IRC:

> if I do `fetch("https://www.google.com")` and then check the last entry of `window.performance.getEntriesByType("resource")` it's there, so network errors do result in entries afaict

And note that in this case the network error is due to CORS. I think we should either report all network errors or none of them.

Doing this would also require some kind of integration with "fetch finale" as only there do we know if a response became a network error.

**Comment by noamr** [comment]
OK this is actually my oversight, CORS errors *should* be reported as an RT entry, but with some of the metrics zeroed. I'll post a PR to that effect.

**Comment by noamr** [comment]
https://github.com/whatwg/fetch/pull/1202 addresses both issues now.

**Comment by annevk** [comment]
Part of this was split into #1215.
