### ISSUE TITLE
Expose `transfer size` for resource timing

### ISSUE THREAD

**Issue by noamr** [whatwg/fetch#1203]
`transferSize` should be the same as `encodedBodySize` for HTTP responses, and zero for cached responses.
As per https://github.com/w3c/resource-timing/issues/238, it should not expose size of headers.

**Comment by annevk** [comment]
Can this not be inferred from other fields? Don't we already have a field to say whether something is from the cache?

**Comment by noamr** [comment]
> Can this not be inferred from other fields? Don't we already have a field to say whether something is from the cache?

No. Currently only from ‘transferSize’. Was thinking to exposed ‘is cached’ or something like that from FETCH and decide how to expose in RT

**Comment by annevk** [comment]
There's https://fetch.spec.whatwg.org/#concept-response-cache-state, isn't that sufficient?

**Comment by noamr** [comment]
> There's https://fetch.spec.whatwg.org/#concept-response-cache-state, isn't that sufficient?

According to the note, it only applies to service workers and not HTTP cache.

**Comment by annevk** [comment]
No, it's intended for usage by service workers, but it's set as part of the HTTP cache operations. Good point that we should update the note if we start using it for more things though.

**Comment by noamr** [comment]
> No, it's intended for usage by service workers, but it's set as part of the HTTP cache operations. Good point that we should update the note if we start using it for more things though.

Ok then. I will pass this flag to RT when creating the entry and RT can decide to expose it as ‘transferSize’.

**Comment by noamr** [comment]
https://github.com/whatwg/fetch/pull/1202 now addresses this.

**Comment by noamr** [comment]
Addressed.
