### ISSUE TITLE
Clarify which network errors create a resource timing entry

### ISSUE THREAD

**Issue by noamr** [whatwg/fetch#1215]
It's not clear from the spec/implementation which errors should or shouldn't create an RT entry.
CORS errors explicitly don't, though in the original Resource Timing spec they should create an RT entry. However, the discrepancy between different error types might create a case where it could be detected whether an error is of CORS nature, which should be avoided. 

See https://github.com/whatwg/fetch/pull/1202#pullrequestreview-634571341

**Comment by noamr** [comment]
See https://github.com/w3c/resource-timing/issues/12

**Comment by noamr** [comment]
See comment: https://github.com/whatwg/fetch/pull/1202#issuecomment-819286114

**Comment by noamr** [comment]
One simplified option would be that the caller is responsible to report the RT entry in case of a network/CORS error.
The caller (e.g. a `script` tag) knows when the call to FETCH was made and when it has received an error, so it could report those timing as the start/end time to resource timing, without exposing anything about the connection info.

Not sure if we want to expose connection info and other things when there was a network error, probably not.

**Comment by annevk** [comment]
Yeah, if we report network errors we want to act as if they are cross-origin and lack TAO. We could store the relevant information on the network error for the caller (it's a type of response after all, albeit rather special). That's my option 1.

Option 2 would be reporting all responses that are not network errors.

Option 3 would be reporting all responses that the caller considers actionable (i.e., would exclude non-2xx in case of `<script>`).

They are not in a preference order. I don't really know what would help web developers the most.

Whichever option we decide to go with should not provide a new information channel.

cc @yoavweiss @npm1 @rniwa @bdekoz @sefeng211

**Comment by annevk** [comment]
I noticed another problem, due to network errors having an empty URL list, finalize and report timing always returns early. So as currently specified option 1 does not work.

**Comment by npm1** [comment]
We briefly discussed this in the WebPerf WG call today, it wasn't clear to me if there's a use case for entries from network errors. Also @nicjansma pointed out that there's already overlap with the Reporting API.

**Comment by annevk** [comment]
You mean with https://w3c.github.io/network-error-logging/? That's true. If everyone is fine to align on no entries for network errors, let's do that.

**Comment by noamr** [comment]
@yoavweiss what's needed to reach consensus/conclusions on this?

**Comment by nicjansma** [comment]
While there is overlap with the Reporting API (Network Error Logging), I think there's value in keeping network-level errors, since the ergonomics and delivery are different (e.g. out-of-band reports).  If we're reporting network-level errors via Reporting API, is there concern about surfacing them through ResourceTiming as well (which is what most browsers are doing today)?

This is a lot of what the issue https://github.com/w3c/resource-timing/issues/12 was about, getting consistency on network-level and non-200 errors among the browsers.

I just did a quick refresh to see where browsers are today, and except for Safari, network-level errors are reported everywhere else:

https://github.com/w3c/resource-timing/issues/12#issuecomment-840316432

What we have today is aligned closer with @annevk 's Option 1, "... to act as if they are cross-origin and lack TAO".  The entries exist (except in Safari), but have all breakdown timestamps zero'd.  Just fetchStart/responseEnd/duration are set.

**Comment by noamr** [comment]
> While there is overlap with the Reporting API (Network Error Logging), I think there's value in keeping network-level errors, since the ergonomics and delivery are different (e.g. out-of-band reports). If we're reporting network-level errors via Reporting API, is there still concern about surfacing them through ResourceTiming as well (which is what most browsers are doing today)?
> 
> This is a lot of what the issue [w3c/resource-timing#12](https://github.com/w3c/resource-timing/issues/12) was about, getting consistency on network-level and non-200 errors among the browsers.
> 
> I just did a quick refresh to see where browsers are today, and except for Safari, network-level errors are reported everywhere else:
> 
> [w3c/resource-timing#12 (comment)](https://github.com/w3c/resource-timing/issues/12#issuecomment-840316432)
> 
> What we have today is aligned closer with @annevk 's Option 1, "_... to act as if they are cross-origin and lack TAO_". The entries exist (except in Safari), but have all breakdown timestamps zero'd. Just fetchStart/responseEnd/duration are set.

I also find that option the most sensible.

**Comment by yoavweiss** [comment]
^^ @achristensen07

**Comment by achristensen07** [comment]
Anne's suggestion seems reasonable, but that still makes it easier to distinguish a fast network error from a timeout.  Relatedly, should we also add an entry as if it were cross-origin and lacking TAO if there is no network error but the request times out?
This is being tracked in WebKit as https://bugs.webkit.org/show_bug.cgi?id=193902

**Comment by yoavweiss** [comment]
> Relatedly, should we also add an entry as if it were cross-origin and lacking TAO if there is no network error but the request times out?

@achristensen07 - We could add an entry in such a case, but it won't be difficult to guess it's a timeout, would it?



> Yeah, if we report network errors we want to act as if they are cross-origin and lack TAO

@annevk - that sounds overall reasonable to me as well, but I'd like for us to spell out the reasoning. Since cross-origin network errors lack TAO anyway, I'm guessing you also want same-origin network errors to not expose details. Is that because you're concerned they may expose details on the user's network? Or some other reason?

**Comment by annevk** [comment]
Yeah, basically until you have established a TLS connection, you don't really know if it's same-origin or not. And post-connection network errors are always about policy enforcement and we do not want to surface that to the caller either.

I think a system timeout should be the same as a network error, information-wise.

**Comment by noamr** [comment]
Have we reached consensus on this, @yoavweiss?

**Comment by yoavweiss** [comment]
I believe we have agreement to expose all network errors as if they are cross-origin with no TAO.

**Comment by noamr** [comment]
Closing the issue, as it doesn't have direct impact on the FETCH spec at this point, but rather on its callers.

**Comment by annevk** [comment]
I don't think that's correct. We'd have to at least start storing some information on network errors related to timing.

**Comment by noamr** [comment]
> I don't think that's correct. We'd have to at least start storing some information on network errors related to timing.

I don't believe so. The start time is stored on the request, and the end time is the time of calling the report function. But we can leave this open until we have the first reporter of network error (I guess that would be the fetch API, which we can track here).

**Comment by annevk** [comment]
I'm pretty sure we don't store anything about timing on requests, except for the timing allow failed flag bookkeeping detail.

**Comment by noamr** [comment]
> I'm pretty sure we don't store anything about timing on requests, except for the timing allow failed flag bookkeeping detail.

Right, the start time is in the fetch params. Perhaps we need to associate its timing info with a network error when we create it, in some "create a network error" algorithm.
