### ISSUE TITLE
Integrate early hints https://tools.ietf.org/html/rfc8297

### ISSUE THREAD

**Issue by ricea** [whatwg/fetch#1225]
Early hints are a mechanism permitting servers to indicate resources that might need to be preloaded before the final status and response headers are ready. This is implemented using the "103 Early Hints" status code. The protocol standard is here: https://tools.ietf.org/html/rfc8297.

Chrome is experimenting with early hints as an alternative to HTTP/2 push to reduce latency, without the complexity and traps of HTTP/2 push. Early results are promising.

Early hints will need to be integrated into the Fetch Standard processing model to ensure interoperability. This issue is to track that effort.

**Comment by noamr** [comment]
I can take on some of the spec'ing of this in fetch if needed, or help out if someone else is already taking it on.

**Comment by noamr** [comment]
The IETF mentions only `Link` headers as possible early hints. Are there any other early hints @ricea? I believe that we should spec link headers together with early hints, or spec link headers first.

**Comment by bashi** [comment]
My understanding is that 103 responses can contain arbitrary headers (unless these are explicitly disallowed). +1 to focus on link headers first.

**Comment by domenic** [comment]
I think this is done?

**Comment by bashi** [comment]
Yeah I think this can be closed. In the HTML spec we may want to relax the restriction (https://crbug.com/1361262) in the future but I think we can file another issue on the HTML spec.
