### ISSUE TITLE
Structured clone body serialization

### ISSUE THREAD

**Issue by pierogitus** [whatwg/fetch#1234]
In the spirit of `.json()`, could we make some enhancements to `Body` that behave more like structured clone? The goal would be more seamless handling of `ArrayBuffer, Date, BigInt`, cycles, etc. 

This would require a standard binary format. CBOR is a good fit since its tag mechanism can support cycles and current and future data types.

The api might look like:
- New property `bodyCBOR` on `RequestInit/ResponseInit` so as not to conflict with the semantics of the `body` property
- `.cbor()` method on `Body`
- Feature detection that exposes supported tags (data types) for future proofing

**Comment by annevk** [comment]
This should be standardized in HTML and is being tracked there in https://github.com/whatwg/html/issues/3517. Doesn't seem to have garnered a lot of interest.
