### ISSUE TITLE
Allow operation to outlive the document unloading (beacon)

### ISSUE THREAD

**Issue by pornel** [whatwg/fetch#124]
The [Beacon API](http://www.w3.org/TR/beacon/) adds a new feature to the platform — non-Service-Worker requests that outlive their document — but adds it in a high-level API with a narrow use-case (and poorly defined delivery, which is nether at-most-once, nor at-least-once).

There is no [lower-level primitive in that "explains"](https://extensiblewebmanifesto.org/) the Beacon API. Perhaps `fetch` could be it? 

```
function sendBeacon(url, body) {
    fetch(url, {
        method: 'post',
        body,
        detachedFromDocumentLifetime: !!"bikeshed",
        keepRetryingInUnspecifiedManner: "like the beacon spec",
        ageHeaderUpdatedOnRetry: 'Beacon-Age',
    });
}
```

**Comment by annevk** [comment]
I think it might be better to let implementations mature a bit around `ping=""` and `sendBeacon()`. The ideal architecture likely hasn't been found yet.

**Comment by pornel** [comment]
OK.

There's one more related feature that I'm interested in: avoiding waking up mobile radio (as far as I understand mobile devices can switch radio to a low power state when it's not in active use, and network activity causes radio to switch back to a high-power mode, which quite expensive battery-wise).

In the app I have many non-critical requests, such as beacons and background data synchronization, that are not time-critical. To save battery, I would like to let the browser delay these requests if the radio is in low-power mode, and fire the requests when something else happens to need to wake the radio up (or after a certain deadline).

**Comment by igrigorik** [comment]
> There's one more related feature that I'm interested in: avoiding waking up mobile radio (as far as I understand mobile devices can switch their radio to a low power state when it's not in active use, and any network activity causes radio to switch back to a high-power mode, which quite expensive battery-wise).

FWIW, this is within scope of Beacon -- this is why we introduced Beacon-Age. That said, afaik none of the existing implementations have implemented any logic to take advantage of this... yet. 

/cc @toddreifsteck

**Comment by pornel** [comment]
How is this supposed to work with Service Workers? Does beacon-related fetch retain beacon's magical behavior?

I can't use Beacon without SW, since unreliable delivery, as well as browser-specific (stats-skewing) retry logic is not acceptable for my use cases.

**Comment by igrigorik** [comment]
> How is this supposed to work with Service Workers? Does beacon-related fetch retain beacon's magical behavior?

Yes, it's the lower-level net stack that's in position to figure out how and when requests can be coalesced to reduce energy use, etc. As such, you'd see a regular request in SW, which you pass through and allow the net-stack to figure out how and when to deliver it.

**Comment by annevk** [comment]
@pornel you might want to weight in on https://github.com/w3c/beacon/issues/27 if you think this should be part of the `fetch()` method somehow. I haven't really made up my mind, but I think you're probably right that it belongs in `fetch()` if that continues to be our low-level primitive.

**Comment by annevk** [comment]
Note that your other request is discussed in #184 (`Beacon-Age` is gone and coalescing might replace it).
