### ISSUE TITLE
blob scheme with non-GET method

### ISSUE THREAD

**Issue by hiroshige-g** [whatwg/fetch#125]
File API Spec stated that only GET method must be accepted:
  http://www.w3.org/TR/2013/WD-FileAPI-20130912/#processingModel
    "User agents must only support requests with GET"

  http://www.w3.org/TR/FileAPI/#requestResponseModel
    "The URL and Fetch Specifications should be considered normative for parsing and fetching Blob URLs. The section below is for informational purposes only, and is not considered normative."
    "Only requests with GET [RFC7231] are supported."

However, the Fetch API spec allows non-GET methods.

Is this change intentional?

Test code:
var url = URL.createObjectURL(new Blob(["foo"]));
var xhr = new XMLHttpRequest;
xhr.open('POST', url);
xhr.onload = function() { console.log("LOAD"); };
xhr.onerror = function() { console.log("ERROR"); };
xhr.send();

Chrome (47.0.2508.0 canary): ERROR
Firefox (nightly, 40.0.2): LOAD
Fetch API Spec: LOAD
File API Spec: ERROR

**Comment by annevk** [comment]
We should add a check to https://fetch.spec.whatwg.org/#basic-fetch "blob" for the request method, I think.

**Comment by wanderview** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1205288
