### ISSUE TITLE
Mismatch between body length and user provided content-length header.

### ISSUE THREAD

**Issue by ronag** [whatwg/fetch#1281]
I don't think the spec handles the case where there is a mismatch between body length and user provided content-length header.

In https://github.com/nodejs/undici we throw and error and kill the connection in this case.

However node-fetch seems to infer that this should be possible, https://github.com/node-fetch/node-fetch/blob/main/test/main.js#L921.

What is the correct behavior for fetch?

**Comment by annevk** [comment]
You cannot set this header, see https://fetch.spec.whatwg.org/#forbidden-header-name (and call sites).
