### ISSUE TITLE
4.7. HTTP-network fetch references undefined "httpRequest"

### ISSUE THREAD

**Issue by ronag** [whatwg/fetch#1283]
> 4. Let httpCache be the result of determining the HTTP cache partition, given httpRequest.

References `httpRequest`. However, that variable is not defined in the context.

**Comment by Krishnaraj-shankar** [comment]
where can I find the issue in that website @ronag .Im a beginner .would you help me to sort it out

**Comment by annevk** [comment]
Either #1290 or #1298 will address this.
