### ISSUE TITLE
provide a way to construct a new Request from an old Request and an overriding URL

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#129]
I've seen a couple different snippets of code now that try to override the URL on a Request.  They want to keep all attributes about the Request, but just change the URL.  All the code I've seen try this has gotten it wrong.  They always forget to propagate some field in Request, the body, headers, etc.  Its also hard to maintain as we keep adding attributes to Request.

It would be nice to have a constructor that consumes an old Request and override the URL.

**Comment by wanderview** [comment]
I guess this mostly works if you treat oldRequest as the dictionary passed as the second arg to new Request().  That does not currently propagate the body, though.  We need streams for that.

**Comment by mislav** [comment]
Has it become possible in the meantime to construct a new Request exactly like the original one, including propagating its body, but with a changed URL?

Why was this closed? It seems like it's a legitimate feature request to have.

**Comment by annevk** [comment]
@mislav I think it should work now in theory, but unsure whether upload streams have shipped.
