### ISSUE TITLE
Does sendBeacon() need to respect CORP?

### ISSUE THREAD

**Issue by domenic** [whatwg/fetch#1299]
No response is ever returned so it doesn't seem like there should be a danger. This might ease cross-origin isolation migration.

I suspect we couldn't do the same for `fetch(, { keepalive: true })` since I think you might be able to get a response code and/or body out of that? But `sendBeacon()` might be safe.

**Comment by domenic** [comment]
I guess this might only be observable today through reporting. So I think what I'm really asking is whether we should just avoid sending reports for sendBeacon()-initiated fetches that violate CORP, since the violation didn't actually change anything about the program.

**Comment by annevk** [comment]
Would this not follow from #1215?

Although maybe you are talking about Network Error Logging? I guess that still lacks Fetch integration so it would be unclear.

**Comment by domenic** [comment]
I'm specifically thinking of https://fetch.spec.whatwg.org/#queue-a-cross-origin-embedder-policy-corp-violation-report , although it sounds like indeed there's a constellation of issues here that might be best solved in a unified way...

**Comment by annevk** [comment]
Ah I see, I guess I would expect a report there (assuming the fetch completed within the lifetime of the document).

**Comment by domenic** [comment]
Yeah, I'm not sure. It seems to fall out of the infrastructure naturally, but in practice, the app will behave exactly the same with or without CORP on the `sendBeacon()` endpoint, so the report isn't actually useful to people and just makes it harder to sort through telemetry and deal with the real reports.

**Comment by yutakahirano** [comment]
We need to check CORP for redirect responses.

**Comment by domenic** [comment]
Hmm. So given `sendBeacon(a)` where `a` redirects to `b`, if `a` is missing the CORP header, then `b` will never get hit. Right?

In that case I agree a report is useful. And, it's probably not worth suppressing the reports in the no-redirect case. So, I'll close this.

Thanks!
