### ISSUE TITLE
Consider renaming processRequestBody

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#1320]
processRequestBodyChunk or even processRequestBodyChunkSize would be more representative and either of those would make it clear it's different from processResponseBody, which is only invoked once and is actually passed a response.

Thanks to Tab for making me realize this.

Marking this as a good first issue as it is somewhat straightforward to rename this in various places, but note that this will also require a change to XMLHttpRequest (https://github.com/whatwg/xhr).

**Comment by Fictionistique** [comment]
I have found processRequestBody in four places in [whatwg/fetch](https://github.com/whatwg/fetch) and in 7 places in [whatwg/xhr](https://gtihub.com/whatwg/xhr).

In whatwg/fetch:
line 3670 and 3678 of /fetch.bs
line 3585 and 3593 of review-drafts/2021-06.bs 

In whatwg/xhr:
line 801 and 899 in /xhr.bs
line 802 and 900 in review-drafts/2021-08.bs
line 796, 908 and 909 in review-drafts/2021-02.bs

Is that all I have to change to processRequestBodyChunkSize and shall I open a PR for this?
Thanks in advance!

**Comment by annevk** [comment]
Hey @Fictionistique, thanks for your interest. We also want to rename "process request body". And the `<dfn>` for that should be given an explicit ID of `fetch-params-process-request-body` to keep the existing links working.

And we don't want to change anything in the `review-drafts/` directories.

Hope that helps!

**Comment by Fictionistique** [comment]
Hey @annevk, thank you for your help! I've made a pull request. Please take a look. Thank you!
