### ISSUE TITLE
Request constructor should propagate origin internal field

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#1321]
Currently, the Request constructor always resets the request `origin` internal field to "client".  See step 12 in:

https://fetch.spec.whatwg.org/#dom-request

This is problematic because a pass-through FetchEvent SW handler will end up using the service worker's origin for things like:

* Origin header
* Sec-Fetch-Site header
* SameSite cookies

It would be safer for sites if we propagated the internal `origin` field from the original request.  We also need to propagate the `tainted origin flag` as well in order to properly handle redirects.

This was discussed at the virtual F2F (w3c/ServiceWorker#1604).  [Notes](https://docs.google.com/document/d/1q74ATke1oG2jEval1yBTVIrXZGItFi6DR5l8n_8ybgs/edit#bookmark=id.bg7ds8878foi) are available.

**Comment by annevk** [comment]
Right, if we care enough about the CSRF angle to propagate origin (and top-level?), we also need ancestor information.

**Comment by wanderview** [comment]
Well, at least for my example I don't think it would matter.  If A frames B1 and B1 navigates to B2, then B2 has the same ancestor chain.  So once service workers are partitioned and set its site for cookies based on the partition key the effect would be the same.

I guess propagating site for cookies would still be relevant for cases where B1 does window.open() to B2.  Do we allow frames to create popups like that?

**Comment by wanderview** [comment]
I don't see any information on request representing "site for cookies" right now.  Does that exist?  Are SameSite cookies not integrated in fetch spec yet?

Maybe we should fork "site for cookies" propagation out into a separate issue.
