### ISSUE TITLE
propagate request tainted origin flag and/or URL list through service workers

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#1335]
Similar to #1321, we also need to propagate the request [URL list](https://fetch.spec.whatwg.org/#concept-request-url-list) through a service worker `evt.respondWith(fetch(evt.request))`.  This is necessary to send the proper values for origin, sec-fetch-site, samesite cookies, etc when a request has redirected through a cross-origin url.

This is related to the collection of topics discussed at w3c/ServiceWorker#1604.

**Comment by annevk** [comment]
I think turning it into an algorithm that operates on request's origin and URL list, and returns "same-origin", "same-site", or "cross-site" is probably reasonable. This would require adjusting the logic in "CORS-preflight fetch" some to clone the URL list.

**Comment by wanderview** [comment]
So I started working on a pull request to remove the `tainted origin flag` and replace it with an algorithm that operates on the `URL list`.  I realized, though, we can't propagate the `URL list` to a CORS preflight without side effects.  Mainly, it would reduce the redirect count permitted for preflights by however large the original request's `URL list` is.

So I guess for now the easiest thing to do is propagate both the `tainted origin flag` and the `URL list` when constructing an unmodified copy of another request.

**Comment by annevk** [comment]
@wanderview I don't think that matters as a preflight response isn't allowed to be a redirect. It has to be a 2xx.

**Comment by wanderview** [comment]
Hmm, I looked to see if it used a redirect mode of `error`, but didn't see it.  I see, though, that its done as a separate check in step 7 of:

https://fetch.spec.whatwg.org/#cors-preflight-fetch-0

For some reason I thought http-network-or-cache-fetch would follow the redirect.

Ok, I'll try changing back to removing the tainted origin flag.

**Comment by wanderview** [comment]
Note, I think we will also need a change to html spec to make navigation populate the request `URL list` when it manually follows redirects.

**Comment by annevk** [comment]
HTML invokes https://fetch.spec.whatwg.org/#navigate-redirect-fetch which invokes https://fetch.spec.whatwg.org/#concept-http-redirect-fetch which appends to request's URL list.
