### ISSUE TITLE
Content-Length on HEAD

### ISSUE THREAD

**Issue by mnot** [whatwg/fetch#135]
https://fetch.spec.whatwg.org/#http-network-or-cache-fetch

> If httpRequest's body is null and httpRequest's method is `HEAD`, `POST`, or `PUT`, set contentLengthValue to `0`.

Why is C-L set on HEAD requests?

See:
  http://httpwg.github.io/specs/rfc7230.html#message.body.length

**Comment by annevk** [comment]
See https://www.w3.org/Bugs/Public/show_bug.cgi?id=25684 and https://chromium.googlesource.com/chromium/src/+/ca9d6916c5fedf6f0ee73dfc397cb0f65ad326b9/net/http/http_network_transaction.cc#894 which it points to.

**Comment by annevk** [comment]
(Your pointer doesn't say much about `Content-Length` on requests as far as I can quickly tell.)

**Comment by mnot** [comment]
From 7230:

> 6. If this is a request message and none of the above are true, then the message body length is zero (no message body is present).

This means that C-L is not required on requests.

To be clear - nothing's going to break if you put C-L: 0 on HEAD requests, but there's no good reason to require them.

The justification in the 25684:

> because maybe you're sending a HEAD request to something which normally only deals with POST requests and needs a message body

Is really poor. Parsing HTTP is well-defined and defined in a certain way to be robust. I'm totally behind making decisions based upon data and real interoperability results, but taking a subsample of implementations and deciding to redefine behaviour based upon that ("because maybe"? Really?) is not data-driven, it's cargo cult design.

In the future, maybe ask - even if it's just pinging me or @mcmanus?

**Comment by annevk** [comment]
That browsers feel compelled to add it based on what other browsers are doing is telling. If those three browsers were to change their behavior then we could maybe change the specification, but given that they are all doing this there is a high likelihood it is actually important.

**Comment by mnot** [comment]
... or that they just look at each other's code and copy it (as the discussion seems to indicate). It'd be great to actually talk to someone who made that decision or had access to the data, rather than guessing.

**Comment by annevk** [comment]
I guess we can ask @sleevi if he would consider changing it.

**Comment by sleevi** [comment]
> To be clear - nothing's going to break if you put C-L: 0 on HEAD requests, but there's no good reason to require them.

The good reason is compatability, not copy-and-paste. In the real world, people don't read the specs, bugs happen. 7230 is not a good justification for behaviour changes - it suffers from the normal aspirational vs reality problems, whereas Fetch() & friends tries to reflect the latter.

The complaint here seems to be primarily with Chrome's comment, which may be poorly worded, but was our best guess at _why_ this was happening, not a statement as to why we were doing it (we were doing it for compatibility with servers and other clients; we presumed it was for X, but regardless, saw it as necessary)

As to the question of would we change, we're not opposed to removing workarounds, especially if the compat story has improved, but figuring out whether it's safe to remove the workarounds often takes 3-6 months and dedicated monitoring, and I don't know if anyone's signing up for that. At the least, you could file a bug in the Chrome bug tracker to see if someone soul will take it up and champion it to measure interop issues.

(For what it's worth, this issue goes back to the very first commit of Chromium; I haven't dug in further to the pre-opensource code to figure out the full metrics, but each of those decisions was not made lightly - Compat was the goal)

**Comment by annevk** [comment]
Closing this since there's no indication browsers will change this.

**Comment by annevk** [comment]
Chrome did change this https://chromium.googlesource.com/chromium/src/+/master/net/http/http_network_transaction.cc#982 as was pointed out to me in  https://bugzilla.mozilla.org/show_bug.cgi?id=1286743 by Thomas Wisniewski.
