### ISSUE TITLE
TAO support for iframes

### ISSUE THREAD

**Issue by noamr** [whatwg/fetch#1387]
Currently TAO (Timing-Allow-Origin) is checked as part of the CORS mechanism.
However, for iframes it needs to be checked at the end, relative to the containing document's origin.
Implementations already do this.

I wonder how to go about it spec-wise:
- To create a variant of `Finalize and Report timing` that does this, receiving an origin
- Export some internals of the TAO check and let HTML do this when reporting an iframe (I think I prefer this, and it's closer to implementations)

**Comment by noamr** [comment]
@annevk, any thoughts?

**Comment by annevk** [comment]
I think I agree with your take that this is something HTML's navigate algorithm needs to solve, relying on infrastructure provided by Fetch.

We should also explore the relation to navigation timing as an `iframe` element is essentially a nested navigation.
