### ISSUE TITLE
Persisting headers on redirect

### ISSUE THREAD

**Issue by adammw** [whatwg/fetch#139]
The spec makes no mention about persisting any headers if the response is a redirect status and redirects are being followed (or at least, that I could see) - is this by design?

For example, must the web developer handle the case of 302 redirects for range requests manually?

**Comment by annevk** [comment]
Do you mean request headers? They are persisted since the underlying request is only tweaked a little bit when following redirects. Headers are not affected.

**Comment by annevk** [comment]
Closing this due to lack of response. Please let me know if anything is still unclear.
