### ISSUE TITLE
fetch() needs to send a */* header

### ISSUE THREAD

**Issue by ehsan** [whatwg/fetch#142]
It seems like fetch() is currently expected to not send an Accept header at all unless one is specified by the caller.  This looks wrong.  We need to send */* when no headers are provided by the author.

**Comment by wanderview** [comment]
As an example, people write code like this which expect Accept to always be present:

```
   var doesRequestAcceptHtml = function (request) {
        return request.headers.get('Accept')
            .split(',')
            .some(function (type) { return type === 'text/html'; });
    };
```

From:

  https://www.theguardian.com/service-worker.js

**Comment by annevk** [comment]
Why should we? We intentionally omitted this defaulting so folks have more control over the network layer.

**Comment by ehsan** [comment]
Do we know that not sending Accept: */* is Web-compatible?

**Comment by wanderview** [comment]
They can still override Accept via the Request headers.  They just have to send something for Accept.

What value is there in allowing them to send no Accept header?  It seems that is not done anywhere today and could break servers, etc.

Again note, we've already seen one large site that assumes every request will have an Accept.

**Comment by wanderview** [comment]
Note, we're trying g to say the default should be `*/*`.  I think markdown was messing with the formatting in previous comments.

**Comment by ehsan** [comment]
I agree, this is what we're going to implement in Gecko.

**Comment by annevk** [comment]
Yes and I'm saying that we explicitly do not want a default. How would you not send this header? I don't see why this would not be compatible, `fetch()` is new.

**Comment by wanderview** [comment]
> Yes and I'm saying that we explicitly do not want a default. How would you not send this header? I don't see why this would not be compatible, fetch() is new.

What semantic difference does sending no header have compared to sending `*/*`?

FWIW, I checked chrome and it does not send an Accept header for fetch() as far as I can tell.

**Comment by wanderview** [comment]
Depending on the outcome of this issue, this is the gecko bug to possibly remove the accept header.

https://bugzilla.mozilla.org/show_bug.cgi?id=1217933

**Comment by ehsan** [comment]
> I don't see why this would not be compatible, fetch() is new.

My point about web-compat was for web servers, not the client code.

**Comment by annevk** [comment]
Well, if you are writing new client code, that might sometimes require changes on the server too. Same with push or some such.

**Comment by ehsan** [comment]
Yes, one could argue that.  But you can also argue that given that we have taken away XHR from `ServiceWorkerGlobalScope`, there is no easy way to get the old behavior back, so if you're dealing with a server that breaks because of missing `Accept` headers you are going to have the joy of debugging what the cause is.  That seems terrible to me if we want this to be friendly to web developers.

**Comment by annevk** [comment]
@domenic, what do you think?

**Comment by domenic** [comment]
This was recently discussed on Twitter a bit: https://twitter.com/bagder/status/660770080108711936 apparently curl sends `Accept: */*`, although they are not sure on if it is necessary (anymore?). @mnot says to not do so.

My personal opinion is that `*/*` seems like a reasonable default for `Accept`, as long as it can be overridden by authors to be whatever they want (including removed entirely). Author control over headers in fetch is already crippled and defaulted in a lot of ways if I recall (for security and other reasons), so one more default doesn't seem too bad.

**Comment by annevk** [comment]
Okay, I'm happy to add it back. Getting it removed entirely would require some special kind of optin flag though that I suppose we can add later.

(And yes, there are a number of headers that cannot be controlled for security reasons, such as `Host`.)

**Comment by wanderview** [comment]
Even if it cannot currently be removed entirely, it can be set to an empty header.

**Comment by annevk** [comment]
While true, that is semantically distinct and therefore does not expose the theoretical full potential of HTTP. But given that it's all tradeoffs we might not offer the `Accept`-less API for the foreseeable future.
