### ISSUE TITLE
Editorial: using serialized origin in TAO check and "null"

### ISSUE THREAD

**Issue by noamr** [whatwg/fetch#1421]
In https://fetch.spec.whatwg.org/#tao-check, the TAO header is checked to see if it includes request's serialized origin.
However, for redirect-tainted requests, https://fetch.spec.whatwg.org/#serializing-a-request-origin will return the string `"null"`.
This would imply that `Timing-Allow-Origin: origin-a.com, null` would succeed for redirect-tainted requests.

Suggesting not to use `serializing-a-request-origin` here.

**Comment by annevk** [comment]
This doesn't seem editorial and I'm also not entirely sure why this is wrong. CORS works the same way.

**Comment by noamr** [comment]
> This doesn't seem editorial and I'm also not entirely sure why this is wrong. CORS works the same way.
Not wrong as in, `Timing-Allow-Origin: origin-a.com, null` is valid for redirect-tainted requests? That's surprising to me. If that's the case it should be better WPT-covered.

**Comment by annevk** [comment]
It works for CORS as well (although there was some argument we should not accept it for credentialed requests, but I think the specification still does).

**Comment by noamr** [comment]
> It works for CORS as well (although there was some argument we should not accept it for credentialed requests, but I think the specification still does).

Got it. I'll amend the iframe-TAO PR to account for this and close this issue. Will add tests separately.
