### ISSUE TITLE
" [SameObject] readonly attribute ReadableStream..."

### ISSUE THREAD

**Issue by martinthomson** [whatwg/fetch#143]
https://fetch.spec.whatwg.org/#response

>  [SameObject] readonly attribute ReadableStream body;

As discussed @TPAC, I think that we need to tee the stream (i.e., clone it) when accessing the body, which suggests that this not use `[SameObject]` and rather that it be a method.

**Comment by annevk** [comment]
Wait why? I don't recall discussing that.

**Comment by martinthomson** [comment]
No, I think that you are right, in retrospect, this isn't right.
