### ISSUE TITLE
Proposal: add a boolean flag `render-blocking` to the `request` concept

### ISSUE THREAD

**Issue by xiaochengh** [whatwg/fetch#1433]
(Edited: Removed the parts about exposing it via the [`Request` API](https://fetch.spec.whatwg.org/#request-class))

The HTML spec recently specified a [render-blocking mechanism](https://html.spec.whatwg.org/C/#render-blocking-mechanism), which allows certain elements to be [render-blocking](https://html.spec.whatwg.org/C/#render-blocking), namely, to block rendering until their external resources have been loaded.

In coordination, I'm proposing to add a boolean flag, `render-blocking`, to the [`request` concept](https://fetch.spec.whatwg.org/#concept-request) to indicate whether the request is for an element that is render-blocking. For now, the flag is not web-exposed via the [`Request` API](https://fetch.spec.whatwg.org/#request-class).

The technical details are at:
- whatwg/fetch#1432
- whatwg/html#7885

The motivations are:

1. It can be used as a signal for "chaining" render-blocking resources: render-blocking resource A can have a link header with `blocking=render` that triggers loading of another render-blocking resource. This is especially useful for eliminating FOIT & layout shifts for 3rd party web fonts (see [exact usage](https://gist.github.com/xiaochengh/9404abbecdc3b45c0e9f3d5e99fbc65d#use-cases)).

2. It can be used as a signal to set the fetch [priority](https://fetch.spec.whatwg.org/#concept-request-priority), so that we never fetch a render-blocking resource at the low priority. The [current spec](https://fetch.spec.whatwg.org/#ref-for-concept-request-priority) only uses two signals, which are not enough. See also discussions at https://github.com/WICG/priority-hints/issues/69

**Comment by xiaochengh** [comment]
@annevk @yoavweiss @domenic

**Comment by annevk** [comment]
These use cases are only applicable when a service worker is in use, right? And when you say Chrome has already been doing it, that's presumably limited to DevTools, which is a somewhat different use case and would not end up standardized by exposing this on `Request` objects (note that these are somewhat distinct from the underlying request concept, where I agree we need to add it for determining priority and such).

**Comment by yoavweiss** [comment]
I believe what @xiaochengh meant is that Chromium exposes this to traces, which are [used](https://blog.webpagetest.org/posts/new-render-blocking-indicator-in-chrome-and-webpagetest/) by developer tooling, and found to be [useful by developers](https://sia.codes/posts/render-blocking-resources/).

It's a different use case, but e.g. makes me think we should [web expose](https://github.com/w3c/resource-timing/issues/262) this info in Resource Timing. I agree that an internal flag would be sufficient for that.

I guess that for web-exposing the flag on the Request object itself we'd need a Service-Worker case that e.g. treats scripts and style requests differently when they are render blocking.

**Comment by xiaochengh** [comment]
Hmm, maybe I didn't realize there's a difference between the request concept and the `Request` object... (as @annevk mentioned in https://github.com/WICG/priority-hints/issues/69#issuecomment-1112951552 but I didn't fully understand...)

What I really want to do is to add it to the request concept, which already supports use cases 2 & 3. We don't really have a service worker use case so we don't really need to add it to the `Request` object.

Is adding it only to the request concept fine to you? If so, I'll revise the proposal and the PRs.

**Comment by annevk** [comment]
Yeah, that is totally fine. It's in fact preferable as it allows us to evaluate the "private API" for some time before deciding it's worth exposing publicly.

**Comment by xiaochengh** [comment]
Thanks. I've updated the proposal and the PRs. Please review them at:
- whatwg/fetch#1432
- whatwg/html#7885

**Comment by noamr** [comment]
I'm not sure about this.
I don't know if the concepts of render blocking should belong in fetch. It's great if blocking resources give some priority indication to fetch, but perhaps extensinf the current definition of fetch priority is sufficient for that?

How would it interact with `fetchpriority=low` for example?
Maybe it should be `fetchpriority=render-blocking` or so? And then we don't need to set blocking=render on preloads (see https://github.com/whatwg/html/issues/7896) and we can set it solely on the resource use itself, and play with the priority only?

**Comment by xiaochengh** [comment]
> How would it interact with fetchpriority=low for example?

UA should look at both `fetchpriority` and render-blocking when setting the "real" priority (see discussion https://github.com/WICG/priority-hints/issues/69). In Blink's implementation, I'm planning to bump the priority to at least `high` if render-blocking (see patch https://chromium-review.googlesource.com/c/chromium/src/+/3627294).

For the remaining questions, I think they all depend on whether we want blocking=render on preloads. I've responded in whatwg/html#7896.
