### ISSUE TITLE
simple range header value parser does not allow for suffix-byte-range-spec

### ISSUE THREAD

**Issue by dlrobertson** [whatwg/fetch#1450]
Currently the [simple range header value](https://fetch.spec.whatwg.org/#simple-range-header-value) does not allow for the [suffix-byte-range-spec](https://httpwg.org/specs/rfc7233.html#rule.ranges-specifier). The [simple range header value](https://fetch.spec.whatwg.org/#simple-range-header-value) would not return true for the following example in [RFC 7233](https://httpwg.org/specs/rfc7233.html):

> Additional examples, assuming a representation of length 10000:
>
>    The final 500 bytes (byte offsets 9500-9999, inclusive):
>
>      bytes=-500

`rangeStart` would be a string with length 0, and would not pass the following:

> If rangeStart, interpreted as decimal number, is greater than rangeEnd, interpreted as decimal number, then return false.

**Comment by jakearchibald** [comment]
Do browsers ever send a header in that format?

My intent was to be cautious, and only allow stuff browsers already send. If browsers already send this, or a browser wants to start sending this (and folks are confident it's safe to do so), then it makes sense to update the spec.

**Comment by dlrobertson** [comment]
Thanks for the info!

> My intent was to be cautious, and only allow stuff browsers already send. If browsers already send this, or a browser wants to start sending this (and folks are confident it's safe to do so), then it makes sense to update the spec.

This makes a lot of sense, especially since all suffix-byte-range-spec ranges can be represented with a byte-range-spec.

> Do browsers ever send a header in that format?

Not that I know of. I opened this issue as I started looking into working on blob range requests (https://github.com/whatwg/fetch/issues/1070). In which, we intend to re-use the single range header parser to also parse the range for the blob request. Once blob range requests are supported, a user could use a suffix-byte-range-spec to attempt to slice the blob. We don't have to support this case (just like we don't support multiple ranges).

**Comment by annevk** [comment]
I think we ended up inadvertently allowing this as part of #1454.

Although really the existing text was buggy and didn't handle _rangeStart_ being the empty string.

I guess we should explicitly disallow it and add a test for it, at least when it comes to "`cors`". That would result in it requiring a preflight, which seems reasonable.

**Comment by annevk** [comment]
I created #1501 to address this. The result of this is that we have parser support, but no preflightless CORS support for this construct.

**Comment by dlrobertson** [comment]
Closing as AFAIK #1454 and #1501 fixed this.
