### ISSUE TITLE
blob: fetch of slice() without valid content type yields unexpected results

### ISSUE THREAD

**Issue by dlrobertson** [whatwg/fetch#1464]
Based on my reading of [blob.slice()](https://w3c.github.io/FileAPI/#dfn-slice), it seems that the resulting blobs content type should be the empty string under the following cases:

 1) `contentType` is not given
 2) `contentType` has a value outside the range of U+0020 to U+007E

After writing a simple wpt test, it seems like no browser does 1 and only one does 2.

| Test | Safari | Chrome | Firefox |
|-----|-------|---------|--------|
|no `contentType`|:x:|:x:|:x:|
|bad `contentType`|:white_check_mark:|:x:|:x:|

Note that in each of these cases the `type` value of the slice is the empty string. This issue may be related to https://github.com/whatwg/fetch/issues/1436.

Just in case the issue is actually my test cases 😄, I've attached the example I used below:

```
promise_test(function(test) {
  var blob = new Blob(["this has no content type"]);
  let slice = blob.slice(12, 24, "\0");
  return fetch(URL.createObjectURL(slice)).then(function (resp) {
    assert_equals(resp.status, 200, "HTTP status is 200");
    assert_equals(resp.type, "basic", "response type is basic");
    assert_equals(resp.headers.get("Content-Type"), "");
    assert_equals(resp.headers.get("Content-Length"), "12");
    return resp.text();
  }).then(function(bodyAsText) {
    assert_equals("content type", bodyAsText)
  });
}, "Set content type to the empty string for slice with invalid content type");

promise_test(function(test) {
  var blob = new Blob(["this has a content type"], {"type": "application/xml"});
  let slice = blob.slice(11, 23);
  return fetch(URL.createObjectURL(slice)).then(function (resp) {
    assert_equals(resp.status, 200, "HTTP status is 200");
    assert_equals(resp.type, "basic", "response type is basic");
    assert_equals(resp.headers.get("Content-Type"), "");
    assert_equals(resp.headers.get("Content-Length"), "12");
    return resp.text();
  }).then(function(bodyAsText) {
    assert_equals("content type", bodyAsText)
  });
}, "Set content type to the empty string for slice with no content type ");
```

**Comment by dlrobertson** [comment]
I originally incorrectly filed this as https://github.com/w3c/FileAPI/issues/177, but @inexorabletash correctly pointed out that in each of the test cases, while the content type from the header was not the empty string, the sliced blob `type` was.

**Comment by inexorabletash** [comment]
I commented on the other bug:

> I haven't stared at Fetch enough, but it does seem inconsistent - _to get a header name_ should only return null if the header list does not contain the header, yet the "blob" fetch algorithm unconditionally appends Content-Type with the blob’s type. It may be that Fetch needs to define an attempt to parse the type, and on failure not append.

**Comment by smaug----** [comment]
So what do browsers do then? Note, an upcoming change to Gecko will probably change case 2 to behave like webkit.

**Comment by dlrobertson** [comment]
> So what do browsers do then?

|Test                         |Firefox       |Chrome| Safari                  |
|-------------------|-----------|--------|-----------------|
|no `contentType`  |`text/plain`|`null`   |`""`                      |
|bad `contentType`|`text/plain`|`null`   |`application/xml`|

> Note, an upcoming change to Gecko will probably change case 2 to behave like webkit.

:+1: with the patch gecko does in fact return `""` for both tests.

**Comment by annevk** [comment]
There's at least two different things here:

1. File API currently doesn't use "parse a MIME type", but it should: https://github.com/w3c/FileAPI/issues/43. (There's already tests for this in WPT.)
2. Fetch should probably special case the empty string value and not set a `Content-Type` header in that case. I think "we" forgot to account for that case.

**Comment by dlrobertson** [comment]
The tests from this issue are posted in https://github.com/web-platform-tests/wpt/pull/35469

**Comment by dlrobertson** [comment]
https://github.com/whatwg/fetch/issues/1436 had a large amount of overlap with this issue, and the associated wpt tests PR https://github.com/web-platform-tests/wpt/pull/36243 contains tests for this [here](https://github.com/web-platform-tests/wpt/blob/master/fetch/api/basic/scheme-blob.sub.any.js#L78-L118).

| Test                                                                                                             | Safari | Chrome | Firefox |
|----------------------------------------------------------------------|-------|---------|--------|
|Set content type to the empty string for slice with invalid content type | :x: | :x: | :x: |
|Set content type to the empty string for slice with no content type        | :x: | :x: | :x: |
|Blob.slice should not sniff the content for a content type                        | :white_check_mark: | :x: | :x: |

Is is a WebKit issue for this? If so, I think we can close this unless we need separate issues from those posted in https://github.com/whatwg/fetch/issues/1436 for Chrome and Firefox (I plan to do the work for this in https://bugzilla.mozilla.org/show_bug.cgi?id=1771423)?

**Comment by annevk** [comment]
Filed https://bugs.webkit.org/show_bug.cgi?id=246519. Thanks again Dan!
