### ISSUE TITLE
Remove about:unicorn

### ISSUE THREAD

**Issue by jdm** [whatwg/fetch#147]
It's cute, but it's also a really large addition to an otherwise unimportant part of the spec.

**Comment by annevk** [comment]
Why not implement it? 😊

**Comment by travisleithead** [comment]
I think we need to keep it. There is precedent.

```
↪An end tag whose tag name is "sarcasm"
   Take a deep breath, then act as described in the "any other end tag" entry below.
```
http://www.w3.org/TR/html51/syntax.html#parsing-main-inbody

**Comment by mnot** [comment]
+1 to keeping it. If it ends up being removed, please consider factoring it out into a separate spec.

**Comment by calvaris** [comment]
+1 to keeping it.

**Comment by clopez** [comment]
Why is the unicorn pink?

**Comment by annevk** [comment]
Cool color. Closing this as worksforme.

**Comment by mnot** [comment]
👍🏼

/me files a bug with the Unicode Consortium due to lack of a unicorn emoji

**Comment by annevk** [comment]
That one is covered: 🦄. Well, a unicorn face.

**Comment by Ms2ger** [comment]
Features should be based on use cases or compat requirements, not stupid inside jokes. Please remove this before it causes more harm.

@travisleithead you are aware that your precedent lead to a bug in the WebKit parser, even though that, at least, was obviously not meant to have web-visible impact?

**Comment by roryhewitt** [comment]
+1 to keeping it. Well, at least if it's implemented.

**Comment by annevk** [comment]
It's not being implemented so I should probably remove it. Rather sad. I wish we'd introduce little easter eggs now and then.

**Comment by jakearchibald** [comment]
Boooooooo

**Comment by roryhewitt** [comment]
@annevk Boooooooo also!

C'mon, you can surely get this slipped in under the radar?
