### ISSUE TITLE
Feature detecting streaming requests

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/fetch#1470]
It would be nice to have a synchronous feature detect for streaming requests. This currently works with the Chrome implementation:

```js
const supportsRequestStreams = (() => {
  let duplexAccessed = false;

  const hasContentType = new Request('', {
    body: new ReadableStream(),
    method: 'POST',
    get duplex() {
      duplexAccessed = true;
      return 'half';
    },
  }).headers.has('Content-Type');

  return duplexAccessed && !hasContentType;
})();
```

This tests that:

- `duplex` is implemented as part of `RequestInit`
- `body` can be a `ReadableStream`. Otherwise, it's converted to a string and gets a `text/plain` content type.

However, it's possible that an implementation could support these two things, but reject when that request is passed to `fetch()` because it doesn't support request streams. In fact, Safari already behaves like this, but it doesn't implement `duplex` so the test still works.

Is it reasonable to expect the above feature detect to mean "fetch supports streaming requests"? Should this be enforced with spec text and/or a wpt?

**Comment by yutakahirano** [comment]
Does `Request.prototype.hasOwnProperty('body')` work?

**Comment by yutakahirano** [comment]
- https://wpt.fyi/results/fetch/api/request/request-init-stream.any.html (Request construction)
 - https://wpt.fyi/results/fetch/api/basic/request-upload.h2.any.html (fetching)

Interesting.

How about asking for their plan at https://github.com/WebKit/standards-positions/issues/24?

**Comment by annevk** [comment]
I'm going to close this as there is test coverage for this. But let me explicitly copy @youennf here so he knows to watch out for this when WebKit gets around to the feature.
