### ISSUE TITLE
Proposal: make `Response.json()` compatible with .jsonc (JSON w/ comments)

### ISSUE THREAD

**Issue by DiriectorDoc** [whatwg/fetch#1478]
This works:
```javascript
{
	"foo":"bar"
}
```
```javascript
fetch("data:application/json;charset=utf-8;base64,ew0KCSJmb28iOiJiYXIiDQp9") // The JSON from above
	.then((response) => response.json())
	.then((json) => {
		/* Do something with json */
	})

```
But this does not:
```javascript
{
	"foo":"bar" // baz
}
```
```javascript
fetch("data:application/json;charset=utf-8;base64,ew0KCSJmb28iOiJiYXIiIC8vIGJheg0KfQ==")
	.then((response) => response.json())
	/* 
	Uncaught (in promise) SyntaxError: Expected ',' or '}' after property value in JSON at position 16
 	*/
```

**Comment by jakearchibald** [comment]
Web features, including fetch, call https://infra.spec.whatwg.org/#parse-json-bytes-to-a-javascript-value to parse JSON. This eventually links to the ECMAScript definition.

Web specs shouldn't 'fork' JSON parsing, so changes like the one you're proposing should happen in ECMAScript.

I found some discussion here https://es.discourse.group/t/support-js-style-comments-in-json/814, but there may be more elsewhere.

**Comment by annevk** [comment]
Yeah, until TC39 decides this is worth doing this will be WONTFIX on the web platform. Closing accordingly.
