### ISSUE TITLE
Response.prototype.clone() should take into account the internal response.

### ISSUE THREAD

**Issue by yutakahirano** [whatwg/fetch#148]
Cloning the body in the internal response is needed.

**Comment by tyoshino** [comment]
Note from the f2f: The result of `clone()` should also preserve most of the properties of the original Response. I.e. the results of cloning an opaque one should be opaque.

**Comment by annevk** [comment]
This is solved in https://github.com/yutakahirano/fetch-with-streams just not merged upstream yet.

**Comment by annevk** [comment]
This was fixed in #200 by @yutakahirano. Yay!
