### ISSUE TITLE
Remove res.json() requirement (do it by default) when content-type application/json

### ISSUE THREAD

**Issue by laukstein** [whatwg/fetch#1489]
I propose to remove res.json() requirement with a backwards compatibility.

Fetch API already knows the content type of response and response is application/json shouldn't require an extra line `.then(res => res.json())` but do it by default. For backwards compatibility even if no longer res.json() required but is still defined, don't fall into exception, make like res.json() returning res

I think almost 100% usage of Fetch API is waiting for JSON response, and requiring `.then(res => res.json())` feels unnecessary.

Ref https://fetch.spec.whatwg.org/#fetch-api
```
fetch("https://pk.example/berlin-calling.json", {mode:"cors"})
  .then(res => {
    if(res.headers.get("content-type") &&
       res.headers.get("content-type").toLowerCase().indexOf("application/json") >= 0) {
      return res.json()
    } else {
      throw new TypeError()
    }
  }).then(processJSON)
```

insted could be
```
fetch("https://pk.example/berlin-calling.json", {mode:"cors"}).then(processJSON)
```
resulting the same result.

The only consideration I see is what would happen if by mistake the response returns a HTML page with status 200. If I try to process inside fetch API then it should still fall into catch(). Maybe it would be great to have additional option e.g. `{verifyJSON: true}` to force to execute res.json() without defining it. In this way if content-type will differ it can succeed to convert to JSON or will fall into correct TypeError

**Comment by annevk** [comment]
That is not a compatible change. We cannot suddenly not return a `Response` object.
