### ISSUE TITLE
 "cors-with-forced-preflight" is a mode

### ISSUE THREAD

**Issue by bblfish** [whatwg/fetch#152]
The documentation seems to say at various points that  "cors-with-forced-preflight" is a mode yet this is not specified in the https://fetch.spec.whatwg.org/#requestinit which states 

```javascript
enum RequestMode { "navigate", "same-origin", "no-cors", "cors" };
```

**Comment by wanderview** [comment]
Script can't set cors-with-forced-preflight and I don't think any other specs invoke fetch with it either.  It would be nice if it could just be completely removed from the spec.

**Comment by bblfish** [comment]
ah ok then. Just wanted to check in case I had misunderstood. I could close, but I'll leave it up to you, in case that can be tied to a clarification.

**Comment by annevk** [comment]
@wanderview XMLHttpRequest uses it. And `fetch()` will need to use it for `Request` objects with an associated JavaScript-controlled stream. We could turn it back into a flag, not sure if that makes things better.

**Comment by wanderview** [comment]
How are javascript-controlled streams different from any other javascript provided Request body?

At least for gecko, treating forced preflight as a flag would be easier to understand.

**Comment by annevk** [comment]
They are different as you can get an indication of what the server is doing and whether it exists.

**Comment by annevk** [comment]
@tyoshino would you rather have "cors-with-forced-preflight" be a distinct flag?

**Comment by wanderview** [comment]
> They are different as you can get an indication of what the server is doing and whether it exists.

It seems normal non-preflight CORS header checks would be performed before uploading the body.  Why is a preflight needed?

**Comment by annevk** [comment]
Because you do not get response headers before the body is transmitted?

**Comment by wanderview** [comment]
Right, ok.

**Comment by tyoshino** [comment]
Sorry for delay. I agree it'll be clearer if the signal is a separate flag.

**Comment by annevk** [comment]
Great! Thank you for confirming.
