### ISSUE TITLE
Unused `timingInfo` in two places

### ISSUE THREAD

**Issue by linusg** [whatwg/fetch#1522]
- https://fetch.spec.whatwg.org/#http-fetch, step 4 - this is not used directly as step 5.5.1 accesses `fetchParams’s timing info’s ...` again. Not sure if local aliases to a property are preferred, or nested property lookups when the struct is actually operated on.

  ![image](https://user-images.githubusercontent.com/19366641/198881446-f58b366b-96fb-4dd4-b667-7559b7523728.png)

- https://fetch.spec.whatwg.org/#http-network-or-cache-fetch, step 8.24.1 - this may be an oversight and some timing info should actually be updated but isn't, or some old leftover step; I haven't looked closer.

  ![image](https://user-images.githubusercontent.com/19366641/198881407-233e7f8a-6dab-4f69-9f40-ed34046a9420.png)

**Comment by annevk** [comment]
I suspect these are both refactoring oversights, but I haven't taken the time to look at blame. Hoping @noamr can take a look when back from leave.

**Comment by noamr** [comment]
> I suspect these are both refactoring oversights, but I haven't taken the time to look at blame. Hoping @noamr can take a look when back from leave.

Will do!
