### ISSUE TITLE
Add `<div algorithm>` wrappers around algorithms

### ISSUE THREAD

**Issue by jgraham** [whatwg/fetch#1526]
This will enable bikeshed features including interactive highlighting of variables in the output. It will also make it easier in general to determine where an algorithm begins and ends.

**Comment by annevk** [comment]
I guess to minimize disruption we shouldn't rewrap when we do this but just put them on the same indentation level as the algorithm itself.

**Comment by jakearchibald** [comment]
_twitches about wrapping_
