### ISSUE TITLE
need setHeaderFunction(  request => newHeaders ) function called before request sent

### ISSUE THREAD

**Issue by bblfish** [whatwg/fetch#156]
In order to be able to sign a request such as with the proposed [HTTP Signatures spec](https://tools.ietf.org/html/draft-cavage-http-signatures-05), one would want to have access to as many of the headers as possible as they will be sent.  Quite reasonably the Fetch API does not allow one to set [a list of forbidden headers](https://fetch.spec.whatwg.org/#terminology-headers). But it should allow those that can be viewed without danger to be part of the to be signed text. This function could only be executed just before the request is sent ( since that is when the `Date` header for example should be set ) So one needs a function in Request that allows one to access the request and especially the headers as they will be when sent.

It would be useful for the function to have access to the Request itself and the HTTP version, ie `GET / HTTP/1.1` as well as all the headers that it would be allowed to see. The function would return a set of new headers such as `Authorize: ...` that would be filtered for legal ones and appended to the request. 

Some headers that would be quite useful to have would be the Date, the Content-Length, the method and the URL to make sure that nothing had been changed in the request along the road. The client can already set a hash header to make sure the content does not get changed, though I am not sure what happens if the content is sent in chunks. So it may be that this should be a function that can be applied to each chunk too.

**Comment by bblfish** [comment]
I am assuming it won't be ready tomorrow, so we're also discussing what to do in the mean time https://lists.w3.org/Archives/Public/public-credentials/2015Nov/0009.html

**Comment by bblfish** [comment]
With the current Fetch implementations I have succeeded in authenticating to a remote web server as [described here](https://github.com/solid/solid-spec/issues/52#issuecomment-157519949) using the WebCrypto API to implement HTTP Signatures.

The issue here would perhaps be needed if the client wanted to sign every chunk of a response, supposing it were quite large.

**Comment by annevk** [comment]
@bblfish is there implementer interest in this functionality? Implementer being a mass market browser.

**Comment by annevk** [comment]
Closing this due to lack of interest.
