### ISSUE TITLE
Fix algorithms with unused variables

### ISSUE THREAD

**Issue by dlrobertson** [whatwg/fetch#1566]
Some algorithms have unused variables:

 - Two algorithms have a `controller` variable, but use `this` in the steps. I think `controller` should be used instead.
   - [report timing](https://fetch.spec.whatwg.org/#finalize-and-report-timing)
   - [extract full timing info ](https://fetch.spec.whatwg.org/#extract-full-timing-info)
 - ~The optional `extract-value flag` for [collect an HTTP quoted string](https://fetch.spec.whatwg.org/#collect-an-http-quoted-string) is never used. Some reading of prior commits seems to indicate this was added to make the algorithm suitable for header list `getting, decoding, and splitting`.~

Using https://github.com/whatwg/fetch/pull/1565:

```
❯ make remote
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  353k    0   459  100  353k     49  38777  0:00:09  0:00:09 --:--:--   124

Error running preprocessor, returned code: 2.
WARNING: The following &lt;var>s were only used once in the document:
  'controller', in algorithm 'report timing' for fetch controller
  'controller', in algorithm 'extract full timing info given a fetch controller controller:' for fetch controller
  'extract-value flag'
If these are not typos, please add an ignore='' attribute to the &lt;var>.
 ✘  Did not generate, due to fatal errors
make: *** [remote] Error 22
```

**Comment by dlrobertson** [comment]
It is interesting that no algorithm definition name is given for the `extract-value flag` case.

**Comment by dlrobertson** [comment]
Ah! The `extract-value flag` error was due to me not placing the [example](https://fetch.spec.whatwg.org/#example-http-quoted-string) in the algorithm wrapper.

**Comment by annevk** [comment]
Also looks like "extract full timing info" is missing a closing tag.

(At some point I'd like to rename "extract-value flag" to "extract-value" and define it as a boolean, but it seems that would require changes to MIME Sniffing and Server Timing as well.)
