### ISSUE TITLE
Rename "extract-value flag" to "extract-value" and define it as a boolean

### ISSUE THREAD

**Issue by dlrobertson** [whatwg/fetch#1567]
We should rename the "extract-value flag" for [collect-an-http-quoted-string](https://fetch.spec.whatwg.org/#collect-an-http-quoted-string) to "extract-value" and define it as a boolean. This would likely require changes to MIME Sniffing and Server Timing as well.

_Originally posted by @annevk in https://github.com/whatwg/fetch/issues/1566#issuecomment-1345477692_

**Comment by annevk** [comment]
I labeled this "good first issue", but note that it is a bit involved if you want to take this on. You'll start by creating a PR for this standard (no need to ask for assignment) and then you'll need to create two downstream PRs for the standards listed above so they use the corrected term.

**Comment by SatyamKharote** [comment]
Hey! I want to work on this issue can you please assign me this issue?

**Comment by annevk** [comment]
Hey @SatyamKharote a good first step to taking on an issue is to read it and the comments. See the comment above yours for instructions.

**Comment by SatyamKharote** [comment]
Hello @annevk, First of all, thanks for replying. I have never done any contribution to open source. This is my first step towards the open-source contribution. So can you please elaborate on what should i have to do?

**Comment by annevk** [comment]
No, sorry. Sufficient knowledge of GitHub and git is required.

**Comment by redone9211** [comment]
i would like to contribute to this issue , can you let me know how i can solve it.

**Comment by Deepak0320Singhal** [comment]
Hey I want to work on this issue, can you assign me this?

**Comment by varunseth5788** [comment]
i would like to contribute to this issue.

**Comment by hiiAnup** [comment]
Hey I want to work on this issue this will be my first open source contribution
