### ISSUE TITLE
Remove promise dependency from "Fully read a body"

### ISSUE THREAD

**Issue by noamr** [whatwg/fetch#1568]
[Fully read a body](https://fetch.spec.whatwg.org/#body-fully-read) is used in contexts that are not necessarily JS related, e.g. loading `<link>`s.
The implementation should go via the streams API without requiring promises internally.
Promises should only be used in JS-related contexts.

**Comment by annevk** [comment]
This sounds like a variant of https://github.com/whatwg/streams/issues/1178.

**Comment by noamr** [comment]
> This sounds like a variant of [whatwg/streams#1178](https://github.com/whatwg/streams/issues/1178).

Possible, but I think https://github.com/whatwg/streams/pull/1250 solves the particular issue and maybe takes us one step further.
