### ISSUE TITLE
Missing tags in create a connection

### ISSUE THREAD

**Issue by dlrobertson** [whatwg/fetch#1571]
[create a connection](https://fetch.spec.whatwg.org/#create-a-connection) might be missing some tags for some steps. The steps

> If http3Only is true, then establish an HTTP/3 connection
> If credentials is false, then do not send a TLS client certificate. 
> ...

Seem to be missing tags.

**Comment by dlrobertson** [comment]
> It kinda is meant to read as one big step, all impacting the connection establishment.

Would it make sense to use an unordered list for these like we do for the next step? If not, I think this issue can be closed.

**Comment by annevk** [comment]
I like that idea!
