### ISSUE TITLE
download progress while using body.arrayBuffer / etc

### ISSUE THREAD

**Issue by deanm** [whatwg/fetch#158]
It is very nice to be able to use the methods like arrayBuffer() to allow the browser to handle chunking and combining to a final single ArrayBuffer.  However, I didn't seem to see a way to monitor the download progress, without instead pumping and concatenating the buffers myself.  Is it possible to still use .arrayBuffer(), which will be much simpler and more performant, but still have a way to be notified when chunks are coming in and the size, or some other way of tracking the download progress for big / slow fetch() requests?

**Comment by annevk** [comment]
Not currently. Perhaps once libraries have evolved around Streams we can provide some obvious shortcuts on `Request` and `Response` objects, but at the moment that would be premature.

Maybe you can write such a library. 😊
