### ISSUE TITLE
Possible typo in "The `Allow` header is not relevant for the purp..."

### ISSUE THREAD

**Issue by lxylxy123456** [whatwg/fetch#1598]
https://fetch.spec.whatwg.org/commit-snapshots/093c622c93d61159cc2d426b869446073c73d38f/#http-responses

>\`Access-Control-Allow-Methods\`
>
>    Indicates which methods are supported by the response’s URL for the purposes of the CORS protocol.
>
>    The \`Allow\` header is not relevant for the purposes of the CORS protocol.

I think there is a typo in the last line. Instead of:
> The \`Allow\` header is not relevant for the purposes of the CORS protocol\. 

I think it should be:
> The \`Access-Control-Allow-Methods\` header is not relevant for the purposes of the CORS protocol\.

**Comment by annevk** [comment]
That's not a typo. The `Allow` method also lists methods, but it's intentionally not used.
