### ISSUE TITLE
Specify cache mode impact on request headers

### ISSUE THREAD

**Issue by pmeenan** [whatwg/fetch#1599]
The [cache mode](https://fetch.spec.whatwg.org/#concept-request-cache-mode) for fetch requests refers to the HTTP cache which I assume is the local cache but doesn't appear to specify what the downstream effects should be (specifically if any headers should or should not be set on outbound requests).

Maybe it';s just an interop issue with the need for web platform tests but the browsers currently differ when doing ```fetch(url, {cache: "no-store"})```.

Firefox and Chrome treat it as a local directive and skip the HTTP cache but send the request to the network with no change in headers.

Safari appears to treat it as a global directive to skip all caches and adds ```Pragma: no-cache``` and ```Cache-Control: no-cache``` to the HTTP requests, busting network caches.

**Comment by mnot** [comment]
@pmeenan see #722

**Comment by pmeenan** [comment]
@mnot thanks.  Guess the issue continues and I'll comment over there.  I assume the devs could add the Cache-Control header themselves directly if they want it down-stream.
