### ISSUE TITLE
Expose body `transmitted` through API surface

### ISSUE THREAD

**Issue by deanm** [whatwg/fetch#160]
The spec has a concept about the body's stream, length, how much was transmitted, etc.

https://fetch.spec.whatwg.org/#concept-body-transmitted

It doesn't seem like there is currently API surface to access that information.  This would be a really simple and useful way for routinely polling to implement something download progress.

**Comment by annevk** [comment]
I feel like we went over this in #158. This is what the various stream issues are about. Feel free to join on https://wiki.whatwg.org/wiki/IRC if you have any questions about this.

**Comment by deanm** [comment]
Yes, this is related to #158 but it was a different suggestion based specifically on the spec.  I don't really specifically what you mean by "various stream issues"... I don't use IRC, is github not also a place to discuss things related to the spec?

Thanks

**Comment by annevk** [comment]
See https://github.com/whatwg/fetch/labels/needsstreams for the streams issues. There's also another repository https://github.com/yutakahirano/fetch-with-streams where some development takes place.

**Comment by deanm** [comment]
Maybe I don't understand because I am using Chrome 46 which has at least some support for streams on fetch?  What do you mean by "needs streams", perhaps I don't understand the current status of spec or implementation?  Seems to me like streams is at least somewhat there already

**Comment by annevk** [comment]
It is somewhat there, but there are a lot of missing bits still. That's all explained in those issues.
