### ISSUE TITLE
The fetch pull algorithm does not pass proper bytesWritten to ReadableByteStreamControllerRespond

### ISSUE THREAD

**Issue by saschanaz** [whatwg/fetch#1610]
(Talking about https://fetch.spec.whatwg.org/#concept-http-network-fetch step 10 that is modified by #1593)

Implementing the algorithm as-is forces the size of resulting array buffer view be equal to that of the byob request view.

The caller may do some subarraying, but maybe the [`enqueue`](https://streams.spec.whatwg.org/#readablestream-enqueue) algorithm should receive `bytesWritten` as an argument?

**Comment by saschanaz** [comment]
>The caller may do some subarraying

It's complicated when the view is not Uint8Array, so better not.

**Comment by domenic** [comment]
I think you are talking about the following case:

- current BYOB request view is non-null
- current BYOB request view's byte length > _available_
- Thus, _bytes_'s length = _available_ is less than current BYOB request view's byte length, and only _bytes_'s length is written

Indeed the caller could create a new Uint8Array wrapping the underlying AB, but that is kind of annoying, and there's no nice Web IDL helper for it. So yeah maybe Streams should provide more help here.

Ideas:

- An optional _bytesWritten_ argument, as you suggest
- Something that abstracts most of steps 10.2.3.1-8 for the caller?

**Comment by saschanaz** [comment]
>Something that abstracts most of steps 10.2.3.1-8 for the caller?

Gecko has an internal implementation that converts any internal byte stream to ReadableStream (that is also used for Fetch), so having an abstraction in the Streams spec would probably better match with Gecko.
