### ISSUE TITLE
Why not support Basic Authentication in the API?

### ISSUE THREAD

**Issue by wmertens** [whatwg/fetch#162]
A lot of services use Basic auth (e.g. webcams etc), and `XMLHTTPRequest` has built-in support for it through user and password.

Why doesn't fetch provide support? The result is having to calculate the `Authentication` header yourself, meaning adding one version (with a polyfill Base64 for IE9) in the browser and using a different version for NodeJS.

It is only a few lines of code but it is annoying, whereas fetch in the browser can use the XHR built-in support.

**Comment by annevk** [comment]
Basic authentication has a ton of issues. There's no reason to further encourage its use or enshrine it with API support.

**Comment by wmertens** [comment]
Ok, fair enough, thanks.
