### ISSUE TITLE
What is meant by "It is initially « »"

### ISSUE THREAD

**Issue by Ethan-Arrowood** [whatwg/fetch#1634]
https://fetch.spec.whatwg.org/commit-snapshots/8f109835dcff90d19caed4b551a0da32d9d0f57e/#ref-for-concept-header-list

> A header list is a [list](https://infra.spec.whatwg.org/#list) of zero or more [headers](https://fetch.spec.whatwg.org/#concept-header). It is initially « ».

https://fetch.spec.whatwg.org/#concept-header-list

**Comment by jakearchibald** [comment]
It means it's a new empty list, like how `[]` is a new empty array in JavaScript.

https://infra.spec.whatwg.org/#list

**Comment by Ethan-Arrowood** [comment]
Ahh I see. Maybe I can update that so it links to the infra spec for clarification? It wasn't obvious to me to search for the symbols nor to look at the infra spec for them specifically

**Comment by annevk** [comment]
I think it's clear enough given that "list" is linked.
