### ISSUE TITLE
Add "must-revalidate" to RequestCache enumeration

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#165]
It would be nice to have a short-hand for the header "cache-control: must-revalidate".  As far as I can tell none of the current RequestCache values do this.

**Comment by jakearchibald** [comment]
Agreed. This would be the next-best-thing for things like cache updates, if the developer doesn't have any control over caching headers from the server but doesn't want to incur full downloads for content they already have.

**Comment by annevk** [comment]
What do you mean by a shorthand for that header? Would it actually set that header or would this be a new behavior that is not captured currently? It sounds like the latter in which case I wonder a) what would be the exact semantics and b) why we didn't think of including this before.

**Comment by mnot** [comment]
Is the intention that the browser's cache will revalidate stale responses, or...?

**Comment by wanderview** [comment]
Maybe I misunderstand what the must-revalidate header does, so lets just talk about the desired behavior.

Basically, I want the code in the service worker's install event handle to get the same behavior that normal pages get when the refresh button is pushed.  The browser revalidates all resources in the cache, but if it gets a 304-not-changed it still uses the local http cache version.

As far as I can tell none of the current primitives do this.  I don't see anything that forces the revalidation requirement.  The "no-cache" value almost does the right thing, but it doesn't force the revalidation headers.

Maybe if we changed step 14.3 of Http-network-or-cache-fetch from:

> Otherwise, if httpRequest's cache mode is either "default" or "no-cache", and the response in the HTTP cache for httpRequest does require revalidation, modify httpRequest's header list with revalidation headers.

To something like:

> Otherwise, if either of the following conditions is true modify httpRequests header list with revalidation headers:
> * httpRequest's cache mode is "default" and the response in the HTTP cache for httpRequest requires revalidation
> * httpRequest's cache mode is "no-cache"

**Comment by annevk** [comment]
"no-cache" does use revalidation headers. How can you add revalidation headers if none are needed?

**Comment by wanderview** [comment]
We discussed on irc, but for the record here:

Yes, the spec currently has no-cache setting revalidation headers, but only if "the response in the HTTP cache for httpRequest does require revalidation".  To me this implies that the http cache entry has reached its max age, but I guess its not defined anywhere.

I was suggesting that if no-cache is set and there is a matching response in the http cache, then always set the revalidation headers regardless of age.

**Comment by annevk** [comment]
@ehsan, what do you think about using the @wanderview semantics for "no-cache"? That is by-and-large the intent of that cache mode, I think.

**Comment by mnot** [comment]
That seems to align with the semantics of `no-cache` in a HTTP request. 

http://httpwg.org/specs/rfc7234.html#rfc.section.5.2.1.4

**Comment by ehsan** [comment]
My understanding of the `no-cache` semantics was that the cached response will always be revalidated before being used.  That being said, step 15.3 of HTTP-network-or-cache fetch makes me second guess that, but I'll go ahead and assume that prose needs fixing.

With that, we do need to set the right headers for `no-cache`, but I don't think `must-revalidate` is the right header since AFAIK that header is only meaningful on a response, not a request.  The right request header to send is `max-age=0`.  I have already filed #232 about that.
