### ISSUE TITLE
Pause readable stream reader

### ISSUE THREAD

**Issue by osintalex** [whatwg/fetch#1651]
As far as I know, once you've started reading a stream from `response.body` you can't pause and resume it like you can [with node](https://nodejs.org/api/stream.html#event-pause).

I think this would be very useful. I've tested this with the below React code sending back a stream of JSON from an app I'm running locally. I thought that if I used `sleep` in a blocking way it would stop the reader from reading but I noticed that it keeps reading in the background. 

Perhaps I've made a mistake here and there is a way to achieve this in pure JS, I'd be really grateful for an example of that if so!

```javascript
import logo from "./logo.svg";
import "./App.css";

function App() {
  let pause = false;
  let cancel = false;
  function changePause() {
    pause = !pause;
  }
  function cancelStream() {
    cancel = true;
  }
  function sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  async function* iterateOverStream(stream) {
    const reader = stream.getReader();
    const decoder = new TextDecoder();

    while (true) {

      if (pause) {
        // Slow down the infinite loop repeating until pause is pressed again
        // I thought that this would pause the reader from reading but it doesn't
        // it just pauses displaying the data, the reader keeps reading in the background
        await sleep( 3 * 1000);
        continue;
      } else {
        const { done, value } = await reader.read();
        if (done) break;
        if (cancel) {
          reader.cancel();
          break;
        }
        yield decoder.decode(value, { stream: !done });
      }
    }
    reader.releaseLock();
  }

  async function readData() {
    cancel = false;
    const response = await fetch("http://localhost:5000");
    for await (const chunk of iterateOverStream(response.body)) {
      console.log(`json chunk is ${chunk}`);
    }
  }

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p onClick={readData}>
          Click me and check out dev tools to test stream
        </p>
        <p onClick={changePause}>Click to pause/unpause</p>
        <p onClick={cancelStream}>Click to cancel stream</p>
      </header>
    </div>
  );
}

export default App;
```

**Comment by annevk** [comment]
cc @saschanaz @MattiasBuelens

**Comment by saschanaz** [comment]
Do you have the full code including the server part? Looks like it should stop reading at some point, could be a browser bug.

**Comment by saschanaz** [comment]
Looks like all browser engines immediately fetches every byte from `fetch("http://localhost:5000")` even without accessing `.body` at all. And I'm not familiar with how the fetch suspension works exactly. @jesup, can you help?

**Comment by ricea** [comment]
I believe the reason for continuing to read from the network even when JavaScript has stopped reading is to ensure that the HTTP cache is populated.

Try adding a `Cache-Control: no-store` header to your response. This avoids writing to the HTTP cache, and so should enable reading the response to be paused.

**Comment by saschanaz** [comment]
```py
r = Response(my_generator(), status=200, content_type='application/json')
r.cache_control.no_cache = True
return r
```

This adds the header but that still doesn't seem to suspend the fetch on any browser. Interesting...

**Comment by saschanaz** [comment]
Forget my previous comment, it's `no-store` and this works:

```py
r = Response(my_generator(), status=200, content_type='application/json')
r.cache_control.no_store = True
return r
```

Hope this helps!
