### ISSUE TITLE
Not clear what CSP directive is limiting iframes/imports

### ISSUE THREAD

**Issue by kenchris** [whatwg/fetch#166]
https://fetch.spec.whatwg.org/#concept-request-type

**Comment by yoavweiss** [comment]
Also relevant for request type, so that such files can be preloaded with a matching `as` attribute.

**Comment by annevk** [comment]
What is imports?

Did you check the newer CSP drafts written on top of Fetch?

**Comment by annevk** [comment]
Closing due to lack of provided information.
