### ISSUE TITLE
Should `processResponse` also receive the internal response, similar to `processResponseConsumeBody`?

### ISSUE THREAD

**Issue by trflynn89** [whatwg/fetch#1664]
Commit 900326635be4509de38f1a61084565731ac115c4 changed the fetch response handover steps to provide `processResponseConsumeBody` with the response's internal response. Should the invocation to `processResponse` just before also receive the internal response?

This was an issue for us over at [SerenityOS](https://github.com/SerenityOS/serenity) when implementing the HTMLMediaElement, for example. When we fetch the media resource, [the spec says](https://html.spec.whatwg.org/multipage/media.html#loading-the-media-resource:concept-fetch) to use the `processResponse` algorithm to incrementally read the response's body. However, all CORS cross-origin (i.e. filtered) responses will have a null body at this step.

Or maybe the HTML spec should say to incrementally read the body of the response's unsafe response?

**Comment by trflynn89** [comment]
Gotcha, makes sense. I can make an issue in the HTML spec repo to use the unsafe response in HTMLMediaElement if that helps :)

Re: #1661, if the first argument is the filtered response, I think we won't be able to check its status code? [Opaque filtered responses](https://fetch.spec.whatwg.org/#concept-filtered-response-opaque) always have a status code of 0, so when we check if it is an "OK" status in e.g. [HTMLLinkElement's fetch](https://html.spec.whatwg.org/multipage/semantics.html#fetching-and-processing-a-resource-from-a-link-element:concept-response-status), we will see a response status of 0 and drop the response. So HTMLLinkElement would need to poke at the unsafe response as well.

**Comment by annevk** [comment]
Yeah that would help, thanks!

And yeah, that's correct. `HTMLLinkElement` would have to do that and I think that's better as it makes it clear that the caller is doing something unsafe.

**Comment by trflynn89** [comment]
FYI I opened https://github.com/whatwg/html/issues/9355 for the HTML spec side of this. Thanks for the help!

**Comment by annevk** [comment]
Thanks, I think that means we can close this.
