### ISSUE TITLE
specify types of streams

### ISSUE THREAD

**Issue by bblfish** [whatwg/fetch#167]
I have been wondering what the type of the stream returned by `Resonse.body` method of the Fetch API is.

The Fetch API's [fetch method](https://fetch.spec.whatwg.org/#fetch-method) [returns a Promise of a Response](https://fetch.spec.whatwg.org/#response), which contains a `body` which is a `ReadableStream`. From this I can then get chunks for my parser.

Since the streams do not specify the type of a chunk ( see [issue 410 of streams api](https://github.com/whatwg/streams/issues/410) ) it would be helpful if the documentation in the Fetch API made clear what type of stream was returned.

Now it is true that the [Response.body](https://fetch.spec.whatwg.org/#concept-body) method says:

> A `body` is a byte stream. It has an associated **transmitted** which is an integer and initially 0, length which is an integer and initially 0, and error flag which is initially unset.

So I suppose that means the content of the chunk contains bytes, but it is not clear that this means that all chunks will be  `Uint8Array`s

**Comment by domenic** [comment]
This is the third issue you've opened on this topic. Please consider being more frugal in the future.

https://fetch.spec.whatwg.org/#dfnReturnLink-1 should answer your question. It is well specced.

**Comment by bblfish** [comment]
that link does not resolve.

**Comment by domenic** [comment]
My apologies. Search for "Enqueue a Uint8Array object wrapping an ArrayBuffer containing the result of reading response's body into stream. If that threw an exception, run the following subsubsteps and terminate these substeps: "

**Comment by bblfish** [comment]
Ah ok. Thanks. sometimes these docs are a bit difficult to read. One could imagine adding such type information into the signature [for the Response class](https://fetch.spec.whatwg.org/#response-class) by writing something like

```
[SameObject] readonly attribute ReadableStream<Uint8Array> body;
```

That would make it much more pleasant I think for a developer.

**Comment by yutakahirano** [comment]
@bblfish We're planning to provide a way to create a Request / Response from a user-created streams.

```
var controller;
var stream = new ReadableStream({start: c => controller = c});
var response = new Response(stream, ...);
assert_equals(response.body, stream);
controller.enqueue(3);
var p = response.body.getReader().read();
// |p| will be resolved with |{done: false, value: 3}|.
```

IIUC we are not going to restrict each chunk type for such cases.

**Comment by wanderview** [comment]
> IIUC we are not going to restrict each chunk type for such cases.

What do you mean?  DOM consumers of Response will need to know how to unwrap bytes from the body stream.  For example, cache.put(req, resp).  I thought we were restricting to Uint8Array,

**Comment by domenic** [comment]
DOM consumers will fail to consume, yeah. But there's no restriction in the creation of the stream.

**Comment by wanderview** [comment]
I guess for some definition of "restriction" that's true.  If you think of it as "what type do I need to provide such that everything works", then it needs to be a Uint8Array as well.

**Comment by yutakahirano** [comment]
@wanderview Yes, I wanted to say that we are not going to guarantee that any chunk read from the body stream is of type Uint8Array.

Note that we state any chunk read from the body stream created by the user agent is of type Uint8Array. Also, as Domenic says, DOM consumers expect Uint8Array chunks and they will fail if that expectation is not satisfied.

**Comment by tyoshino** [comment]
Yutaka, please clarify the plan by answering these questions?

1. whether stream === response.body or not
1. how much validation we would do on the input

As the body argument of Response constructor is overloaded, we need to anyway decide the group of objects we handle as ReadableStream(-like). Are we sure that we accept only ReadableStream (or derived classes) instances, but not ReadableStream like objects? If so, and (1) is Y, then Response.body may have to be `any`.

**Comment by domenic** [comment]
We should probably only handle real readable streams. My duck typing original ideas are kind of nice but not worth the potential pain. The spec is in general moving toward nominal typing now.

**Comment by tyoshino** [comment]
Given that, at least Response constructor would accept only ReadableStream type instances, and therefore Response.body is always ReadableStream. OK.

Maybe later we'd use piping-to-transform-stream for duck typing to real conversion if it's really needed.

**Comment by bblfish** [comment]
Hi, [my commit to scala-js-dom](https://github.com/scala-js/scala-js-dom/pull/177/files) was accepted. About 1200 lines of code and documentation. Of interest to this thread is [Stream.scala](https://github.com/bblfish/scala-js-dom/blob/12658a41b82e44c4c27315daacd7fba9d9d8f0b5/src/main/scala/org/scalajs/dom/experimental/Stream.scala), which makes the typing of the Stream API machine readable for the Scala compiler.  It also makes the generic nature of the stream API explicit. For example 

```scala
trait WriteableStream[-T] extends js.Object { ... }
```

shows that WriteableStream is generic on some type `T`, which is the type of the `Chunk`s that are written to it.  It also shows that `T` is [covarient](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)). Chunk is itself generic on the `value` field.

```scala
trait Chunk[+T] extends js.Object {
 
 def value: T  = js.native

  def done: Boolean = js.native
}
``` 

That part of Scala should not be too difficult to follow for people here. I hope it's useful.

**Comment by yutakahirano** [comment]
Sorry for the delay.

I don't fully understand Scala, but it's generally good to define `body` as ReadableStream[Uint8Array] in Scala. I don't think of any use-cases for a body with arbitrary chunks.

In JS side, the current proposal doesn't run a runtime check to ensure the assumption.

> Yutaka, please clarify the plan by answering these questions?
>

My current proposal is https://github.com/yutakahirano/fetch-with-streams/blob/master/response-stream-constructor.md. We haven't had much discussion on that and any comments are welcomed.

In the current proposal, stream == response.body and there is no validation in the Response constructor but I'm open to change.

**Comment by annevk** [comment]
This can be discussed further in https://github.com/yutakahirano/fetch-with-streams if we indeed want to change approach, but it seems like we do not. Perhaps at some point we can add a note of what a stream is likely to contain, but specifying types seems not possible.

**Comment by bblfish** [comment]
ok, no problem for us. It looks like you are actually using types... it's just a question of how explicit you can make it ( without requiring of course compile time verification of it ).
