### ISSUE TITLE
Note about credentials & wildcards probably incorrect for Access-Control-Expose-Headers

### ISSUE THREAD

**Issue by hamishwillee** [whatwg/fetch#1671]
[3.2.4. HTTP new-header syntax](https://fetch.spec.whatwg.org/#http-new-header-syntax) has a note in the end that says this:

> For `Access-Control-Expose-Headers`, `Access-Control-Allow-Methods`, and `Access-Control-Allow-Headers` response [headers](https://fetch.spec.whatwg.org/#concept-header), the [value](https://fetch.spec.whatwg.org/#concept-header-value) `*` counts as a wildcard for [requests](https://fetch.spec.whatwg.org/#concept-request) without [credentials](https://fetch.spec.whatwg.org/#credentials). For such [requests](https://fetch.spec.whatwg.org/#concept-request) there is no way to solely match a [header name](https://fetch.spec.whatwg.org/#header-name) or [method](https://fetch.spec.whatwg.org/#concept-method) that is `*`.

That makes sense for the other two headers, but maybe not for `Access-Control-Expose-Headers`. Specifically, that method tells a client what response headers it can expose to clients. The `Authorization` header would never appear in a response so is irrelevant here. How would cookies or other credential information be relevant in this context?

I think that means that `*` should allow sharing of all response headers. Right?

This fell out of a Mozilla bugzilla discussion here: https://bugzilla.mozilla.org/show_bug.cgi?id=1687364#c5

**Comment by annevk** [comment]
We only allow wildcarding for non-credentialed requests. To prevent responses from accidentally sharing too much information. So the note is accurate. `*` is a wildcard, but only if the request is non-credentialed. And when it functions as a wildcard, you cannot match a header whose name is `*`.
