### ISSUE TITLE
Typo: request'a -> request's

### ISSUE THREAD

**Issue by johnathan79717** [whatwg/fetch#1676]
I think the `request'a` should actually be `request's`.

https://fetch.spec.whatwg.org/#ref-for-concept-request-policy-container%E2%91%A2:~:text=Assert%3A%20request%E2%80%99a%20mode%20is%20%22navigate%22.

**Comment by annevk** [comment]
Yes! Want to PR?

**Comment by johnathan79717** [comment]
Sure.  Let me work on it.
