### ISSUE TITLE
Question about credentials mode of no-cors mode requests.

### ISSUE THREAD

**Issue by horo-t** [whatwg/fetch#168]
What is the credentials mode for `<img src="test.png">`?

According to HTML spec, it seems to be "include".
https://html.spec.whatwg.org/multipage/infrastructure.html#fetching-resources
But according to this comment in Fetch spec discussion, it seems to be "same-origin".
https://github.com/whatwg/fetch/issues/106#issuecomment-128735776

If my understanding is correct, there is no difference between "same-origin" and "include" when the request mode is "no-cors", because the credentials flag is set in HTTP fetch spec 4.3.
https://fetch.spec.whatwg.org/#http-fetch
> 3\. Let credentials flag be set if one of
>    - request's credentials mode is "include"
>    - request's credentials mode is "same-origin" and either the CORS flag is unset or response tainting is "opaque"

> is true, and unset otherwise.

But I want to know which is correct to write tests with Service Worker's fetch event handler.

**Comment by wanderview** [comment]
> If my understanding is correct, there is no difference between "same-origin" and "include" when the request mode is "no-cors", because the credentials flag is set in HTTP fetch spec 4.3.

I don't think this is true.  If you are in "no-cors" and cross-origin then the response tainting is opaque.  So you trigger the "or response tainting is opaque" part of the second bullet there.

Not sure on the initial question, though.  Would be nice to hear from @annevk on this.

**Comment by wanderview** [comment]
Wow, that bullet should read "response tainting is not opaque". :-\  I'll file a new bug.

**Comment by annevk** [comment]
When mode is "no-cors", credentials mode is "include" for all existing features. Can we fold this into #169 at this point or vice versa?

**Comment by annevk** [comment]
Ping.

**Comment by horo-t** [comment]
OK. Then, it is a bug of Chromium.
I filed a bug.
https://code.google.com/p/chromium/issues/detail?id=576534
