### ISSUE TITLE
Difference between xhr and fetch in response headers for multipart requests

### ISSUE THREAD

**Issue by neothemachine** [whatwg/fetch#170]
For [getAllResponseHeaders()](https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest#getAllResponseHeaders%28%29) it says:
> Note: For multipart requests, this returns the headers from the current part of the request, not from the original channel.

How does this compare to fetch? I couldn't find any info on how the headers of multipart requests are handled. Are they all merged? Is just the first set returned? Or the last?

I'm also not absolutely sure what a multipart request is. Is that when I POST multipart/form-data? Or when the server sends a chunked transfer encoding? Or when redirects happen?

**Comment by annevk** [comment]
I think that is referencing an old Gecko feature that has been removed: https://bugzilla.mozilla.org/show_bug.cgi?id=843508. Note that https://xhr.spec.whatwg.org/ makes no mention of that. You should probably update MDN.
