### ISSUE TITLE
"Let internalResponse be response's internal res..."

### ISSUE THREAD

**Issue by Ms2ger** [whatwg/fetch#171]
https://fetch.spec.whatwg.org/#main-fetch

> Let internalResponse be response's internal response\. 

In the case of a network error, there is no "internal response".

**Comment by annevk** [comment]
So I think it might be time to rethink this filter concept and see if there's a simpler way out. It was great when there was not much poking into the bits, but now that there is, a somewhat less error prone "API" seems warranted.

**Comment by annevk** [comment]
I decided against rethinking it entirely. Would have a lot of consequences.
