### ISSUE TITLE
Clarity of Location URL Algorithm

### ISSUE THREAD

**Issue by Redfire75369** [whatwg/fetch#1720]
### What is the issue with the Fetch Standard?

Under [Fetch Spec - Response Location URL](https://fetch.spec.whatwg.org/#concept-response-location-url) Step 3, there is no clear indication for what happens if extracting the header list values gives multiple `Location` headers.

Say, the response has the following headers:
```http
Location: https://www.example.com/
Location: https://www.example.net/
```
Although such a response is malformed, it should still be addressed explicitly.
Presumably, the algorithm should return `failure` in this scenario.

**Comment by annevk** [comment]
That's correct, if you're willing to help writing tests for this that'd be appreciated. This is tracked by #883 so resolving this as a duplicate.
