### ISSUE TITLE
add a method to get a Uint8Array to Body

### ISSUE THREAD

**Issue by bakkot** [whatwg/fetch#1732]
### What problem are you trying to solve?

Body has an `.arrayBuffer()` method, but that's [almost never what you actually want](https://github.com/w3ctag/design-principles/issues/463), since you can't read out of a buffer directly - you need a view. Uint8Array is the canonical "sequence of byte values" view.

### What solutions exist today?

`new Uint8Array(await body.arrayBuffer())`

### How would you solve it?

Add a `.bytes()` method which gives a new `Uint8Array`.

### Anything else?

Some brief discussion [here](https://matrixlogs.bakkot.com/WHATWG/2024-01-18#L1-L3).

PushMessageData and Blob (which live elsewhere) would need this too, since they just copied Body.

(Also, watch out for https://github.com/whatwg/fetch/issues/1675 while specifying.)

**Comment by annevk** [comment]
FWIW, WebKit is okay with adding this.

cc @valenting @ricea

**Comment by saschanaz** [comment]
Sounds okay to me.

**Comment by ricea** [comment]
Chromium supports.
