### ISSUE TITLE
"Let preflightResponse be the result of performi..."

### ISSUE THREAD

**Issue by KiChjang** [whatwg/fetch#174]
https://fetch.spec.whatwg.org/#http-fetch

> Let preflightResponse be the result of performing a CORS\-preflight fetch using request\.
> 
> If preflightResponse is a network error, return preflightResponse\. 

What is the purpose of `preflightResponse`? It is referenced nowhere after this step. Is it simply just used to check whether the result of `preflight-fetch` is a network error?

**Comment by annevk** [comment]
That is the purpose of the variable, indeed.

**Comment by KiChjang** [comment]
In that case, wouldn't there be performance overhead by initiating a `preflight-fetch`? I am thinking that it may be more efficient by defining a new function that only checks for the conditions defined in `preflight-fetch` and returning a boolean instead.

**Comment by annevk** [comment]
I don't understand. We have to make a preflight fetch either way. That comes with a lot of cost since it's an additional fetch and IO is expensive. Returning a boolean or the response itself seems trivial compared to that. If you think it matters a lot you could let your implementation return a boolean instead I suppose.

**Comment by nikkisquared** [comment]
If the preflight fetch doesn't return a network error, the information inside `preflightResponse` is never used anyways. After the last point a preflight fetch can return a network error (step 7 substep 6 or step 8), the only purpose is to update the `CORS-preflight cache`. Where does that cache come up again? `HTTP Fetch` doesn't refer to it directly. I get the feeling that doing the whole preflight fetch call is important for that cache, but it's hard to tell why it matters.

**Comment by annevk** [comment]
"method cache match" and "header-name cache match" in a prior step is that cache, no? The preflight fetch is important for when there's no cache entry for the request.

**Comment by nikkisquared** [comment]
Ahh, I didn't catch the significance of that when I first read through HTTP Fetch! You're right, it checks against the pre-flight cache, and will make it as needed. But where does the cache later get used?

**Comment by annevk** [comment]
It does not get used later, it's called the CORS-preflight cache for a reason.

**Comment by nikkisquared** [comment]
Like we discussed in #whatwg, there could be some notes added to HTTP Fetch and the CORS-preflight Fetch regarding the purpose of the CORS-preflight cache.

Step 4.1 of HTTP Fetch could say something like "If there's a CORS-preflight cache match, then this request is validated already. If there isn't, it needs to be validated."

CORS-preflight Fetch could have more detail about what it means for it to be validated, and how it gets stored in a cache to prevent redundant checks.

**Comment by annevk** [comment]
Thank you!
