### ISSUE TITLE
Consider renaming or replacing http3only?

### ISSUE THREAD

**Issue by ekinnear** [whatwg/fetch#1744]
### What is the issue with the Fetch Standard?

In the context of WebTransport, the use of the term `http3only` in [obtain a connection](https://fetch.spec.whatwg.org/#concept-connection-obtain) came up in discussion of https://github.com/w3c/webtransport/issues/561.

We've been trying to adhere to more transport agnostic principles, allowing developers to express their needs based on properties of the transport, rather than hardcoding a particular protocol or a version of a protocol. 

In that context, the reason for requiring `http3only` was determined to instead represent the desire to obtain unreliable transport that can eliminate head-of-line blocking, perhaps we should use some spelling of the term `requireUnreliableTransport`.

Filing an issue to discuss if we want to transition to something more transport agnostic in fetch as well when obtaining connections. What happens when we have HTTP/4? HTTP/3.1? What if HTTP/3.1 doesn't provide the same underlying transport properties? It seems like enshrining the protocol version itself as the name of the field leaves us in an undesirable position.

**Comment by domenic** [comment]
> leaves us in an undesirable position.

The "undesirable position" being that we might have to slightly change a variable name in the future?

**Comment by annevk** [comment]
That makes a lot of sense. I created #1745.
