### ISSUE TITLE
Replace "flags" with "booleans"

### ISSUE THREAD

**Issue by nikkisquared** [whatwg/fetch#175]
The Fetch standard refers to both flags and booleans, which are separate in prose. However, in technical implementation, there is no difference. I found a technical redundancy caused by this in step 1 of HTTP-network Fetch[1], which makes a boolean version of a flag.

@annevk said he's been thinking of getting rid of "flags" in the Fetch standard, so I'm making this issue as a reminder!

[1] https://fetch.spec.whatwg.org/#http-network-fetch

**Comment by annevk** [comment]
@domenic what is your thinking on this? This seems like it should be in line with where JavaScript and IDL will eventually go, no?

**Comment by domenic** [comment]
I like booleans but am not sure how I feel about changing all the specs in the world that use flags. JavaScript uses booleans. I am not sure this is for IDL to decide but I think you have a broader view of IDL as telling people how to write algorithms than I do.

**Comment by annevk** [comment]
Closing this for now. This would have to be part of an effort to change this terminology everywhere. I'll keep it in mind when defining new things though.

(My idea about IDL is that it's basically the platform's ECMAScript specification. So whatever style it dictates everyone else should follow. Ideally we'd make it closer to ECMAScript before we go there though.)
