### ISSUE TITLE
Re-arrange some HTTP-network Fetch substeps

### ISSUE THREAD

**Issue by nikkisquared** [whatwg/fetch#176]
In HTTP-network Fetch[1] step 4, the final set of substeps (starting with "Run these substeps in parallel") would be better moved out of step 4, which is already covering a lot, and to step 10. The current step 10 would become step 11. The new step 10 wouldn't need the "after the outer set of steps has returned" clause anymore, which would help make it straightforward.

[1] https://fetch.spec.whatwg.org/#http-network-fetch

**Comment by annevk** [comment]
Thank you!
