### ISSUE TITLE
Expected behavior of Response.redirect(null)?

### ISSUE THREAD

**Issue by KhafraDev** [whatwg/fetch#1764]
### What is the issue with the Fetch Standard?

When running `Response.redirect(null)`, different platforms give one of two results:

- node, deno, and cloudflare workers throw an error
- firefox and chrome pass (response.url is an empty string here)

the webidl declaration for it is

[[NewObject](https://webidl.spec.whatwg.org/#NewObject)] static [Response](https://fetch.spec.whatwg.org/#response) [redirect](https://fetch.spec.whatwg.org/#dom-response-redirect)([USVString](https://webidl.spec.whatwg.org/#idl-USVString) url, optional [unsigned short](https://webidl.spec.whatwg.org/#idl-unsigned-short) status = 302);

I'm wondering which platforms are correct here? Thanks

**Comment by domenic** [comment]
Browser behavior is correct here. The processing of USVString arguments is given here: https://webidl.spec.whatwg.org/#js-USVString which defers to https://webidl.spec.whatwg.org/#js-DOMString which defers to https://tc39.es/ecma262/multipage/abstract-operations.html#sec-tostring .

Note that the argument passed to `redirect()` is not reflected in `response.url`, but instead in `response.headers.get("Location")`. You can see that this returns, e.g., `https://example.com/null`, as the result of parsing the relative URL `"null"` against the base URL `https://example.com/`.
