### ISSUE TITLE
Unclear how to serialize request origin "client"

### ISSUE THREAD

**Issue by simonwuelker** [whatwg/fetch#1773]
### What is the issue with the Fetch Standard?

When [`serializing a request origin`](https://fetch.spec.whatwg.org/#serializing-a-request-origin), Step 2. tells us to
`Return request's origin, serialized`. A [request's origin](https://fetch.spec.whatwg.org/#concept-request-origin) is either `"client"` or an [Origin](https://html.spec.whatwg.org/multipage/browsers.html#concept-origin). However, the 

 [`ASCII serialisation of an origin`](https://html.spec.whatwg.org/multipage/browsers.html#ascii-serialisation-of-an-origin) algorithm referenced in Step 2. does not handle the case of a `"client"` origin. (Because it is about serializing an origin as described in the HTML spec, not a request's origin as described in the fetch spec.)

How should an origin of `"client"` be serialized?

**Comment by annevk** [comment]
I don't think it can ever be "`client`" at that point in time? Might be reasonable to add an assert though.

**Comment by Wuelle** [comment]
Right, its set during [fetching](https://fetch.spec.whatwg.org/#concept-fetch) and then never touched again:
> If request’s [origin](https://fetch.spec.whatwg.org/#concept-request-origin) is "client", then set request’s [origin](https://fetch.spec.whatwg.org/#concept-request-origin) to request’s [client](https://fetch.spec.whatwg.org/#concept-request-client)’s [origin](https://html.spec.whatwg.org/multipage/webappapis.html#concept-settings-object-origin).

Adding an assert seems reasonable. There are more places where its not immediately obvious that they are only called when the origin cannot be `"client"`, like [`append a request origin header`](https://fetch.spec.whatwg.org/#append-a-request-origin-header). I assume those should get an assert too?

**Comment by annevk** [comment]
I think that would be reasonable, yeah.
