### ISSUE TITLE
Empty statusText does not match the reason-phrase token production

### ISSUE THREAD

**Issue by F3n67u** [whatwg/fetch#1794]
### What is the issue with the Fetch Standard?

In [initialize a response](https://fetch.spec.whatwg.org/#initialize-a-response) algorithm:
> 2. If init["statusText"] does not match the reason-phrase token production, then throw a TypeError.

but [reason-phrase](https://httpwg.org/specs/rfc9112.html#status.line) token production requires at least one characters:

> reason-phrase  = 1*( HTAB / SP / VCHAR / obs-text )

so if `init["statusText"]` is a empty string "", this step would fail.

**Comment by annevk** [comment]
Wow, I'm surprised this hasn't been noticed before.

**Comment by annevk** [comment]
If you could take a look at #1795 I'd appreciate it.
