### ISSUE TITLE
Parsing `application/x-www-form-urlencoded` byte sequence is infallible

### ISSUE THREAD

**Issue by F3n67u** [whatwg/fetch#1798]
### What is the issue with the Fetch Standard?

https://fetch.spec.whatwg.org/#dom-body-formdata

In "The formData() method steps":

> "application/x-www-form-urlencoded"
> 1. Let entries be the result of parsing bytes.
> 2. If entries is failure, then throw a TypeError.
> 3. Return a new FormData object whose entry list is entries.

Step 2 seems not necessary because parsing `application/x-www-form-urlencoded` byte sequence is infallible: https://url.spec.whatwg.org/#concept-urlencoded-parser

**Comment by nektro** [comment]
looks like in https://url.spec.whatwg.org/#concept-urlencoded-parser step 5 2 https://encoding.spec.whatwg.org/#utf-8-decode-without-bom can fail

**Comment by annevk** [comment]
Nice find! Seems this has always been wrong: 6a9ae23aaace5aabf78433e0380cb4283f3ab0a8. (And I checked the URL standard which got the definition from the HTML standard about twelve years ago, a move I was responsible for as well, and that never returned failure either.)
