### ISSUE TITLE
Header guards

### ISSUE THREAD

**Issue by phuu** [whatwg/fetch#182]
As part of [fetch-engine](https://github.com/phuu/fetch-engine), @ahume and I have run into the [guard][concept-guard] state of the [Headers][headers-class] object. We have some questions:

- How is the guard initially set? There doesn't seem to be a parameter for it.
- What does the external API for getting and setting the Headers' guard value look like?

[headers-class]: https://fetch.spec.whatwg.org/#headers-class
[concept-guard]: https://fetch.spec.whatwg.org/#concept-headers-guard

**Comment by annevk** [comment]
There's no external API at the moment. It's an internal slot controlled by the user agent.

**Comment by phuu** [comment]
Ok, thanks for getting back to me. What do you suggest for a polyfill implementation? We don't want mutable Response Headers!

**Comment by annevk** [comment]
I'm not sure. The way we sometimes explain this "magic" is that if these objects were solely implemented in JavaScript they would accept a magic token in the constructor somewhere known only to the user agent that would do the right thing. It's not clear you can really polyfill that though. @domenic?

I suspect at some point we should give this constructor a second argument that takes a dictionary that does expose this. And perhaps also expose guard as a getter on the object's prototype. Not sure.

**Comment by phuu** [comment]
I guess we can if we use a private object.

The spec contains lines like `Set r's Headers object's guard to "request-no-cors"` although it looks like it could be decidable at instantiation, so no need to "set"?

**Comment by annevk** [comment]
Yeah, I don't think we ever change it over time. Either way could be implemented through some kind of private access, but I don't think we really want to be changing it over time, this was just easier to write down.

**Comment by phuu** [comment]
Ok. I think for our case we'll make some factories close over the guard. Happy for me to leave this issue open pending some more spec detail, or would you rather close it?

**Comment by annevk** [comment]
Is there anything you would want to change in the specification? (Other than perhaps creating a public API for guards which we should probably do as a distinct issue if it comes up again.)

**Comment by phuu** [comment]
Not at the moment. If something crops up during our implementation then I'll open another issue. Thanks for your help!

**Comment by domenic** [comment]
For internal slots I have been using symbols, but for IE-compatible code underscore-prefixed properties (`headers._guard`) is traditional.

**Comment by ahume** [comment]
I ended up implementing subtypes of the Headers class for each of the guard values. RequestHeaders, ResponseHeaders, etc... which set a private guard property in their constructors. Seems like a clean approach, but we'll see how this pans out as we implement Request/Response. The base class still relies on the internal guard property, but the APIs never have to worry about reading or writing these.

@phuu made the point that eg. immutable headers throws a TypeError if you try to write to it. Could that be an indication that types are a good way to go here?

**Comment by domenic** [comment]
> I ended up implementing subtypes of the Headers class for each of the guard values.

This seems bad, as it is a web-observable difference in the prototype chain, .constructor property, etc.

**Comment by phuu** [comment]
Hey @domenic. Could you clarify that a little bit? Is your worry that people will be able to tell what kind of request was made?

**Comment by domenic** [comment]
@phuu I can write a bunch of tests that will pass with a real fetch implementation and fail with a polyfill implemented as you describe. For example, `Object.getPrototypeOf(response.headers) === Headers.prototype`, `response.headers.constructor === Headers`, etc.

It seems better to implement this as the spec says, with a single Headers class and an internal (i.e. underscore-prefixed) guard.

**Comment by phuu** [comment]
Ok. Thanks for your feedback, we'll take a good look at the options and let you know if we find something that persuades us in another direction.
