### ISSUE TITLE
Request body should be removed when method changed to GET

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/fetch#187]
https://fetch.spec.whatwg.org/#http-fetch 5.redirect.10.4

> 4. If either actualResponse's status is 301 or 302 and request's method is `POST`, or actualResponse's status is 303, set request's method to `GET`.

The body should be removed at this point to avoid a `GET` request with a body.

**Comment by annevk** [comment]
Thank you!

**Comment by wanderview** [comment]
I believe we already do this in gecko thanks to reusing existing network code.  No impl bug needed.

**Comment by jakearchibald** [comment]
Chrome is also ok, but we have some problems on navigate https://code.google.com/p/chromium/issues/detail?id=573937

**Comment by wanderview** [comment]
Thanks for the link with the test case.  We do indeed seem to pass it.  (Much better than me trying to read code the first day after holiday...)
