### ISSUE TITLE
Behavior unspecified with multiple headers with same name

### ISSUE THREAD

**Issue by achristensen07** [whatwg/fetch#190]
https://fetch.spec.whatwg.org/#headers-class could be more specific in these two cases:
1) Does delete(name) delete all headers with the given name, or just the first such header?  If the former, should it be called deleteFirst? If the latter, should there be a deleteAll?
2) Does set(name, value) overwrite the first header with the given name if there is one?  Should it leave the other headers with the given name untouched? If there isn't one, does it append it at the end?

Sorry, I'm new to working with whatwg.  How would I go about changing this or suggesting tests for a test suite?

**Comment by annevk** [comment]
1. How is the definition of `delete()` not clear? It links to https://fetch.spec.whatwg.org/#concept-header-list-delete which is extremely specific.
2. The same goes for `set()`.

Tests need to go into the `fetch/` directory of https://github.com/w3c/web-platform-tests/. There's not very many currently so any contributions there would be most welcome. I'll update the `README.md` of this repository to point out that it exists.

**Comment by youennf** [comment]
As per https://fetch.spec.whatwg.org/#concept-header-list-delete, delete is similar to "deleteAll".

It is indeed a good idea to build a test-suite :)
We have some tests related to fetch API that we would like to contribute.
They are already WPT formatted.
Is it ok to submit them all in once or is it better as smaller batches?

@annevk do you have any idea of a good fetch/ directory structuring?
I was thinking it might help to separate fetch-api specific tests from other fetch tests, either in a subdirectory or a separated fetch-api/ directory.

**Comment by annevk** [comment]
@youennf adding an api/ subdirectory seems good. No concrete ideas unfortunately. I think you can submit them all at once, though @jgraham or @Ms2ger might have more insight.

**Comment by youennf** [comment]
Fetch API test PR is https://github.com/w3c/web-platform-tests/pull/2454

**Comment by wanderview** [comment]
I believe blink tree has some wpt tests that could be upstreamed after some work to remove php-specific stuff.

**Comment by annevk** [comment]
Closing this as I think all the points @achristensen07 raised have been addressed. Feel free to reopen this if you disagree. If you have any further questions you're also always welcome to reach out on IRC: https://wiki.whatwg.org/wiki/IRC.
