### ISSUE TITLE
Only append Authorization if none is set

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#198]
Currently we happily append `Authorization` headers even though someone might have already set one. Instead, we should just give priority to the custom header.

**Comment by wanderview** [comment]
Not sure what we do here, but here's a bug to write a test and fix if necessary:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1240755

**Comment by annevk** [comment]
Oh thank you, but this actually originated here: https://bugzilla.mozilla.org/show_bug.cgi?id=1064378. Though @hallvors might still want to write tests indeed.

**Comment by hallvors** [comment]
These tests are on the way into web-platform-tests:
https://github.com/w3c/web-platform-tests/issues/2503
https://github.com/w3c/web-platform-tests/issues/2502

..and one is yet to be written:
https://github.com/w3c/web-platform-tests/issues/2512

@wanderview if you can think of scenarios that are not yet covered by those tests and the ones you see if going to https://github.com/w3c/web-platform-tests/find/master and typing ```send-authentication-``` please let me know :)

**Comment by hallvors** [comment]
(That said, we have a "Todo" sort of on figuring out how to turn the XHR tests into corresponding Fetch tests. I haven't looked at that yet.)

**Comment by annevk** [comment]
@hallvors you may want to look into https://github.com/w3c/web-platform-tests/pull/2454 which is adding a ton of Fetch API tests.

**Comment by youennf** [comment]
Custom Authorization headers should probably be removed when doing cross-origin redirections.
Is there a place in the spec where this is defined?

**Comment by annevk** [comment]
@youennf why? They would require a CORS-preflight for the new URL, so there's no real difference from using them with the redirected URL directly.

**Comment by youennf** [comment]
It seems strange to send a piece of data which is usually scoped by the server URL.

WebKit is dropping Authorization header whenever going from a server/origin A to a server/origin B, be it custom or not. It may be readded later on for server B, following more or less step 13 of https://fetch.spec.whatwg.org/#http-network-or-cache-fetch

Not dropping this custom header will preclude sending any valid Authorization header for server B that could be computed from pre-existing authentication entries).
Instead, an Authorization header that we know is irrelevant to server B will be sent.

**Comment by annevk** [comment]
> It seems strange to send a piece of data which is usually scoped by the server URL.

Maybe, but it's also consistent and does not require special casing existing headers (and new headers going forward).

Also, with a custom value we do not know that it is going to be useless for the other origin. It may very well work.

**Comment by youennf** [comment]
This would need to be confirmed but Chromium might also be removing the Authorization header.

As of special casing, I understand the desire, but Authorization is already special-cased by the spec.
It is one of the few non-forbidden header that is also controlled/set by the network layer.

**Comment by annevk** [comment]
I think currently a bigger problem is that user agents do not follow redirects after a CORS-preflight, no?

**Comment by youennf** [comment]
Agreed.
I am not sure why this restriction was added.
Technically this is pretty easy to remove that restriction (two line changes in WebKit probably).
Maybe this is just lacking a good test suite.

**Comment by annevk** [comment]
Yeah. We added the restriction because nobody wanted to think it through from what I remember, despite the restriction actually adding complexity.

Anyway, it's gone now, but implementations and tests haven't been updated yet.

**Comment by youennf** [comment]
When cors-preflight-flag is set, the redirect mode of the request is set to "error" according the spec.
Doesn't it preclude following redirects after preflight?

**Comment by annevk** [comment]
Thank you, I will fix that as part of (reopened) #204.
