### ISSUE TITLE
RequestCache "reload" type must also set no-cache headers

### ISSUE THREAD

**Issue by ehsan** [whatwg/fetch#201]
For `reload`, I think the UA needs to set the correct headers to signal to HTTP proxies that the request should not be served from cache.  Gecko does the following in this case:

* It sets the `Pragma: no-cache` request header.
* If the protocol is HTTP >= 1.1, it also sets the `Cache-Control: no-cache` request header.

I think this needs to be spec'ed, since otherwise an HTTP cache along the way will break the contract of the fetch API.

**Comment by annevk** [comment]
What if the developer had already set these headers?

**Comment by ehsan** [comment]
Hmm, good question.

From one perspective, in case the developer has not included `no-cache` then they're probably doing the wrong thing (unless if they can somehow guarantee that there will never be an HTTP cache along the way!).

But more importantly, they might have set the header as `Cache-Control: no-cache no-store` or some such.  So I guess we should only set these headers if the developer has not set them...

(FWIW this is already how Gecko behaves for things such as XHR, if my reading of the code is correct.)

**Comment by annevk** [comment]
Thank you.

(And you can also imagine the developer setting some kind of future or extension value the browser might not know about. That was mainly what I was thinking about.)
