### ISSUE TITLE
Headers.get/getAll/has do not byte-lowercase the name

### ISSUE THREAD

**Issue by jdm** [whatwg/fetch#203]
The algorithms for insertion/deletion/appending all explicitly byte-lowercase the provided name. The algorithms for retrieving header values only say "whose name is _name_".

**Comment by annevk** [comment]
See https://fetch.spec.whatwg.org/#concept-header for why this works. "Case-insensitive byte sequence" is not the greatest concept I suppose, but changing this around would be quite a bit of work.

See also https://github.com/whatwg/xhr/issues/34.

**Comment by annevk** [comment]
I should fix this as part of fixing #304 by basically ditching the case-insensitive byte sequence concept.
