### ISSUE TITLE
error types too vague for TLS certificate error

### ISSUE THREAD

**Issue by bblfish** [whatwg/fetch#205]
If the JS opens a URL to a server that has a problem with the TLS connection because the server certificate is not signed correctly, the `fetch(...)` method just returns a TypeError

<img width="493" alt="screenshot 2016-01-25 16 05 48" src="https://cloud.githubusercontent.com/assets/124506/12556454/de131d64-c37d-11e5-83cf-b082fbb117b9.png">

It would be useful in this case to have a TLSConnectionError exception, explaining the problem so that JS could at least build an explantation of what went wrong. Perhaps this would allow people to send feedback to the web site owner. It would also allow us to run sites locally for testing (as in the picture `joe.example` is running on my machine) and not constantly be wondering why we have problems (I keep jumping around tasks and I keep forgetting this)

**Comment by annevk** [comment]
We haven't done this historically because browser security teams don't want it. I'm not sure whether that changed.

**Comment by annevk** [comment]
I recommend asking browsers about this first. As far as I know we should keep this kind of information sealed.

**Comment by timbl** [comment]
This is an example of what seems to be a major conflict of motivations.  For developers, it is really important to understand what when wrong at many levels, in a nested exception report,  when any system function is called -- but particularly fetch.  Meanwhile browser vendors seem to just plain distrust JS authors and try to return as little as possible sometimes zero.  This a made the web platform a total pain to work with at the moment for developers, and web apps which just hang and fail for no user-evident reason.

**Comment by annevk** [comment]
I think the reason is mostly that browsers don't want to allow developers to probe the user's visible network. That's a hard security constrain that I don't really see a way around.

**Comment by timbl** [comment]
- Some sort of way of empowering/managing trusted apps.   
- Use native
- use Atom, APM ...

**Comment by mnot** [comment]
There's been some speculation among some folks about letting the network describe its "shape" to the browser; e.g., "this address range is private, that address range is not. That subdomain is private..." If there were such a positive signal, it could be used to expose more information about requests where the browser knows they're public. 

That's just speculation now, however, and a lot of questions would need to be answered to make it feasible.

**Comment by bblfish** [comment]
how do we get the right people involved? Is there a forum where the security people and the people here meet?

**Comment by bifurcation** [comment]
FWIW (browser security guy here) while I would have very serious reservations about exposing granular error information to JS (because there's private information there that we don't want to expose without user consent), I would be totally fine putting information like this in the dev console.   I think both Chrome and Firefox already do so, just not in the area your screenshot shows.
