### ISSUE TITLE
Should request constructor throw in case of invalid enumeration parameter

### ISSUE THREAD

**Issue by youennf** [whatwg/fetch#208]
Request constructor has enumeration parameters such as RequestMode, RequestCache...
It is not clear to me whether constructor should throw in case the provided value is not part of the enumeration or whether the default value should be used.

**Comment by annevk** [comment]
That is defined by IDL. You get an exception for enumeration types (not when invoking an attribute's setter, there it becomes a no-op, but in all other cases you do).

**Comment by youennf** [comment]
Good, this is how it is being implemented in WebKit.
Firefox and Chrome seem to have different behaviors.
I will upload tests to keep track of these differences.
