### ISSUE TITLE
Should user be prompted in case Request credentials is set to "omit"

### ISSUE THREAD

**Issue by youennf** [whatwg/fetch#209]
Following on https://critic.hoppipolla.co.uk/showcomment?chain=12616 and https://fetch.spec.whatwg.org/#http-fetch, it is not clear whether step 5 -> 401 -> 3 should  actually happen (user prompted for credentials) if Request credentials is set to "omit" .

**Comment by annevk** [comment]
I'll check later if this is actually defined, but to answer your question we should not prompt for any scenarios where that was not previously required. Prompting the user is a legacy feature that is considered bad (since it's unclear what triggers the rather confusing UX).
