### ISSUE TITLE
upload progress?

### ISSUE THREAD

**Issue by radubrehar** [whatwg/fetch#21]
Is there any way I can attach a progress listener to the xhr.upload object used in fetch?
```js
xhr.upload.addEventListener('progress', function(){ ... })
```
since I use fetch to upload files (with FormData), I would find this very useful.

I initially reported this at https://github.com/github/fetch/issues/89, and was suggested to have it reported here

**Comment by annevk** [comment]
The native `fetch()` API implemented by browsers does not use XMLHttpRequest underneath. The eventual API for progress is building something on https://streams.spec.whatwg.org/ which https://github.com/yutakahirano/fetch-with-streams/ is adding to `fetch()`.

**Comment by bORm** [comment]
Okay, 
```
function consume(reader) {
  var total = 0
  return pump()
  function pump() {
    return reader.read().then(({done, value}) => {
      if (done) {
        return
      }
      total += value.byteLength
      log(`received ${value.byteLength} bytes (${total} bytes in total)`)
      return pump()
    })
  }
}

fetch("/music/pk/altes-kamuffel.flac")
  .then(res => consume(res.body.getReader()))
  .then(res => return res.json())
  .then((resultFromServer) => log(resultFromServer.file))
  .catch(e => log("something went wrong: " + e))
```

how return real response.json() from Server?

**Comment by cusspvz** [comment]
> The native `fetch()` API implemented by browsers does not use XMLHttpRequest underneath.

But yet, it does not mean it couldn't be pondered and proposed.

Native promises are not yet cancellable and/or progressed, so my proposal would be for a callback on the second argument object of `fetch` which would receive a `ProgressEvent` (which is already present because of XHR).

As a polyfill, it could be easily placed with the `progress` event listener as stated by the OP.


API Example: 
```js
aync fetchSometing ( form ) {
  const res = await fetch('/upload', {
    method: 'POST',
    body: form,
    progress: (e) => { console.log(`Progress: ${e.loaded/e.total}%`) }
  })
}
```

**Comment by NitroBAY** [comment]
So why @cusspvz's idea doesn't seem to have been taken in consideration ?
It seems a good idea to me.

**Comment by jakearchibald** [comment]
Discussion around fetch observation is over at https://github.com/whatwg/fetch/issues/447.

**Comment by caub** [comment]
The discussion in #447 was about fetch cancellation, now it's added in the spec with AbortController

For fetch upload progress, it would be great, that's the only missing thing compared to XHR

**Comment by annevk** [comment]
Ah, thanks for pinging this thread. Observation moved to #607. Hope that helps.

**Comment by oliverjanik** [comment]
Please reopen this issue. This is real world scenario on millions of websites daily. Fetch needs needs an upload progress. period.  We've been stuck with the bad XHR API for decades now. 

Yet, no one seems concerned that despite all the efforts and years of debates that went into fetch it does not deliver.

Can everyone on this committee stop treating it as a hot potato a deal with it.

**Comment by annevk** [comment]
There is no committee… And this issue is closed because there is a more focused issue around a concrete proposal towards addressing this.

**Comment by mindtonic** [comment]
@oliverjanik Use the `.on('progress', ...... )` feature of Superagent. https://github.com/visionmedia/superagent

**Comment by oliverjanik** [comment]
No thanks, I like my batteries included.

**Comment by Mouvedia** [comment]
> And this issue is closed because there is a more focused issue around a concrete proposal towards addressing this.

Which is…?

**Comment by xgqfrms** [comment]
https://github.com/AnthumChris/fetch-progress-indicators

**Comment by oliverjanik** [comment]
@xgqfrms I only see download progress, where is upload progress ?

@annevk What proposal are you talking about? Can you post a link?

**Comment by annevk** [comment]
https://github.com/whatwg/fetch/issues/21#issuecomment-381425704

**Comment by jakearchibald** [comment]
There's a PR in progress at https://github.com/webmachinelearning/translation-api/issues/61 for this.

Don't use streams to do this, as it isn't measuring the correct point in time https://jakearchibald.com/2025/fetch-streams-not-for-progress/
