### ISSUE TITLE
Redirect handling is wrong for opaqueredirect

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#212]
We should probably use the response url as the base URL, if there is one, and only if there isn't fallback to the current url. That is a little weird, but otherwise you can figure out where an "opaqueredirect" goes per @jakearchibald's example in #194:

> ```js
event.respondWith(fetch("//static.example.com/foo/", { redirect: 'manual' }))
```
>
> Where:
>
> * The request URL is `//example.com/bar/`
> * Request has a manual redirect mode
> * `//static.example.com/foo/` redirects to `/bar/`
> 
> This would result in redirecting to `//example.com/bar/` rather than `//static.example.com/bar/` right?

The alternative would be to add a check to step 3.3 of https://fetch.spec.whatwg.org/#http-fetch that for an opaqueredirect, request's current url has to match response' url.

What do folks prefer?

**Comment by annevk** [comment]
@jakearchibald @wanderview, opinions?

**Comment by wanderview** [comment]
Ugh.  I guess using response.url as base makes sense.  Pretty sure we do the described bad behavior today in gecko.

**Comment by annevk** [comment]
I guess the only case where we could not use the response URL would be a synthetic response. However, it would be fine with me if in that scenario a non-relative `Location` would simply fail.

If you use `Response.redirect()` to create this synthetic response by the way we get the base URL from script so that will not be affected. It only affects synthetic redirect responses created from scratch.

So that all seems pretty great. Another victory for the response URL.

**Comment by wanderview** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1248417

**Comment by jakearchibald** [comment]
Sounds good to me. Happy for this to fail with synthetic responses, or make them relative to the location of the client.
