### ISSUE TITLE
Preserve fragment in Request/Response URLs

### ISSUE THREAD

**Issue by ParkFramework** [whatwg/fetch#214]
Removing `#hash` of URL, it prevents to use history API:
```javascript
fetch("url#hash").then(response => history.pushState(null, null, response.url))
```

The server redirect, `response.url` needed use, that correct display url in address bar.
I do propose to not delete the `#hash`, it will be more convenient in practice.

`Request.url` and `Response.url` should be similarly `URL.href` (within `#hash`)

**Comment by wanderview** [comment]
Are hashes maintained through server side redirects for xhr?  Or another existing API?

**Comment by annevk** [comment]
Yeah, they are. I guess we should probably revert this "fetch URL" thing. 😟

**Comment by ParkFramework** [comment]
All is well, the only problem auto deletion `#hash` from `Request.url`

```javascript

new Request('/url#hash') // request.url === 'http://example.org/url' (without #hash)
```

**Comment by wanderview** [comment]
If we make this change I worry about places in service worker spec where we might be relying on the hash being removed from the url.

**Comment by annevk** [comment]
@jungkees @jakearchibald any thoughts on the above comment from @wanderview?

**Comment by wanderview** [comment]
I know we had a previous issue about removing the spec from service worker script.  Maybe all that stuff is explicit, but I know we've depended on fetch spec to have certain side effects before for other things.  I guess its just something to double-check.

**Comment by wanderview** [comment]
I guess this would expose the hashes to the fetch event where previously they were not exposed.

It also creates a new requirement on Cache API to store hashes.  The Cache match algorithm would also have to be updated to take into account hashes.

**Comment by annevk** [comment]
Note that I argued in https://github.com/slightlyoff/ServiceWorker/issues/854#issuecomment-216823777 that responses never have a fragment identifier. What happens with redirects is that the fragment from the `Location` header URL can end up being important. Not a fragment on a response, which isn't really a thing.

**Comment by wanderview** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1264178

**Comment by mattto** [comment]
Chrome status: https://www.chromestatus.com/feature/4753419730419712
Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=624278
