### ISSUE TITLE
"If request's origin is "client", set request's ..."

### ISSUE THREAD

**Issue by KiChjang** [whatwg/fetch#219]
https://fetch.spec.whatwg.org/#fetching

> If request's origin is "client", set request's origin to request's client's origin\. 

Should this be the url's origin instead? Or are they equivalent?

**Comment by jdm** [comment]
They're not equivalent, and that's not necessarily the desired outcome. Consider loading a cross-origin image element, for example - the request's client's origin (ie. the origin of the page containing the element) is different from the origin of the url being fetched.

**Comment by annevk** [comment]
Yeah, we definitely want the origin of the client here, not of the URL. And there will be many cases where they differ. @KiChjang can this be closed or do you think this warrants clarification somehow?

**Comment by KiChjang** [comment]
I think that's a good enough explanation. Thanks for the clarification!
