### ISSUE TITLE
consider providing a json serializer for Request and Response

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#22]
Currently `JSON.stringify()` returns simply `{}` for Request and Response objects.  It might be nice to define serializers for these classes to help developers debug their code.

http://heycam.github.io/webidl/#idl-serializers

**Comment by annevk** [comment]
So there are a bunch of objects without pretty JSON representations. Shouldn't developer tools have a way to look at all of them nicely? Or do you want to serialize these and transmit them to the server or some such?

**Comment by wanderview** [comment]
Yea, this is mainly for devtools and console.log.  I'm fine either way.  Just wanted to note that I had someone testing the API get tripped up by this.

**Comment by awalGarg** [comment]
:+1:

**Comment by annevk** [comment]
Let's revisit once there's an actual use case.
