### ISSUE TITLE
Add hooks for foreign fetch

### ISSUE THREAD

**Issue by mkruisselbrink** [whatwg/fetch#223]
slightlyoff/ServiceWorker#751 adds the service worker bits of foreign fetch to the foreign fetch spec. To actually make this work fetch needs to be modified to call "Handle Foreign Fetch" at the appropriate time while fetching (probably between step 3 and 4 of HTTP Fetch).

**Comment by annevk** [comment]
Is it acceptable that you figure out a design and provide a patch as an exercise to get more familiar with things and I'll try to do timely reviews?

**Comment by mkruisselbrink** [comment]
Yes, that's how I was imagining this would work. I'll try to get to this sometime next week.

**Comment by annevk** [comment]
Great! https://github.com/slightlyoff/ServiceWorker/issues/841#issuecomment-189601139 has an outline of the things we need to consider here (apart from figuring out where to invoke the foreign fetch service worker).
