### ISSUE TITLE
Should we send an Origin header for no-cors fetches?

### ISSUE THREAD

**Issue by ehsan** [whatwg/fetch#225]
Currently there seems to be nothing that sets the `omit-Origin-header` flag for no-cors fetches, so per spec we should send the `Origin` header for such fetches which is very strange given that the `Origin` header is mostly used for CORS.

**Comment by annevk** [comment]
Note that Chrome also includes this header for "navigate" when the method is non-GET. Per @tyoshino in https://github.com/whatwg/xhr/issues/31 @hiroshige-g would look into when exactly we want to include the `Origin` header.

A better design might be to not have this flag and all and instead specify in https://fetch.spec.whatwg.org/#concept-http-network-or-cache-fetch exactly under which conditions it is to be included (request mode "cors", request mode "navigate" and request method non-GET, ...).

@jeisinger might also have thoughts on this.

**Comment by jeisinger** [comment]
Chrome actually bases the Origin header on the Referer headers value, so it doesn't really match what the spec says anyways :-/

@mikewest for even more opinions

**Comment by annevk** [comment]
@tyoshino in https://github.com/whatwg/xhr/issues/31 you said @hiroshige-g would check this out but it never happened. I'd love for you to check my proposal.

Per https://bugzilla.mozilla.org/show_bug.cgi?id=1272302 it does seem that Chrome includes `Origin` for "no-cors" (and probably other cases) when method is POST.

I'm inclined to make these changes:

* Remove "omit-Origin-header flag"
* Change HTTP-network-or-cache fetch to include the `Origin` header when either _CORS flag_ is set or request's method is neither HEAD nor GET. (I could be convinced to only include it for POST, but it seems more reasonable to protect the other unsafe methods too.)

**Comment by annevk** [comment]
Also note that discussion in https://github.com/w3c/resource-timing/issues/64 to make `Origin` exclusive for CORS and introduce a new header for CSRF defense.

**Comment by annevk** [comment]
@tyoshino any updates? See also the discussion with @igrigorik in https://github.com/w3c/resource-timing/issues/64. It might actually be good to just restrict `Origin` to CORS exclusively and if we need something beyond same-site cookies to introduce a new header specifically for that purpose. It's not clear to me that the dual purpose of `Origin` for CORS and somewhat anti-CSRF but not really is beneficial.

**Comment by annevk** [comment]
@mikewest thoughts?

**Comment by annevk** [comment]
From the Bugzilla bug it seems that @fmarier considers this worth doing despite `Origin` no longer being useful to tell "cors" from "no-cors" requests.

I'd rather we just recommend same-site cookies as anti-CSRF and keep `Origin` for CORS, but with Chrome already shipping the semantics from https://github.com/whatwg/fetch/issues/225#issuecomment-238874536 and @fmarier interested in aligning I'm no longer super interested in fighting for that.

**Comment by mikewest** [comment]
My recollection is that Facebook and others depend on the form submission behavior to prevent actual attacks today (@hillbrad?). If that's the case, I'd prefer not to pull the rug out from under them.

**Comment by annevk** [comment]
They can't really depend on that since only Chrome and maybe Safari have that kind of behavior.

**Comment by fmarier** [comment]
Facebook uses that header when it's available, otherwise, I think they fall back to checking the Referrer, which is a lot less reliable.

To prevent login CSRF, we can't rely on cookies because users don't have cookies at that point (for various reasons, not every site is able to set pre-login cookies).

I'm open to renaming the header if Chrome is on board too (and we think we can do it), but what Chrome does seem like a worthwhile mechanism, especially if we want sites to move away from relying on Referrer on their login pages.

**Comment by annevk** [comment]
You cannot set the cookies while serving the login dialog? @n8schloss thoughts?

I guess it's simpler to just keep the dual-purpose `Origin` header then and preserve the status quo that servers cannot reliably tell whether it's a CORS request.

**Comment by fmarier** [comment]
> You cannot set the cookies while serving the login dialog?

Correct. Some organizations are unable to set a cookie until the user is logged in.

**Comment by hillbrad** [comment]
Yes, in some jurisdictions there are restrictions about setting cookies that might be used to track logged-out user behavior.  The entropic cookie one would need to prevent login CSRF looks exactly like a tracking cookie, so being able to get a reliable Origin header on POST helps prevent attacks like the one described at http://sakurity.com/reconnect

**Comment by annevk** [comment]
My PR requires the header to be included whenever the CORS flag is set (CORS requests that are cross-origin, roughly) and all requests whose method is `POST`. So a same-origin `fetch(url, {method:"POST"})` would include it. Does that sound okay?

Do we have WPT tests for this already?

**Comment by fmarier** [comment]
>  and all requests whose method is `POST`.

Should that be "all requests whose method is **not `GET`** or is `POST` the only problematic one?

**Comment by annevk** [comment]
@fmarier I forgot what Chrome did. Per https://github.com/whatwg/fetch/issues/91#issuecomment-128261982 it should be non-GET-non-HEAD. I'll update the patch.

Would still be good to know if we have tests.

**Comment by annevk** [comment]
Also, is there a term for GET and HEAD as a set?

**Comment by youennf** [comment]
There are some fetch tests but I am not sure they will be sufficient.
Search for x-request-origin in fetch/api tests.

**Comment by mikewest** [comment]
> Also, is there a term for GET and HEAD as a set?

You might be looking for "safe methods" https://tools.ietf.org/html/rfc7231#section-4.2.1. That includes `OPTIONS` and `TRACE`, which seems fine.

**Comment by annevk** [comment]
@mikewest I don't think that's fine for replacing usage of GET/HEAD in the specification today. (It's also not a fixed set. Other specifications can add to it.)

**Comment by annevk** [comment]
I added some tests at https://github.com/w3c/web-platform-tests/pull/4299. I wanted to write some cross-origin tests too but that got too involved.

**Comment by youennf** [comment]
There are also some tests in fetch/api/cors/cors-redirect.js testing Origin header after redirections (cross-origin or not).

**Comment by annevk** [comment]
It looks like those tests are already correct. Firefox doesn't pass a bunch strangely enough.

**Comment by cup** [comment]
https://github.com/web-platform-tests/wpt/pull/4299
https://github.com/whatwg/fetch/issues/225
https://github.com/whatwg/fetch/issues/871#
