### ISSUE TITLE
Reviver param for response.json()

### ISSUE THREAD

**Issue by tiancheng2000** [whatwg/fetch#230]
How about adding an optional _reviver_ function parameter like that in `JSON.parse()`?
I referenced documents but didn't find alternatives for such a convenient type conversion during the first parse. Any hint will be welcomed.

**Comment by annevk** [comment]
Hi @tiancheng2000, thank you for your feedback. Unfortunately this is not possible. See #104. Perhaps at some point we get a JSON parser that operates on a stream, at that point this might be feasible, though the API would look different.
