### ISSUE TITLE
RequestCache "no-store" type must also set no-cache headers

### ISSUE THREAD

**Issue by ehsan** [whatwg/fetch#231]
Similar to #201.  Both "reload" and "no-store" want to avoid looking the response up in the cache, so in both cases the UA needs to set the no-cache headers to signal this to the HTTP proxies.

I forgot to mention this in #201, sorry about that!

**Comment by annevk** [comment]
Thank you!

**Comment by yutakahirano** [comment]
Shouldn't "no-store" be appended for "no-store" cache mode?

https://fetch.spec.whatwg.org/#concept-request-cache-mode says
 - "no-store": Fetch behaves as if there is no HTTP cache at all.
 - "reload": Fetch behaves as if there is no HTTP cache on the way to the network. Ergo, it creates a normal request and updates the HTTP cache with the response.

If "no-store" cache mode is specified, the browser should not use a response stored in a HTTP proxy, I think.

cc: @matto @toyoshim @tyoshino

**Comment by annevk** [comment]
Could you file that as a new issue? It doesn't seem like it regressed from this one.
