### ISSUE TITLE
RequestCache "no-cache" type must also set the right headers

### ISSUE THREAD

**Issue by ehsan** [whatwg/fetch#232]
Again, similar to #201.

When always validating the contents of the cache, Gecko sends `Cache-Control: max-age=0` to signal to the HTTP proxies along the way to revalidate their cached entries.  This is the behavior for HTTP/1.1.  For HTTP/1.0, Gecko only sends `Pragma: no-cache` since there is no better header to send.

I think we should spec the HTTP/1.1 behavior.

**Comment by annevk** [comment]
Thank you!
