### ISSUE TITLE
Give user entered data: URI documents the HTTPS state 'modern'

### ISSUE THREAD

**Issue by jwatt** [whatwg/fetch#243]
Currently:

https://fetch.spec.whatwg.org/#basic-fetch

leaves data: URI documents with the HTTPS state 'none' if their request's client is null. That means that people testing things by pasting data: URI's directly into a browser's location bar will be getting a document that is not treated as a secure context and therefore is unable to use various new APIs.

We should consider giving user entered data: URI documents the HTTPS state 'modern'.

CC: @mikewest

**Comment by mikewest** [comment]
In Gecko, 'data:' would need to inherit the state of the document that initiated the navigation. It would be strange to treat user-entered top-level data navigations differently from page-initiated top-level navigations, right?

In Chrome, we divorce 'data:' from most capabilities, and I don't think there's much interest in going the other direction on that.

**Comment by annevk** [comment]
See also https://github.com/w3c/webappsec-secure-contexts/issues/26.

**Comment by annevk** [comment]
Per the resolution of the other issue it seems that the status quo is preferred.
