### ISSUE TITLE
Handling of empty bodies

### ISSUE THREAD

**Issue by sicking** [whatwg/fetch#246]
Currently the spec says that `new Response("")` and `new Response(new FormData()`) is handled different from `new Response()`. All three generate a Response with an empty body, but the first two also set the `content-type` header.

Is this intentional? Does it really make sense to set the `content-type` header even if no body is set?

**Comment by sicking** [comment]
Oh, I guess `new Response(new FormData())` might actually generate a non-empty body. At least in Gecko. I'm currently unable to figure out what the spec says.

But the issue applies to `new Response(new URLSearchParams())` and `new Response("")`. I.e. both generate an empty body but still set the `content-type` header.

**Comment by annevk** [comment]
The first two will presumably also have a `Content-Length` header set. Also, due to streams we can't really tell whether things will be the empty byte sequence easily (not without reading, which we don't necessarily want to happen synchronously).

**Comment by sicking** [comment]
I'm not sure I understand the rest of your answer (and I had missed that the question applies to `Request` objects as well).

To clarify my question, is the behavior described below intentional. Or is it unintentional and should be changed. Or is my reading of the specification wrong.

* `new Response(new URLSearchParams())` results in a `content-type: application/x-www-form-urlencoded;charset=UTF-8` header added. No `content-length` header is added.
* `new Response("")` results in a `content-type: text/plain;charset=UTF-8` header added. No `content-length` header is added.
* `new Request(new URLSearchParams())` results in a `content-type: application/x-www-form-urlencoded;charset=UTF-8` header added. No `content-length` header is added to the Request object, but `content-length: 0` is added if the request is sent over the network.
* `new Request("")` results in a `content-type: text/plain;charset=UTF-8` header added. No `content-length` header is added to the Request object, but `content-length: 0` is added if the request is sent over the network.

**Comment by annevk** [comment]
Hmm, I wonder if we should be adding a `Content-Length` header to synthetic responses after they have come from the service worker.

It's somewhat intentional to not special case the empty string even though we could do that for some objects if we wanted to.

Are you seeking to make this consistent with something else that does special case the empty string?

**Comment by sicking** [comment]
> Are you seeking to make this consistent with something else that does special case the empty string?

I'm saying that it's surprising to set a `Content-Type` header in a `Response` that doesn't have any content. I.e. which doesn't have a body. This seems to go against the http defined semantics of the `Content-Type` header.

**Comment by mnot** [comment]
@sicking a text/plain file can have zero length on every OS I'm aware of. I agree it's not typical to send one on the network, but I don't know why it should be disallowed.

**Comment by sicking** [comment]
Fair enough
