### ISSUE TITLE
The reason why Access-Control-Request-Headers includes simple headers

### ISSUE THREAD

**Issue by tyoshino** [whatwg/fetch#249]
/cc @mattto

IIUC, the Access-Control-Request-Headers is built by scanning all the entries in `request`'s header list's headers, and therefore it includes the names of the simple headers if any. Right?

If so, is there any reason to do so? We just found that the Firefox doesn't include them while Chrome does.

Including simple ones provide more info to the server via the preflight, but it should be not so important?

When checking the response, only request headers that are not simple are compared with the Access-Control-Allow-Headers. So, the server doesn't need to know simple ones for building the Access-Control-Allow-Headers.

**Comment by annevk** [comment]
One problem would be `Content-Type`, of which only a subset is simple. Would it only be included if header list contained a non-simple value for it?

Paging @sicking and @wanderview.

**Comment by wanderview** [comment]
> One problem would be Content-Type, of which only a subset is simple. Would it only be included if header list contained a non-simple value for it?

We do pretty much that in gecko:

https://dxr.mozilla.org/mozilla-central/source/netwerk/protocol/http/nsCORSListenerProxy.cpp#966

The logic is a bit convoluted, but effectively we add `Content-Type` to `Access-Control-Request-Headers` if its not an allowed simple content-type value.

I'm sure @sicking would know more.

**Comment by tyoshino** [comment]
> The logic is a bit convoluted, but effectively we add Content-Type to Access-Control-Request-Headers if its not an allowed simple content-type value.

This looks reasonable. Once the spec is changed to follow this, Blink would also.

**Comment by sicking** [comment]
My recollection is that I implemented what the spec said at the time when the implementation was written. But that could be wrong.

Generally speaking, I think we should include the headers in `Access-Control-Request-Headers` that we require to be returned in `Access-Control-Allow-Headers`. No more and no less.

So in situations where we require `Access-Control-Allow-Headers` to contain `content-type`, we should also include it in `Access-Control-Request-Headers`.

And if we don't require `accept` in `Access-Control-Allow-Headers`, then we should also not include it in `Access-Control-Request-Headers`.

**Comment by tyoshino** [comment]
https://dev.w3.org/cvsweb/2006/waf/access-control/Overview.src.html#rev1.220 added a clarification text saying that `Access-Control-Request-Headers` includes simple ones.

I don't see any related discussion in http://lists.w3.org/Archives/Public/public-webapps/2009JanMar/

**Comment by annevk** [comment]
@tyoshino would you be okay aligning with Firefox?

**Comment by tyoshino** [comment]
@annevk Yes. I believe that works.

**Comment by annevk** [comment]
Thanks for reporting this!
