### ISSUE TITLE
Stop hardcoding the list of schemes that inherit HTTPS state

### ISSUE THREAD

**Issue by jwatt** [whatwg/fetch#255]
Right now the 'Basic fetch' section in the spec hardcodes the schemes that result in the HTTPS state of the request's client being inherited onto the response. That requires the Fetch spec to know about every single scheme. Better would be to allow the sections/specs that define a scheme to define whether HTTPS state inherits for the given scheme.

I'm not sure how this would interact with https://github.com/whatwg/html/issues/856

CC @bzbarsky

**Comment by annevk** [comment]
Per Fetch any other scheme results in a network error.

**Comment by bzbarsky** [comment]
That doesn't match implementation reality, though: implementations can and do implement other schemes in various cases, and will add future ones, I expect...

**Comment by annevk** [comment]
Sure, and those that are standardized/interoperable make it to this list. I guess I could acknowledge that some implementations chose not to follow the specification and that for the schemes for which that is true it's a "chose your own adventure".

Anyway, even if there were more schemes and it was open-ended, each scheme would still be required to have a specification that defines how it creates a response, including HTTPS state, so I'm not sure how to satisfy the request. Unless there's classes of schemes that could have some kind of code reuse perhaps?

**Comment by bzbarsky** [comment]
I think the request here is to be able to write such a scheme specification without either monkeypatching the fetch spec or having to edit it....

**Comment by annevk** [comment]
Is there even a generic way to do that given the origin checks, disabling certain types of schemes, etc? Any kind of scheme probably needs some kind of integration or at least careful review to make sure everything works properly.

I haven't heard of any such schemes recently (the only one is "filesystem" and that seems to be on the backburner now). Which one are you thinking of?

**Comment by bzbarsky** [comment]
I don't have a specific one in mind right now.  This came up while trying to implement https state in Gecko, which does have a pluggable scheme infrastructure and hence needs to provide this sort of functionality in general...

**Comment by annevk** [comment]
Yeah, that seems like an interoperability hazard, if exposed to the web. (`registerProtocolHandler()` would convert arbitrary schemes into some kind of HTTP URL, that seems like the extensibility the web needs here.)

**Comment by bzbarsky** [comment]
We're talking about extensions implementing schemes here.  Yes, there's an interop hazard as with any API extensions can expose to web pages...

**Comment by annevk** [comment]
So if it's only extensions, should those be covered by standards? E.g., if someone replaces the global object with a different kind of object, should the HTML Standard account for that?

**Comment by bzbarsky** [comment]
I think it's worth writing standards in ways that make them amenable to extensions.  That doesn't require that we support all possible things extensions can do.

For the record, extensions can't replace the global in any browser I know of.  ;)

**Comment by annevk** [comment]
I'm not really sure what to do here. User agent extensions are outside the scope of specifications. And user agents supporting new schemes is a big enough deal that we can update the specification for it.

Also, personally, I'm not at all convinced that it's a good idea for this to be extensible in the manner it is in Firefox, since it'll likely result in security issues for users with such extensions installed.

**Comment by annevk** [comment]
Closing this since extensions haven't really been accommodated for in standards thus far. If we want to change that we should have a wider discussion.
