### ISSUE TITLE
Setting strategy to control ReadableStream's internal buffer

### ISSUE THREAD

**Issue by howientc** [whatwg/fetch#257]
Hi,

I'm trying to limit the internal buffering when reading from a URL to avoid using too much memory (I'm loading a 620MB file). From what I've read, ReadableStream supports the possibility to define a strategy which sets a high water mark on the number of bytes in the buffer. This sounds good, but my question is, is it possible to use it from a fetch call?

I'm basing my code off Jake Archibald's (excellent) example from his blog:

```
fetch(url).then(response => {
			let reader = response.body.getReader();
```

reader is a ReadableStream. Is there anyway to either tell fetch to use a strategy when constructing this stream, or can I modify or construct a new ReadableStream from the old one that implements a strategy?

Thanks!

**Comment by annevk** [comment]
Paging @domenic and @yutakahirano.

**Comment by yutakahirano** [comment]
@domenic, BYOB reader will address this request, right?

**Comment by yutakahirano** [comment]
> @domenic, BYOB reader will address this request, right?

Seems I was wrong.

@howientc, even if you were able to control the stream's strategy, a typical UA would have additional native buffers and the OS might have its own buffering mechanism. Currently the UA can determine the stream's strategy, but even without it the UA can have intermediate buffers as much as it likes. So I'm not sure if controlling the strategy is important in this case.

**Comment by howientc** [comment]
Thanks @yutakahirano for the quick and useful information. 

I implemented a pause/resume manually in my code to only call read() when my buffered data drops below a threshold, but the impact was minor. Memory was still being gobbled up. Performance was slightly better, probably because buffering by the UA is more efficient that managing my own queue of buffers in javascript.

**Comment by domenic** [comment]
Right. I think BYOB reader can be used to give you more direct control over JS memory allocation, but it won't necessarily control UA and OS memory allocation.

I am sympathetic to the idea of being able to provide fetch with some kind of high water mark, but I'm not sure it's very implementable in practice given all the behind-the-scenes work going on. Maybe it would be useful, not as much for controlling memory allocation, but for hinting cases when you know that backpressure should not be applied too quickly (and you're willing to sacrifice memory for this). But that's a pretty rare use case.

**Comment by jimmywarting** [comment]
hmm, just faced the same issue...
