### ISSUE TITLE
Add examples for PATCH and PatcH (or some such)

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#260]
To illustrate these are different methods. Maybe also add "CHICKEN"  to show "anything" is possible.

**Comment by annevk** [comment]
Acknowledge "Adam Lavin".

**Comment by Lavoaster** [comment]
How about documenting [RFC2324](https://tools.ietf.org/html/rfc2324) examples?

**Comment by annevk** [comment]
@Lavoaster I couldn't come up with a good one. If you have any ideas, please do provide a pull request. Would be fun (though I prefer tea myself).
