### ISSUE TITLE
Should fetch(evt.request) send original RequestDestination and RequestType?

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#262]
While reviewing some gecko related code I noticed that step 8 of the Request constructor copies most values, but does not copy RequestDestination or RequestType:

  https://fetch.spec.whatwg.org/#dom-request

This means that a service worker that does `fetch(evt.request)` will make a network request with the default destination and type.  This is significant because CSP checking uses these attributes in order to enforce things like child-src, etc.

Is this intentional?  It would seem to break CSP on SW passthrough requests.

**Comment by wanderview** [comment]
Related gecko bug:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1250048

**Comment by annevk** [comment]
This is by design. Letting `fetch()` control the CSP policy would be a security violation. I suppose I could make it more explicit that certain fields are intentionally not copied there.

**Comment by annevk** [comment]
(The only way to make that work safely is by earmarking the response in some way with the destination/type/etc. and only allowing it to be used as earmarked. I don't think anyone is interested in implementing the infrastructure required for that.)

**Comment by wanderview** [comment]
Thanks Anne!
