### ISSUE TITLE
The CSP hooks for `<script src='...' nonce='...'>` are broken.

### ISSUE THREAD

**Issue by mikewest** [whatwg/fetch#269]
The hooks I wrote for HTML and Fetch are a bit broken for nonces. In short: `<script src='https://example.com/' nonce='abcde'>` should be allowed by `script-src 'nonce-abcde'`, even though `example.com` isn't whitelisted.

Chrome handles this by setting a flag on the outgoing request during script loading ([in `ScriptLoader.cpp`](https://blink.lc/chromium/tree/third_party/WebKit/Source/core/dom/ScriptLoader.cpp#n376)), which I suppose we could replicate in HTML's "prepare a script".

@annevk: how do you feel about an "Already passed CSP checks so please don't do more" flag on Fetch's `request`?

**Comment by annevk** [comment]
And the reason we don't set nonce on request is because we want to do the check for inline and external scripts at the same time?

It seems a little weird that if you can specify a nonce, you can suddenly make cross-origin requests. Isn't that a security issue?

**Comment by mikewest** [comment]
> And the reason we don't set nonce on request is because we want to do the check for inline and external scripts at the same time?

We could set the nonce on request and do the whole check there, I suppose. I guess that could be a better layering...

> It seems a little weird that if you can specify a nonce, you can suddenly make cross-origin requests. Isn't that a security issue?

As implemented, nonces are basically capability tokens: if you have the token, you can execute script. This turns out to be a super-useful model that I'm actually interested in expanding (see `'unsafe-dynamic'` and https://lists.w3.org/Archives/Public/public-webappsec/2016Mar/0080.html).

**Comment by annevk** [comment]
That is great, but if a page uses capability tokens, you can use them to leak information (even if the capability doesn't match the response of that server). Basically, you created a hole in CSP.

**Comment by mikewest** [comment]
> That is great, but if a page uses capability tokens, an attacker can use them to leak information (even if the capability doesn't match the response of that server)

Yes. Nonces reduce CSP's effectiveness as a defense against exfiltration. Happily(?) it's already pretty bad at that, and preventing XSS is a significantly more valuable goal. Especially since executing odd script is a precondition for exfiltration.

> Basically, you created a hole in CSP.

As the thread explains, whitelisting doesn't work for any sufficiently wild origin (`googleapis.com`, `google.com`. We're replacing a hole in CSP with a significantly smaller hole, which happens to be shaped in such a way that it makes deployment in general simpler. *shrug* I'm excited about it.

**Comment by annevk** [comment]
Mkay... I do think it's slightly cleaner to put the nonce on the request and have HTML only do a nonce check for inline scripts (and event handlers?).
