### ISSUE TITLE
Ability to configure default Headers

### ISSUE THREAD

**Issue by ironfroggy** [whatwg/fetch#271]
For many systems *all* requests require certain headers, either for authorization, load balancer selection in testing scenarios, or CSRF protection schemes. Having to pass headers explicitly with every individual call to `fetch()` makes this difficult, especially compared to the ability to inject them into every call of `$.ajax()` that a lot of projects may be moving to `fetch()` from.

I'd like to suggest configuring some API to configure default headers that would be used for all future `fetch()` calls in the session. Maybe an object at `fetch.headers` which could be used as a default set of headers to extend by the `headers` parameter to each `fetch()` call?

**Comment by annevk** [comment]
I think it would be best to create your own abstraction for this. I recall seeing this request before, so it's worth considering in the future maybe, but for now the focus is on basic functionality. Hope that's understandable.

**Comment by domenic** [comment]
It's pretty simple to achieve what you're asking with just `window.fetch = function (...) { ... }` where you call the original `fetch` with headers pre-filled.
