### ISSUE TITLE
How does request url differ from url list and current url?

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#275]
The spec says the following:

* A request has an associated url (a fetch URL). 
* A request has an associated url list (a list of one or more fetch URLs). Unless stated otherwise, it is a list containing a copy of request's url. 
* A request has an associated current url. It is a pointer to the last fetch URL in request's url list. 

Shouldn't the first bullet "associated url" just be the first URL in the list?  Why are we storing this separately?

**Comment by annevk** [comment]
It's not really stored separately, but you want to use language like "create a new request whose url is /x/", not "create a new request whose url list has a single entry that is /x/". We could maybe provide some kind of "prose constructor", but I haven't seen a need thus far.

**Comment by wanderview** [comment]
It would perhaps be nice to clarify it should never be different from the first entry in the URL list.  Or just make its definition as the first URL in the list similar to how "current URL" is defined.

**Comment by annevk** [comment]
Well if we did that people creating a request wouldn't be able to use the simpler language. Since they'd put a url in a place that takes a pointer. But we can add a note as to why the setup is as it is.
