### ISSUE TITLE
Credentials flag text in "CORS-preflight fetch" is unnecessarily convoluted

### ISSUE THREAD

**Issue by jdm** [whatwg/fetch#279]
Step 7.12 of CORS-preflight fetch includes this text: `False if request's credentials mode is not "include", and true otherwise`. As far as I can tell, this is equivalent to `True if request's credentials mode is "include", false otherwise`.

**Comment by annevk** [comment]
Also 7.14.

**Comment by annevk** [comment]
Thanks for reporting!

**Comment by jeffcarp** [comment]
🎆 🎉 yay thank you!
