### ISSUE TITLE
Body's total bytes for HEAD requests

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#284]
Apparently in Chrome (and IE) when you do a HEAD request, the progress event will have total set to the value of the response's `Content-Length` header, if any. In Firefox it will be 0.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1264219.

I'm not entirely sure if this makes much sense, but it does actually appear to be the way things are specified unless I'm missing something (despite me insisting that is not the case in the aforementioned bug).

**Comment by shaharmor** [comment]
Any update on this?

**Comment by annevk** [comment]
No, I've been hoping for feedback from @tyoshino and @yutakahirano on this.

**Comment by tyoshino** [comment]
Discussed with @yutakahirano.

If it's well defined (e.g. what value `loaded` should be (0 or the same value as `total`)), it sounds not in-acceptable that we give `total` the role of telling the value in the Content-Length header of a response (more generally, the expected total length of the response body for various scheme, not only HTTP(S)) when the HEAD method is used, not the length of the actual response body (which expected to be non-existent (defined so at least for HTTP(S))).

That said, the main purpose of the ProgressEvent API is for tracking progress of loading the body of the response for non HEAD reqs. The above exception makes the API a bit complicated (a).

The only benefit is that users can use the unified way to probe the expected size leaving the protocol processing details (decoding decimal, understanding which meta deta is representing the expected body size) to the user-agent (b).

I think the question is which of (a) and (b) wins. I'm leaning toward (a), i.e. aligning Chrome to Firefox.

**Comment by annevk** [comment]
@tyoshino okay, so in that case Fetch doesn't need any changes. 0 is the obvious result of step 16 in https://fetch.spec.whatwg.org/#main-fetch which happens before any progress events can take place.

**Comment by annevk** [comment]
Closing this in favor of Firefox.
