### ISSUE TITLE
"origin-only" and "origin"

### ISSUE THREAD

**Issue by yutakahirano** [whatwg/fetch#287]
Fetch spec uses the former and the referrer policy spec uses the latter. Should the values be unified? @jeisinger @estark @ehsan @annevk

**Comment by jeisinger** [comment]
yes, fetch explicitly references the referrer spec, so it should also use the referrer policy values from that spec

**Comment by annevk** [comment]
Okay, so the referrer specification is a little weird here. In that it calls the policy "Origin Only" but the value is apparently "origin". And while https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-delivery-meta and https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-delivery-referrer-attribute do say "origin", they don't refer to "Origin Only" (but instead to some RFC which seems like a bug).

Clearly `<meta>` predates the Fetch feature (added in #80) though so this is my fault.

This would require a breaking change to existing implementations assuming they copied the enum from Fetch, is everyone okay with that or should we preserve compatibility?

**Comment by jeisinger** [comment]
afaik there is no shipping implementation of this, so I'd prefer to just change it

**Comment by annevk** [comment]
Given https://hacks.mozilla.org/2016/03/referrer-and-cache-control-apis-for-fetch/ and https://wiki.mozilla.org/RapidRelease/Calendar I guess we can still change this in time for Firefox 48 indeed. I'd like @ehsan to confirm and then I'll make the change. Apologies again for getting this wrong and thanks a lot @yutakahirano for catching it.

**Comment by ehsan** [comment]
Yeah we still have enough time to change the Firefox implementation.  That being said, I'd appreciate if the change was made *ASAP* to the spec if we want to do it at all.  I can also update the hacks blog post if needed.

**Comment by annevk** [comment]
@ehsan go ahead! Thanks again everyone.

**Comment by ehsan** [comment]
Thanks! Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1265941
