### ISSUE TITLE
consider different default context value than "fetch" for new Request()

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#29]
Currently `new Request()` will get a context of "fetch" even though it may not be used with the `fetch()` function.  Perhaps we should distinguish this case by using a different default context value.  Maybe empty string or "synthesized".

This is related to "what should we do with context" in Cache:

  https://github.com/slightlyoff/ServiceWorker/issues/664

**Comment by ehsan** [comment]
Yeah, I found the default value of "fetch" weird too (I originally thought I'm misreading the spec!)

Perhaps we could default to "unknown"?  Don't feel very strongly on what we end up naming this.

**Comment by annevk** [comment]
I think I prefer the empty string since it's not an actual request context. It's mostly a placeholder.

The reason it is "fetch" now is because I had not considered Cache. It tells you straight away what the request context will be if you use it with `fetch()`, but maybe that is not super useful.

**Comment by ehsan** [comment]
Empty string is fine as far as I'm concerned.
