### ISSUE TITLE
response.ok = false for opaque responses may be misleading

### ISSUE THREAD

**Issue by liabru** [whatwg/fetch#299]
When making a cross-domain fetch one may receive a response with `response.type === 'opaque'`.
Currently this seems to mean (at least in Chrome) that `response.ok` is `false` _even if the response succeeded_.

The current spec does not appear to specify what the value for `response.ok` should be in this situation ([see the spec here](https://fetch.spec.whatwg.org/#concept-filtered-response-opaque)), while it does specify other values like `response.status` being `0`). The [docs on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok) also do not discuss the value in opaque cases (or that they are even a possibility).

I feel that a `response.ok` value of `false` is misleading and may catch other people out who are not aware of the meaning of opaque responses. As for what the value should be, I'm not sure. A value of `true` may also be equally misleading. A value of `null` might be better, but still has potential for issues for people naively checking for `ok` like most examples do.

For those just looking for a code solution, here is one way to catch this case:

      if (response.type === 'opaque' || response.ok) {
        return response;
      } else {
        // do something else
      }

Thanks!

**Comment by annevk** [comment]
Since response's status is 0 per https://fetch.spec.whatwg.org/#concept-filtered-response-opaque, `response.ok` will be false (only true if status is 2xx). It automatically follows from that.

So this is defined and this is intentional.

In https://github.com/whatwg/html/issues/1142 we did determine you can figure out the response status for some opaque responses, but I don't think we're going to change what is exposed here for now.

**Comment by liabru** [comment]
Thanks for the response.

> Since response's status is 0 per https://fetch.spec.whatwg.org/#concept-filtered-response-opaque, response.ok will be false (only true if status is 2xx). It automatically follows from that.

Sure, this makes sense and is per-spec currently. My point is that I feel that this definition feels a little misleading since it doesn't account explicitly for this special case where the meaning of `response.status` changes. By that I mean that `response.status = 0` essentially means _N/A_ (if I understand correctly), which is unlike the meaning of any other status code.

So following the current definition seems to imply that `response.ok == false` can become ambiguous, as it can mean 'response failed' or 'response may or may not have failed' depending on the context. I guess it might just be a good idea to clearly caveat this somewhere (maybe a note)?

**Comment by annevk** [comment]
That sounds reasonable. Probably a more general thing worth pointing out about opaque responses.

**Comment by liabru** [comment]
Thanks for making this clearer!

**Comment by MrKleiner** [comment]
> `response.ok == false` When the request was successful.
> "intended to be like that"
This is utterly fucking retarded.
Name ONE universe (not even galaxy, but a fucking UNIVERSE) where the word `ok` means the OPPOSITE of "good".

**Comment by Shikho18** [comment]
[****]()
