### ISSUE TITLE
TypeError new Headers(obj)

### ISSUE THREAD

**Issue by thurt** [whatwg/fetch#300]
Works:
```javascript
var gh_headers = new window.Headers()
gh_headers.append('Accept', 'application/vnd.github.v3.html')
```

Doesn't Work:
```javascript
var gh_headers = new window.Headers({ 'Accept': 'application/vnd.github.v3.html' })
// Uncaught TypeError: Failed to construct 'Headers': Invalid value
```

Am I missing something?
Edit: In Chrome v49

**Comment by wanderview** [comment]
What browser?  This seems to work in FF46.

**Comment by thurt** [comment]
@wanderview -- chrome v49
I will try in FF when I'm back at computer later.

**Comment by thurt** [comment]
I confirmed it works in FF45 when typing directly into the console.

The strange thing I am seeing here in Chrome is that it works when typing directly in console (same as FF), but it does not work in a script file.
See picture: bottom right shows script file that generated an error for the same operations.
![headers_problem](https://cloud.githubusercontent.com/assets/8955144/15090091/dda5cb24-13e6-11e6-9493-1359226f02a4.PNG)

**Comment by thurt** [comment]
I have now confirmed that both the direct console entry and the script version of these operations works in FF. FF gave me a nice warning about about not having a character encoding set so I added `<meta charset="utf-8"/>` at the top of the html document, but this did not fix for script version in chrome.

Looks like I maybe should file a chrome bug report.
