### ISSUE TITLE
Only specific APIs should skip the fetch event when called within a service worker

### ISSUE THREAD

**Issue by mvano** [whatwg/fetch#303]
Currently it is not clear whether resource fetches for notifications (e.g. icons) shown from a service worker should trigger the service worker onfetch handler. As a use case it makes sense to enable offlining these resources.

My understanding is that fetches initiated directly from a service worker are not passed through the service worker onfetch handler, which seems reasonable. However, what about the fetches triggered indirectly by actions initiated in the service worker, like showing a notification?

CC @annevk @jakearchibald @beverloo @slightlyoff

**Comment by beverloo** [comment]
+1, notification resources should be cacheable by a Service Worker regardless where a notification was shown from. Today this is a failure case for people using push on flaky connections, in a future having a job scheduler/timers there is no guarantee that the device will be online at all when a notification is to be shown.

**Comment by annevk** [comment]
How many APIs in a service worker can cause a fetch?

1. `fetch()` (we cannot let that be captured by the same service worker)
2. `openWindow()` (is captured, though not necessarily by the same service worker, depends on the URL)
3. `showNotification()` (currently not captured, despite being able to fetch multiple resources that should probably work offline)
4. ?

**Comment by annevk** [comment]
@jungkees @wanderview @jakearchibald you might want to discuss this at the SW F2F?

**Comment by annevk** [comment]
@mvano it might be better to file this at https://github.com/slightlyoff/ServiceWorker/issues/new perhaps? Or at least track it in both places.

**Comment by wanderview** [comment]
I don't see anything in the notifications API about setting the skip-service-worker flag:

https://notifications.spec.whatwg.org/#fetch-steps

So I think per spec this should be intercepted.  This isn't all that different from Client.navigate() which might also trigger an onFetch.

So I think it should be intercepted.  I'm not sure what behavior is currently implemented, though.  It would be nice to have a test case.

**Comment by wanderview** [comment]
Actually, I take that back.  Something like foreign fetch would allow these to be intercepted.  Currently I don't think the notification image is loaded in a controlled Client, so its not intercepted.

**Comment by wanderview** [comment]
An alternative here would be to let the Notification API accept Response objects instead of URLs.  Then the SW push event handler could specify resources it already has offlined without a separate fetch event.

**Comment by annevk** [comment]
Foreign fetch only works across origins. Same-origin is not intercepted since the request client is the service worker itself.

**Comment by wanderview** [comment]
@annevk What is the "origin" of the notification popup?  Is it even defined as a window or Client?  AFAICT these requests made from within the browser without a window defining a source origin.  No?

**Comment by annevk** [comment]
The origin of a notification is the origin of the global it was created in. But I was talking about the notification's resources, not the notification itself.

**Comment by wanderview** [comment]
@annevk The spec seems a bit vague right now.  Notification API says to "fetch notification’s icon URL".  It links, however, to a spec text in fetch that depends on having a request:

https://fetch.spec.whatwg.org/#concept-fetch

How does the conversion from URL to request occur here?

**Comment by annevk** [comment]
@wanderview that seems like something that should be fixed, but in principle a notification is no different from `<img>`.

**Comment by wanderview** [comment]
Well, it matters when I'm trying to figure out what the Client should be to determine if its controlled or not.

**Comment by annevk** [comment]
When created in a service worker the client can be nothing but that service worker.

**Comment by jungkees** [comment]
The use case sounds reasonable here, and I'd expect there would be more such needs in future.

Basically, I don't think we want to change the base rule that requests initiated from a service worker won't go through a service worker by default. So, I believe we need an optional parameter to fetch that'd override this behavior.

@annevk, maybe we'll need to discuss more on this in line with the https://github.com/whatwg/html/pull/322 where we try to move the active worker definition to Document/WorkerGlobalScope. I remember you sort of proposed replacing the skip-service-worker flag with using the active worker internal slot of a request's client or something like that?

**Comment by annevk** [comment]
Yeah, my idea was that client-creating requests would specify the service worker they want to use and we'd have a "client" default value that gets it from the client. And a "none" value to bypass the whole thing.

**Comment by jungkees** [comment]
Coming back to issuecomment-234630570, the problem to solve is which service worker this request will use. As the request in this particular case (e.g. icon) is a subresource request, and the client (the service worker) has no controller, we can't decide which service worker to use. Matching a service worker registration for a subresource request seems not quite right either to me.

**Comment by jungkees** [comment]
I think https://github.com/whatwg/fetch/issues/303#issuecomment-234587460 is a good option?

**Comment by annevk** [comment]
Yeah, changing the API is an option and might be the best really. We have been discussing some kind of `IconSet` object that might help with this depending on the characteristics. Although I suppose that would not solve it for sounds and such.

You could use blob URLs today of course...

**Comment by wanderview** [comment]
> You could use blob URLs today of course...

I thought we removed createObjectURL() and revokeObjectURL() from service workers because the life cycle for the URL objects was difficult to define in a SW.

**Comment by annevk** [comment]
Ah, data URLs to the rescue! So yeah, we should fix this 😟

**Comment by wanderview** [comment]
I think we should take this opportunity to experiment with setting a Response instead of a URL.  This is something we want more generally, so it would be helpful to try it out on a small API to start.

**Comment by beverloo** [comment]
For notifications, how would that interact with something like `IconSet`, where the UA will choose the most appropriate resource to fetch? You'd need `Response` objects for all options...

**Comment by annevk** [comment]
Yeah. Or we have some API with which the browser can resolve ahead of time somehow…

**Comment by jakearchibald** [comment]
Other APIs to think of here: workers, shared workers, and any kind of async module loading API we may get in future.

The simplest solution may be to special-case `fetch` in terms of skipping the fetch event. Others go through the fetch event. Let's discuss it at the f2f.

**Comment by annevk** [comment]
That doesn't sound too bad actually.

**Comment by jakearchibald** [comment]
F2F:

* We need to check worker loading in fetch - does it use clients correctly. 
* There's also the font loading API, CSP reporting
* `EventSource` too, but that shouldn't go through the fetch event from a SW, as it creates a loop as it reconnects
* We'd also need to "skip service worker" for `cache.addAll` and `importScripts` (as well as `fetch`)
* This is a lot more complicated than I thought
* Seems much simpler to allow notification to take a response/file for the icon, but this gets tough when it gets to iconsets. Although getting 10 responses doesn't mean we have to read their body into memory
* We could create a new client type for the notification, but how long does this client live? As long as the notification is there
* Decision: special-case notification so it triggers a fetch event in the active worker of this registration, client will be null

**Comment by wanderview** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1290950

**Comment by jakearchibald** [comment]
@mvano @beverloo are you happy with the decision here? We're going to special-case notification fetches so they go through the fetch event of the active worker in the current registration.

**Comment by jakearchibald** [comment]
We may allow other APIs to do this in future, but feels like it should be considered case-by-case. Eg it might make sense for the font loading API to go through fetch, but it probably isn't an interesting use-case until canvas can be used in workers.

**Comment by annevk** [comment]
Why would, e.g., nested workers not go through the same service worker? `EventSource` doesn't seem like much of a problem either, but perhaps we should not expose it in service workers to begin with. We don't expose `WebSocket` either, right?

I still think that most cases we probably do want to round trip through the fetch event.

**Comment by jakearchibald** [comment]
Workers & shared workers are their own client, so they'd do through their own SW (which may be the same one).

Wouldn't `EventSource`'s retry behaviour make this really complicated? I suppose it's no more complicated than ensuring a SW can't keep itself alive by triggering fetches on itself.

Cases we don't want to loop back through fetch:

* `fetch` - although we could expose the `skipSerivceWorker` option which defaults to true in a SW, but could be explicitly set to false
* `cache.add`, `cache.allAll`
* `importScripts`
* `import`, but we may allow it for dynamic module loading if that lands

**Comment by wanderview** [comment]
> I still think that most cases we probably do want to round trip through the fetch event.

I'd rather default to the safe thing and not go through the service worker.  We should only intercept in these cases if we absolutely need to.  Its too easy to trigger infinite loops or pathological behavior.

**Comment by mvano** [comment]
@jakearchibald I'd be happy for the notifications spec to indicate that the fetch must go through the service worker if there is a clear hook for it.

**Comment by wanderview** [comment]
I think today we intercept requests in two different situations:

1. Because they are non-subresource requests with a target URL that matches the scope.
2. Because they are subresource requests that are initiated by a controlled client.

I think we said we were going to just make these non-subresource requests like in (1).  So you just need to make sure notification icon requests end up in here:

https://fetch.spec.whatwg.org/#non-subresource-request

And then they will get picked up by step 12 of Handle Fetch:

https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#on-fetch-request-algorithm

(The stuff about secure client in 12.1 is bogus and we have a separate issue to fix/remove it.)

The other alternative is to create some kind of controlled client to own these icon requests, but I think we chose not to do that.

**Comment by mkruisselbrink** [comment]
I'm not sure if that was exactly what we decided on. One suggestion that was brought up was that it would be possible to assign a specific service worker to a request to make that request go through that particular service worker.

**Comment by wanderview** [comment]
> I'm not sure if that was exactly what we decided on. One suggestion that was brought up was that it would be possible to assign a specific service worker to a request to make that request go through that particular service worker. 

Doesn't that have the problem that a SW script could potentially trigger the notification on a service worker that is not currently activated?  Following the existing interception paths ensures that we only fire FetchEvents on service workers in the correct state.

**Comment by mkruisselbrink** [comment]
Yeah, it would have that effect. Not sure if that is good or bad. For the notifications case it probably doesn't matter, since I don't think an installing worker is likely to be able to show notifications anyway. For other potential future uses I'm not sure what would be the desired effect though. It seems a bit weird to me that a fetch (indirectly) triggered by an installing worker would go through the older but still active worker, rather than through itself. But I agree that some fetches not going through the active worker is equally weird.

But what would you expect with: SW1 at scope /foo, SW2 at scope /bar; SW1 creates a notification with an icon at /bar/icon.jpg (or even with multiple icons/resources, some at /bar/ and some at /foo/...). Should SW1 or SW2 intercept that icon? It seems a bit odd to me to treat the icon as its own top-level resource.

And what if a document controlled by SW1 creates a notification associated with the registration for SW2? Should resources in that notification be fetched through SW1 (with or without the document as client) or SW2?

**Comment by wanderview** [comment]
> But what would you expect with: SW1 at scope /foo, SW2 at scope /bar; SW1 creates a notification with an icon at /bar/icon.jpg (or even with multiple icons/resources, some at /bar/ and some at /foo/...). Should SW1 or SW2 intercept that icon? It seems a bit odd to me to treat the icon as its own top-level resource.
>
> And what if a document controlled by SW1 creates a notification associated with the registration for SW2? Should resources in that notification be fetched through SW1 (with or without the document as client) or SW2?

I think its reasonable for those to be handled by SW2.  Its explainable with the given primitives we have.  I feel like adding a new exception would just make things even more confusing.  Just my opinion of course.

**Comment by annevk** [comment]
> I think we said we were going to just make these non-subresource requests like in (1).

I don't think this makes much sense. That means to include images used for notifications, the scope of your service workers might need to be much wider. For cross-origin resources it wouldn't even work.

The rules for clients only really work well for clients (and maybe reports).

**Comment by wanderview** [comment]
> I don't think this makes much sense. That means to include images used for notifications, the scope of your service workers might need to be much wider. For cross-origin resources it wouldn't even work.

Wow, sure sounds like we really need a controlling client here.  Thats what I would prefer to see myself.

In the absence of a controlling client, however, what is the mechanism that keeps the service worker in the `activated` state between when it triggered the notification and when the browser actually shows the popup?

**Comment by annevk** [comment]
Can you elaborate on that question? I don't really follow.

(Also, I thought you argued for no controlling client above, but I guess my point convinced you?)

**Comment by wanderview** [comment]
At the meeting I wanted a controlling client.

Today we have two mechanisms to keep a service worker in the `activated` state:

1) Clients are being controlled
2) The SW thread is actively handling events or being held alive by extension promises (this is newish)

If we say that the notification requests should just be "intercepted by the SW that made the request", then we run the risk of the SW going redundant before the FetchEvent is fired.  What guarantees that won't happen?  I don't think either of the two cases above are guaranteed to be in effect here.

It would be breaking for a redundant worker to handle a FetchEvent because its state will have been completely stomped on by the updated SW version that took its place.

**Comment by wanderview** [comment]
I think it would just be easier just to use our scope mechanism here.  Since its the SW making the request it can be pretty darn sure the notification will get intercepted.  It can then use pre-cached images, translate to cross-origin requests, or whatever it wants at that point.

**Comment by annevk** [comment]
What is the scope mechanism? If you mean to trigger on the URL of the icon or audio resource, I don't think that makes sense for the reasons I stated earlier. Also, having different fetch policies for notification resources in documents and in service workers seems confusing for developers as well.

Perhaps instead of saying we'll use a specific service worker, we determine some scope and pass that along with the request so the active service worker can be determined at the correct time? I'd love to explore the issues around that a bit more (and since I'm not super familiar with the constraints I appreciate your patience).

**Comment by wanderview** [comment]
> What is the scope mechanism? If you mean to trigger on the URL of the icon or audio resource, I don't think that makes sense for the reasons I stated earlier.

Yes.  I'm disagreeing with you.

Either we need to hold the service worker in the activated state or we need to look up the currently active service worker.

I'd like to see a proposal for how to solve that issue.  Ideally I'd like to avoid creating a new third mechanism that essentially duplicates the controlled Client case.

**Comment by annevk** [comment]
Well, the original proposal of the SW acting as its own client, with some APIs opting out of that, would essentially give you that.

**Comment by wanderview** [comment]
> Well, the original proposal of the SW acting as its own client, with some APIs opting out of that, would essentially give you that.

The service worker holds itself alive as a Client?  That sounds extremely leak prone.

If we really want to go the route of no client, but its still a subresource load (ignoring that subresource implies its a sub- of a client), then I'd suggest we:

1) Distill out the concepts from the client subresource interception into a new concept.
2) Re-write current subresource loads to use that new concept.
3) Write notifications to use the new concept as well.

**Comment by annevk** [comment]
1) Client subresource seems to basically take the active worker of the client and go from there. Per https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#on-fetch-request-algorithm anyway there seems to be nothing to it. But that leads to the situation of the SW acting as its own client which you didn't want.

Although I'm not entirely sure why. There seem to be many ways to end up in loops regardless.

**Comment by wanderview** [comment]
> Although I'm not entirely sure why. There seem to be many ways to end up in loops regardless.

A client is an outside thing using a service worker and has a defined life cycle.  It will go away.  And we trigger functionality on it going away.

Notifications need to have a similar concept so we can define when its safe to trigger the "no one is using the any more".  I think it makes the most sense to tie that to the notification popup in someway instead of a self-reference to the service worker.

**Comment by wanderview** [comment]
To clarify, I have no problem if this notification "client" is hidden from script.  But I think conceptually we should define a lifetime for this notification thing because it impacts the other service worker algorithms.

**Comment by annevk** [comment]
The notification itself can be long-lived, but its fetching needs to happen immediately. The notification is tied to the service worker, as interaction with it can trigger further events in the service worker. But that is the service worker concept, not an individual running instance.

**Comment by jakearchibald** [comment]
Thinking about this again, I still think individual APIs should set the skip-service-worker-flag. The following APIs should set that flag *if* the request's client is a service worker:

* `fetch` - else you get loops
* `cache.add`/`addAll` - else an existing service worker can break installing ones
* `importScripts` - these have special caching & fetching behaviour
* `import` & `import()` - these should follow the same caching & fetching behaviour as `importScripts`

I think notifications should use the current settings object as their client, and shouldn't be a client of their own (they don't have their own CSP rules and can't perform fetches after creation etc etc).

There's the issue of using fetches to keep the service worker open, but I think we can solve that (and other issues) using the timeout pattern described in https://github.com/w3c/ServiceWorker/issues/980#issuecomment-248920422. A fetch from one service worker to another (or itself) will get an expiry time equal to the longest expiry time currently holding the originating service worker open.

**Comment by mkruisselbrink** [comment]
> Thinking about this again, I still think individual APIs should set the skip-service-worker-flag. The following APIs should set that flag if the request's client is a service worker:

We can't just use the existing skip-service-worker-flag as-is for that though, as currently the skip-service-worker-flag also skips foreign fetch service workers (although that's already incorrect and needs fixing for #362).

**Comment by jakearchibald** [comment]
@wanderview how do you feel about https://github.com/whatwg/fetch/issues/303#issuecomment-265483054? If you're happy with it, I'll spec it.

**Comment by wanderview** [comment]
I'm still concerned about allowing `FetchEvent` without a `Client` source we can refer to.  The truth is there is a thing triggering the request, but we are just choosing to hide it from script for some reason.

I mean, I'd be happy with something as simple as a "opaque client", "simple client", or something that doesn't allow postMessage, focus, etc.  But the SW could compare its ID, etc.

**Comment by jakearchibald** [comment]
The client would be the serviceWorker in this case. It makes sense to expose those I think.

**Comment by jakearchibald** [comment]
@wanderview does it solve your concerns if we add a new [client type](https://w3c.github.io/ServiceWorker/#client-type) of "serviceworker"?

**Comment by wanderview** [comment]
> does it solve your concerns if we add a new client type of "serviceworker"?

Well, it seems we should do that for foreign fetch anyway.  So that is ok.

What protections will we have to prevent a SW from keeping itself alive infinitely via fetch events if it can generate its own fetch event?  We must provide some keep-alive budget so that work can be done, but we don't want this to be a way to persist the SW in memory for long periods.

**Comment by mkruisselbrink** [comment]
> What protections will we have to prevent a SW from keeping itself alive infinitely via fetch events if it can generate its own fetch event? We must provide some keep-alive budget so that work can be done, but we don't want this to be a way to persist the SW in memory for long periods.

Probably the same thing we do to prevent a SW from keeping itself alive indefinitely via message events (w3c/ServiceWorker#980)? What chrome currently implements is to limit the timeout of events that are triggered by a service worker to the remaining timeout of whatever event the worker was processing when triggering the new event.

Note that if we allow service workers to start shared/dedicated workers, we'd need to apply the same logic to fetch events triggered by those workers.

**Comment by mkruisselbrink** [comment]
>> does it solve your concerns if we add a new client type of "serviceworker"?
>
> Well, it seems we should do that for foreign fetch anyway. So that is ok.

There has been discussions about whether foreign fetch should expose client IDs (w3c/ServiceWorker#1017), but I'm not aware of any proposals to have actual `Client` objects you can look up for these IDs. So not sure we really need a new client type for that use case. It do think it seems reasonable to add such a client type for this.

**Comment by wanderview** [comment]
> Note that if we allow service workers to start shared/dedicated workers, we'd need to apply the same logic to fetch events triggered by those workers.

True.  I guess we have to cross this bridge in order support nested workers.

Ok, sounds good to me.

**Comment by slightlyoff** [comment]
Dumb question! Is it now possible to call `showNotification()` (e.g., w/ a `tag`) from inside `onfetch` which is triggered by `showNotification()` (perhaps initially called within an `onpush`) to keep a loop going?

**Comment by jungkees** [comment]
@slightlyoff, I understand.. you were talking about this:

```js
self.addEventListener('push', e => {
  registration.showNotification('Seeing this again?', {icon: 'same-scope/atlocal.png'});
};

self.addEventListener('fetch', e => {
  registration.showNotification('Seeing this again?', {icon: 'same-scope/atlocal.png'});
};
```

Not sure if we considered this point (or missed it) that the APIs that intend to follow the proposed default behavior (i.e. enter SW again) can create a loop in this way. Should each API deal with this by having some internal state in the spec algorithm to avoid a loop?

**Comment by wanderview** [comment]
I had thought of this, but for some reason I also thought `showNotification()` was only available from push events.

> Should each API deal with this by having some internal state in the spec algorithm to avoid a loop?

It would be really hard to trace this through async callbacks.  Consider a fetch handler that did a setTimeout() and then a `showNotification()`.

**Comment by jakearchibald** [comment]
I had also thought of this & mentioned it in https://github.com/whatwg/fetch/issues/303#issuecomment-265483054 - is this solution not good enough?

**Comment by annevk** [comment]
What about CSP and NEL reports? Or things that don't necessarily have a client nor should go through a service worker, such as OSCP? Do we need to set the enum for those to "none"?

**Comment by jakearchibald** [comment]
@annevk I thought we were happy with reports going through the service worker? But yeah, anything which doesn't want to go through any SW should set the enum to "none".

**Comment by annevk** [comment]
@jakearchibald yeah, reports should go through, but might not have a client I think. Forgot exactly how they are setup. From what I remember we wanted them to go through the service worker that was associated with their URL, not the one associated with some document.

OSCP wouldn't have a client either and I guess we'd need to define that somewhere since their specification is in IETF land.

**Comment by wanderview** [comment]
@jakearchibald Do you mean in that comment that we can get a loop, but its ok because we'll kill it at after its been running for 5 minutes?

**Comment by sleevi** [comment]
> OSCP wouldn't have a client either and I guess we'd need to define that
> somewhere since their specification is in IETF land..
>
Considering FF is the only UA (out of Edge, Safari, Chrome, IE) to use its
network stack for that, I don't think Fetch should be mentioning OCSP (or
CRLs or AIA, which FF doesn't do but other UAs do, just not in their
process / with the network stack associated with the browsing), no more
than we would suggest SafeBrowsing/SmartScreen should be mentioned.

**Comment by jakearchibald** [comment]
@wanderview yeah, we should probably spec how a serviceWorker gets some time to remain open, and how two service workers (or a worker created by a serviceWorker) cannot give each other more time than they have themselves.

**Comment by wanderview** [comment]
I guess it feels a bit of a foot gun to me.  Devs have to understand which API call might possibly have self-interception and carefully avoid fetch loops.

I am also reminded about my other annoyance with this change.  We used to be able to say FetchEvent was triggered by either navigation or a request from a controlled client.  We now have a third condition which just feels weird.

Anway, even if we made the notification a Client, we would still have the same problem here.  I think we could even get this kind of loop by a fetch event handler doing `clients.openWindow()` triggering another FetchEvent, etc.

So I guess the timer thing is ok.

**Comment by annevk** [comment]
@sleevi fair, didn't realize support was limited to Fx. Isn't there some fetching related to certificates though that everyone implements and needs to bypass service workers?

**Comment by annevk** [comment]
> We used to be able to say FetchEvent was triggered by either navigation or a request from a controlled client.

This wasn't true for reports back then either (unless you bucket them with a navigation somehow, but then this would be similar to that in a way).

**Comment by wanderview** [comment]
> Anway, even if we made the notification a Client, we would still have the same problem here. I think we could even get this kind of loop by a fetch event handler doing clients.openWindow() triggering another FetchEvent, etc.

Oh, this openWindow() loop doesn't happen because we only allow it via "user interaction".

**Comment by sleevi** [comment]
>
> @sleevi <https://github.com/sleevi> fair, didn't realize support was
> limited to Fx. Isn't there some fetching related to certificates though
> that everyone implements and needs to bypass service workers?
>
That's AIA, which FF doesn't support, on macOS/iOS/Win are handled by OS
(and an out of process network stack shared with all users and processes).
Chrome uses its "not at all web/fetch" network stack for it on Linux/CrOS.
So fetch never sees them, even to begin with.

Given architectures today, I *think* only FF is at risk of ever
"accidentally" sending a request for certs/OneCRL/SafeBrowsing/spelling/etc
through Fetch-enabled/compliant networking - for all other UAs, happens
well, well below where Fetch spec is implemented, in bowels of other
systems, not the "UA" per se.

**Comment by wanderview** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1339434

**Comment by jakearchibald** [comment]
Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=592188
