### ISSUE TITLE
Clear response body under certain conditions

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#31]
From @wanderview:

> Looking at the gecko code it appears that there are many cases where the content is explicitly ignored regardless of what the server does:
>
> * HEAD method
> * CONNECT method
> * Responses with status codes 101, 204, 205, 304
>
> See mNoContent in the code here:
>
> https://dxr.mozilla.org/mozilla-central/source/netwerk/protocol/http/nsHttpTransaction.cpp#1523

See also https://github.com/slightlyoff/ServiceWorker/issues/655 and https://github.com/w3c/web-platform-tests/pull/1697

**Comment by annevk** [comment]
Also need to take into account `respondWith()` responses here. I don't think I want to restrict the `Response` constructor for those status codes (and instead handle it all in Fetch), but I'm open to arguments to the contrary for now.

**Comment by wanderview** [comment]
I don't think there is any impact to gecko here since our network stack code was already doing this for us.

**Comment by annevk** [comment]
@wanderview even with synthetic responses?
