### ISSUE TITLE
Non-http fetch doesn't set response URL

### ISSUE THREAD

**Issue by Manishearth** [whatwg/fetch#312]
XHR needs to know the response URL (https://fetch.spec.whatwg.org/#concept-response-url). However, datauri/about/etc fetches don't set it.

We should probably set the response URL in basic fetch itself.

**Comment by annevk** [comment]
This regressed in https://github.com/whatwg/fetch/commit/ed37f5e4cf0ec6615f93b8a575d7349b977ffc3a. 😟

**Comment by annevk** [comment]
Maybe a way to prevent further mistakes is to figure out a way to make this field immutable and set at the time we construct a response rather than this rather weird approach.

**Comment by annevk** [comment]
I think I should just move this back to main fetch. There's no real reason to do it locally.
