### ISSUE TITLE
same origin requests should allow credentials if credentials mode is sameorigin

### ISSUE THREAD

**Issue by Manishearth** [whatwg/fetch#319]
https://fetch.spec.whatwg.org/#concept-http-fetch, when status is `401`,

> If one of the following conditions is true, return response:
>
> - The CORS flag is set.
> - request's credentials mode is not "include".
> - request's window is "no-window". 

However, if the CORS flag is not set, and credentials mode is same-origin, we should be proceeding to the next step.

**Comment by annevk** [comment]
This should use the credentials flag from step 4.3 I think.

**Comment by Manishearth** [comment]
Yeah, makes sense

**Comment by annevk** [comment]
Thanks.
