### ISSUE TITLE
HTTP-redirect-fetch preserves all pre-redirect headers for post-redirect request

### ISSUE THREAD

**Issue by jdm** [whatwg/fetch#320]
This means that things like cookie headers are sent along with the redirected request, which is entirely incorrect for cross-origin redirections, for example. Gecko has been very conservative in its implementation of preserving headers across redirections in the past; currently user-set headers (ie. XHR.setRequestHeader) are preserved, but otherwise each request begins with a clean slate.

**Comment by jdm** [comment]
cc @manishearth

**Comment by annevk** [comment]
This is how the standard is setup as well, no? That's why step 1 of https://fetch.spec.whatwg.org/#http-network-or-cache-fetch clones the request in most scenarios.

**Comment by annevk** [comment]
And to elaborate more, e.g., cookies are only added after that cloning happens.

**Comment by jdm** [comment]
Whoops, I totally overlooked the cloning operation.
