### ISSUE TITLE
json() function does not support anti-json hijacking techniques

### ISSUE THREAD

**Issue by lostmsu** [whatwg/fetch#321]
See http://stackoverflow.com/questions/2669690/why-does-google-prepend-while1-to-their-json-responses
I can't prefix my JSON with while(1); to avoid hijacking, because the parser will reject it.

**Comment by wanderview** [comment]
What browser are you testing in?  Do you have an example site that shows the problem?

In any case, fetch spec does not say how to parse the json AFAIK.

**Comment by lostmsu** [comment]
I am using Chrome.
It is not a valid JSON with the prefix. However, in many cases any JSON has to be prefixed for the reasons mentioned in the above SO question.

**Comment by duanyao** [comment]
json hijacking is no longer possible in modern browsers:
http://stackoverflow.com/questions/16289894/is-json-hijacking-still-an-issue-in-modern-browsers

For older browsers, you can choose not to generate JSON with top level `[ ]`. see
http://www.thespanner.co.uk/2011/05/30/json-hijacking/

**Comment by annevk** [comment]
Thanks @duanyao.

**Comment by lostmsu** [comment]
@annevk , as it also mentioned in comments to the SO answer @duanyao provided, one can not rely on users having modern browser in a question regarding security. From cainuse.com, only Android 4.4 implements full ES5, which ensured invulnerability to this kind of attack. Status of 4.3- is unclear, and it comprises almost 20% of active Android devices, which would comprise 3%+ of all browser users ( see https://en.wikipedia.org/wiki/Usage_share_of_web_browsers#Crossover_to_mobile_getting_more_popular and https://developer.android.com/about/dashboards/index.html ).

Essentially, anyone, who cares about not leaking information via hijacking, must take into account, that at least 3% of users require that protection. I'd expect essentially every major web site, and every enterprise continue using this particular technique to mitigate it.

**Comment by duanyao** [comment]
@lostmsu , did you read http://www.thespanner.co.uk/2011/05/30/json-hijacking/ ? You don't have to prefix your JSON with `while(1);` to protect old browsers, just make sure your JSON is always an object `{ "foo" : ... }`, not an array `[ ... ]`, because the former is not valid JS.

**Comment by lostmsu** [comment]
@duanyao , you are right, that should be enough.
