### ISSUE TITLE
no-referrer should not set referer header

### ISSUE THREAD

**Issue by Manishearth** [whatwg/fetch#323]
https://fetch.spec.whatwg.org/#http-network-or-cache-fetch, step 6

> Append `Referer`/empty byte sequence, if httpRequest's referrer is "no-referrer", and `Referer`/httpRequest's referrer, serialized and utf-8 encoded, otherwise, to httpRequest's header list. 

This indicates that XHR fetches will always have a referer header.

However, the WPT test http://web-platform.test:8000/referrer-policy/no-referrer/meta-referrer/cross-origin/http-http/xhr-request/generic.keep-origin-redirect.http.html expects the referer header to be unset (not empty), and inspecting the requests in firefox show no referer header, only an origin header. This looks like a case of the spec being wrong; I don't see the value in an empty referer header.

**Comment by annevk** [comment]
@estark37, @ehsan, thoughts? I thought the idea was that the `Referer` header would always be there, but I suppose I was wrong.

**Comment by Manishearth** [comment]
I'm seeing many cases without a referrer header being sent in firefox in the WPT tests

**Comment by jeisinger** [comment]
if the referrer header is present, it should always have a non-empty referrer. Conversely, if no referrer is to be sent, the header should be dropped entirely

**Comment by annevk** [comment]
Thank you both!
