### ISSUE TITLE
Model HSTS and Upgrade-Insecure-Request as a redirect.

### ISSUE THREAD

**Issue by mikewest** [whatwg/fetch#324]
Chrome models HSTS as a 307 redirect internally, which has implications for things like referrer policy, CORS, etc. Based on https://dxr.mozilla.org/mozilla-central/source/netwerk/protocol/http/nsHttpChannel.cpp#2141, it looks like Firefox works like this as well (though someone who's more familar with the code should help me out... :) ).

It seems reasonable for us to model UIR similarly, with similar implications.

**Comment by annevk** [comment]
How would that work for `WebSocket` or when redirect mode is not "follow"?

What are the implications for CORS and referrer policy that would be different from the current model in the standard?

I know this is what some implementations do, but it has also caused a ton of bugs as these "internal redirects" need to be privileged in all kinds of scenarios.

**Comment by annevk** [comment]
Closing due to lack of information.
