### ISSUE TITLE
Mark Accept-* request headers as simple / safe

### ISSUE THREAD

**Issue by RubenVerborgh** [whatwg/fetch#326]
I recently had a rather troublesome experience getting CORS to work with the Memento framework.

### Problem
[Memento (RFC7089)](https://tools.ietf.org/html/rfc7089) provides additional HTTP headers to perform time-based content negotiation. Concretely:
- client requests indicate their preference with `Accept-Datetime`
- server responses indicate the timestamp with `Memento-Datetime`

Negotiation can be performed in two ways [1]:
- the server redirects to the negotiated representation with `302`
- the server serves the negotiated representation with `200`
  (using `Content-Location` to indicate its URL)
For various reasons, `302`-style negotiation is preferred.

In contrast to regular content type and language negotiation, however, **it is impossible to make time-based content negotiation work in the browser cross-origin with `302`-style negotiation**.
This is because the Fetch spec requires that requests with [non-simple headers](https://lists.w3.org/Archives/Public/public-webappsec/2016Jan/0119.html) (such as `Accept-Datetime`) are preceded by a preflight `OPTIONS` request asking the server permission to use such headers.
Moreover, in cases that need such a preflight request, `30x` responses from the server are not accepted.

In other words: if the client wants to negotiate cross-origin on content type and language, `302` is allowed. If the client wants to negotiate cross-origin on time, `302` is not allowed and `200` is needed (which is not appropriate in several use cases).

### Proposed solution

**Could it be a considered to mark `Accept-*` headers safe on requests?** After all, no harm can be done with such headers (not more than with `Accept` or `Accept-Language`), so requiring preflight is not necessary.

### Practical use case

The practical discussion of such a use case can be found [here](http://ruben.verborgh.org/blog/2016/06/22/querying-history-with-linked-data/), together with a [live demo](http://bit.ly/artists-york-2012) that uses a [preflight performance hack](https://github.com/LinkedDataFragments/Client.js/commit/a0438531bbfcbd36aec04c73ab16e8d0279f3ef). A different but related discussion was held [here](https://lists.w3.org/Archives/Public/public-webappsec/2013Feb/0078.html).

**Comment by annevk** [comment]
1. To determine whether harm can be done with `Accept-*`, one would theoretically have to study all servers in existence.
2. Per the current standard if you reply to the *preflight* with an appropriate 200, you can reply to the actual request with a 302. We'll then issue another preflight for the new location, and so on. I recommend encouraging browser vendors to implement this.

**Comment by youennf** [comment]
As of 2, if that is not yet covered in W3C WPT test suite, some tests and bug filing to the various browser teams might help.

**Comment by annevk** [comment]
Yeah, we should do that. See also #204 for some previous discussion on how this became the case.

**Comment by annevk** [comment]
Ah, some bugs were filed in https://github.com/whatwg/fetch/issues/204#issuecomment-184254104. I can file one against WebKit.

**Comment by annevk** [comment]
Hope I picked the correct component: https://bugs.webkit.org/show_bug.cgi?id=159056.

**Comment by RubenVerborgh** [comment]
Thanks!

> To determine whether harm can be done with Accept-*, one would theoretically have to study all servers in existence.

I don't agree: it's the other way round: servers have to study the Fetch spec (which scales better than studying all servers). If a server sets `Access-Control-Allow-Origin`, it is the server's responsibility to be aware what the client is allowed to do. And even though there can be an infinite amount of `Accept- *` headers, I think it's fair to say there's not a single one of them that would make a request non-safe (in the HTTP sense). I mean, we're not talking about `X-HTTP-Method-Override` or similar. Could there be a discussion on what headers are considered safe and why?

> Per the current standard if you reply to the preflight with an appropriate 200, you can reply to the actual request with a 302. 

That's great, I didn't know that!

However, it does not fully solve the performance issue of the Memento case, where the client makes a list of requests (all using the `Accept-Datetime` header):
- http://fragments.dbpedia.org/2015/en
- http://fragments.mementodepot.org/timegate/dbpedia
- http://fragments.mementodepot.org/dbpedia_201510?queryA
- http://fragments.mementodepot.org/dbpedia_201510?queryB
- http://fragments.mementodepot.org/dbpedia_201510?queryC
- …

Even though only 1 of these requests would result in a 302, each of the requests to `http://fragments.mementodepot.org/dbpedia_201510?query…` requires an individual `OPTIONS` preflight request, which doubles the number of total requests.

> Ah, some bugs were filed in #204 (comment). I can file one against WebKit.

Thanks for this!

However, for the reason above, I would still be interested in an option where the range of safe headers can be extended; if not in the spec, then at least server-wide. Any other thoughts on this?

**Comment by domenic** [comment]
Isn't this proposal saying that you should be able to override CORS protections just by smuggling your header name with an `Accept-` prefix?

**Comment by RubenVerborgh** [comment]
@domenic Could you give an example use case for that? After all, renaming a header makes it harmless for an unwitting server; and if client and server agree on a header name, it would be the same as explicitly allowing it with `Access-Control-Expose-Headers`.

**Comment by annevk** [comment]
> Could there be a discussion on what headers are considered safe and why?

Per the Fetch standard almost no header is safe since historically almost no header could be transmitted across origins. Browsers have been carving out exceptions, but only for headers with specific values. It's vastly unclear what is safe to do here and what is unsafe so we error on the side of caution.

The idea that servers should just study the Fetch standard and we can add more same-origin policy exemptions over time is not workable. We cannot just put them at new risks tomorrow they were not facing today. It's a tradeoff of course, but the idea doesn't work as policy.

Perhaps there is a prefix we can agree on that is the opposite of `Sec-` that you can use without a CORS-preflight though. If there is some agreement that is not a significant enough risk.

**Comment by RubenVerborgh** [comment]
>  It's vastly unclear what is safe to do here and what is unsafe so we error on the side of caution.

That's the wise approach indeed. However, it could be worthwhile re-evaluating the list, as from what I understand, its members were selected without a clear process. For instance, we could find a list of headers that are definitely unsafe (e.g., `X-HTTP-Method-Override`), headers that are definitely safe (e.g., `Accept`), headers that require investigation.

> we can add more same-origin policy exemptions over time is not workable.

The list should not keep on growing of course. But perhaps a study of what is allowed now and in the future could be timely, given that it is currently “vastly unclear what is safe”.

> Perhaps there is a prefix we can agree on that is the opposite of `Sec-`

But then we're building custom one-offs for the browser only… there's other HTTP clients.

------

Looking up `Sec-`, I noticed that `Accept-Charset` and `Accept-Encoding` are also in the [list of forbidden header names](https://fetch.spec.whatwg.org/#forbidden-header-name). This of course makes sense, and now I understand better why `Accept- *`might seem undesired. However, at the same time, I wonder what the consequences can be from using other `Accept-Charset` and `Accept-Encoding` than what the browser would do (other than the browser not being able to interpret the response). So that's perhaps also something to be studied: for each header, what are the negative consequences of (dis-)allowing it.

**Comment by annevk** [comment]
`Accept-Encoding` is hard to let the application handle by itself, especially SDCH. `Accept-Charset` is somewhat harmless, but also vastly obsolete as everyone should use UTF-8.

**Comment by RubenVerborgh** [comment]
No application _has_ to handle `Accept-Encoding` by itself, as they are not obliged to set it. Furthermore, decoding is handled by the browser currently, so there is no need to change that.

What could happen is that the server sends a response in an encoding the browser does not support. This can be caused by the application using an unsupported value in `Accept-Encoding`, or by the server ignoring the `Accept-Encoding` value. In those cases, the request fails (as it would anyway).

**Comment by annevk** [comment]
I'm going to close this since the original concerns appear addressed. Hopefully the performance problem will lesson over time with https://github.com/mikewest/origin-policy (see also #210). I don't think `Accept-` is a good prefix if we're going to allow certain headers to bypass the preflight check. Maybe `Safe-` or some such, but that would have to be a distinct discussion if we really want to pursue that, and given origin-wide opt-in I'm not sure we do.

**Comment by RubenVerborgh** [comment]
The original concerns are not really addressed (302-style conneg still not possible), but Origin Policy indeed seems the way forward.
