### ISSUE TITLE
Sentence fragment when making CORS preflight request

### ISSUE THREAD

**Issue by jdm** [whatwg/fetch#328]
```
Set request's response tainting to "cors" and request's redirect mode to "error".

The result of performing an HTTP fetch using request with the CORS flag and CORS-preflight flag set.
If the result is a network error, clear cache entries using request. 
```
See second sentence.

**Comment by jdm** [comment]
Reading the surrounding step (11 of Http Fetch), I see what it's trying to do, but it's not doing it very well in my opinion :) The other cases generally make sense, but the ones with any steps besides the response value come out reading very strange.

**Comment by annevk** [comment]
I suppose we could just set "response" to a return value of the first matching statement and then add "Return" here and there and maybe some steps if there are any. Bit more verbose, but should be clearer.

**Comment by annevk** [comment]
Thanks, this looks a lot better.
