### ISSUE TITLE
fetch() memory use proportional to amount downloaded

### ISSUE THREAD

**Issue by ithinkihaveacat** [whatwg/fetch#33]
In Chrome Canary, if searching for a non-existent pattern via https://domenic.github.io/streams-demo/, memory usage increases from ~65MB to ~155MB (as measured by the Task Manager on OS X). That is, the Chrome process seems to grow by about 90MB for each 1000MB downloaded.

(Perhaps this is because the standard method of processing "infinite" streams via a recursive calls seems to require at least two (?) stack frames per read() chunk. Is there any TCO?)

**Comment by domenic** [comment]
This would be a Chrome bug, you should file it there.

FWIW memory usage stayed constant on my Windows box.

**Comment by ithinkihaveacat** [comment]
For those following along, this was logged as http://crbug.com/473062, which spawned https://github.com/domenic/streams-demo/issues/4.
