### ISSUE TITLE
fetch filter the symbols

### ISSUE THREAD

**Issue by yuanalexwu** [whatwg/fetch#331]
```
    // body
    const body = raw_list.join('&');

    // header
    const headers = new Headers();
    headers.set('Content-Type', 'application/x-www-form-urlencoded');
    headers.set('Accept', 'application/json, text/javascript, */*;');
    const fetch_options = {
        method: 'POST',
        headers,
        body,
        credentials: 'include'
    };
    
    // fetch
    fetch(api_uri, fetch_options)
```

The body lookes like this before fetching:

> a=1&b=5p7zv9+5M7

But, my server got this:
> a=1&b=5p7zv9 5M7

It replace the **+** with a space.I use the Jquery.ajax and send the same data,the server got the right thing with **+**.
So how can I avoid the **+** to be replaced

**Comment by annevk** [comment]
Are you sure + is being replaced? Or is it something jQuery.ajax adds?

**Comment by annevk** [comment]
Closing due to lack of follow up.
