### ISSUE TITLE
Some link corrections

### ISSUE THREAD

**Issue by domenic** [whatwg/fetch#333]
While working on some referrer policy stuff I noticed the following could be better:

> If request's referrer policy is the empty string and request's client is non-null, then set request's referrer policy to request's client's **associated referrer policy**. [REFERRER]

Associated referrer policy currently points to the Referrer Policy spec, but an environment settings object's referrer policy algorithm is no longer defined there. Instead, it is defined at https://html.spec.whatwg.org/multipage/webappapis.html#environment-settings-object, although we don't have a more specific ID. Not sure what to do there, but right now it's just a broken link.

> If request's skip-service-worker flag is unset and either request's client is null or request's client's **global object** is not a ServiceWorkerGlobalScope object, run these substeps: [HTML] [SW]

> If request's window is "client", set request's window to request's client, if request's client's **global object** is a Window object, and to "no-window" otherwise.

These days a better destination for these is https://html.spec.whatwg.org/multipage/webappapis.html#concept-settings-object-global

**Comment by annevk** [comment]
Thanks, I just linked to the environment settings object directly for the former.
