### ISSUE TITLE
HTTP-redirect fetch should invoke "Set request's referrer policy on redirect"

### ISSUE THREAD

**Issue by estark37** [whatwg/fetch#334]
https://w3c.github.io/webappsec-referrer-policy/#integration-with-fetch has rotted a little (it references Step 15 of HTTP-redirect fetch, which no longer exists), but the idea is that Fetch should call into the Referrer Policy to update the referrer policy on redirect, before the main fetch follows the redirect.

I can send a PR for this in a bit.

**Comment by estark37** [comment]
As noted in https://github.com/w3c/webappsec-referrer-policy/issues/59

**Comment by annevk** [comment]
Thank you for writing PR #335. Is my understanding correct that we only care about setting/updating the referrer policy for redirects and when the final response results in a document or worker? So for Fetch the only update/set integration point is redirects and the rest is handled by HTML?

**Comment by estark37** [comment]
@annevk yes I think that's correct.
