### ISSUE TITLE
Make it more clear that cache mode "default" does respect Cache-Control headers and such

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#336]
Basically, when you go to the HTTP cache with a request whose cache mode is "default", and the request also has Cache-Control or Pragma headers, those need to be respected by the HTTP cache, just as they always were.

Alternatively we could make those headers and their values change the cache mode:
- If the cache mode is “default” and a `Cache-Control` or `Pragma` Header is present, whose value is “no-cache”, then set the cache mode from “Default” to no-cache.
- If the cache mode is “default” and a `Cache-Control` or `Pragma` Header is present, whose value is “no-store”, then change the cache mode from “Default” to no-store.

That's not observable so either approach is probably fine. Thoughts anyone?

**Comment by ehsan** [comment]
Hmm, wouldn't this be observable through a service worker script which intercepts the original fetch and looks at the `Request.cache` field?

**Comment by annevk** [comment]
I thought so too, but where we modify it today is way later. Basically just before asking the HTTP cache. Which seems fairly sensible.

**Comment by annevk** [comment]
However, it's probably better to not special case headers and header values since we might introduce new headers and header values and "default" should remain working the same way. The current switch from "default" to something else is largely a legacy thing.

**Comment by wanderview** [comment]
Can't the service worker just inspect the headers anyway?  Why are we worried about it observing it?

**Comment by annevk** [comment]
I think we're only worried to the extent that it would affect existing implementations.
