### ISSUE TITLE
Block text/csv for requests whose type is "script"?

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#337]
Some IRC discussion regarding https://bugzilla.mozilla.org/show_bug.cgi?id=1048535 resulted in the suggestion by @evilpie to not just block `image/` MIME types for scripts, but also `text/csv`. @mikewest?

**Comment by mikewest** [comment]
Sounds reasonable to me. Ideally, we'd get to the point at which we'd just block everything that isn't explicitly script. Baby steps in that direction seem totally reasonable to try.

**Comment by evilpie** [comment]
We have some **very** limited data on this now (three data points from Firefox Nightly): https://mzl.la/2bEqia8 (if you are reading this in the future, change Nightly 51 to something more relavant). It does seem like `text/csv` basically never happens compared to almost every other mime type that we track.

**Comment by annevk** [comment]
Fixed by https://github.com/whatwg/fetch/pull/379.
