### ISSUE TITLE
Reconsider treatment of non-GET for non-HTTP(S) schemes

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#339]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1063526 for details. In particular, someone (probably me?) should test what user agents do here. Ideally we can align on consistent treatment for the various schemes.

**Comment by annevk** [comment]
Looking at the tests @youennf wrote for this it looks like most implementations already agree with the standard and reject non-GET for blob and data URLs. We could lift the restriction, but is there a point?

I did create https://github.com/w3c/web-platform-tests/pull/3459 to account for about:unicorn being gone and about:blank supporting non-GET methods.

**Comment by youennf** [comment]
As of WebKit, data URL currently supports any  method when being loaded from forms at least.
Blob method checking is a recent addition. I am not sure to see a use case to lift this constraint, except maybe HEAD?

**Comment by annevk** [comment]
And with HEAD we'd force there to be no body? Interesting, but prolly not compelling enough.

**Comment by annevk** [comment]
@sicking is still pushing to allow any method, including HEAD presumably. Would you be opposed to that for blob URLs @youennf?

**Comment by youennf** [comment]
I am not opposed to this change, I just do not understand the rationale and the problem it tries to solve.

For me, returning a network error seems simple, consistent and web-compatible. In any case, I would not special case blob scheme.

So, if most browsers agree with the standard, what is the value of changing the standard? Does it bring something new to the table?

Also, if HEAD is allowed for other URLs than HTTP(s), the semantics should be consistent for all URL schemes. That probably applies for other methods as well.

**Comment by annevk** [comment]
Let's recap.

1. All browsers allow any method for about URLs.
2. Data URLs are inconsistent. Firefox allows other methods, Chrome does not, but you mentioned WebKit does. http://w3c-test.org/fetch/api/basic/scheme-data.html does not work in Safari Technology Preview for me.
3. Blob URLs seem consistent in rejecting non-GET: http://w3c-test.org/fetch/api/basic/scheme-blob.html.

What @sicking wants is consistency across schemes. I don't care too strongly about that, but it's arguably better that if we have no argument to restrict methods we should allow all of them. And HEAD is the only one with the special semantics, but its special semantics are handled in "main fetch" already for all responses.

**Comment by youennf** [comment]
As of WebKit and data URL, it currently applies CORS when loaded by fetch/xhr, hence fails loading. There is a patch to fix that and plan is to align with the spec.

Changing blob handling while we have full interop seems needless to me but I do not have strong feelings.

**Comment by annevk** [comment]
@mkruisselbrink @ inexorabletash @smaug---- @mikewest do any of you care what we do here? I'm leaning towards allowing all methods for data URLs and keeping blob URLs restricted to GET.

**Comment by smaug----** [comment]
sounds ok to me.

If there is currently consistency with blob url handling, no need to change that, or that change could be later if for some reason needed.

**Comment by mkruisselbrink** [comment]
I don't have any particularly strong opinions here. To me allowing non-GET requests (other than maybe HEAD) to non-HTTP(S) schemes feels a little bit weird, but yeah, it does seem like there aren't any strong arguments to actually restrict methods.

Not sure if treating blob URLs differently from data URLs is the most sensible thing, but if that is closest to what implementations already do, I suppose we might as well do that...

**Comment by annevk** [comment]
I updated the tests. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1341389 and https://bugs.chromium.org/p/chromium/issues/detail?id=694661 as a result. Safari TP is already excellent.
