### ISSUE TITLE
Support same-origin, strict-origin, strict-origin-when-cross-origin in request' referrer policy

### ISSUE THREAD

**Issue by tungmangtdh3** [whatwg/fetch#342]
There're 3 new states "same-origin, strict-origin, strict-origin-when-cross-origin" have added to Referrer Policy specs [1]
These states should be added to request's referrer policy [2]
[1] https://w3c.github.io/webappsec-referrer-policy/
[2] https://fetch.spec.whatwg.org/#referrer-policies

Thanks

**Comment by sideshowbarker** [comment]
See also https://github.com/whatwg/html/pull/1589

**Comment by annevk** [comment]
@fmarier, interested in fixing this?

**Comment by fmarier** [comment]
@annevk Sure, feel free to assign this to me.

I prepared a pull request for it: #346.
