### ISSUE TITLE
Default value for ByteString in ResponseInit should be removed

### ISSUE THREAD

**Issue by malisas** [whatwg/fetch#348]
The [Response IDL](https://fetch.spec.whatwg.org/#response-class) has a `ResponseInit` dictionary with a default value for the `statusText` `ByteString`:
```
dictionary ResponseInit {
  unsigned short status = 200;
  ByteString statusText = "OK";
  HeadersInit headers;
};
```
but the [WebIDL definition for ByteString](http://heycam.github.io/webidl/#idl-ByteString) says
> There is no way to represent a constant ByteString value in IDL.

**Conclusion: the default value for ByteString in ResponseInit should be removed.**
[Firefox](https://dxr.mozilla.org/mozilla-central/source/dom/webidl/Response.webidl?q=path%3Aresponse.webidl&redirect_type=single#) is already doing this.

(@jdm helped me figure this out.)

**Comment by annevk** [comment]
I see. I tend to think we should fix IDL since as long as the string is within U+0000-U+00FF it can be easily represented. As much as any other string can.

**Comment by annevk** [comment]
Note that Firefox does use "OK" as its default value.

@heycam how do you feel about fixing this in IDL?

**Comment by heycam** [comment]
Looks like we already have wording in IDL to describe what it means to use a string literal as a default value for a `ByteString`-typed operation argument or dictionary member http://heycam.github.io/webidl/#string-literal so we just need to update that sentence @malisas references to allow it.

**Comment by heycam** [comment]
(I guess it was a bug in https://github.com/heycam/webidl/commit/672e73d476d8c4341339cc22592bb5ff01c69823 .)

**Comment by heycam** [comment]
Fixed in https://github.com/heycam/webidl/commit/7e2d743779eb47959ab3c5520937a4bb7948a6b8.  @malisas please feel free to file a Bugzilla bug to make this work in Firefox's bindings generators, thanks!

**Comment by annevk** [comment]
Thanks everyone!
