### ISSUE TITLE
Request's current url is undefined for a new request

### ISSUE THREAD

**Issue by jdm** [whatwg/fetch#351]
Step 8 of the Request constructor says `Set request to a new request whose url is request's current url`. A request's current url is defined as `A request has an associated current url. It is a pointer to the last URL in request's url list.`. If the Request constructor receives a string as the input, we are told to create `a new request`. The url list is defined as `A request has an associated url list (a list of one or more URLs). Unless stated otherwise, it is a list containing a copy of request's url.` And finally, the request's url is defined as `A request has an associated url (a URL).` with no default value, and a note suggesting that it should be an alias of the first URL in the url list, which yields a circular definition.

**Comment by annevk** [comment]
Fair I suppose. This would require restructuring https://fetch.spec.whatwg.org/#dom-request to have step 12 before creating a request. Or alternative we allow for requests to exist without a URL, but I'm not sure that's very sensible.

**Comment by jdm** [comment]
I think requiring that the request creator provide a URL at creation time would make sense.

**Comment by annevk** [comment]
Yeah, that's the intent, I just didn't follow that requirement in the `Request` constructor since I guess I thought this was easier to write down or I didn't think of it. Probably easy to fix, but need to be careful about side effects when moving steps around.
