### ISSUE TITLE
Does the spec suggest Fetch can only handle UTF-8 content?

### ISSUE THREAD

**Issue by bitinn** [whatwg/fetch#353]
I am not sure if this is the case, from the looks of it, `res.text()` always assumes UTF-8 content.

Is there a discussion I am missing out on? Does it require user to self-decode `res.body` instead?

**Comment by annevk** [comment]
If you don't want UTF-8, yes.

**Comment by jakearchibald** [comment]
```js
response.arrayBuffer().then(buffer =>
  new TextDecoder(format).decode(buffer)
);
```

**Comment by bitinn** [comment]
@annevk thanks for clearing that up.

@jakearchibald true, that should work.

But I am quite surprised that `res.text()` enforce UTF-8 (I mean it doesn't convert other encoding into UTF-8, just blindly assume it's UTF-8 content).

I would think, and that's mostly my uninformed opinion, users will prefer browser to handle that encoding conversion, instead of having to think about webpage in terms of arrayBuffer.

**Comment by annevk** [comment]
The reason we force UTF-8 in the convenience APIs is because there's no reason to use any other encoding. See https://encoding.spec.whatwg.org/ for more details.
