### ISSUE TITLE
Unclear intent in steps 29, 34.3, and 36 of the Request constructor

### ISSUE THREAD

**Issue by malisas** [whatwg/fetch#358]
Step 29 of the [Request constructor](https://fetch.spec.whatwg.org/#dom-request) says:
> Empty r's request's header list.

This refers to `Request's request's header list`.

Step 34.3 says:
> If Content-Type is non-null and r's request's header list contains no header named `Content-Type`, append `Content-Type`/Content-Type to r's Headers object. Rethrow any exception.

Here it seems like `Request's request's header list` is being checked for a header named `Content-Type`, even though it was emptied in step 29 (and never filled again).

Similarly, step 36 checks `Request's request's header list`:
> Set r's MIME type to the result of extracting a MIME type from r's request's header list.

Could the intended headers lists please be clarified? Thank you!

**Comment by annevk** [comment]
I think you missed that step 31 fills _r_'s Headers object (which is backed by r's request's header list)?

**Comment by jdm** [comment]
@annevk The way the text uses `r's request's headers list` and `r's Header's object` to refer to the same header list (ie. aliasing) feels unnecessarily confusing to me. Additionally, in step 26, should `r's request's headers list` and `r's Header's object's headers list` both refer to `request's headers list`, or are they different at that point?

**Comment by annevk** [comment]
I agree it's confusing, but it's important as mutating `Headers` comes with restrictions that might cause exceptions to be thrown, whereas mutating the underlying header list is a free-for-all.

Step 26 could probably use some clarification. I think at the moment the surrounding text assumes the Headers object is associated with r's request's header list, but that's not explicitly stated.

**Comment by jdm** [comment]
@annevk What about consistently referring to header object instead of querying the request's headers list?

**Comment by annevk** [comment]
I'm not sure that makes sense. If you say "Empty `Headers` object" that doesn't quite have the same meaning as emptying a "headers list", which is defined as a list. We could do it I suppose, but we'd then have to define what all those operations mean at that level and make sure there's nothing wrong.

**Comment by jdm** [comment]
You could use "Empty r's `Headers` object headers list".

**Comment by annevk** [comment]
Yeah, that's reasonable I suppose.

**Comment by malisas** [comment]
Ah, yep, I did not understand that "`Headers` object" and "r's request's header list" always have the same underlying headers list contents. Thanks, Josh and Anne, for clarifying.

I guess there is a sentence before the section I linked above that says:
> A Request object also has an associated Headers object which is itself associated with request's header list.

In this case the word "associated" means "the same object's (or piece-of-the-object's) contents referenced in two places". Is this true for all 85 instances of the word "associated" in the document?. Maybe an explicit definition of "associated" would be helpful (at least for me, who is newer to reading specs). I also like @jdm's idea for adding consistency.

**Comment by annevk** [comment]
@malisas I have a long term plan of formalizing "associated" as "internal slot", possibly through IDL, in a way similar to how it's used in the ECMAScript standard if you're familiar with that. Basically private state of an object that is necessary for the implementation, but not exposed to JavaScript.

**Comment by malisas** [comment]
I see, thanks!

**Comment by annevk** [comment]
Thank you! (If you want your full name in the acknowledgments or you prefer your nickname to be listed there, let me know.)
