### ISSUE TITLE
Fix ReadableStream abstract operations markup

### ISSUE THREAD

**Issue by yutakahirano** [whatwg/fetch#361]
- Use  &lt;span&gt; instead of &lt;code&gt;.
- Fix dead links.

**Comment by annevk** [comment]
We should also use "." rather than "@" when referencing internal slots.

**Comment by annevk** [comment]
I started looking into this and this seems much more broken than I thought. Most abstract operations are just gone.

It would probably be good to get this updated soonish.

**Comment by annevk** [comment]
Thanks!
