### ISSUE TITLE
Dispatch to foreign fetch for redirects

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#362]
Currently we set the skip-service-worker flag so a new location of a redirect does not get intercepted by a same-origin service worker. However, a cross-origin service worker should likely intercept that, otherwise we make service migration harder.

See https://github.com/slightlyoff/ServiceWorker/issues/793 for context.

@mkruisselbrink will fix this (and will soon be able to assign himself).

**Comment by annevk** [comment]
This should be quite a bit easier now thanks to #363.

**Comment by sirdarckcat** [comment]
Just to clarify. Would this mean that a 30X redirect on any subresource HTTP request would trigger the service worker of the target URL and dispatch a foreign fetch event?

**Comment by annevk** [comment]
No, only requests that are cross-origin, but same-origin with a foreign-fetch service worker. Same-origin we cannot expose without some kind of server-side opt-in.
