### ISSUE TITLE
Move 401/407 to  HTTP-network-or-cache fetch

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#363]
And with that I guess the CORS check since this would require passing the _CORS flag_ along.

The reason being that 401/407 responses that cause a subsequent request are purely a network affair. Service workers should not be able to cause that subsequent request and should never get a fetch event for it. The easiest way to guarantee that is by simply making them network-only.

Realized this while going through https://github.com/slightlyoff/ServiceWorker/issues/793.

**Comment by jungkees** [comment]
One check point is service workers still can return a synthetic response with 401/407. So, it seems HTTP fetch step 3.3.3 should consider that response as a network error?

**Comment by annevk** [comment]
No, we'd just return it to whoever asked. Let them handle it.

**Comment by jungkees** [comment]
Agreed.
