### ISSUE TITLE
Should "set response's CSP list" be in Main fetch?

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#364]
It's not clear to me why we do it separately for service worker responses and network responses. We could handle both of them at the same time in Main fetch, no?

**Comment by annevk** [comment]
I'm starting to remember now that the reason we have this is cookies. Is that correct?

**Comment by mikewest** [comment]
Yes. We put it that far down in the algorithm so that we'd be able to check the policy for the response when processing the `set-cookie` header. We could move it around now that we've punted on cookie-related changes in CSP.

**Comment by annevk** [comment]
If CSP no longer does cookies that might be good as it would simplify the setup.
