### ISSUE TITLE
Remove Headers

### ISSUE THREAD

**Issue by tinspin** [whatwg/fetch#368]
I would like to be able to remove all headers except "Host" for a request to the same origin.

So that I can control the bandwidth to my own servers.

**Comment by tinspin** [comment]
Well, I don't know which headers you set!? All that are not Host is what I want removed.

Likely User-Agent, Referer, Accept-Encoding, Accept-Language and Connection but you might set others.

**Comment by annevk** [comment]
I recommend raising this with https://wicg.io/ and if this turns out to be a popular problem work with the community there on a concrete proposal we can evaluate. Thanks!

**Comment by tinspin** [comment]
I'm abandoning the browser as the path you guys are taking is not the same as me. I'm sticking with HTTP and going with machine code on the client! Good luck and may your electricity prices remain low indefinitely!
