### ISSUE TITLE
Fetch would silently ignore the input body if it's not an existing data type?

### ISSUE THREAD

**Issue by bitinn** [whatwg/fetch#371]
[Spec](https://fetch.spec.whatwg.org/#concept-bodyinit-extract) seems to suggest this is the case, and Chrome is implemented in this way as well.

Any reasons for it? In real-world use case, we see quite a few developers sending in a plain object without realizing it's not supported.

**Comment by wanderview** [comment]
What is the alternative?

**Comment by bitinn** [comment]
@wanderview is changing to throwing an Error a viable solution at this point? Seems like a good idea to let developers know they made a programming error.

**Comment by wanderview** [comment]
Seems reasonable.  I was confused about which issue you were talking about at first.

**Comment by wanderview** [comment]
We get this even more wrong in firefox:

![screenshot 2016-08-19 10 38 53](https://cloud.githubusercontent.com/assets/1256526/17813397/3362079e-65f9-11e6-98f8-903428cec41d.png)

**Comment by wanderview** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1296626

**Comment by domenic** [comment]
I think Firefox's behavior is correct. Objects can be converted to USVStrings; this happens automatically in IDL.

In general everywhere on the platform that accepts a string will just convert your object to a string instead of throwing. E.g.

```js
document.body.setAttribute("a", { foo: "bar" });
console.assert(document.body.getAttribute("a") === "[object Object]");

document.body.setAttribute("b", { toString() { return "this is intentional"; } });
console.assert(document.body.getAttribute("b") === "this is intentional");
```

I don't think Request/Response should be any different.

What you really want here is a strongly typed language, like TypeScript.

**Comment by wanderview** [comment]
Interesting, so if an API takes a USVString as one of the allowed types, then we will always at least get a string?  Can we effectively assert that no other type could be passed here?

**Comment by annevk** [comment]
The IDL layer takes care of the other types (stringifies them), so depends on where you place the assert.

Since this is the default throughout the platform I'm closing this.

**Comment by wanderview** [comment]
I'll close the gecko bug.  I tested chrome, btw, and it behaves the same as firefox AFAICT.

**Comment by jimmywarting** [comment]
Think it would be useful if object got json stringify automatically if giving the body a plain object...

**Comment by wanderview** [comment]
> Think it would be useful if object got json stringify automatically if giving the body a plain object...

Correct me if I'm wrong, but I think `toString()` works the way it does by default because `JSON.stringify()` can trigger side effects through getters.

**Comment by annevk** [comment]
Both can trigger side effects. We looked into falling back to JSON at some point, but that did not pan out.

**Comment by jimmywarting** [comment]
> but that did not pan out.

Hmm, to bad :(
