### ISSUE TITLE
Clarification on step 4 of Headers `delete` method

### ISSUE THREAD

**Issue by jeenalee** [whatwg/fetch#372]
Step 4 of `delete` states:
> 4. Otherwise, if guard is "request-no-cors" and name/`invalid` is not a CORS-safelisted request-header, return. 

I'm a little confused what `invalid` in this case is. 

Step 5 of `append` is similar to step 4 of `delete`, and it states:
> 5. Otherwise, if guard is "request-no-cors" and name/value is not a CORS-safelisted request-header, return. 

Is `invalid` in `delete`'s step 4 a place holder for a headers value?

**Comment by annevk** [comment]
Yeah, that's the intention. I guess I can rename it `placeholder` and maybe add a note that it basically disqualifies `Content-Type` from being deleted.

**Comment by annevk** [comment]
Although I guess there's more headers these days than just `Content-Type` that need a "valid value".

**Comment by annevk** [comment]
Oh, doh, the reason is because `delete()` is not passed a _value_ argument, so we need to make something up.

**Comment by jeenalee** [comment]
I see! It makes sense why it is phrased the way it is. Thank you for clarifying.

**Comment by annevk** [comment]
A note should probably be added to avoid confusing others.
