### ISSUE TITLE
Go deeper into HTTP caching

### ISSUE THREAD

**Issue by mnot** [whatwg/fetch#373]
My first inclination is to break out some parts of HTTP-network-or-cache Fetch into new sections and then grow them.

Specifically - 
- bullets 17 and 18 ("If httpRequest's cache mode is neither...", "Otherwise, if httpRequest's cache mode is either...") should be shifted to a new "HTTP Cache Lookup" section, that specifies http://httpwg.org/specs/rfc7234.html#constructing.responses.from.caches algorithmically. 
- after bullet 19 ("If response is null, run these substeps..."), insert a new item (or reference to a new section, "HTTP Cache Storage" or similar, along the lines specified in http://httpwg.org/specs/rfc7234.html#response.cacheability. 

If that makes sense, I'll start a branch, and probably some tests too.

Question - Is the Streams work largely done? I suspect some of the fine points here are going to need them.

**Comment by annevk** [comment]
Yeah, that aligns with my tentative plan for the cache. Either something like "HTTP-cache fetch" or a new Infrastructure section.

Streams is still being improved and uploads isn't done yet. We can probably find some temporary wording though if it's required anywhere and we lack something.

**Comment by mnot** [comment]
Am starting in https://github.com/mnot/fetch/tree/http-cache -- not done yet, but would love any feedback you have so far.

**Comment by annevk** [comment]
One thing that would be good to take into account is #307. Effectively a browser needs at least two global instances of an HTTP cache, as defense-in-depth for CORS. That's why I was considering having the cache lookup be in its own section.

I have editorial quibbles, but maybe those are better to do once you're ready?
