### ISSUE TITLE
Use of response's cache state

### ISSUE THREAD

**Issue by jungkees** [whatwg/fetch#376]
Service worker has been using the response's cache state to check if the response hit the network or gotten from the cache: https://github.com/whatwg/fetch/commit/8d343bbcefc952fedc22e4020518acf52548a483#commitcomment-18789695.

Please consider either restore the cache state concept or anything similar that service worker can reference to.

**Comment by annevk** [comment]
@mnot we should probably wait with this until after #496 lands I suppose?

**Comment by mnot** [comment]
Landed. @jungkees, where is the relevant part of SW now? 

NB. If the browser cache were to update the `Age` header, you might be able to get the information you want from examining the response.

**Comment by jungkees** [comment]
It's [Update](https://w3c.github.io/ServiceWorker/#update) step 7 > To perform the fetch step 20. [importScripts()](https://w3c.github.io/ServiceWorker/#importscripts) does the same thing in the step 2.5.

So, should I check the response's `Age` header and consider it's gotten from the network (including a validation) if the value is zero?

**Comment by annevk** [comment]
@jungkees we probably can't rely on that. If browsers included that it seems like that would also be a fingerprinting leak of sorts.

**Comment by annevk** [comment]
@jungkees @wanderview this concept is implemented in user agents as specified and tested? If so, I'll work on adding this back.

**Comment by annevk** [comment]
So basically, step 4 and step 6 of step 2.20 of https://fetch.spec.whatwg.org/#concept-http-network-or-cache-fetch:

> If httpRequest’s cache mode is "force-cache" or "only-if-cached", then set response to storedResponse and abort these substeps. 

> Otherwise, if the revalidatingFlag is unset, then set response to storedResponse.

Would need to be updated to set a flag on response.

I suppose we could add back "cache state" and make the default the empty string (set it to "local" per above). And add a note that if you plan on using this for something other than service workers you let Fetch know.

**Comment by annevk** [comment]
(Thanks for digging that up, by the way! I guess the one thing that remains unclear is whether it's tested.)

**Comment by wanderview** [comment]
This code is exercised here:

https://searchfox.org/mozilla-central/source/testing/web-platform/tests/service-workers/service-worker/update-after-oneday.https.html

But I don't think the test does enough work to truly validate that its working properly.  It doesn't check in-cache vs out-cache, etc.

I thought we had an internal firefox test for this, but also do not.  We expose it the "last update time" to browser features like devtools, but devtools has not been updated to use it yet.
