### ISSUE TITLE
There's no reason to make fetch of about:blank same-origin for loads other than navigations and `<object>`

### ISSUE THREAD

**Issue by bzbarsky** [whatwg/fetch#384]
I don't think it's required for web compat.  Gecko only does this for navigations and `<object>` (things that can end up with a browsing context).  Specifically, about:blank stylesheets are cross-origin in Gecko, and you can't XHR to about:blank in either Gecko or Blink (but can in WebKit, apparently).

**Comment by annevk** [comment]
@youennf what do you think?

Navigate is already always same-origin. `<object>` would require some special casing but that seems fine.

If we changed this we'd automatically fix #385 since all about URL fetching would just be cross-origin (unless it's the result of a navigation).

**Comment by youennf** [comment]
I don't think XHR/fetch is working for about:blank in WebKit.
Sounds good to make consistent all about URLs.

**Comment by annevk** [comment]
Thanks.
