### ISSUE TITLE
upload progress return response.json()?

### ISSUE THREAD

**Issue by bORm** [whatwg/fetch#389]
https://github.com/whatwg/fetch/issues/21

Okay, **Fetch API integrated with Streams** it`s really cool, but
from https://fetch.spec.whatwg.org/#fetch-api, i correct this sample
```
function consume(response, total=0) {
  var reader = response.body.getReader()
  return pump()
  function pump() {
    return reader.read().then(({done, value}) => {
      if (done) {
        return response
      }
      total += value.byteLength
      log(`received ${value.byteLength} bytes (${total} bytes in total)`)
      return pump()
    })
  }
}

fetch("/music/pk/altes-kamuffel.flac", {method: 'POST', body: MYFormData})
  .then(response => consume(response))
  .then(response => return response.json() // "Already read" )
  .then((resultFromServer) => log(resultFromServer.file))
  .catch(e => log("something went wrong: " + e))
```

how return real response.json() from Server?

**Comment by annevk** [comment]
You cannot consume a body twice. https://stackoverflow.com/ is a better place for these kind of questions. Hope that helps.

**Comment by bORm** [comment]
You don`t cache response body from server and save it?

**Comment by annevk** [comment]
I'm not sure what you're saying.

**Comment by guest271314** [comment]
@annevk _"You cannot consume a body twice."_ It is possible to clone a `Response` or use `.tee()`, to consume the "same" body twice, yes?

**Comment by annevk** [comment]
Yes.

**Comment by bORm** [comment]
a@guest271314, @annevk it`s not possible by clone response, after clone, we don`t have access to responce.json() on this case we have ReadableStream { locked: true }

**Comment by annevk** [comment]
If the first thing you do once you have a response is clone it, that should be possible. If it's not, you might have found a browser issue.
