### ISSUE TITLE
Clarification of Body package data algorithm with bytes, FormData and multipart/form-data MIME type

### ISSUE THREAD

**Issue by eehakkin** [whatwg/fetch#392]
The Body package data algorithm with bytes, FormData and multipart/form-data MIME type step 1 says

> Parse bytes, using the value of the `boundary` parameter from MIME type and utf-8 as encoding, per the rules set forth in Returning Values from Forms: multipart/form-data. [RFC2388]

That is not very detailed parsing specification.
While implementing the algorithm for Chromium, I ran into interpretation issues.
My main question is how to parse different kind of multipart parts.

Parts whose Content-Disposition header field contains a filename parameter must surely be parsed into **Blob**s. That is what Mozilla does.

What about multipart parts which have a Content-Type header field but whose Content-Disposition header field does not contain a filename parameter? To my understanding, it is not possible to construct such parts with **FormData** because **USVString**s will never generate a Content-Type header field and **Blob**s have a default file name ("blob"). Should these parts be parsed into **Blob**s in spite of the missing filename parameter?

Should a multipart part with a name "_charset_" have no effect on decoding encoding?
I think that probably yes, because RFC2388 does not even describe that name (but RFC7578 does) and because  the body package data algorithm with bytes, FormData and application/x-www-form-urlencoded MIME type runs the application/x-www-form-urlencoded parser steps with a use_charset_flag implicitly unset thus it does not change decoding encoding based on the "_charset_" component.

If string parts can never have a Content-Type header field, they can never have a charset parameter either. The multipart part with a name "_charset_" does not seem to have an effect on decoding, either. Does it thus follow that string parts must always be decoded using utf-8 encoding?

**Comment by eehakkin** [comment]
The "_charset_" component/name/part should be the "\_charset_" component/name/part.

**Comment by annevk** [comment]
See also https://www.w3.org/Bugs/Public/show_bug.cgi?id=16909. It's a known issue and thus far nobody has taken the time to solve it once and for all. Perhaps I can convince you to solve it for the web?

What we need is basically a test suite and two algorithms (decode/encode) and then convince all implementations to align with each other over time. While that happens the test suite and two algorithms will likely need to be updated to take into account implementation feedback and such.

I'm not entirely sure what the best place is for these algorithms, but either XMLHttpRequest (since it defines the `FormData` object) or HTML (since it defines forms) seems like a good fit. Perhaps the former is a little better since we also coupled the `URLSearchParams` object and application/x-www-form-urlencoded together in URL.

**Comment by eehakkin** [comment]
> See also https://www.w3.org/Bugs/Public/show_bug.cgi?id=16909. It's a known issue and thus far nobody has taken the time to solve it once and for all. Perhaps I can convince you to solve it for the web?

That bug seems to be a quite different although related issue. The bug is about encoding and decoding of form field names while my issue is about parsing multipart part octets into form field values and I am especially interested to clarify what parsing steps should be done before before a possible character decoding.

> Should a multipart part with a name "\_charset_" have no effect on decoding encoding?
I think that probably yes, because RFC2388 does not even describe that name (but RFC7578 does) and because the body package data algorithm with bytes, FormData and application/x-www-form-urlencoded MIME type runs the application/x-www-form-urlencoded parser steps with a use_charset_flag implicitly unset thus it does not change decoding encoding based on the "\_charset_" component.

In addition to my previous reasoning, https://encoding.spec.whatwg.org/ requires the UTF-8 encoding for existing formats deployed in new contexts (and Fetch API probably is a context). So a method (such as a multipart part with a name "\_charset_") to specify an encoding other than UTF-8 must not be supported.

The main question which I have is that with the following body:
> --boundary
> Content-Disposition: form-data; name="field1"
> Content-Type: text/html; charset=iso-8859-1
>
> ... ISO-8859-1 encoded HTML content ...
> --boundary--

Should the Body package data algorithm with bytes quoted above, FormData and multipart/form-data; boundary="boundary" MIME type

1. return a FormData object with one entry whose value is a **Blob** object with a MIME type "text/html; charset=iso-8859-1" containing raw content bytes from the multipart part body. In this case the content bytes are NOT decoded as **Blob** contains bytes and not characters. 
2. return a FormData object with one entry whose value is a **USVString** object containing UTF-8 decoded content bytes from the multipart part body (if that happens not to cause a decoding error). In this case the content type is completely ignored. This is what Firefox does.
3. return a FormData object with one entry whose value is a **USVString** object containing ISO-8859-1 decoded content bytes from the multipart part body. In this case the content type is ignored but its charset parameter is not ignored. This violates the Encoding Standard as a non-UTF-8 decoding is used in a new context.
4. throw a **TypeError** because the multipart part is missing a Content-Disposition filename parameter although it seems to represent a **Blob** because it has a Content-Type header field.

**Comment by annevk** [comment]
Right, the main problem is that going from FormData to bytes is undefined and going from bytes to FormData is undefined. The latter being something that was not exposed to web browsers until this feature (I think). So what needs to happen is for someone to do research and define a reasonable processing model.

**Comment by yutakahirano** [comment]
Sorry, I don't understand what "utf-8 as encoding" means in

> Parse bytes, using the value of the `boundary` parameter from MIME type and utf-8 as encoding, per the rules set forth in Returning Values from Forms: multipart/form-data. [RFC2388]

I couldn't find a parsing operation in RFC2388 that takes a encoding.

**Comment by yutakahirano** [comment]
@annevk Do you have an answer for https://github.com/whatwg/fetch/issues/392#issuecomment-252887205?

@eehakkin is implementing formData function on Chrome and I would like to know what can be implemented safely with the current spec. Or do you think we should update the spec before implementing anything?

**Comment by annevk** [comment]
@yutakahirano it tries to say that any field values should be utf-8-decoded. (The field values are byte sequences as I understand it, whereas `FormData` uses strings.)

**Comment by yutakahirano** [comment]
Thank you!

**Comment by eehakkin** [comment]
I studied related specifications and existing implementations. Based on that:

 * I created a pull request for the Fetch Standard: #424
 * I also created a pull request for WPT: w3c/web-platform-tests#4248

Here are my findings and recommendations.

## Definitions

In the case of the _multipart/form-data_, according to RFC-7578:

 * Each part MUST have a _Content-Disposition_ header field which MUST contain a _name_ parameter and MAY contain a _filename_ parameter.
 * Each part MAY have a _Content-Type_ header field which MAY contain a _charset_ parameter.

## Existing implementations

### Server side implementations

I checked the following ones:

 * Node.js frameworks:
   Always decode non-file parts using a predefined encoding.
 * PHP:
   Does not decode non-file parts but store raw bytes.
   Does not store _charset_ parameters.
 * Python 2 cgi:
   Does not decode non-file parts but store raw bytes.
   Does not store _charset_ parameters.
 * Python 3 cgi and web frameworks:
   Always decode non-file parts using a predefined encoding.
 * Ruby cgi:
   Always decode non-file parts using a predefined encoding.

### Web browser implementations

 * Firefox
 * Chrome patched with https://codereview.chromium.org/2292763002/

## Different kind of _multipart/form-data_ parts

### A part with a _filename_ parameter and with a _Content-Type_ header field

This is a clear case. There is one sensible option:

 * The part must be parsed into an entry whose name is the value of the _name_ parameter and whose value is a **Blob** whose content is the content of the part and whose _type_ attribute value is the content of the _Content-Type_ header field.
   This is the same or similar to what all existing implementations do.

### A part with a _filename_ parameter but without a _Content-Type_ header field

This is not a clear case. There are basically two sensible options:

 * The part must be parsed into an entry whose name is the value of the _name_ parameter and whose value is a **Blob** whose content is the content of the part and whose _type_ attribute is _text/plain_ which is the default _Content-Type_ for a part according to RFC-7578.
   This is what Firefox does and what is specified in RFC-7578.
 * The part must be parsed into an entry whose name is the value of the _name_ parameter and whose value is a **Blob** whose content is the content of the part and whose _type_ attribute is unset.
   This is similar to what all existing server side implementations do but it is against what is specified in RFC-7578.

I am in favor of the first option as it is actually specified and there is an existing browser implementation.

### A part without a _filename_ parameter and a _Content-Type_ header field

This is quite a clear case. There is one sensible option:

 * The part must be parsed into an entry whose name is the value of the _name_ parameter and whose value is a **USVString** whose content is the _utf-8_ decoded content of the part because the Fetch Standard specifies that _multipart/form-data_ parsing is done using _utf-8_ as encoding.
   This is basically the same or similar to what all existing implementations do if they expect _utf-8_ input as the Fetch Standard does.

In RFC-7578 that encoding which is supplied by an applications of the RFC-7578 specification (namely the Fetch Standard) is called as a _form-charset_.

### A part without a _filename_ parameter with a _Content-Type_ header field without a _charset_ parameter

The _Content-Type_ header field should probably just be ignored. Therefore, this case should be handled in the same way as the previous one.

### A part without a _filename_ parameter with a _Content-Type_ header field with a _charset_ parameter which specifies a _utf-8_ encoding

Regardless of whether the _charset_ parameter is ignored or not, the decoding encoding is _utf-8_. Therefore, this case should be handled in the same way as the two previous ones.

### A part without a _filename_ parameter with a _Content-Type_ header field with a _charset_ parameter which does not specify a _utf-8_ encoding

This is not a clear case. There are basically two sensible options:

 * The part must be parsed into an entry whose name is the value of the _name_ parameter and whose value is a **USVString** whose content is the _utf-8_ decoded content of the part because the Fetch Standard specifies that _multipart/form-data_ parsing is done using _utf-8_ as encoding.
   This is basically the same or similar to what all existing implementations do if they expect _utf-8_ input as the Fetch Standard does.
   Some server side implementations (such as PHP and Python 2 cgi) do not decode at all but store raw bytes. However, they do not store the _charset_ parameters either, so web backends using them cannot do other than expect that the stored raw bytes are encoded using the expected encoding.
 * The part must be parsed into an entry whose name is the value of the _name_ parameter and whose value is a **USVString** whose content is the decoded content of the part. The decoding is done using an encoding specified by the _charset_ parameter.
   There are no implementations which do this.

I do not think that the Fetch Standard is a correct place to introduce a completely new way to handle _multipart/form-data_ parts. Therefore, I am in favor of the first option.

### A part with a _name_ parameter equal to _\_charset\__

This is not a clear case. There are basically two sensible options:

 * The part is parsed like any other part.
   This is basically the same or similar to what all existing implementations do.
 * The part is parsed and the parsed content of the part is used as a new encoding for subsequent parts.
   There are basically no implementations which do this.
   Some server side implementations (such as PHP and Python 2 cgi) do not decode at all but store raw bytes, so web backends using them could use the parsed value for deciding decoding encoding. However, in the case of the Fetch Standard, that would mean that non-file parts should be parsed into **ArrayBuffer**s instead of being parsed into **USVString**s so that web applications could do the decoding.

I do not think that the Fetch Standard is a correct place to introduce a completely new way to handle _multipart/form-data_ parts which has not been implemented by any server side or browser implementation. Therefore, I am in favor of the first option.

## My recommendations

A part with a _filename_ parameter must be parsed into an entry whose values is a **Blob** whose content is part’s content and _type_ attribute has the value of part’s _Content-Type_ header if the part has such header or _text/plain_ otherwise.

A part without a _filename_ parameter must be parsed into an entry whose name is the value of the _name_ parameter and whose value is a **USVString** whose content is the _utf-8_ decoded content of the part.

A part whose _Content-Disposition_ header contains a _name_ parameter whose value is _\_charset\__ is parsed like any other part. It does not change the encoding.

**Comment by annevk** [comment]
Thanks a lot for doing this research @eehakkin. Your recommendations sound sensible. Is there a particular reason why we would not use `File` objects as well when we have a filename? It seems we'd want to expose that as well since we do use it the other way around.

**Comment by eehakkin** [comment]
I so no reason not to use <code>File</code> objects. Somehow I did not thought about that.

A <code>File</code> object make much more sense. Only parts with a filename are parsed into <code>Blob</code>/<code>File</code> objects thus there are no reason to use a more limited <code>Blob</code> objects instead of more complete <code>File</code> objects.
