### ISSUE TITLE
Editorial: "stream of data" reference

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#406]
@yutakahirano I'm working on cleaning up our integration with Streams now we're all on bikeshed (see https://github.com/whatwg/streams/pull/581 for the Streams side) and found one reference that doesn't make much sense.

I guess this is just meant to describe the equivalence between ReadableStream as IDL interface and ReadableStream as JavaScript class?

@domenic any ambition of integrating that into IDL?

**Comment by yutakahirano** [comment]
Probably (I don't fully remember, sorry). Having a link to https://streams.spec.whatwg.org/#rs-class is a good thing, I think.

**Comment by domenic** [comment]
I think there are separate issues here. I think the "stream of data" reference is just a conventional "here is a URL that explains the concept" link and probably shouldn't be a Bikeshed auto-link. In this sense it might be best to link to https://streams.spec.whatwg.org/#readable-stream.

There's a separate issue of the IDL type versus the JS type. That is https://www.w3.org/Bugs/Public/show_bug.cgi?id=28988. I think the Bikeshed side is taken care of by declaring the appropriate dfn in Streams already. The IDL issue indeed needs some work and I can do that, but in the meantime I think we're all just assuming we know how it works (i.e. the same as other object-ish types, with a clear 1:1 mapping).

**Comment by annevk** [comment]
Okay, I guess once https://github.com/whatwg/streams/pull/581 is resolved I can turn that into an actual link and remove the "anchors" block for Streams. Once IDL is updated we can remove even more concepts from Fetch.
