### ISSUE TITLE
Provide opt-in for Expect = "100-continue"

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#41]
We could avoid teeing the request body with this protocol feature: http://httpwg.github.io/specs/rfc7231.html#header.expect

We would need to decide how much of the protocol is implemented in Fetch and how much we leave up to developers.

**Comment by annevk** [comment]
@tyoshino @mnot @wanderview @nikhilm do we still want this given the conclusion in #42?

**Comment by annevk** [comment]
Also, @mnot, it does not seem like this header guarantees there will be no redirects.

**Comment by mnot** [comment]
No, it doesn't. 

Expect/Continue is a mechanism for avoiding unnecessary *transfer* of the request body; it won't help you avoid buffering it.

I think what you want to do is assure that developers can use expect/continue. It *might* be useful to have fetch do it natively too, but I think it's a very implementation-specific decision.

Question: How does Fetch handle these sorts of genuinely optional, implementation-specific behaviours? In other places I see hand-waving about "do whatever HTTP stuff you want to do", but here it's pretty intrusive into the request handling model. 

I suppose you might do that by putting a note in to the effect "You can make an implementation choice to support Expect/Continue HERE, but we leave the details as an exercise for the reader."

**Comment by annevk** [comment]
Ideally, if it's not specified, it's not allowed. But there's still quite a bit of handwaving the lower on the stack you go. Servers seem to rely on clients behaving in a certain way. I'm sure they're not going to be happy if we start sending them these headers without optin.

**Comment by mnot** [comment]
Servers already get `Expect` on requests with bodies, and have to deal with it. Really, `Expect` itself is a form of opt-in (for the request).

**Comment by scshunt** [comment]
Even without the teeing optimization, supporting Expect: 100-continue could be useful for large requests, in particular file uploads. The server may be able to respond immediately with an error (like a 401 or 403), meaning that clients for whom network usage is important (mobile in particular) can avoid wasting network on a request whose body will be ignored.

**Comment by annevk** [comment]
@mnot `Expect` is a forbidden header name at the moment. But even if we lift that, we can only handle a single response. I'm not sure how we'd adjust the API signature for a stream(?) of responses.

**Comment by scshunt** [comment]
Could Fetch handle the 100-continue transparently?  Or would that just lead to requests not to and let the client handle it?

**Comment by annevk** [comment]
@scshunt we could let the client handle them and let the client handle when to transmit the request body (if the 100 response never shows). I thought we maybe wanted to expose them. Letting the client handle them certainly makes things easier.

**Comment by mnot** [comment]
I think that's what you'd want to do. 

Note that Expect/Continue has lots of problems; defining its behaviour in fetch might help some of them, if it's done carefully.

**Comment by annevk** [comment]
First step here is probably fixing #366.

**Comment by annevk** [comment]
Given the discussion in https://github.com/yutakahirano/fetch-with-streams/issues/66 I'm closing this. There's no real benefit in `Expect` if it is only for 100 and that status does not give us the guarantees we are looking for.

Note that #366 clarified that most 1xx (apart from 101) are to be ignored by the client.

**Comment by mnot** [comment]
As @scshunt said, there's still benefit for avoiding large transfers. Not that I'm strongly arguing for it, just noting that the issue discussed over there is orthogonal to the one discussed here.

**Comment by annevk** [comment]
Fair, though I'm not sure the added complexity is worth it just for that. The client is much more informed about whether it wants to initiate a large transfer or not. Also, with H2 and also with early responses you can somewhat mitigate the "damage". And with streaming uploads that are coming soon you should have all the control you need.

**Comment by covener** [comment]
I think one benefit not mentioned here is that a a POST w/ Expect: 100-continue that runs into a HTP/1.1  keepalive closure race can be detected and safely retried.

**Comment by fuweichin** [comment]
Inspired by Server-sent Events, I'm trying to implement Client-sent Events based on [fetch upload streaming](https://web.dev/fetch-upload-streaming/), while Fetch API supports neither  `Expect: 100-continue` request header nor `100 Continue` response status.

So I quit for now, either be patient or forget it.
