### ISSUE TITLE
Streams and fetches that outlive the environment settings object

### ISSUE THREAD

**Issue by domenic** [whatwg/fetch#411]
Spinning off from the discussion in https://github.com/whatwg/fetch/pull/388#issuecomment-248290780. /cc @yutakahirano 

I am not actually sure this is a problem. Note that JS objects can outlive their realm, e.g.

```html
<!DOCTYPE html>
<iframe srcdoc="<script>window.hello = {};</script>"></iframe>
<script>
const hello = frames[0].hello;
frames[0].location.href = "http://example.com/":
// `hello` is still a valid object
</script>
```

So is there any issue with this also being the case for streams that act as bodies?

One might think there is a problem with the object creation done by various stream operations. But no, that works fine too. Extend the above:

```js
const ObjectFromDeadFrame = hello.constructor;
const anotherObjectCreatedInDeadRealm = new ObjectFromDeadFrame();
```

I guess it might be accurate to say the realm isn't destroyed as long as someone holds a reference to it. You could still collect various things, e.g. the `Document` object and so on. But all the stuff streams needs to function is still there.

**Comment by annevk** [comment]
Yeah, globals stay alive if someone holds a reference to them (though Edge might do something funky here); it's not necessarily ideal though.

**Comment by yutakahirano** [comment]
When a request is made from a ReadableStream with an underlying source implemented by a developer, pull / cancel can be called after the realm destruction. @domenic, do you think it's OK as well?

**Comment by domenic** [comment]
It seems OK to me? Is there something problematic about it?

**Comment by yutakahirano** [comment]
I see, sounds good. Thank you for clarifying.
