### ISSUE TITLE
Does terminating a fetch before headers come back reject the promise?

### ISSUE THREAD

**Issue by domenic** [whatwg/fetch#416]
It seems like it logically would, but I cannot find spec support for that: https://fetch.spec.whatwg.org/#concept-http-network-fetch

> Wait until all the headers are transmitted or fetch is being terminated with reason reason. If fetch is being terminated, then set response’s termination reason to reason.

After that we jump to step 5 and start doing stream body stuff, which will eventually land at "If at any point fetch is terminated with reason reason, run these subsubsteps:". So I guess it would fulfill with a stream that's errored? But how would you even know what status code to use?

Similarly, what if a network error occurs during the header transmission? I can't figure that out either.

**Comment by annevk** [comment]
I think the original text accounted for this and then with the addition of streams and CSP it no longer correctly accounts for this.

We should probably just check for a network error after step 4 and then do an early return. Step 13 will then no longer have to check if response is a network error.

**Comment by domenic** [comment]
You'd also need to check for a termination reason, right?

**Comment by annevk** [comment]
Hmm yeah. I guess we never really decided what a termination reason should result in. Whether the promise is rejected or canceled. That might be in part why this is handwavy.

**Comment by mnot** [comment]
FWIW - I ran against a case where https://jobs.about.com/ was sending a redirect, but not the terminating `CRLFCRLF`.

They've fixed it now, apparently, but the browsers I checked with followed the redirect after the server closed the connection. You can fake it with `nc` to test.

**Comment by annevk** [comment]
@mnot that's actually something that might be worth filing a bug on. Making decisions based on potentially incomplete header data seems dangerous.

**Comment by annevk** [comment]
This got clarified when we added abort support: https://github.com/whatwg/fetch/commit/0bcd5dfc71ef44319873887f4b83119bd6d0b71d.
