### ISSUE TITLE
Sharing cookies from one subdomain to the other

### ISSUE THREAD

**Issue by m4nuC** [whatwg/fetch#417]
When using credential include flag, the cookies follow just fine from `domain.invalid` to api.domain.invalid. However from `test.domain.invalid` to `api.domain.invalid` cookies are not sent. Does the fetch spec allow to share cookies `.domain.invalid` scoped cookie from one subdomain to the other

**Comment by annevk** [comment]
Cookies work exactly the same as they would with `<img>`. Fetch doesn't really offer any granularity there.

So I suspect you are either hitting a browser issue or just the way things are supposed to work.

**Comment by annevk** [comment]
Let me know if you have any new information.
