### ISSUE TITLE
Provide opt-out for HTTP proxy authentication?

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#42]
Currently all fetches will tee the request body due to these three reasons:

1. Redirects
2. HTTP authentication
3. HTTP proxy authentication

1 can be disabled through `redirect: "error"`. 2 is already disabled for `fetch()` (handling it automatically and prompting the user that is). 3 cannot be disabled at the moment.

The question is whether it would be acceptable to provide an option to error on 3 as well and thereby opening up the ability to make a client-side decision not to tee request's body.

**Comment by annevk** [comment]
Per #70 and linked issues we're going to make `fetch()` do HTTP auth and HTTP proxy auth by default, but you will be able to opt out. I guess I'll leave this open to make sure we actually define that so that user agents will make that optimization.

**Comment by wanderview** [comment]
Gecko impl bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1184553
