### ISSUE TITLE
FormData content-type doesn't match form submission behavior in browsers

### ISSUE THREAD

**Issue by bzbarsky** [whatwg/fetch#422]
The FormData case in https://fetch.spec.whatwg.org/#concept-bodyinit-extract says:

> Set Content-Type to `'multipart/form-data;boundary='` ...

This doesn't match how form submission works in browsers.  Testcase:

    <form action="http://software.hixie.ch/utilities/cgi/test-tools/echo"
          enctype="multipart/form-data" method="POST">
      <input name="a" value="b">
      <input name="c" type="submit">
    </form>

When I submit that in Firefox, Chrome, Safari, and Edge, they all send:

    Content-Type: multipart/form-data; boundary=stuff

which differs from what the fetch spec says to do for FormData by having an ASCII space after the `';'`.  It would probably be better to align behavior here so HTML form submission can actually be modeled in terms of a Request constructed from a FormData...

**Comment by youennf** [comment]
This is not very consistent with other Content-Type header values in the fetch spec.
Is the issue related to breaking web sites?
If there is no compatibility issue, why wasting 1 byte?

**Comment by bzbarsky** [comment]
> This is not very consistent with other Content-Type header values in the fetch spec.

Well, maybe those should be changed too?  ;)

> Is the issue related to breaking web sites?

Which issue?

The current situation, before the commits above is as follows:

1. Fetch spec says that sending FormData doesn't have a space there.
2. All browsers submitting HTML forms _do_ have a space there.  Changing this may or may not break websites; we simply don't know.
3. The HTML spec is consistent with the browser behavior.  See https://html.spec.whatwg.org/multipage/forms.html#submit-body the multipart/form-data case.

From my point of view, all I want is that Fetch and HTML agree, so browsers can actually implement HTML on top of Fetch.  We can add the space to Fetch.  We can remove the space from HTML and make all browsers change longstanding form-submission behavior and hope there is no compat issue. The former seems much simpler to me, for what it's worth.

**Comment by youennf** [comment]
I also agree HTML forms should use fetch.
It is true that RFC examples usually contain a space before the first parameter.
Other fetch CT values are also engraved in implementations for quite some time.

I am not sure there is a real compat issue, but probably it is not worth bothering.

**Comment by annevk** [comment]
Hmm, I'm happy to change things either way. And I apologize for not matching the RFC-style, that was not really intentional, although I do find the space there rather weird. The separator is ";" after all.

So is the current agreement that we add a space for `multipart/form-data` and leave the rest alone, since it's not worth the hassle?

**Comment by youennf** [comment]
> Hmm, I'm happy to change things either way. And I apologize for not matching the RFC-style, that was not really intentional, although I do find the space there rather weird. The separator is ";" after all.

I also prefer values without space.

> So is the current agreement that we add a space for multipart/form-data and leave the rest alone, since it's not worth the hassle?

Right. I guess this is inline with the idea of fetch spec describing what browsers actually implement.

**Comment by annevk** [comment]
Thanks, tests have also been updated.

**Comment by bzbarsky** [comment]
Yep, thank you for updating the tests!

I think the RFC style is the way it is because it's way more human-readable, fwiw, but if for the other fetch cases browsers agree with each other that there is no space after ';', then I agree that we should leave things be there.
