### ISSUE TITLE
See if resource exists

### ISSUE THREAD

**Issue by rektide** [whatwg/fetch#428]
Per [stackoverflow](http://stackoverflow.com/questions/7035466/check-if-file-exists-but-prevent-404-error-in-console-from-showing-up) and others, it would be nice to have a way to see if a resource exists that doesn't always, forcibly result in an error in the console when the resource doesn't exist.

Perhaps a new option could be created to be silent during failure?

Given that Fetch resolves all responses (4xx, 5xx included), it seems odd that a response would resolve but still forcibly generate an error that the developer has no way to block.

**Comment by domenic** [comment]
This seems like a UI issue best solved via UI, not the spec. For example in Chrome you can click the Filter icon then "Hide network messages".

**Comment by annevk** [comment]
Yeah, or possibly something you can control through the Console Standard? It doesn't really fit in Fetch though since whether to show messages for that is entirely up to the user agent.

**Comment by rektide** [comment]
I've opened https://bugs.chromium.org/p/chromium/issues/detail?id=677599 with Chromium. This Chrome behavior is (as you both indicate) unspecified. Firefox, for example, does not log to console. I have not tried Safari or Edge, lacking access to OSes to try whatever it is they implement.

@domenic: I highly disagree with leaving this purely to end-developers to toggle on broad-scale for all resources ("Hide network messages"). I very much think developers should have some ability to mark certain, known to be speculative requests as such, via programmatic means that the browser can pick up and follow. That way start-developers can mark up speculative requests, and end-developers can continue to get the logging they normally would for other resources. It doesn't make sense to me to have Chrome performing an unspecified, misleading, *un-opt-outable* developer-affecting behavior for something as mundane as speculatively trying to fetch resources that might simply not exist yet.
