### ISSUE TITLE
why not add an option of json 

### ISSUE THREAD

**Issue by Galen-Yip** [whatwg/fetch#430]
currently, we write code as below if we need json response 
```js
fetch(myRequest)
.then(function(response) {
  return response.json();
})
.then(function(res) {
 // ...
});
```

wht not add an option of dataType optionally like jQuery
```js
fetch(myRequest, {
  dataType: 'json'
})
.then(function(res) {
 // ...
});
```

@annevk  hope your reply

**Comment by annevk** [comment]
It's not really clear how that is better as you would lose access to all other information exposed on a response, which might be important for interpretation. E.g., without the URL of the response, how would you interpret relative URLs within the JSON data?

**Comment by jakearchibald** [comment]
@Galen-Yip I don't think this should be part of the API, but you can do it yourself:

```js
function fetchType(request, type, opts={}) {
  if (!['json', 'arrayBuffer', 'blob', 'formData', 'text'].includes(type)) {
    return Promise.reject(TypeError('Invalid response type'));
  }
  return fetch(request, opts).then(r => r[type]());
}

// usage:
fetchType('/', 'json').then(data => …);
```

**Comment by Galen-Yip** [comment]
@annevk oh, i see . thx

**Comment by Galen-Yip** [comment]
@jakearchibald yep, we can do that, but it lose access to some information like url ,ok , bodyUsed etc...

**Comment by Galen-Yip** [comment]
@annevk there is a question else, use fetch api to send a http request , the response is always  a json data , right? 
so, the other information exposed on a  response is always being ignored . For convenience, `dataType` should be added optionally for a way . how is it? Otherwise, developer need to some a wrapper function like @jakearchibald mentioned

**Comment by jakearchibald** [comment]
> use fetch api to send a http request , the response is always a json data , right?

Nah data can be in one of many formats. 

* https://jakearchibald.com/2016/sounds-fun/#playing-a-sound - fetching as an `arrayBuffer` for processing sound
* https://jakearchibald.com/2016/fun-hacks-faster-content/#newline-delimited-json fetching as a ND-JSON stream

**Comment by annevk** [comment]
I'm going to close this. I think we considered this suffieciently. Happy to keep the conversation going though.
