### ISSUE TITLE
Is it allowed to create a GET request with body?

### ISSUE THREAD

**Issue by yutakahirano** [whatwg/fetch#44]
IIUC we can create a GET request with a non-null body:

```
var req = new Request('https://www.example.com/', {method: 'POST', body: 'hello'});
var req2 = new Request(req, {method: 'GET'});
```

Is this OK?

**Comment by annevk** [comment]
No, I think we should amend step 27 to also run its substeps when *temporaryBody* is non-null, agreed?

(How do you want to be acknowledged? See https://fetch.spec.whatwg.org/#acknowledgments for options, but anything goes.)

**Comment by yutakahirano** [comment]
Looks good.

Please write as "平野裕 (Yutaka Hirano)". Thanks!

**Comment by yutakahirano** [comment]
Oh, I didn't notice extracting _init_'s body doesn't work when it's null (and _temporaryBody_ is non-null). How about the following?

(27) If _init_'s body member is present:

  1. Let stream and Content-Type be the result of extracting init's body member.
  1. Set temporaryBody to stream.
  1. If Content-Type is non-null and r's request's header list contains no header named `Content-Type`, append `Content-Type`/Content-Type to r's Headers object. Rethrow any exception.

(28) If _temporaryBody_ is non-null and request's method is `GET` or `HEAD`, throw a TypeError.

**Comment by annevk** [comment]
Good point. However, to avoid impacting any passed in readable streams, I opted for reversing those two steps and adding a conditional to your step 28.

**Comment by annevk** [comment]
(The idea is to make failure as side effect free as it can be.)

**Comment by wanderview** [comment]
Nice catch!  Gecko bug:  https://bugzilla.mozilla.org/show_bug.cgi?id=1154268
