### ISSUE TITLE
Define "to read a request" more specifically

### ISSUE THREAD

**Issue by yutakahirano** [whatwg/fetch#441]
https://fetch.spec.whatwg.org/#read-a-request

See https://github.com/w3c/web-platform-tests/pull/4362#issuecomment-268006360 for the background.

**Comment by yutakahirano** [comment]
@annevk I would like to make a separate change from #425. Right now I'm not sure the capability of the network layer in the fetch spec. What kind of object does it consume / generate?

**Comment by annevk** [comment]
It's rather opaque. Bytes go in and bytes come out. But with `Request` and `Response` objects JavaScript developers now have some control over what happens there in a way. So we need to filter when reading from them (or when creating them, but it seems like that was not the way streams ended up being designed).

**Comment by annevk** [comment]
The high-level goal is that we only allow Uint8Array in streams associated with either `Request` or `Response` objects, right? That seems important to test for and implement, even if we haven't quite figured out how to require that in the specification.

**Comment by yutakahirano** [comment]
My understanding is you can create a `Request` object from arbitrary ReadableStream, but you need to pass a ReadableStream each of whose chunks is a `Uint8Array` object if you want to make a `fetch()` call.

**Comment by yutakahirano** [comment]
For receiving a response body, it is specified in https://fetch.spec.whatwg.org/#http-network-fetch.

> Whenever one or more bytes are transmitted from response’s message body, ...

For transferring a response from a service worker, it's specified in https://w3c.github.io/ServiceWorker/#dom-fetchevent-respondwith.

> If response’s body is non-null, run these substeps:

**Comment by annevk** [comment]
> My understanding is you can create a Request object from arbitrary ReadableStream

So the only case for this is you also write the reader to consume the request yourself, right? Because any browser-supplied reader for a request, be it `fetch()` or `req.json()` or some such, will error.
