### ISSUE TITLE
fetch() doesn't properly handle errors from pre-flight responses with CORS

### ISSUE THREAD

**Issue by dkoston** [whatwg/fetch#443]
I've opened this issues because I'm suprised to not see another one open/closed. Maybe I missed it.

I really don't understand how people are creating production-quality applications with `fetch()` as it does not give access to pre-flight responses.

When an application throws a 403 for example. How is that supposed to be handled with `fetch()`? The only information we have access to is the error from `fetch()` which doesn't even contain a status code. All it contains is the generic string `TypeError: Failed to fetch`

How do we know the difference between a 401? a 403? a 502? a 500? 

Sorry for the dramatic example below but this is really frustrating:

```
function handleErrors(response) {
    if (!response.ok) {
        console.log(response)
    }
    return response;
}

fetch("http://httpstat.us/403")
    .then(handleErrors)
    .then(function(response) {
        console.log("ok");
    }).catch(function(error) {
        console.log('there was an error');
        console.log('but I don\'t have access to the status code');
        console.log('So how can my application know what to do?');
        console.log('Should I send the HTTP request again?');
        console.log('Maybe my cookie is expired so I need to log in?');
        console.log('Why don\'t I have access to response.statusCode?');
        console.log(error);
    });
```

Is whatwg expecting all applications to send back a 200 for every pre-flight CORS request?

**Comment by annevk** [comment]
Yes. That's how CORS has worked for a decade.

**Comment by dkoston** [comment]
There's nothing in the w3c recommendation that says you have to strip the status code when applying the network error steps.

https://www.w3.org/TR/cors/#network-error-steps

Sounds like you don't care about adjusting it to be more user friendly based on your response. I'll close the issue.

**Comment by annevk** [comment]
That document no longer defines CORS (Fetch does these days). But we cannot expose such details as they would reveal aspects the same-origin policy is "designed" to protect.

**Comment by dkoston** [comment]
I understand that providing back a status code could be a potential information leak (i.e. a 404 from a GET request vs a 200).

Offering developers flexibility in this matter would be nice. If there's a 403 for example, we're not leaking anything other than you have bad credentials and a reasonable rate limit will prevent abuse.

Our goal is to not send a second HTTP request/response when the first one would be sufficient to satisfy the condition.

I understand he security implications but not allowing us to choose how to consume CORS means that there will be quadrillions of extra http requests per year wasting CPU cycles and global power. Having the ability to choose to send back an error code on the pre-flight response would allow us to make things much more efficient.

**Comment by annevk** [comment]
The preflight is an ack that the server understands CORS. It never includes credentials. The server should only be concerned in the response with whether it understands CORS, nothing else. The 403 can be in the response to the actual request.

**Comment by dkoston** [comment]
I absolutely understand what you are saying. A pre-flight response and the normal http response can be made. That's exactly how CORS works now. We were hoping to bypass the second http response by providing a code back from the pre-flight response. This will save the second http response for an uncountable amount of http requests. I understand this may be something that you don't want to consider. That is fine. I'm just trying to suggest that developers may want to be able to exert more control over how CORS works.

If it's not something whatwg is open to, I'm happy to leave this thread as is.

**Comment by annevk** [comment]
If https://github.com/WICG/origin-policy (preflight waiver) does not work out we might want to reconsider this, but this would complicate the handshake semantics quite a bit just for improving the latency of error handling.

**Comment by annevk** [comment]
@maicWorkGithub can you show more of your code? Ideally a full demonstration.

**Comment by maicWorkGithub** [comment]
It seems my mistake, but I don't know why...please help

```
// works fine
fetch('https://httpbin.org/post1', {mode: 'cors', json: JSON.stringify({aa: 11, bb: 22}), method: 'POST',})
    .then(response => {
      if (response.ok) {
        return response.json()
      } else {
        return Promise.reject(response)
      }
    })
```

```
// cannot get response，error occurred. diff is `headers[Content-Type]=application/json`
fetch('https://httpbin.org/post1', {mode: 'cors', json: JSON.stringify({aa: 11, bb: 22}), method: 'POST', headers: {'Content-Type': 'application/json'}})
    .then(response => {
      if (response.ok) {
        return response.json()
      } else {
        return Promise.reject(response)
      }
    })
```

**Comment by annevk** [comment]
The latter will issue a CORS preflight and that's not supported by httpbin.org. I get the exact same error with
```js
x = new XMLHttpRequest(); x.open("POST", "https://httpbin.org/post1"); x.setRequestHeader("Content-Type", "application/json");  x.send(); x.onload = console.log; x.onerror = console.log;
```
so this really isn't an API issue.
