### ISSUE TITLE
"3.3. `X-Content-Type-Options` header"

### ISSUE THREAD

**Issue by nickshanks** [whatwg/fetch#444]
https://fetch.spec.whatwg.org/commit-snapshots/9ca258d4919a55c8219bf92ccbb616a5633aff07/#x-content-type-options-header

Specifications should not codify `X-` prefixes in header names. Any extant usage over the previous 25 years is irrelevant in the context of the protocol's next 1025 years of use. Code that is maintained can send or check for both the standardised and the experimental header names.

**Comment by annevk** [comment]
Why would we break compatibility and make lives more difficult?

**Comment by mnot** [comment]
`x-` should be avoided in *new* headers, not when documenting pre-existing ones.

**Comment by annevk** [comment]
Closing per above comments, but happy to continue to discuss.
