### ISSUE TITLE
Track request originator.

### ISSUE THREAD

**Issue by mikewest** [whatwg/fetch#45]
As discussed a bit in https://github.com/mikewest/internetdrafts/commit/d2e4cd80fc9417a4d4d2d74e7d9be2781454c972, the `First-Party-Only` cookie attribute requires tracking the originator of a request across navigations. That doesn't seem possible at the moment via Fetch's current definition.

**Comment by annevk** [comment]
So originator is an environment settings object? Presumably you this concept implemented in Chromium somehow? Could you perhaps explain what that is used for? It would help me figure out the requirements.

**Comment by mikewest** [comment]
1. It's not implemented in Chromium yet. 
2. The use case I have is changing cookie behavior based on originating origin (see the last bullet of https://tools.ietf.org/html/draft-west-first-party-cookies-02#section-4.3).

**Comment by annevk** [comment]
@mikewest isn't that just the origin field which is already available?

**Comment by mikewest** [comment]
Doesn't the origin header get wiped out during redirects?

**Comment by annevk** [comment]
I think in part that depends on whether this is for navigation or workers/resources. Since the former doesn't follow redirects automatically.

But yes, redirects currently set origin to null. You want a distinct field request's origin and request's current origin?

**Comment by mikewest** [comment]
Reviewing this today, I believe it's taken care of with the `client` property. Closing this out.
