### ISSUE TITLE
Should using .json on a response with 204 yield {}?

### ISSUE THREAD

**Issue by AlexFrazer** [whatwg/fetch#453]
So, on a 204, if you use `.json` on the response, it will throw an error:

```
export async function deleteUser(id: string) {
  const response = await fetch('/users', { method: 'DELETE' });
  console.log(response.status) // 204
  return response.json();  // shouldn't it return {}?
}
```

Instead, it says it can't parse the json.

I would expect it to return an empty object, hence, "no content". I had to write an adapter around it.

```
function parseJSON(response) {
  if (response.status === 204) {
    return {};
  }
  return response.json();
}
```

**Comment by domenic** [comment]
The empty string is not a valid JSON string, so that is why you are getting that error.

Why would you expect the default to pretend the empty string is actually the string `{}`? Why not `""` or `null` or `0` or `false`?

**Comment by annevk** [comment]
Closing per above comment. Let us know if you have any further questions.
