### ISSUE TITLE
fetch assumes a url's object is always a Blob

### ISSUE THREAD

**Issue by isonmad** [whatwg/fetch#457]
When it could be a MediaSource or a MediaStream. https://github.com/whatwg/url/commit/1099bb20c056ed5226ee36f20296fe5850fe1cc9 So the following doesn't make sense:

> Append `Content-Length`/blob’s size attribute value to response’s header list.
> Append `Content-Type`/blob’s type attribute value to response’s header list.

What happens if someone tries to fetch one of the other kinds of `blob:` URIs?

**Comment by annevk** [comment]
That is a good question. The problem is that implementations do different things here, but we should indeed work on figuring this out. See also https://github.com/w3c/mediacapture-main/issues/404.

Adding @foolip and @jan-ivar.

**Comment by jan-ivar** [comment]
Another reason media streams and sources should not be urls.

**Comment by annevk** [comment]
That would be ideal. @jan-ivar do you think we can eventually remove support? I suppose I could start by just adding a warning to Fetch about non-blob: usage (I don't think we can get ever rid of those).

**Comment by foolip** [comment]
For this issue specifically, I suppose one could simply treat it as an error and fail the request? What do implementations actually do?

If no implementers wants to move on https://github.com/w3c/mediacapture-main/issues/404 then I suppose one alternative would be to go back to a separate protocol for the non-Blob `blob:` URLs, but that's a bit of churn too.

**Comment by annevk** [comment]
So
```js
stream = new MediaStream();
streamURL = URL.createObjectURL(stream);
fetch(streamURL);
```
does indeed result in a `TypeError` in Chrome and Firefox (same for `MediaSource`), but what can _streamURL_ be used for then? If you cannot fetch it, why support it to begin with?

**Comment by annevk** [comment]
Aaah, okay, so the way this works is that https://html.spec.whatwg.org/#concept-media-load-resource handles `blob:` URLs itself and doesn't pass anything toward Fetch. That indeed makes things easier here.
