### ISSUE TITLE
Set blob.type according to Content-Type header

### ISSUE THREAD

**Issue by caub** [whatwg/fetch#461]
Wouldn't that makes sense? If a response has the Content-Type header 'image/png' let's say, that

`.then(r => r.blob()).then(blob => console.assert(blob.type=='image/png'))`

Currently blob.type is always undefined

**Comment by annevk** [comment]
As far as I can tell the specification already requires that behavior. Perhaps it's not tested by https://github.com/w3c/web-platform-tests in fetch/api? Would you be willing to add a test?

**Comment by caub** [comment]
Ah, sorry I don't know well why, but yesterday I had an issue with it. It works actually well
``` // ex
fetch('http://i.imgur.com/EWV6EZf.jpg', {mode:'cors'}).then(r=>r.blob().then(blob=>console.log(r.headers.get('Content-Type'), blob.type)))
```
