### ISSUE TITLE
Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by Vesli** [whatwg/fetch#467]
I'm working with django as an API like and reactjs for client side.

I'm trying to make a POST request and as I've to send the csrf token I'm facing this issue:

```
return fetch(endpoint, {
	method: req,
	headers: {
                'Content-Type': 'application/json',
                'X-CSRF-Token': csrfToken,
        },
	body: JSON.stringify(data),
})
```

but I'm having this error from chrome:

> Fetch API [...] Request header field x-csrf-token is not allowed by Access-Control-Allow-Headers in preflight response.

I don't find something working from the web.. Any ideas?

**Comment by annevk** [comment]
Sounds like http://stackoverflow.com/questions/32500073/request-header-field-access-control-allow-headers-is-not-allowed-by-itself-in-pr. I'm going to close this since it doesn't seem like a problem with the standard.
