### ISSUE TITLE
Lack of warning when reading headers

### ISSUE THREAD

**Issue by caub** [whatwg/fetch#471]
When doing:
`fetch('http://localhost:3000/login', {method:'POST', headers: {'Content-Type': 'application/json', 
            Accept:'*/json'}, body: JSON.stringify({email:'foo', password:'bar'})}).then(x => {console.log(11, x.headers.get('authorization')); return x.json()}).then(console.log)`

it logs: "11 null" even though I see the authorization header in network tab

when using XmlHttpRequest, it's the same with a helpful warning:
> Refused to get unsafe header "authorization"

**Comment by annevk** [comment]
You're sending it as a response header or a request header? Same-origin or cross-origin? In any event, I'm not sure what the issue with the standard is here.

**Comment by caub** [comment]
as a response header, and cross-origin. Yes it lacked 'Access-Control-Expose-Headers' but fetch give no warning compared to XHR

**Comment by annevk** [comment]
Console warnings are not something that the standard dictates. They're decisions that implementers can make.

**Comment by caub** [comment]
ok, thanks
