### ISSUE TITLE
Allow context to be set

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#48]
The use case here is to allow a service worker to make a fetch just like `<img>` can with equivalent effects.

This requires an opaque response that can only be used by features that can legitimately set the same context as otherwise CSP could be circumvented. E.g. if a page were only allowed to fetch images this could be used to fetch "an image" and instead use the result for something else.

I think do this properly I need @mikewest to finish the CSP rewrite in terms of Fetch. And we need to fix the SW and CSP issue: https://github.com/w3c/webappsec/issues/227

**Comment by mikewest** [comment]
Yeah. Maybe I can still do those this quarter. It's certainly on my list.

**Comment by annevk** [comment]
Given #93 this won't happen.
