### ISSUE TITLE
Constructing a Headers from another Headers is lossy

### ISSUE THREAD

**Issue by bzbarsky** [whatwg/fetch#481]
We've changed the constructor signature to take:

    sequence<sequence<ByteString>> or record<ByteString, ByteString>

so when passing a Headers we will iterate over it, instead of just copying its list of stuff.

But iteration over headers is specced to run through https://fetch.spec.whatwg.org/#concept-header-list-sort-and-combine which means it will reorder the headers, combine them from multiple header lines to one line, and so forth.  This process is lossy and the result may well behave differently from the original when sent to a server.  Yes, per HTTP spec it probably mostly should not.  No, that's not guaranteed even per spec (e.g. behavior for non-list headers that are duplicate is ... well, the RFCs don't really define it very well).  No, not all servers implement HTTP correctly.

**Comment by annevk** [comment]
Hmm. Thoughts @youennf?

Note that this only affects headers that developers control themselves. Browsers don't really manipulate this list.

**Comment by bzbarsky** [comment]
Note that this affects cases when `Request` or `Response` are constructed via their respective constructors.  Those constructors involve calling https://fetch.spec.whatwg.org/#concept-headers-fill with the thing that was passed in, which will have the same issue, right?

**Comment by youennf** [comment]
Yes, the process is lossy. We might end up loosing some header casing information as well for well known header names. WebKit internal structure is a map which is lossy.
It seems good that the header API is sanitising things and makes things consistent amongst browsers.

As of Request/Response constructors, we could special case the transfer of headers in a "lossless" way. We could also put the burden on web developers to be extra careful at how they use the API in those edge scenarios.

**Comment by annevk** [comment]
Given the change needed to the `Request` constructor in #484, perhaps we should just make `HeadersInit` accept a `Headers` object again and copy things in order whenever that takes place... I don't really care strongly one way or another though.
