### ISSUE TITLE
Consider blocking port 9100 (printers)

### ISSUE THREAD

**Issue by mikewest** [whatwg/fetch#482]
* 6697: IRC over TLS. Chrome restricted this in https://bugs.chromium.org/p/chromium/issues/detail?id=676951 (sorry we didn't file a bug at that time).

* 9100: Printers! We already restrict LDP (port 515), and Chrome plans to restrict this printer port in https://bugs.chromium.org/p/chromium/issues/detail?id=687530#c8.

@bzbarsky, @teddink, @johnwilander: Would y'all be interested in making similar changes to your respective bad ports lists?

_(@hannob noted that I misread some things about IPP. I no longer wish to block port 631, as it's actually completely normal for CUPS to serve it's web interface over that port. I've updated the above accordingly.)_

**Comment by bzbarsky** [comment]
Networking questions go to @mcmanus, not me. ;)

**Comment by mikewest** [comment]
@bzbarsky: Thanks for pointing me in the right direction!

**Comment by mikewest** [comment]
(Also, regarding tests: it's not clear how I can write tests for this in an interoperable way. None of our test servers listen on any of these ports, so the failure case for tests will be the same as the passing case. I'm facing the same problem in https://github.com/whatwg/fetch/pull/464, FWIW)

**Comment by annevk** [comment]
I would accept documenting somewhere the things we cannot test. Perhaps even in WPT fetch/. Probably best coordinated with those driving WPT.

**Comment by mikewest** [comment]
Filed https://github.com/w3c/web-platform-tests/issues/4751 to talk about that issue.

**Comment by evilpie** [comment]
Just got this reviewed in [bug 1335688](https://bugzilla.mozilla.org/show_bug.cgi?id=1335688) for Firefox. When do you plan to start blocking this in Chrome, so we can coordinate?

**Comment by teddink** [comment]
Adding Rob Trace to the thread @UWDawgfan12

**Comment by annevk** [comment]
I pushed a commit to #738 that adds port 6697 since that's apparently shipping in Chrome already. It seems 9100 failed thus far. Is that still in the cards @mikewest?

**Comment by annevk** [comment]
https://groups.google.com/a/chromium.org/d/msg/blink-dev/Ttkgd4aPkW0/Mxt0JprqBAAJ strongly suggests 9100 is not doable.

**Comment by annevk** [comment]
I'm closing this due to lack of follow-up. If there's a renewed effort to block 9100 please let us know!
