### ISSUE TITLE
Type confusion in Request constructor leading to underdefined behavior

### ISSUE THREAD

**Issue by bzbarsky** [whatwg/fetch#483]
https://fetch.spec.whatwg.org/#dom-request step 28 says:

> Let _headers_ be a copy of r’s Headers object and its associated header list.

OK, so _headers_ is a Headers object.

Step 29 says:

> If _init_’s `headers` member is present, set _headers_ to init’s `headers` member.

Let's say it's not present.

Step 32 says: 

> Fill _r_’s Headers object with _headers_. Rethrow any exceptions.

with a link to <https://fetch.spec.whatwg.org/#concept-headers-fill>.

But that algorithm expects the input to be a sequence or a record, and it's neither: it's a Headers.  Yes, you can create a sequence from a Headers by round-tripping through to-JS and from-JS conversion, but if that's the expectation that needs to be clearly spelled out here, because that's obviously observably different from just copying over the things from the Headers instance that was passed in.

**Comment by annevk** [comment]
So this regressed in https://github.com/whatwg/fetch/commit/00fce0d96e799f5bc8bc53b30fcec56c4e0b948c.

Since this is only needed for requests, I guess I'll try to fix it there locally and not add a `Headers` conditional back to the fill algorithm.

**Comment by annevk** [comment]
Created a pull request that fixes this.
