### ISSUE TITLE
should CSP be checked on each redirect?

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#485]
AFAICT the spec currently does a pre-request CSP check at step 3 of Main Fetch and a post-response CSP check at step 16 of Main Fetch.  Between those two points the request could have traversed any number of redirects.

Shouldn't CSP like `connect-src 'self'` prevent an xhr or fetch() from traversing a cross-origin redirect?

Also, can someone verify what should be returned in the case of a redirect CSP failure?  Should the entire request result in a NetworkError or should the last 30x response before the policy failure be returned?

**Comment by bzbarsky** [comment]
@mikewest

**Comment by wanderview** [comment]
> Also, can someone verify what should be returned in the case of a redirect CSP failure? Should the entire request result in a NetworkError or should the last 30x response before the policy failure be returned?

FWIW I think the safest course here would be to return a NetworkError.  Gecko currently returns the 30x response,  but I'd like to change it.

**Comment by mikewest** [comment]
@annevk can confirm, but the algorithm is recursive: that is, the last step of https://fetch.spec.whatwg.org/#http-redirect-fetch calls back into Main Fetch. The bits and pieces at the top of that algorithm (including mixed content, hsts, etc) should be executed on every step of a redirect chain. If the request is blocked, it would return a network error.

**Comment by wanderview** [comment]
Ah, you are correct.  For some reason I thought it recursed within http.  Thanks!
