### ISSUE TITLE
Error-prone: "Response with null body status cannot have body"

### ISSUE THREAD

**Issue by ConradIrwin** [whatwg/fetch#487]
We were trying to stub out the fetch API using XmlHttpRequest (so that we could access progress events).

We ran into a bug because some response codes are handled specially, so now we have code that looks like this:

```
       if (this._xhr.status == 101 || this._xhr.status == 204 || this._xhr.status == 205 || this._xhr.status == 304) {
         body = null
       } else if (this._xhr.response) {
          body = @_xhr.response
       } ...

      new Response(body, ...)
```

Is there a reason for special casing these response codes? It seems a rather nasty edge-case that everyone has to handle.

**Comment by annevk** [comment]
I don't think you need to special case them in XMLHttpRequest, since XMLHttpRequest uses the same underlying primitives. If you can produce a non-null body in XMLHttpRequest with these status codes I'd love to know.

**Comment by ConradIrwin** [comment]
Hah! My mistake for not including the entire snippet:

```
       if (this._xhr.status == 101 || this._xhr.status == 204 || this._xhr.status == 205 || this._xhr.status == 304) {
         body = null
       } else if (this._xhr.response) {
          body = @_xhr.response
       } else {
          body = @_xhr.responseText
       }
```

So in this case it goes wrong because the `responseText` is the empty string, which is not null, and it explodes.
