### ISSUE TITLE
ABNF Notation Reference

### ISSUE THREAD

**Issue by JosephPecoraro** [whatwg/fetch#489]
In the [Infrastructure](https://fetch.spec.whatwg.org/#infrastructure) section, the Fetch spec only links to to only one [ABNF spec (rfc5234)](https://tools.ietf.org/html/rfc5234). However the Fetch spec uses custom w3 defined syntax `<a>#<b>` in many places, such as [here](https://fetch.spec.whatwg.org/#http-new-header-syntax).

The custom w3 syntax defined at [https://www.w3.org/Notation.html](https://www.w3.org/Notation.html) should be linked somewhere.

**Comment by annevk** [comment]
It's defined at https://tools.ietf.org/html/rfc7230#section-7. I'll see about making that clearer somehow.
