### ISSUE TITLE
Expose PerformanceResourceTiming in Response Objects

### ISSUE THREAD

**Issue by n8schloss** [whatwg/fetch#491]
## Problem

Currently the process of linking a fetch request to a specific resource timing object is imperfect. If there are two fetch api requests for the same resource that happen within a short time it's impossible to tell exactly which fetch call initiated which request, leading to some errors in performance logging. Orthogonally, if all a developer cares about is the perf result for a single fetch, having to use the whole performance api could be cumbersome.

## Solution?

The ideal solution here (imo) is for there to be a way to get a resource timing object for a specific response. This could be accomplished by adding a method to response objects that give you a promise which will eventually resolve to the PerformanceResourceTiming object once it's ready.

Thoughs?

*Note: Since I think this should be a change to the fetch api I filed the issue here as opposed to the performance timeline repo. Happy to move it tough if we think it's better suited there.*

(cc, @igrigorik, @spanicker for their thoughts)

**Comment by spanicker** [comment]
Not being able to distinguish which resource timing entry corresponds to which fetch seems like a legitimate shortcoming of resource timing API. 
Your proposal sounds quite interesting and plausible, it does break away significantly from the performance timing model but would open up a lot of new possibilities. This requires more thought and discussion as this is not just about fetch, but making performance entires available via other platform API interfaces (in general).
I'd move the issue to Performance timing repo, as this is not specific to fetch as I see it.

**Comment by annevk** [comment]
The problem does sound more generic than just `fetch()`, indeed. The way browsers manage this is that each global has a "fetch group" (defined with not sufficient detail in Fetch today) that tracks all the ongoing fetches. It's a little more complicated than that as fetch groups can sometimes cross globals, but that's the basics. If we had that kind of thing and also a way to represent ongoing fetches through `fetch()` (which we're working on for the termination API), we could link them together more easily and you could find one from the other. And then we could do the same for elements, etc.

**Comment by n8schloss** [comment]
Alright, I filed https://github.com/w3c/resource-timing/issues/102. Let's talk about this there :)
