### ISSUE TITLE
421 Status Code

### ISSUE THREAD

**Issue by mnot** [whatwg/fetch#497]
Should Fetch specify how to handle the 421 status code?

http://httpwg.org/specs/rfc7540.html#MisdirectedRequest

This is sort of like a redirect -- a client is supposed to automatically start a new connection and reissue the request, because the chosen connection isn't authoritative for it.

cc @mcmanus

**Comment by annevk** [comment]
I suppose. This seems rather hard to test with the current web-platform-tests infrastructure. Are browsers interoperable for this status code?

**Comment by mnot** [comment]
Roughly, yes (and it took some work to get there, and so tests would be really handy). Of course, the devil is in the details...
