### ISSUE TITLE
Calling Request.clone() stops Chrome from being able to read request body

### ISSUE THREAD

**Issue by morsdyce** [whatwg/fetch#498]
Hi,

I'm not sure if this is the correct place to post this, If not feel free to close this issue.

I've noticed an issue with Request.clone() implementation in Chrome.
If you clone a request, Chrome network tools are unable to read the request body.
I've set up a test case where you could see this behaviour:
http://glikm.com/fetch.html

I've tested on the following browsers:
Chrome 56.0.2924.87
Firefox 51.0.1
Safari Technology Preview

In Firefox and Safari the request works as normal, but in Chrome the developer tools are missing the Request Payload. I assume this is due to a bug in the implementation of this spec.

**Comment by annevk** [comment]
Please file that issue at https://crbug.com/new, thanks!
