### ISSUE TITLE
baseURI for all fetchs

### ISSUE THREAD

**Issue by rianby64** [whatwg/fetch#507]
Hello! I will be glad if you could give me a hint about baseURL for ```fetch```.
Please, [check this comment](https://github.com/m3co/pseudoimport-html/issues/64#issuecomment-286077396)

The rough idea around this question is:
May I have a way to setup a baseURL for all fetchs?
Consider the case when an script contains a lot of ```fetch``` calls with relative paths. And I'd like to reuse this script without changing the existing code by adding ```new URL('relative_path', document.baseURI).toString()``` to each ```fetch``` call.

What about if try something like ```fetch.baseURI = "//base-url";```?

**Comment by annevk** [comment]
You'll have to change script as things stand today and I don't think we want to support this given that you could trivially fix it yourself by refactoring.

**Comment by rianby64** [comment]
You're right, @annevk . Instead of adding something new to ```fetch``` I may add my monkey-patch and perform all the necessary stuff before sending the request. Thanks!
