### ISSUE TITLE
Can't add Authorization on Request Header with Chrome 57.0.2987

### ISSUE THREAD

**Issue by sevenLee** [whatwg/fetch#509]
**Chrome version**: 57.0.2987

Actually, in older Chrome version I also have this problem.
I added `Authorization` on Request Header with my access token,
```
{
    headers: {
                    'Authorization': 'Bearer ' + accesstoken
                }
}
```
I always get `Access-Control-Allow-Headers:authorization` in Chrome
Besides, My fetch is always Request Method:**OPTIONS** (not display GET), then `Status Code` is 200 OK in Chrome

But if I run the same fetch code in Firefox (ver 52.0.1 ), everything works great. I can add `Authorization` on Request Header correctly. It will display `Authorization: Bearer  accesstoken` on Request header.

The server side already processed CORS for my request header..

This is a Chrome bug or my code fault? How should I do to make `Authorization` on Request Header correctly in Chrome?

**Comment by annevk** [comment]
This is best asked on https://stackoverflow.com/ (and I recommend adding more details about your setup, perhaps creating a minimal demo). This repository is used for the Fetch Standard itself.

**Comment by sevenLee** [comment]
Thanks @annevk , I will try to find solution on stackoverflow. I'm just curious fetch is supported fully in Chrome? Why fetch Request Method is OPTIONS, not GET in Chrome?

**Comment by annevk** [comment]
It should be. It's OPTIONS because it's a CORS preflight. You should be getting a preflight too in Firefox. I suspect you don't get it because you're already authenticated in Firefox somehow.

**Comment by sevenLee** [comment]
@annevk  you are right. I found CORS preflight before GET in firefox. But Why I can't finish CROS preflight in Chrome, it results I can not set Authorization on Request Header. I think if it can finish CORS preflight, it can set Authorization on Request Header correctly in Chrome. I already post this question on stackoverflow http://stackoverflow.com/questions/42889511/fetch-api-cant-add-authorization-on-request-header-with-chrome, if you have free time please check it, thanks!
