### ISSUE TITLE
"With Credentials" flag possibly inconsistent with web architecture

### ISSUE THREAD

**Issue by ylafon** [whatwg/fetch#517]
This is a followup of [TAG issue 76](https://github.com/w3ctag/spec-reviews/issues/76) with a proposal to address the issue, as discussed during the last [TAG meeting](https://pad.w3ctag.org/p/2017-02-08-minutes.md).

One solution could be to alias the "\*" value of Access-Control-Allow-Origin: to something more explicit, like "\***public-noauth**\*" (and link to the explanation behind the design decision behind "\*", see #206 ), this makes the intent more clear. "\*" can be later deprecated if needed.

Then add new value(s) for ACAO:
- "\***public-deauth\***" (name up to bikeshedding) that would mandate the Request credential mode to always be "omit". Having that value would solve the issue of being dependent of a context while calling fetch(), so solving [TAG issue 76](https://github.com/w3ctag/spec-reviews/issues/76) by letting the server decide of the nature of the interaction and not depend only on user context.
- "\***public-auth\***" could potentially be added to avoid the common recipe of blindly echoing back the Origin, if added, this should be labelled as "Footgun", but with proper explanations, the situation might be different than when the original choice of forbidding auth for a static server was made (but if not, it is entirely fine to not add it).

Cc: @mikewest

**Comment by annevk** [comment]
I don't understand this proposal.

**Comment by ylafon** [comment]
So the main issue is to allow access to a public resource without having the a-priori knowledge of the value of `withCredentials` (i.e.: relying on the URL and not on URL+context).
It is of course possible to always echo back the Origin, but it won't solve the issue that the introduction of '*' allowed, which is disallowing access to some protected resources. (Note that echoing back Origin in ACAO is a common solution given to people complaining that '*' doesn't work).

The introduction of "*public-deauth*" which is setting withCredentials to false regardless of what the user set is a way to declare a resource fully public without needing to know the context. The second part of the proposal (renaming '*' to something more explicit) is not linked, but would be a good clarification.

**Comment by annevk** [comment]
I still don't understand. You're conflating values of response headers (`Access-Control-Allow-Origin`) with attributes that are only controlled by the client (`withCredentials`). The server doesn't get to dictate whether the client included credentials in the request, that's not possible.

**Comment by mikewest** [comment]
1.  For `public-deauth`, I'm with @annevk. The server only gets a chance to send a header of any sort after the client has already sent a request, so `public-deauth*` can't set `withCredentials`; it's already been set and evaluated. That is, given `fetch("https://example.com/endpoint/", { credentials: "include" })`, credentials will be sent along with the request to `https://example.com/endpoint/` regardless of what it responds.

    Are you asking for something more involved, like `public-deauth` causing the client to retry the request without credentials?

2.  From the [linked minutes](https://pad.w3ctag.org/p/2017-02-08-minutes.md), it sounds like `public-auth` is what folks on the TAG really want. I recognize that some folks are doing this manually by reflecting the `Origin` header. Still, `crossdomain.xml` seems to prove that a sizable subset of developers didn't understand the implications of opening up credentialed access to responses. I don't think it's out of the question to add as a resource-specific opt-in, but I'd be a bit worried about folks setting this without auditing the endpoints first to ensure they weren't doing anything terribly risky (especially in the context of https://wicg.github.io/origin-policy/).

**Comment by ylafon** [comment]
In the case of a preflight, then the subsequent request should avoid sending credential, for an initial cross-domain GET, the result should not be presented at the caller directly, and yes a new request without credential would be the right way to go. It would be suboptimal in terms of latency, but better than blocking. 

I don't think that `\*public-auth\*` is what TAG people wanted, as it is more likely to cause unwanted leaks, the main issue was really for public resources blocked when using '\*' and its implication on knowing context+URL to address a resource. 
Also the fact that the 'echo back Origin' recipes are used sometimes without realizing the issue, just as a workaround for the issue people have with '\*' (hence the proposal to have a less confusing name for it).

**Comment by annevk** [comment]
If you're happy doing extra requests you can just implement it yourself and see if such a library becomes popular.

**Comment by annevk** [comment]
@ylafon any updates? Perhaps it's best to close this and if you have a new or refined idea open a dedicated issue for that.

**Comment by ylafon** [comment]
The TAG recently discussed this and various ways to avoid that extra request in the case of \*public-deauth\*, including using "Cache-Control: public" to signal that the result would be usable even if the request was with credentials.
Also the fact that \*publish-auth\* is what Tim wanted the most (but it would require a specific entry in the security section).
So I'd rather avoid closing it right now, unless you want to split in different issues for the different proposed values.

**Comment by ylafon** [comment]
After discussions on w3ctag/design-reviews#76 (and decision during the july 2018 TAG f2f) the best solution for this would be to return another error than `network error` when credentials are sent and ACAO is `*` instead of the initial proposal in this thread.

**Comment by annevk** [comment]
I don't think that's acceptable from a security perspective. It seems that would make timing attacks easier.

**Comment by ylafon** [comment]
See [Jonas' comment](https://github.com/w3ctag/design-reviews/issues/76#issuecomment-379140804). The issue about discoverable cases, so the timing difference between a status ok and a `network error` would be the same as between a status ok and a 'network cors wildcard error'. You can already see timing differences between non existent servers (DNS-related error) and non existent (or forbidden) URLs, even without the introduction of a new error.
Could you elaborate more on what will be the threat here?

**Comment by annevk** [comment]
Basically, we shouldn't give any more information on fetches that include credentials to attackers. There have been a number of novel attacks demonstrated in this area and I don't think this is a good enough reason to expose an additional bit.

It also violates the design contract of CORS whereby we wouldn't reveal information about servers in case of a non-match, but this would reveal information.

**Comment by ylafon** [comment]
From our last [meeting with @mikewest ](https://github.com/w3ctag/meetings/blob/gh-pages/2018/07-seattle/07-26-minutes.md#mike-west-discussion-with-credentials)

> Yves: we came up with .. define a new error type when withCredential used and ACAO: *. Jonas Sicking was in favor of this. Something more specific then generic Network Error.
> 
> Mike: Is this part of the promise t?hen pipeline?
> 
> Yves: yes, it would bubble out.
> 
> Mike: Seems fine. Data it leaks is fairly minor. Leakage probably has no real impact.

As far as violating the design contract or CORS, the current situation violates the design contract or URL and venture in the "URL+Context" that was in WS-Addressing and EndPoint References...

@mikewest would your "probably" statement in the minute be confirmed or clarified ?

**Comment by annevk** [comment]
We might, but I can't find an answer in that thread either. I don't think there's any guarantee about there being such information. Also, that doesn't define the design contract of URLs.

**Comment by ylafon** [comment]
See this [Finding](https://www.w3.org/2001/tag/doc/whenToUseGet.html#uris) linked from [WebArch](https://www.w3.org/TR/2004/REC-webarch-20041215/#dereference-uri) for the design contract or URLs.

**Comment by mikewest** [comment]
> @mikewest would your "probably" statement in the minute be confirmed or clarified ?

The proposal at this point, as I understand it, is that `fetch("https://cross-origin-thing/", {credentials: "include", mode: "cors"})` would reject with something like a `SecurityError` `DOMException` whose `message` was along the lines of:

> The request specified a `mode` of "CORS", and included credentials. The response included `Access-Control-Allow-Origin: *`, which only succeeds for non-credentialed requests.

Is that accurate?

If that's the case, then I agree with @annevk that there's some risk in revealing the information that the resource would have allowed itself to be read if it had been requested without credentials, and that it does violate the philosophical boundary between a resource that has opted-into sharing its state cross-origin and one that hasn't. But I think that risk is fairly minimal, since the resource _did_ allow itself to be read if requested without credentials, and the developer could certainly try that out themselves to see what happens. This feels like a little sugar on top of an existing mechanism that doesn't seem to uniquely expose anything interesting from a security standpoint, but potentially gives developers/libraries the ability to know when a retry would be a reasonable thing to do.

It seems like the smallest thing that could possibly work, and is certainly less invasive than creating new CORS modes. If developers are feeling this pain, it doesn't seem unreasonable to carve out this explicit signal for them.

**Comment by annevk** [comment]
Well, it could be that if requested without credentials the server closes the connection and `Access-Control-Allow-Origin: *` was mostly set in error when requested with credentials. We don't really know.

**Comment by mikewest** [comment]
> Well, it could be that if requested without credentials the server closes the connection and `Access-Control-Allow-Origin: *` was mostly set in error when requested with credentials. We don't really know.

Yup. And in that case, the developer would make another non-credentialed request, see it fail, and be sad. That's an ergonomic failure, but doesn't seem like a security risk to be concerned about.

I'm not saying this is the best idea ever or that it will always succeed. I'm saying that I don't see a substantial security risk to revealing to the developer that they would have been able to access the response they just got if they hadn't sent credentials along with the request, and giving them the opportunity to write their own retry logic. That seems fine?

**Comment by annevk** [comment]
What I'm saying is that if you set `Access-Control-Allow-Origin: *` in error, but in a way that today does not leak anything, this would leak a bit.

Anyway, past all that, even if everyone was comfortable making that change (it's unclear to me who besides timbl is asking for this), it's unclear to me how to make this work given that we cannot extend `TypeError`. (Using `DOMException` with a custom message seems rather error prone as that field is up to the user agent and it would break with the exception we use today which means existing higher level libraries that operate on the exception might get confused.)

**Comment by mikewest** [comment]
> What I'm saying is that if you set `Access-Control-Allow-Origin: *` in error, but in a way that today does not leak anything, this would leak a bit.

I agree.

> Anyway, past all that, even if everyone was comfortable making that change (it's unclear to me who besides timbl is asking for this)

@slightlyoff asks me about this on a regular basis, and I can believe that it annoys some developers beyond the TAG.

> it's unclear to me how to make this work given that we cannot extend `TypeError`

That's an interop risk I didn't consider. I think it's somewhat unlikely that there are libraries out there that depend on `TypeError`. Skimming the spec, it looks like libraries that hard-code that assumption would already be incorrect, since we can throw an "AbortError" `DOMException`. Adding another possible `DOMException` doesn't seem unthinkable.

**Comment by annevk** [comment]
Is this still a problem for anyone? I'm inclined to close it.

**Comment by ylafon** [comment]
Well, the fact that fetch+cors is not f(url) as stated by @timbl is still there, so yes it is still an issue.

**Comment by annevk** [comment]
That's way too abstract to be actionable. As I've pointed out before, the web deals in requests, which include quite a bit more than a URL. Once there's a more concrete proposal that has implementer interest I'm happy to reconsider this.

**Comment by timbl** [comment]
The fact that (a) there is no proposed solution yet or (b) no one in the bowser implementer community is interested in fixing this doesn't the bug isn't a bug.

You can't write middleware which uses fetch.  If you write general library code which alls fetch, it won't know whether to set credentials or not, so it will have to try with and then without, or vice versa.   This increases the number of round trips in a system which is already has the round trips needed for the CORS prefetch.  So it s a very broken system.

A concrete proposal is for  `Access-Control-Allow-Origin  PUBLIC-AND-UNCUSTOMIZED`  in the server response to satisfy the client whether the request comes with authentication or not.   This could be put on all open data servers, and allow the world of data mashups to return to the web.

**Comment by annevk** [comment]
By that reasoning it also won't know what headers to set or whether to avoid looking at the client cache. If you want middleware for fetch it needs to match its API.

And servers already have the capability to expose their response to any kind of request.

**Comment by torgo** [comment]
Anne I can't quite believe my eyes that you closed an issue in our design review repo without bringing it up to the chairs. For avoidance of doubt, issues are closed here based on TAG consensus, not individual opinions of people.
