### ISSUE TITLE
Fetching with a particular destination

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/fetch#521]
Some browsers will change their headings based on the type of request, eg Chrome will include `image/webp` in the `Accept` header for image requests.

Should we have an API to create requests that contain these details? Eg `Request.as('image', url, opts)`.

Moved from https://github.com/w3c/ServiceWorker/issues/945

**Comment by annevk** [comment]
The main question is how this relates to CSP and what that means with respect to constraints on the response.  (We could make a parallel field I suppose that only affects `Accept` headers and priorities and such, but that doesn't seem great.)

See also #43 and #64.

**Comment by annevk** [comment]
Updated the title to reflect type being folded into destination, but the same general concern applies. Consider, a site safelists `image-src` requests, but not `connect-src`. This would allow you to read arbitrary third-party data with `fetch()`, despite that CSP policy.

**Comment by annevk** [comment]
@jakearchibald do you still wish to pursue this?

**Comment by jakearchibald** [comment]
@annevk it isn't something I've had many requests for. The main use case is when caching content, you want the correct accept header for images. Happy to close for now until we work out the CSP parts.

**Comment by yoavweiss** [comment]
> The main use case is when caching content, you want the correct accept header for images

I assumed that the accept headers are set before the SW gets the request (and therefore passed along when `fetch()`ing the same request). Is that not the case?

**Comment by yoavweiss** [comment]
nm. I thought this is somewhat similar to https://github.com/whatwg/fetch/issues/717 but re-reading this, the use-case is about creating a `Request` from scratch. Apologies for the noise

**Comment by jakearchibald** [comment]
@yoavweiss yeah, but the accept header for webP isn't there if you do `cache.add('/path/to/img')` since it isn't an image request.
