### ISSUE TITLE
Are properties on Request object explicit enumerable?

### ISSUE THREAD

**Issue by bitinn** [whatwg/fetch#525]
I am sorry as I can't find any words on it in spec, but I was told some browsers do make them enumerable? Maybe it's implied by a clause in IDL? (which I couldn't find, sorry.)

**Comment by domenic** [comment]
https://heycam.github.io/webidl/#es-attributes (and https://heycam.github.io/webidl/#es-operations for methods)

**Comment by bitinn** [comment]
@domenic thx, I don't know how I can read that paragraph twice and not see this line:

`The property has attributes { [[Get]]: G, [[Set]]: S, [[Enumerable]]: true, [[Configurable]]: configurable } ...`
