### ISSUE TITLE
"Extract a MIME type" algorithm should pick the first entry?

### ISSUE THREAD

**Issue by tyoshino** [whatwg/fetch#529]
`extract header list values` algorithm returns a list. `extract a MIME type` and sites calling `extract a MIME type` look using the result as a byte sequence.

Should `extract a MIME type` pick the first entry of the result of `extract header list values` if it's not null?

**Comment by annevk** [comment]
Yeah, although we should probably have tests for multiple `Content-Type` headers. I haven't researched that much at all.

**Comment by tyoshino** [comment]
I see. Considering the following, `extract header list values` would return failure when there are multiple entries. So, the fix is not what I said in the OP but pick the single entry while asserting it's a single element list if it's not either null or failure.
- https://tools.ietf.org/html/rfc7230#section-3.2.2
- https://tools.ietf.org/html/rfc7231#section-3.1.1.5
- https://tools.ietf.org/html/rfc7231#section-3.1.1.1

**Comment by annevk** [comment]
Is that what browsers implement? What if you navigate to a URL with two Content-Type headers. Do you get a network error? We should probably have a bunch of web-platform-tests. The HTTP WG generally does a bad job of making sure their requirements can actually be implemented.

**Comment by tyoshino** [comment]
Chrome's fetch() is currently broken (Blink's ExtractMIMEType is using combined value http://crbug.com/713634), but looks Chrome has been not erroring for multiple Content-Types but using the last Content-Type header before the break.

Navigating to a resource with multiple Content-Type also works. Haven't checked which one is used for navigation.

**Comment by annevk** [comment]
Another angle to test would be a single `Content-Type` header with a comma-separated value. They ought to be treated identically, but browsers...

Relates to https://github.com/whatwg/mimesniff/issues/30.

**Comment by annevk** [comment]
https://github.com/whatwg/mimesniff/issues/30#issuecomment-382721437 has my findings on this. Input there much appreciated, even though we'll likely define it here.

**Comment by annevk** [comment]
For anyone subscribed to this issue, please note that #831 is pretty close towards solving this. Tests are linked from there as well.
