### ISSUE TITLE
Abort fetch upon document unload

### ISSUE THREAD

**Issue by Rob--W** [whatwg/fetch#53]
The `fetch` spec doesn't define what a user agent should do when the document unloads. I expect the fetch request be aborted. This expectation seems reasonable, since it is similar to what the SW spec states: https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#on-fetch-request-algorithm:

> 18 .  ...
> If task is discarded or the script has been aborted by the termination of activeWorker, set handleFetchFailed to true.
> ...
> 21 . If handleFetchFailed is true, then:
>    1. Return a network error and run the following substeps in parallel.

> 22 . Else:
>    1. Return a response represented by response and run the following substeps in parallel.

Chrome's implementation already follows this behavior, Firefox does not (see https://bugzilla.mozilla.org/show_bug.cgi?id=1165237).

**Comment by igrigorik** [comment]
Note that this is not always the case. For example, if it's a prefetch or prerender request, then we want to allow those to proceed. The UA should implement own / custom logic for how long its willing to keep those around, when to cancel, and so on. 

Concrete use case is "reactive prefetch": https://plus.google.com/+IlyaGrigorik/posts/ahSpGgohSDo

**Comment by annevk** [comment]
This is basically https://www.w3.org/Bugs/Public/show_bug.cgi?id=23878

**Comment by annevk** [comment]
@Rob--W see https://www.w3.org/Bugs/Public/show_bug.cgi?id=23878#c20 for how this is resolved. It's still pending some changes in HTML, which I have no control over.
