### ISSUE TITLE
Request constructor does not check used flag on null body

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#55]
Over in https://github.com/yutakahirano/fetch-with-streams/issues/37#issuecomment-103587329 @yutakahirano noticed that this code may not do what is expected:

```
var req = new Request(url, {body: 'hello'});
fetch(req);
fetch(req);
```

I think we would expect the second fetch() to reject on a drained Request, but it won't.  The first fetch() sets the request's used flag to true and its body to null.  The second fetch(), however, only looks at the used flag if the body is not null.

What do you think @annevk?

**Comment by annevk** [comment]
Oh yes that is bad. I'm starting to think we should do #61 while we still can.

**Comment by annevk** [comment]
Can we simply move the used flag check out of the non-null body clause? Would that miss anything? Over in #61 we talked about introducing an obsolete flag, but I don't really think that's necessary here.

**Comment by wanderview** [comment]
Gecko impl bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1184550
