### ISSUE TITLE
How can I create a response with redirected: true

### ISSUE THREAD

**Issue by wheresrhys** [whatwg/fetch#552]
I maintain https://github.com/wheresrhys/fetch-mock (a mock fetch implementation) and it's been brought to my attention that I don't support the `redirected` property on Responses. 

Reading the spec, the `redirected` property is a getter dependent on the private implementation of `url list`. Is there any way I can create a synthetic redirected Response?

**Comment by annevk** [comment]
Not with the same branding as a `Response` has.

**Comment by annevk** [comment]
I'm going to close this since OP just contained a question that's been answered. I recommend filing a new issue if there's an actual problem or some change to Fetch is needed.
