### ISSUE TITLE
Why is media fragment uri stripped from fetch URL?

### ISSUE THREAD

**Issue by guest271314** [whatwg/fetch#557]
```
fetch("https://upload.wikimedia.org/wikipedia/commons/b/be/Hidden_Tribe_-_Didgeridoo_1_Live.ogg#t=30,50")
```

strips media fragment `#t=30,50` from request at `Network` tab at `DevTools` at chromium. Why?

**Comment by annevk** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=624278

(Duplicate of #214.)

**Comment by guest271314** [comment]
@annevk [Media Fragment URI](https://www.w3.org/TR/media-frags/) is different from `location.hash`, no? Not sure how links address or resolve issue?

**Comment by guest271314** [comment]
@annevk Installed chromium 59. `fetch()` does not include media fragment uri at URL.
