### ISSUE TITLE
Should CORS preflight fetch also copy request's service-workers mode?

### ISSUE THREAD

**Issue by KiChjang** [whatwg/fetch#558]
https://fetch.spec.whatwg.org/commit-snapshots/f3bb21991abdd335175fcc5d26a0d0b7b380d4fe/#cors-preflight-fetch

> Let preflight be a new request whose method is \`OPTIONS\`, url is request’s current url, initiator is request’s initiator, type is request’s type, destination is request’s destination, origin is request’s origin, referrer is request’s referrer, and referrer policy is request’s referrer policy\.

_preflight_ does not seem to have copied _request_'s service-workers mode. Should it do so?

**Comment by annevk** [comment]
No, a preflight always goes to the server. I suppose we could add a note to that effect.
