### ISSUE TITLE
"Extracting header list values" algorithm returns a list, but is being treated as a string

### ISSUE THREAD

**Issue by KiChjang** [whatwg/fetch#559]
https://fetch.spec.whatwg.org/commit-snapshots/f3bb21991abdd335175fcc5d26a0d0b7b380d4fe/#cors-preflight-fetch

> Let methods be the result of extracting header list values given \`Access\-Control\-Allow\-Methods\` and response’s header list\.
> 
> If methods is \`\*\`, then set methods to a new list containing \`\*\`\.

There are other places in the spec currently that has this pattern where we're checking if the resultant value from the "extract header list values" algorithm is a string (in this case `"*"`), but the return type of that algorithm is clearly a list.

**Comment by annevk** [comment]
Folding this into #814. The idea is to get rid of this algorithm altogether.
