### ISSUE TITLE
WebSocket: "HTTP authentication will not function" is not correct

### ISSUE THREAD

**Issue by ricea** [whatwg/fetch#565]
https://fetch.spec.whatwg.org/commit-snapshots/f3bb21991abdd335175fcc5d26a0d0b7b380d4fe/#websocket-opening-handshake

> HTTP authentication will not function

Actually HTTP authentication functions with WebSockets in Chrome, Firefox, IE, and Edge. It doesn't work in Safari, but that's a bug: https://bugs.webkit.org/show_bug.cgi?id=80362

Firefox will also give you a password prompt if it gets a 401 response on a WebSocket. Chrome and Edge will only use cached credentials. In Chrome's case, this is the policy for all subresources, rather than being a WebSocket-specific restriction.

**Comment by annevk** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1380973 to remove the prompting in Firefox.

**Comment by annevk** [comment]
@ricea do you wait for a challenge or just send credentials if you have them?

**Comment by annevk** [comment]
Also, are there tests for this?

**Comment by ricea** [comment]
As far as I know, Chrome always sends credentials in the initial request if it has them, but from the limited testing I've done it appears that Firefox doesn't. In Chrome we share the logic with ordinary HTTP.

There don't appear to be any web-platform-tests testing this. We have Chrome-specific tests, but not of a sort that could be straightforwardly ported.

**Comment by ricea** [comment]
I can't actually find any normative text that prohibits HTTP authentication. I will create a PR to remove the text that says it doesn't.

**Comment by ricea** [comment]
Simple wpt at https://github.com/web-platform-tests/wpt/pull/11433.

**Comment by dveditz** [comment]
> As far as I know, Chrome always sends credentials in the initial request if it has them, 

Without the 401 that could in theory be sending auth for the wrong realm.

**Comment by ricea** [comment]
@dveditz wrote:
> Without the 401 that could in theory be sending auth for the wrong realm.

Thanks for the clarification! If I catch Chrome doing the wrong thing I will file a bug.
