### ISSUE TITLE
Allow .blob() to return disk-backed resource

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/fetch#569]
It seems that both Chrome & Firefox point to an item on disk when you do:

```js
const cache = await caches.open('test');
const response = await cache.match('/really-large-resource');
const blob = await response.blob();
```

Test: https://cache-memory-test.glitch.me/

This is pretty cool, as you can get a slice of the data without reading it all into memory. However, it seems to go against https://fetch.spec.whatwg.org/#concept-body-consume-body which requires reading the whole response.

We should spec the Chrome/Firefox behaviour, possibly by flagging requests/responses whose body is on disk.

**Comment by wanderview** [comment]
I'm not sure I believe this for firefox.  The `Response` body will point to a file on disk, but when you do `.blob()` I'm pretty sure we read it all into memory.  Unless our blob code has started magically pushing these back to temp files on disk I think it should be in memory.

**Comment by wanderview** [comment]
Actually, we do spill large blobs back to a temp file.  It was implemented in FF52 here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1312410

I don't understand why this is a problem, though.

**Comment by jakearchibald** [comment]
Hmm yeah, it seems like Firefox does process the whole response.

Get as blob and read small slice:

* Firefox 815ms
* Chrome 10ms

So I guess the question is, do we want to spec something smarter here, or is it just implementation detail since performance is the only observable difference?

**Comment by jakearchibald** [comment]
From IRC:

This is just an implementation detail, the only observable difference is performance.

**Comment by wanderview** [comment]
> Hmm yeah, it seems like Firefox does process the whole response.

With Cache API we have to since we store the Response compressed on disk.  Once we exceed 1MB in Blob size, though, it gets put back into an uncompressed temp file.  Clearly we've optimized for long term storage space and sequential read here.  Maybe thats the wrong choice?  I'm not sure.

**Comment by jakearchibald** [comment]
Chrome has to deal with blob references, so if you transfer the blob of a cached response to another thread, then delete the item from the cache, it needs to avoid deleting the disk entry until the blob is GCd.

**Comment by wanderview** [comment]
> Chrome has to deal with blob references, so if you transfer the blob of a cached response to another thread, then delete the item from the cache, it needs to avoid deleting the disk entry until the blob is GCd.

Yea, we have to deal with the same thing.  We have a native stream representing the Cache body entry.  We need to keep the entry alive as long as that native stream is active.  This could be due to Blob code or something else (like respondWith, etc).

**Comment by jakearchibald** [comment]
TIL! I thought the temp file thing might have been done to avoid that.

**Comment by wanderview** [comment]
> TIL! I thought the temp file thing might have been done to avoid that.

Its mainly to avoid OOM crashes AFAIK.

**Comment by asutherland** [comment]
Just as a "the more you know..." thing, Firefox does also have a fancy (cross-process) system for dealing with blob references, it's primarily used by disk-backed IndexedDB Blobs/Files (and the XHR/fetch spill-to-disk-to-avoid-OOMs-if-we're-not-a-private-browsing-session heuristic at play here.)  We even have tricks involving weak references so that if you IDB.put() a memory-backed Blob to disk multiple times we can de-duplicate it to a single on-disk reference, and without keeping the memory-backed blob alive beyond when it would normally die.  Which is to say, IDB is the best and everyone should use it for everything.
