### ISSUE TITLE
response.bodyUsed is an ambiguous name

### ISSUE THREAD

**Issue by JohanLorenzo** [whatwg/fetch#57]
After trying to stub `fetch()` in some unit tests [in this project](https://github.com/gaia-components/serviceworkerware), I came across that `bodyUsed` wasn't what I expected. I thought it was a boolean showing that the response contained a body, instead of a value telling that the body has already been used somewhere in your own code.

[As the specs](https://fetch.spec.whatwg.org/#concept-response) are currently not very explanatory on that particular subject:
> The bodyUsed attribute's getter must return true if the used flag is set, and false otherwise.

I'd suggest to rename `bodyUsed` to `bodyAlreadyUsed`, to make the intent clearer.

What do you all think?

**Comment by annevk** [comment]
I think it's going to depend a bit on what happens with Streams integration and how @yutakahirano and @wanderview end up thinking about this.

In general though we prefer short names over completely unambiguous names.

**Comment by annevk** [comment]
I'm going to keep this as-is. Perhaps it changes as part of Streams integration, but then it wouldn't be a simple rename like suggested by OP.
