### ISSUE TITLE
May interceptors  will be supported?

### ISSUE THREAD

**Issue by fewiki** [whatwg/fetch#574]
like axios
so can do general error
```
// Add a request interceptor
axios.interceptors.request.use(function (config) {
    // Do something before request is sent
    return config;
  }, function (error) {
    // Do something with request error
    return Promise.reject(error);
  });

// Add a response interceptor
axios.interceptors.response.use(function (response) {
    // Do something with response data
    return response;
  }, function (error) {
    // Do something with response error
    return Promise.reject(error);
  });
```

**Comment by annevk** [comment]
I recommend reading through https://wiki.whatwg.org/wiki/FAQ#Is_there_a_process_for_adding_new_features_to_a_specification.3F and also keep in mind that not everyone will be familiar with the same libraries.

**Comment by fewiki** [comment]
User fetch，I need to set header in every request，this is very boring.
I want to set header at one place， like fetch.interceptors.request.use('header', ''custom-header")
Thanks~

**Comment by annevk** [comment]
This is similar to #507 and other such requests. I recommend writing a wrapper function for the shared code.
