### ISSUE TITLE
[Question] Is there any suggested way to tell if we are dealing with a fetch request server-side?

### ISSUE THREAD

**Issue by Bartmax** [whatwg/fetch#58]
In a discussion on .NET MVC Framework, https://github.com/aspnet/HttpAbstractions/issues/245 there's some talk about what's the future of the old mvc version feature: Request.IsAjaxRequest() Method.

Right now, the only way we developers checks for a request that's initiated via javascript we check the used `X-Requested-With` custom header.

I was wondering if there's some plan or intention to have a 'standard' header or realiable mechanism for a server to know if the request originates from a fetch request or we should use custom headers for this kind of scenario.

Thanks and sorry if this has already been addresses, couldn't find it on current issues.

**Comment by dgraham** [comment]
The standard Accept header can be used to perform content negotiation with the server for responses needed by a `fetch` request vs a normal full page request. Something like:

```js
fetch('/users', {headers: {Accept: 'text/partial'}})
```

**Comment by annevk** [comment]
There is no such plan. Each framework/site can make up their own conventions, as with `XMLHttpRequest`, but we do not want to dictate and certainly not add "cruft" to requests that is not strictly speaking required.
