### ISSUE TITLE
Link preload's `as` value should impact Accept headers

### ISSUE THREAD

**Issue by yoavweiss** [whatwg/fetch#580]
As commented on https://github.com/w3c/preload/issues/95#issuecomment-305237486 Fetch should indicate that `as` also impacts the request type, and therefore impacts the `Accept` headers that preload requests go out with.

**Comment by yoavweiss** [comment]
Is there a normative way to map from a request's `destination` to a `type`?

**Comment by annevk** [comment]
Closing this as a duplicate of #581.
