### ISSUE TITLE
Fold request type into destination

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#581]
Since ba175cf1100045da83ed0d7768629653aa979c20 merged there's no reason for type and destination to be different fields as far as I can tell. We'll need to change the following specifications to make this change:

* Fetch
* CSP, https://w3c.github.io/webappsec-csp/#effective-directive-for-a-request (and maybe elsewhere?)
* Mixed Content, https://w3c.github.io/webappsec-mixed-content/#should-block-fetch
* HTML

In Fetch we should mention these specifications in a source comment below the definition of destination so we know where the dependencies are. SRI https://w3c.github.io/webappsec-subresource-integrity/ is another dependency but doesn't use type currently so doesn't need to be updated.

I can do Fetch and HTML. @yoavweiss are you willing to do CSP and Mixed Content?

cc @mikewest

**Comment by annevk** [comment]
Complication: we do expose `type` on `Request` at the moment. We can either remove that or continue doing that by just returning the empty string for non-safelisted values. @jakearchibald @wanderview thoughts on this?

**Comment by annevk** [comment]
Sorry, I should have tested, `((new Request("about:blank")).type)` yields undefined. Same for `.destination`.

**Comment by yoavweiss** [comment]
@annevk I can take on [preload](https://w3c.github.io/preload/#link-element-extensions), as well as CSP and Mixed Content.

**Comment by annevk** [comment]
PRs for Fetch #582 and HTML https://github.com/whatwg/html/pull/2949 are ready for review.

**Comment by annevk** [comment]
@yoavweiss could you link the other PRs from here?

**Comment by annevk** [comment]
https://github.com/w3c/webappsec-csp/pull/231 and https://github.com/w3c/webappsec-mixed-content/pull/11
