### ISSUE TITLE
Request and response body as async iterable ArrayBuffer

### ISSUE THREAD

**Issue by mariusGundersen** [whatwg/fetch#586]
NodeJS is [looking](https://github.com/tc39/proposal-async-iteration/issues/74) into supporting async iterables as a way to stream data, and it would be great if fetch (or the readable stream part of fetch) supported the same interface. This would make easier to move code between nodejs and the browser.

**Comment by domenic** [comment]
Yeah, we plan to add it to readable streams quite soon. So this really belongs on the whatwg/streams repository, but you don't have to move it if you don't want to.

**Comment by mariusGundersen** [comment]
Ah, didn't realize it had its own repo
