### ISSUE TITLE
POST calls - Request Payload is not shown with native fetch

### ISSUE THREAD

**Issue by vigneshshanmugam** [whatwg/fetch#59]
```
fetch(url, {
  method: 'post',
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    id: 'Hubot',
    name: 'hubot',
  })
})
```

The payload body is not shown on both Chrome and Firefox Dev tools. Tried even with Canary and Nightly builds.

However, the Github Fetch polyfill is properly showing the payload data.

**Comment by domenic** [comment]
This is not an issue with the spec (which is what this repo is for). You should consider filing an issue on Chrome and Firefox for their dev tools to support things as you wish.

**Comment by vigneshshanmugam** [comment]
Sure will do. Thanks @domenic

**Comment by jongbeau** [comment]
@vigneshshanmugam did you ever find a solution to get the payload to show?

**Comment by vigneshshanmugam** [comment]
I am using fetch-polyfill from Github, So its not causing issue for me now.

**Comment by jongbeau** [comment]
are you talking about this: https://github.com/github/fetch ?
installed with `npm install whatwg-fetch` ?
That's what I am using, and i'm having the request payload not showing issue.

**Comment by vigneshshanmugam** [comment]
Yeah I am using this only and getting the request payload properly showing up. 

However, if you are in the latest browser the polyfill will not replace the browser's native fetch method. So under the hood you will be using the browsers fetch.

**Comment by mewben** [comment]
+1 Request payload is not showing on Chrome but shows in Firefox.

**Comment by juancampa** [comment]
+1

**Comment by ilyaa1** [comment]
+1

**Comment by jakearchibald** [comment]
This should be fixed in Chrome Canary https://code.google.com/p/chromium/issues/detail?id=457484
