### ISSUE TITLE
"serviceworker" in the RequestDestination enum

### ISSUE THREAD

**Issue by martinthomson** [whatwg/fetch#602]
From the spec:

> "serviceworker" is omitted from RequestDestination as it cannot be observed from JavaScript. Implementations will still need to support it as a destination. 

But "serviceworker" is clearly listed in the IDL.

**Comment by annevk** [comment]
This regressed in https://github.com/whatwg/fetch/commit/6b9cdaa9be7acd2b8074c74823981ef994d17857. Given that https://w3c.github.io/preload/ doesn't use `RequestDestination` it seems like adding it there was a mistake and I missed it during review. Fancy doing a PR?
