### ISSUE TITLE
Wrong authors listed for WSP

### ISSUE THREAD

**Issue by stefhak** [whatwg/fetch#613]
As much as I wish I could say I was one of the authors of the web socket protocol, that would not be true, and the ref section should be updated (https://fetch.spec.whatwg.org/#biblio-wsp)

**Comment by annevk** [comment]
Thanks, I wonder what went wrong there. Looks like a very outdated version of the protocol too! Will investigate.

**Comment by annevk** [comment]
Fix for the source issue can be found at https://github.com/tobie/specref/pull/410 by the way. Thanks again.

**Comment by stefhak** [comment]
NP!
