### ISSUE TITLE
How to set a Basic Authentication headers ?

### ISSUE THREAD

**Issue by smknstd** [whatwg/fetch#623]
Any news on https://github.com/whatwg/fetch/issues/162 ? What are my options ?

Is it normal that I can't set headers manuallly ?

```
            headers: {
                'Authorization': 'Basic ZWZyYToyMDE44'
            }
```

Thanks for your help

**Comment by annevk** [comment]
No, that's either a bug in a browser or some other kind of issue. Per the standard that's supported.

**Comment by smknstd** [comment]
Forgot to say thank you for answering :)
