### ISSUE TITLE
Nitpick: The user agent can terminate the fetch ... "res => res.body.getReader().closed"

### ISSUE THREAD

**Issue by ricea** [whatwg/fetch#625]
https://fetch.spec.whatwg.org/commit-snapshots/8ab040a62c993a3f730da333a3f0ae42fc341d14/#terminate-examples

> The user agent can terminate the fetch because the termination cannot be observed\.
> 
> fetch\("https:​//www\.example\.com/"\)\.then\(res =​&gt; res\.body\.getReader\(\)\.closed\)
> 

Nitpick: The termination can be observed by replacing ReadableStream.prototype.getReader on the global object.

Since this section is non-normative, I assume it doesn't have to be nitpick-proof. Feel free to close this issue. I am mentioning it just in case it matters.

**Comment by annevk** [comment]
@domenic what would be the right terminology to make this nitpick-proof? "(This is assuming none of these functions are replaced.)"?
