### ISSUE TITLE
Isn't request.body not part of the spec?

### ISSUE THREAD

**Issue by jimmywarting** [whatwg/fetch#643]
...Or is it just not implemented in any browser yet?

Request and Response both implement Body. But so far i have only seen Response having a readable body stream.

The only way to get the content from a Request is throught arrayBuffer, text, FormData, json or Blob but i wan't the stream so i can use pipes

**Comment by annevk** [comment]
Yeah, browsers have not implemented this yet. As far as I know it's mostly a matter of resources.

There is still some work to be done though, such as #463.

Closing this on the assumption that this was just a question.

**Comment by jimmywarting** [comment]
Yes, thank you
