### ISSUE TITLE
Requests cant "live" longer than 5 minutes?

### ISSUE THREAD

**Issue by nexflo** [whatwg/fetch#647]
Seems we cant keep long living connections alive. (Not request pooling ala keep-alive) but on a request level....so 1 request will ECONNRESET after 5 minutes.
In Https one can add  socket.setKeepAlive(true, 240000); on a per socket level...so requests wont be collected by the other side.

**Comment by annevk** [comment]
Is your concern with a browser implementation or a library?

**Comment by annevk** [comment]
Closing due to lack of a reply.
