### ISSUE TITLE
Should Body.formData() always strip the BOM?

### ISSUE THREAD

**Issue by rakuco** [whatwg/fetch#650]
This came up in https://bugs.chromium.org/p/chromium/issues/detail?id=796192. Blink's currently failing some of the tests added in https://github.com/w3c/web-platform-tests/pull/4517 due to multiple issues.

The `\uFEFFtest=\uFEFF` tests, specifically, fail with `Request` and `Response` because the leading `\uFEFF` ends up being stripped when `Body.formData()` is called.

The input string is correctly [parsed as a USVString and encoded in UTF-8](https://fetch.spec.whatwg.org/#body-mixin) as `\xef\xbb\xbftest=\xef\xbb\xbf`, and calling `Body.formData()` with `Content-Type: application/x-www-form-urlencoded` causes it to be [parsed](https://url.spec.whatwg.org/#urlencoded-parsing) and the string to be decoded via [UTF-8 decode without BOM](https://encoding.spec.whatwg.org/#utf-8-decode-without-bom).

Calling `Body.json()` and `Body.text()`, however, decodes the same UTF-8 string with [UTF-8 decode](https://encoding.spec.whatwg.org/#utf-8-decode), which does strip the BOM from the beginning when it's present.

I was wondering if this "asymmetry" is intentional, or whether we should be using the same decoding algorithm for all functions mentioned above.

**Comment by annevk** [comment]
Are you only talking about stripping an initial BOM and not for name/value? https://url.spec.whatwg.org/#urlencoded-parsing doesn't do such a thing, though we could consider changing how it works I suppose.

Doing an early decode there would be unfortunate however as for percent decoding that would end up with quite a few more roundtrips. And you cannot percent decode first as that would mangle with the syntax. You'd basically have to special case the initial UTF-8 BOM as an initial step and strip it or some such.

**Comment by rakuco** [comment]
> Are you only talking about stripping an initial BOM and not for name/value? https://url.spec.whatwg.org/#urlencoded-parsing doesn't do such a thing, though we could consider changing how it works I suppose.

Your question made me realize my description was biased by the way the code currently works in Blink. I was indeed only talking about the initial BOM, but only because we're not doing https://url.spec.whatwg.org/#urlencoded-parsing properly in `Body.formData()` (we're essentially [UTF-8 decoding](https://encoding.spec.whatwg.org/#utf-8-decode) everything first and then doing the rest).

The only thing I have in mind now is whether there needs to be some sort of consistency:
* `Body.json()`: whether the BOM is preserved or not seems irrelevant.
* `Body.text()`: should it return the same data it received, BOM included, to match `Body.formData()`?

**Comment by annevk** [comment]
Generally I think BOM stripping is good and we definitely want it for JSON (consistency with JSON consumed elsewhere) and text (same consistency). I guess arguably that means we should do it here too since it's a text format. It does sound though like the code in Blink is not super efficient as you end up decoding, then encoding so you can do percent decoding, and then decoding the result of that. Instead of decoding the result of percent decoding as the specification does now.

**Comment by rakuco** [comment]
> Generally I think BOM stripping is good and we definitely want it for JSON (consistency with JSON consumed elsewhere) and text (same consistency). I guess arguably that means we should do it here too since it's a text format.

Do you mean stripping the BOM from each name/value pair parsed by the application/x-www-form-urlencoded parser or just the leading one?

> It does sound though like the code in Blink is not super efficient as you end up decoding, then encoding so you can do percent decoding, and then decoding the result of that. Instead of decoding the result of percent decoding as the specification does now.

Not sure about the first decoding bit. Right now, we do something like this for this specific case of a string containing `\uFEFF` (I'm writing it down here mostly so I can come back to this later):
* The test is read, the JS string parsed as a USVString and we have an UTF-16 string
* The UTF-16 string is encoded to UTF-8
* The entire UTF-8 string is decoded without the BOM into a UTF-16 string
* The UTF-16 string is passed to https://url.spec.whatwg.org/#urlencoded-parsing, with each `name`/`value` pair being separately re-encoded into UTF-8 and percent-decoded into UTF-16 strings
* The list created in the previous step is fed into `FormData`, which re-encodes everything into UTF-8

**Comment by annevk** [comment]
I meant just the initial leading one for the entire resource. I'd be opposed to to doing it for each name/value. I'm not entirely sure it's worth the complexity though given that this parser is also used by `URLSearchParams` and I'm not sure we'd want to strip a BOM in that case.

**Comment by rakuco** [comment]
I'm fine either way; would the rationale for not stripping the BOM for `URLSearchParams` also apply to what we're discussing here? As long as there's a reason for not changing things I'm fine just fixing Blink.

**Comment by annevk** [comment]
The rationale for `URLSearchParams` would be that it just takes a string and we generally only strip a leading BOM for a resource.

**Comment by rakuco** [comment]
So IIUC `.text()` and `json()` consider the bytes in `Body` a resource, whereas they're treated as a string by `.formData()`?

**Comment by annevk** [comment]
I think it's mostly that `application/x-www-form-urlencoded` deviates a little by just being a somewhat different format. We could align it more, but it's unclear what that would mean for other entry points of that format.

**Comment by hiroshige-g** [comment]
The discussion above is about BOMs in `application/x-www-form-urlencoded`, which doesn't strip BOMs.
@eehakkin is going to change Chromium's behavior to align with the spec and Firefox (i.e. not to strip BOMs).

How about BOMs in `multipart/form-data`?
The spec https://fetch.spec.whatwg.org/#concept-body-package-data says

    Each part whose `Content-Disposition` header does not contain a `filename` parameter must be parsed into an entry whose value is the UTF-8 decoded content of the part.

So BOMs are NOT stripped in the spec. (Chromium strips BOMs, Firefox doesn't. See https://github.com/web-platform-tests/wpt/pull/17589)
What do you think about this case?

**Comment by annevk** [comment]
It seems the specification does strip the BOM (it invokes https://encoding.spec.whatwg.org/#utf-8-decode not https://encoding.spec.whatwg.org/#utf-8-decode-without-bom), but @hsivonen doesn't think it should (and I tend to agree). Usually BOM stripping only makes sense if it's at the start of some resource.

I'll create a patch to make the specification invoke the UTF-8 decode algorithm without BOM stripping. Can you ensure the test is changed?
