### ISSUE TITLE
what is the Request.destination for modules and es `import()`?

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#652]
I think the `Request.destination` table here needs to be updated for modules:

https://fetch.spec.whatwg.org/#concept-request-destination

I assume they have a destination of "script".

**Comment by wanderview** [comment]
@domenic does "script" destination sound reasonable?  cc @yoavweiss

**Comment by domenic** [comment]
Yes, this is already specified in HTML. It uses script/audioworklet/paintworklet/serviceworker/sharedworker/worker as appropriate.

I'm not sure the table needs any updates since it's just an alternate entry point into all the same APIs?

**Comment by wanderview** [comment]
Ah, I'm not used to the other specs being updated!  I guess that's fine, although the table is nice for checking test coverage, etc.

**Comment by wanderview** [comment]
I guess I worry about people looking at the table and thinking it covers all cases.  Could we either:

1. Make a note that its not exhaustive.
2. Or make a note outside the table itself that summarizes how modules work and points at the html spec.

I assume things like `import()` would be added on the same line as `importScripts()` in the table, etc.
