### ISSUE TITLE
No documentation of which ports are used by default

### ISSUE THREAD

**Issue by SteveALee** [whatwg/fetch#667]
I was trying to find out which ports are used by fetch when none are specified. 

And while browsers seem to use 80 and 443 as might be expected I was surprised not to find this specified anywhere. But why 80/443 when payloads are unlikely to be HTML?

In fact this appears to be true of any request mechanism I looked at.

**Comment by yutakahirano** [comment]
https://url.spec.whatwg.org/#url-miscellaneous

**Comment by SteveALee** [comment]
@yutakahirano Thank you!

I realised I got mixed up in my thinking and though 80/443 were for HTML, not HTTPS. D'oh.
