### ISSUE TITLE
ReadableStreamDefaultReader.read() Errors Unavailable to Response Reader Promise

### ISSUE THREAD

**Issue by AnthumChris** [whatwg/fetch#676]
Errors that originate in `ReadableStreamDefaultReader.read()` to not propagate to Promise rejections for `Response` stream reader (`Response.text()`, `Response.json()`, etc) errors.

```JavaScript
// Test 1 - ReadableStreamDefaultReader.read() error successfully propagated to catch()
new ReadableStream({
  start(controller) {
    // controller.close();

    controller.error(Error('Test 1 Error'));
  }
}).getReader().read()
.then(o => console.log('Test 1 OK', o))
.catch(error => console.error(error))


// Test 2 - ReadableStreamDefaultReader.read() error lost and unavailable to catch().
// Instead, TypeError: Failed to fetch is propagated
new Response(
  new ReadableStream({
    start(controller) {
      // controller.enqueue(new TextEncoder().encode('hello'))
      // controller.close();

      controller.error(Error('Test 2 Error'));
    }
  })
).text()
.then(string => console.log('Test 2 OK', string))
.catch(error => console.error(error))
```

Catching the originating errors in Promise rejections would be very useful to our applications so that we could take appropriate action.   For example, network errors that occur mid-fetch() ([example](https://gist.github.com/AnthumChris/39ebe19f2f226e2858e0511febf2a002)) originate as "TypeError: network error" but are reported to the application as "TypeError: Failed to fetch".

**Comment by annevk** [comment]
@yutakahirano what ends up replacing the exception here? I don't see it in https://fetch.spec.whatwg.org/#concept-body-consume-body or https://fetch.spec.whatwg.org/#concept-bodyinit-extract.

@AnthumChris as far as I can tell this is an implementation bug and we should make sure the test suite covers it.

**Comment by yutakahirano** [comment]
Implementations should propagate the error. Chrome is incorrect at that point.

**Comment by AnthumChris** [comment]
@annevk PR submitted with tests
