### ISSUE TITLE
worker request context definition references undefined "serviceworker" context

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#68]
Currently the spec says:

  A worker request context is one of "serviceworker", "sharedworker", and "worker". 

But the webidl does not define a "serviceworker" value for RequestContext.

**Comment by annevk** [comment]
Right, see https://github.com/whatwg/fetch/commit/1cc2584d1174b65bd076be3a75b9250016b5c191 which fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=28803 which asked for this to be removed since it's not observable.

**Comment by wanderview** [comment]
Ok, I guess its just confusing to me to have references to undefined RequestContext values elsewhere in the spec.  What other values are possible, but not defined because they should not be user visible?

**Comment by annevk** [comment]
Only "serviceworker" for now. I could add a note I suppose.

**Comment by wanderview** [comment]
Or remove the enumeration from the definition of worker request context.

**Comment by annevk** [comment]
Why? It should still affect how `nosniff` behaves.

**Comment by wanderview** [comment]
If it matters then I think it should be included in the enumeration.  I'd rather have a value exposed that content can't currently see then have to maintain two copies of the same enumeration that could then get out of sync.

**Comment by annevk** [comment]
The specification maintains two copies at the moment. I don't really see the problem. But you could include it in your enumeration I suppose. It's not observable after all.
