### ISSUE TITLE
Should the safelisted request header list still include `Downlink`?

### ISSUE THREAD

**Issue by richardkmichael** [whatwg/fetch#684]
The current version of the Fetch Living Standard indicates `Downlink` is [safelisted request header](https://fetch.spec.whatwg.org/#cors-safelisted-request-header) and links to `Downlink` in the [HTTP Client Hints](http://httpwg.org/http-extensions/client-hints.html) draft. However, `Downlink` has since been removed from the Client Hints. ([merge](https://github.com/httpwg/http-extensions/pull/361), [commit](https://github.com/httpwg/http-extensions/commit/b8143222fbd427eb46ad51e0cb0fd79f1746075d))

Should `Downlink` be removed from the safelisted request headers; or, should the Fetch LS link to the NetInfo API ([here](http://wicg.github.io/netinfo/#-dfn-downlink-dfn-attribute))? (Although, there it is an attribute, and not a header.)

(FWIW I'm not following any of the WG draft discussion, but rather, came across this after reading then wanting to update the [MDN CORS documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).  Also, somewhat related, `Last-Event-Id` is also listed on MDN as a safelisted request header, although it still appears to be [forthcoming](https://github.com/whatwg/fetch/pull/597) in Fetch LS.)

**Comment by annevk** [comment]
Thanks!

@igrigorik thoughts?

**Comment by igrigorik** [comment]
The intent in https://github.com/httpwg/http-extensions/commit/b8143222fbd427eb46ad51e0cb0fd79f1746075d was to move the definition to NetInfo spec, but that hasn't landed, WIP: https://github.com/WICG/netinfo/issues/46. 

With Accept-CH-Lifetime landing we should be unblocked from making progress on above now. I propose we keep this open and resolve it by updating Fetch spec to point to NetInfo dfn's once that lands.

**Comment by annevk** [comment]
Merging this into #726 as Client Hints has been removed for now. That issue will work adding it back at which point we can decide how it should affect CORS.
