### ISSUE TITLE
Requests for http URLs should fail when there's no browsing context

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#69]
This should probably be a Mixed Content check in the end (the response becomes a network error because there's no browsing context to indicate the mixed content error too), but will need infrastructure from Fetch first. The exact infrastructure depends on the outcome of https://github.com/slightlyoff/ServiceWorker/issues/119 most likely.

**Comment by sleevi** [comment]
Funny, we discussed this somewhat extensively between the Chrome networking, security, and service worker teams.

Some of that conversation is captured in https://code.google.com/p/chromium/issues/detail?id=453191 or https://code.google.com/p/chromium/issues/detail?id=448672 or https://code.google.com/p/chromium/issues/detail?id=392409

The TL;DR is that we agree - if the `fetch()` cannot be directly attributed/connected to a client (which it can be in the case of a Window fetch, but at present, cannot be in the case of a Worker fetch), then we block any form of error that we might normally warn on.

@KenjiBaheux wrote all of this up from our meetings, but I see the document is restricted to Googlers. I'm tagging him in to see if there's a sanitized version of the broader discussion, but my attempt to summarize is as follows:

If the `fetch()` is on behalf of a client (and this gets back to the need to tag fetchEvents with the requesting client - https://github.com/slightlyoff/ServiceWorker/issues/119 - and if there are multiple, _at least_ the first client), then we could evaluate the fetch() in the context of that client and that clients' mixed content settings. This means that a fetch() in the case of Window is treated similar to a mixed-content XHR - uses the document/window settings re: mixed content.

If the `fetch()` is not attributable to a client (e.g. a ServiceWorker), then we block the request.

This notably breaks for situations when the SW wants to offer pass-through services, as this means any site using a SW loses the ability to have optionally-blockable content. While 'nice' on one level, this does create a new set of hurdles and inconsistencies that don't strictly seem necessary.

**Comment by sleevi** [comment]
I suppose https://code.google.com/p/chromium/issues/detail?id=392409#c48 (comments 48 - 50) is one summary (to save you wading through a huge pile of comments and back and forth)

**Comment by annevk** [comment]
@sleevi according to @mikewest in https://lists.w3.org/Archives/Public/public-webappsec/2015Jul/0075.html mixed content is simply not allowed for service workers in Chrome.

Either way I guess this is an issue for the Mixed Content standard, which can use "request's window" for determining whether any UI needs to be downgraded.

**Comment by annevk** [comment]
This got added to mixed content here: https://github.com/w3c/webappsec/commit/e577d4d5746bd33248a7dd4dbe0db515c16f20fb

**Comment by wanderview** [comment]
gecko bug to verify this: https://bugzilla.mozilla.org/show_bug.cgi?id=1187328
