### ISSUE TITLE
"Internal response" for "internal"?

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/fetch#695]
```html
<p>A <dfn export id=concept-filtered-response>filtered response</dfn> is a limited view on a
<a for=/>response</a> that is not a
<a>network error</a>. This
<a for=/>response</a> is referred to as the
<a>filtered response</a>'s associated
<dfn export id=concept-internal-response for=internal>internal response</dfn>.
```

Shouldn't the internal response be for "filtered response"?

**Comment by annevk** [comment]
Yeah, a lot of the `for` attribute was done incorrectly when converting this document to Bikeshed. I hadn't spotted this one yet.

**Comment by jakearchibald** [comment]
What's the right thing to do in this case? Any way to find all the specs that reference it so they can be updated?

**Comment by annevk** [comment]
I think we can just fix this one since I don't think specifications are appropriately layered yet around this (and the ID is fixed meaning any direct links won't be broken).
