### ISSUE TITLE
Add dialogWindow to the API

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#70]
To deal with https://github.com/slightlyoff/ServiceWorker/issues/119 we need a way to set a non-worker client on a `Request` object. I suspect we want to allow these values: null, `Client` object that represents a window, `WindowProxy` object.

In a document environment it defaults to the `WindowProxy` object of global object. In a worker environment it defaults to null. When constructing a `Request` object based on another `Request` object (as e.g. `fetch()` does) we simply copy the client.

Rather than client I think we should call this new feature `dialogWindow`, since it's not equal to https://fetch.spec.whatwg.org/#concept-request-client which is used for referrer and figuring out if the fetch originated from a service worker and such. It's sole purpose is to be the target of network-spawn dialogs.

**Comment by jakearchibald** [comment]
Would this be automatically set on `fetchEvent.request` to `fetchEvent.client`?

**Comment by annevk** [comment]
I'm not sure what that means. I would expect `fetchEvent.request.dialogWindow` to have the appropriate value. So that if you pass `fetchEvent.request` to `fetch()` it does the "right" thing by default. And if you do `fetch(fetchEvent.request, {dialogWindow: null})` you can override that.

**Comment by annevk** [comment]
This would leave worker clients solely exposed through `fetchEvent.client`. Hmm. Need to think about it a bit more.

**Comment by annevk** [comment]
Currently request has an associated client. It's null for client requests, which seems broken.

Within Fetch client is used for:
* Queuing tasks in the correct event loop.
* Adding fetches to the correct fetch registry.
* Inheriting HTTPS state.
* Determining the request does not come from a service worker. (Not all APIs set the "skip service worker flag", e.g. `fetch()` doesn't. We could change this, but see the next point for why it might not matter.)

Outside of Fetch it is used by CSP and Referrer. For these we want that the policy used is that associated with the service worker, which means client and dialog window need to be distinct things. (If @sleevi, @mikewest, and @jeisinger could confirm, that'd be great.)

I think this means that aside from client, a request also needs a concept of "dialog window". For `fetch()` we could base it on the client of the `Request` object passed in (works for documents and service workers; for others workers that would fail nicely since the passed in request's client could never be a document client). And then we would allow overriding it to null. We could also allow overriding it to a different client, but perhaps we should not do that for v1, might get a tad complicated.

Although some if that is complicated already due to `<iframe>` and `window.open()` and passing `Request` objects around. I guess we should carefully consider where the "dialog window" comes from in that case. That's the last thing that warrants some more thought.

**Comment by sleevi** [comment]
> Although some if that is complicated already due to <iframe> and window.open() and passing Request objects around. I guess we should carefully consider where the "dialog window" comes from in that case. That's the last thing that warrants some more thought.

Could you elaborate these concerns here? I'm not too up to date on the specifics here.

**Comment by annevk** [comment]
Say you have A that embeds B through an `<iframe>` or some such. You construct `Request` in B and then pass it to `fetch()` in A. Gets even quirkier with `document.domain`.

**Comment by annevk** [comment]
And once we allow `Request` to be structured cloned, I don't even… (It kind of suggests we should not take client information from the `Request` and while that would work for the document scenario, it falls flat for service workers.)

**Comment by annevk** [comment]
@abarth, @bholley, and @bzbarsky might be interested in the above multiple global scenarios.

**Comment by annevk** [comment]
Requests have an additional "dialog window" field, initially null.

`new Request()`:
* If request's client is a `Window` object, set request's dialog window to request's client.

`FetchEvent`'s `Request` objects are unadjusted. (E.g., a fetch from a window will result in a request with both its client and dialog window set to that window.)

That's the easy part. The hard part is what `new Request(someOtherRequest)` (which `fetch()` et al use underneath) does. My proposal is to simply copy the dialog window (client will be set to the "current" global as before) as long as the dialog window object is same-origin with the client object. 

This gets somewhat weird with multiple browsing contexts that can reach each other, but at least does not get cross-origin weird (document.domain and potentially structured cloning). It also does not seem that harmful since all of those windows could make the same fetch anyway and the user would be none-the-wiser. It's just fundamentally broken to have the network spawn dialogs, even though there are some use cases for it.

I'm going to specify this and try to make the specification more clear about network-spawned dialogs in general.

**Comment by annevk** [comment]
"dialog window" -> "user-interface window" (Mixed Content and other features do not necessarily show dialogs.)

**Comment by annevk** [comment]
@sleevi so when youtube.example is embedded through an `<iframe>` and uses service workers it cannot necessarily show mixed content warnings, but can show dialogs. How should we deal with that? Will it be allowed to load mixed content?

**Comment by annevk** [comment]
Per https://people.mozilla.org/~tvyas/http_parent_with_mixed_passive_https_child.html it seems like that can show mixed content warnings, it's just not obvious who caused them, but we have accepted that already.

**Comment by wanderview** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1183625
