### ISSUE TITLE
Termination's aborted flag

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#703]
While working on #702 I found that some additional global state slipped in that's a little unclear:

> Let _aborted_ be the termination's aborted flag.

Neither termination nor aborted flag is referenced in the above step, which seems problematic.

**Comment by jakearchibald** [comment]
This comes from https://fetch.spec.whatwg.org/#concept-fetch-terminate which I think predates the `AbortSignal` stuff.

I agree it's unclear. I think this is another case where you want a fetch instance in the spec.

**Comment by annevk** [comment]
Hmm, so should we pass an instance around? The only complication with that is that HTML's navigate can invoke one of the subalgorithms directly (due to manual redirects), so we'd have to give it access to the fetch somehow.

Perhaps that means storing it on request?

**Comment by jakearchibald** [comment]
Other places this is a problem:

> Let record be a new fetch record consisting of request and this instance of the fetch algorithm.

And:

> …terminate the ongoing fetch…

That one also appears in other specs:

> Terminate the ongoing fetch operated by the `XMLHttpRequest` object.

I agree that storing it on the request or creating an association makes sense.

1. Terminate the fetch associated with *request*.

And:

1. If the fetch associated with *request* was aborted…

But can't a request be used for more than one fetch?

**Comment by annevk** [comment]
The idea is that it can't, I think.

I guess the other idea we had here is that spec-level fetch would return something that would kinda be the observer thingy. Because having an instance of an algorithm doesn't make a whole lot of sense and we should probably not continue with that.

**Comment by annevk** [comment]
@noamr ended up refactoring this away with the fetch controller. \o/
