### ISSUE TITLE
Client hints difference between navigation and subresources

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#707]
@igrigorik is it intentional that for subresources we always append client hints headers and for navigation only if they're not already present?

That doesn't actually make a whole lot of sense to me, since navigation is the one where it's currently impossible for those headers to already be present...

**Comment by igrigorik** [comment]
Most recent IETF draft updates the opt-in flow. The short of it:

- Servers must [advertise Accept-CH with list of hints](http://httpwg.org/http-extensions/draft-ietf-httpbis-client-hints.html#accept-ch) they want to receive.
  - If this opt-in is present on response to navigation request, then we should emit the requested request header fields for same-origin subresources. 
- Optionally, the server can also [provide Accept-CH-Lifetime](http://httpwg.org/http-extensions/draft-ietf-httpbis-client-hints.html#rfc.section.2.2.2) to persist above preference. This means that future navigation+subresource requests should emit requested header fields. 

Sending requested header fields to 3P origins is subject to Feature Policy, the plumbing for which is WIP — see https://github.com/WICG/feature-policy/issues/129.

**Comment by yoavweiss** [comment]
Taking a cautious peek at that, it seems like that work would comprise of:
* Adding a step after step 10 in [Main Fetch](https://fetch.spec.whatwg.org/#main-fetch), which reads `Accept-CH-Lifetime` and adds it to some CH-opt-in cache
* Add definition of said cache
* Change steps 6-7 in [Fetching](https://fetch.spec.whatwg.org/#fetching) to take `Accept-CH` and/or CH-opt-in cache into consideration.
* Limit above steps to secure origins
* Limit above steps to same-origin - unless the origin is on some list of allowed origins
* Hook up FeaturePolicy and https://github.com/WICG/feature-policy/issues/129 to said list of allowed origins.
* Add all the new hints to [Client Hints list](https://fetch.spec.whatwg.org/#client-hints-list) and to the [cors-safelisted request headers](https://fetch.spec.whatwg.org/#cors-safelisted-request-header).

@annevk - does that sound about right?

**Comment by annevk** [comment]
Yeah (also tests).

**Comment by igrigorik** [comment]
@annevk let's close this and track progress in #726?

**Comment by annevk** [comment]
Sure.
