### ISSUE TITLE
Add three new client hint headers to the fetch spec: rtt, downlink, ect 

### ISSUE THREAD

**Issue by tarunban** [whatwg/fetch#720]
blink-dev discussion: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/G_rkd0yo2AM

Three new client hint headers have been proposed. These headers expose the network quality estimates to the origin servers.  These three headers ("rtt", "downlink", "ect" ) should be added to the list of existing client hints in the fetch spec.

/cc @yoavweiss @igrigorik

**Comment by igrigorik** [comment]
@tarunban let's close this and track progress in #726?

**Comment by annevk** [comment]
Closing as per above.
