### ISSUE TITLE
CORB: empty response VS erroring out

### ISSUE THREAD

**Issue by anforowicz** [whatwg/fetch#727]
In a few cases people wondered why [CORB](https://github.com/whatwg/fetch/issues/681) blocking does't result in a network error:
- @annevk [in a CORB PR](https://github.com/whatwg/fetch/pull/686#issuecomment-376790056): "Are you planning on changing the implementation to use a network error for the cases enumerated in the PR?"
- @mikewest [in a From-Origin comment](https://github.com/whatwg/fetch/issues/687#issuecomment-390555524): "CORB does not fail the load, but instead delivers a filtered response. I don't have a strong feeling about which behavior we ought to end up with, but I do think that diverging would be confusing. I'd prefer for us to align the response that's returned from both From-Origin and CORB if we're going to fold their processing model together. My intuition is that that's simpler to do by treating both as network errors"
- @youennf [in a From-Origin comment](https://github.com/whatwg/fetch/issues/687#issuecomment-390722953): "A network error seems consistent with other fetch error handling."

Based on what @csreis [wrote](https://github.com/whatwg/fetch/pull/686#issuecomment-381256391) it seems that there are no specific backcompatibility concerns here (and to change Chromium implementation we just need to do the grunt work of making sure that CORB console messages and prefetching/caching behavior are preserved in presence of CORB-induced network errors).  Let me reactivate https://crbug.com/827633 (although I am not sure what would be the timeline for working on this bug...).

**Comment by jakearchibald** [comment]
Here's the problem:

```js
fetch('https://example.com/whatever', { mode: 'no-cors' }).catch(() => {
  // This smells like a CORB-blocked resource.
});
```

The question is, this is an acceptable data leak?

**Comment by jakearchibald** [comment]
It's mostly interesting if that content changes when the user is logged in or not. But I agree that if there are a lot of cases that return network-error, then the assumption isn't as useful.

Whatever we do here, I'd like to do the same for step 8 of https://whatpr.org/fetch/560.html#main-fetch (https://github.com/whatwg/fetch/pull/560). Are you happy with that too?

**Comment by mikewest** [comment]
> Are you ok with that too?

Yup.

**Comment by jakearchibald** [comment]
Sold.

**Comment by annevk** [comment]
My plan is to close this issue when #1441 lands. Its replacement which is worked on in #1442 requires a network error.
