### ISSUE TITLE
Give examples of "deprecated authentication".

### ISSUE THREAD

**Issue by mikewest** [whatwg/fetch#73]
https://github.com/w3c/webappsec/commit/2fa9d6757123cd3e4d53a347ba8bc57437c5d292 removes the "deprecated TLS-protection" concept from MIX. It would be lovely if some of the examples from https://github.com/w3c/webappsec/commit/2fa9d6757123cd3e4d53a347ba8bc57437c5d292#diff-8dca0feb072c68e4bbf5349106c1b324L466 would make their way into Fetch to explain the "HTTPS State" concept's values a bit there.

**Comment by annevk** [comment]
So how is deprecated different from failure?

**Comment by sleevi** [comment]
Navigations vs subresources vs context, for example.

Part of this goes back to the notion of dialogWindow in https://github.com/whatwg/fetch/issues/70 / the related discussion in https://code.google.com/p/chromium/issues/detail?id=392409#c48 - if there's an associated visual context, perhaps allow it (optionally-blockable), but in non-interactive contexts (e.g. SW) block. For navigations, permitted, for subresources, blocked.

**Comment by annevk** [comment]
Thanks. Would you guys mind of we bikeshed this one more time as the terms are so confusing with "HTTP authentication"? My proposal would using these three values instead:

* "`no-https`"
* "`deprecated-https`"
* "`https`"

**Comment by mikewest** [comment]
`no-https` -> "unauthenticated"
`deprecated-https` -> "deprecated authentication"
`https` -> "authenticated"

*shrug* I guess? They don't seem significantly clearer to me, but whatever. Given that the thing is called "HTTPS State", perhaps `none`, `deprecated`, `modern` would be enough?
