### ISSUE TITLE
CORS request-header Content-Type check should be on a combined value

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#748]
In particular if there are multiple `Content-Type` headers this check should most likely fail.

This is probably best addressed after #736.

This also affects the `Headers` API... Relates to https://github.com/whatwg/mimesniff/issues/30 as well, but can probably be addressed separately as request `Content-Type` can be much stricter than response `Content-Type`...

**Comment by annevk** [comment]
I don't think this is a problem anymore as we should always combine request headers, but warrants further investigation.

**Comment by annevk** [comment]
So I think the main problem is in https://fetch.spec.whatwg.org/#concept-headers-append. If you do
```js
headers.append("Content-Type", "s".repeat(127));
headers.append("Content-Type", "s".repeat(127));
```
both calls will succeed for a `Headers` object with guard "`request-no-cors`".

@yutakahirano I guess we need to combine first into some temporary value, validate that, and only if that's okay do the append?

**Comment by yutakahirano** [comment]
sounds good.

**Comment by annevk** [comment]
Another problem is that `delete()` uses `invalid` as dummy value but that does not parse as a MIME type. I should probably only check header names there and not try anything with the value.
