### ISSUE TITLE
Port blocking: "Typical service"

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#750]
I'd like to format this column a bit better. There must be some canonical spelling for these things that can be used here.

**Comment by annevk** [comment]
Let's make this a good first issue for someone who wants to do a little research behind port numbers and more clearly document their typical services.

This is what I think is wrong with the current approach:
* Initialisms in all lowercase.
* Mention of SSL, which is TLS these days

To be clear, this concerns the table in https://fetch.spec.whatwg.org/#port-blocking.

**Comment by ricea** [comment]
I think they probably originate in an /etc/services file like this one: https://svnweb.freebsd.org/base/head/etc/services?view=markup.

The IANA names look somewhat official:
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml

**Comment by annevk** [comment]
One worry with the IANA names is that we lose some information. E.g., 465 is urd, submissions, or igmpv3lite there, but none of those captures "smtp (alternate)" as Fetch has it which is the real reason it is blocked. So maybe those should be kept as-is, but others can be updated a bit.
