### ISSUE TITLE
What does "combined value" return for a name not in the header list?

### ISSUE THREAD

**Issue by jyasskin** [whatwg/fetch#752]
> A [combined value](https://fetch.spec.whatwg.org/#concept-header-value-combined), given a name (name) and header list (list), is the values of all headers in list whose name is a byte-case-insensitive match for name, separated from each other by 0x2C 0x20, in order.

* The call in https://fetch.spec.whatwg.org/#concept-header-list-sort-and-combine only calls it for names in the header list. That'd match an "Assert: There are some values."
* The call in https://fetch.spec.whatwg.org/#dom-headers-get explicitly returns null for a non-contained name. That'd match having "combined value" return null.
* If we interpret the specification as the Javascript `[values].join(", ")`, we'd get `""` for no-values.

I'd appreciate specifying one of these so I don't accidentally write a use that's ambiguous.

**Comment by annevk** [comment]
The current setup requires you to do a contains check (which maybe we should rename to has?).

I want to add "get" to https://fetch.spec.whatwg.org/#concept-header-list that gives you null or a byte sequence, but I'm not a 100% sure if the current "combined value" definition is good enough.

In particular, I think @mnot's structured headers don't have the additional space. So:
```
Some-String-Header: "test
Some-String-Header: test"
```
ends up with `"test,test"` and not `"test, test"` as Fetch (and believe most implementations) do.

**Comment by annevk** [comment]
@domenic was also interested in this.

**Comment by mnot** [comment]
SH doesn't specify how to combine headers; HTTP does. Currently it doesn't have advice about this, but if we did enough testing, perhaps we could get some in.

SH *could* specify how to combine headers when the actual SH processor is doing it; do you think that would be useful?

**Comment by annevk** [comment]
See also #757 about us currently not excluding empty values whereas HTTP does do that. (I don't think browsers do that universally though.)

**Comment by annevk** [comment]
@mnot I don't think it makes sense for SH to define it. SH should just operate on combined values and leave combining to HTTP (or Fetch).

**Comment by annevk** [comment]
#818 has a fix for this in the form of a "get" operation.
