### ISSUE TITLE
Maybe define "payload body length"?

### ISSUE THREAD

**Issue by ricea** [whatwg/fetch#754]
https://fetch.spec.whatwg.org/commit-snapshots/2e456740b0ce4145ef2a84bcc3bb5fa2e8b1f5b5/#http-network-fetch

> If response has a payload body length

I assume that "payload body length" is intended as a reference to RFC7230, but it doesn't define that term specifically. It does define the related term "message body length" as being the length of the payload after undoing transfer decoding. Could this be clarified?

**Comment by annevk** [comment]
#1184 ended up removing this. This basically came down to parsing the `Content-Length` header, which #1183 defines and XMLHttpRequest makes use of as of https://github.com/whatwg/xhr/pull/317 (landed earlier today).

#1136 is a minor clarification follow-up.
