### ISSUE TITLE
Creating new request & response objects could be easier

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/fetch#771]
In specs, if I want to create a new request, I'm creating the request object, then creating the headers object, then hooking the two up.

With responses it's slightly more complicated, as I need to deal with the trailer promise too.

Is this worth simplifying?

**Comment by jakearchibald** [comment]
Otherwise, I need to export https://fetch.spec.whatwg.org/#concept-response-trailer-promise.

**Comment by jakearchibald** [comment]
Yeah, I mean the platform objects. I'm doing this for background fetch https://wicg.github.io/background-fetch/#create-settled-fetches-algorithm. I'm attempting a more specific description of how requests/responses come out of the cache.

**Comment by annevk** [comment]
I guess service workers and the cache API need this too in some way. Should probably take that into account too.
