### ISSUE TITLE
CORS should not be enforced on cross-origin requests where credentials is omit or same-origin

### ISSUE THREAD

**Issue by davidbarratt** [whatwg/fetch#787]
Native apps are able to make a cross-origin, credential-less requests without the need of the CORS header. Web Apps should have the ability to make credential-less requests cross-origin without requiring the origin to state that the request is allowed. Credential-less requests pose no threat to the requested server. 

Without this feature, it is more likely that a server-administrator will unknowingly add `Access-Control-Allow-Origin: *` to ALL requests (even credentialed requests), thereby creating a security vulnerability where there wasn't one before. The browser should do all of this for everyone and there isn't a good reason why it shouldn't.

Browser Bug Reports:
Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1483250
Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=874079

**Comment by annevk** [comment]
I'm sorry, but this would break the same-origin policy. See https://annevankesteren.nl/2015/02/same-origin-policy for an explanation.

You cannot really compare this to native applications as they have a different trust model.

**Comment by davidbarratt** [comment]
"We invented CORS so that Untrusted can access the contents of resources on Example (and even on Credentialed and Intranet) as long as the resource opts in."

Why does the resource need to opt-in to un-credentialed requests? That doesn't make any sense.

**Comment by annevk** [comment]
@davidbarratt local network resources, IP-authenticated resources, etc.

**Comment by davidbarratt** [comment]
@annevk so instead of making the less than 1% of sites that that applies to opt-in to a _restriction_ we'd rather the 99%+ of sites out-in to the request being _allowed_? Asking that number of sites to opt-in creates a potential security vulnerability if they use `*` with credentials? On top of that, it cripples web apps from being able to access publicly available resources without _asking_ for permission to do so.

**Comment by annevk** [comment]
There's basically no way to change the status quo here without unduly affecting end users.

**Comment by davidbarratt** [comment]
It wouldn't be the first time the web has changed the status quo without unduly affecting end users.

Let me give an example:
Suppose I want to create an RSS reader web app. It would be impossible to do that, because I'd have to ask every single site owner on the web to correctly implement CORS on their server.

So basically, it's impossible to create an web app like that (even though, it's a perfect use case for a web app).

To your point about same-origin policy... why is it that credential-less cross-origin requests are subject to the same origin policy?

**Comment by davidbarratt** [comment]
The way this could be implemented without breaking backwards-comparability is, if a request is cross-origin, credential-less, then do the preflight request (like normal) if the response does not have any `Access-Control` headers, then the request is _implicitly_ allowed. Likewise, on the _actual_ request, the headers are checked again to ensure there are no `Access-Control` headers are present. If they are present, the normal CORS / same-origin policy applies. This way, existing sites that utilize CORS correctly can continue to do so, and sites that have no implemented CORS do not have to in order for their public resources to be accessible.

**Comment by annevk** [comment]
I'm sorry, but you continue to misunderstand the same-origin policy and what it protects against. I've given an external pointer and I'm sure you can find more on your own. Suffice to say that it's not just about credentials and isn't really about CORS either (CORS was created to enable sharing of resources within the confines of the same-origin policy).

**Comment by gileswells** [comment]
I see what @davidbarratt is saying though. If it's a publicly accessible resource that can be accessed through a server-side language without credentials or any other restrictions then why is the policy such that it prevents access to these same, fully publicly available resources, through ajax calls? I feel this is more of an issue that should be opened up for discussion. Per the policy as it stands right now it's not a bug but a discussion about if the policy should be updated might be a fair use of time.

**Comment by annevk** [comment]
@davidbarratt there's no way you can phrase that question in a way users will comprehend. https://annevankesteren.nl/2015/03/public-internet-proxy has some other alternatives I've considered.

@gileswells there's no guarantee that it's publicly accessible. There's no way to tell that it is (other than using a proxy of sorts).

**Comment by davidbarratt** [comment]
"Due to the same-origin policy protecting servers behind a firewall, cross-origin HTTP came to browsers as CORS and TCP as WebSocket."

Perhaps, that's the root of the problem... I guess what I am saying is that the web browser ought not be responsible for protecting servers behind a firewall. Those servers ought to be responsible for protecting themselves.

**Comment by annevk** [comment]
Sure, but we cannot flip that at this point. It'd put hundreds of millions of people at risk.

**Comment by davidbarratt** [comment]
_[citation needed]_

That assumes that hundrds of millions of people use a site behind a firewall that has absolutely no other protections.

I have yet to see a site like that. Every intranet site I've used (at a Fortune 500 company) have not only been restricted to to the firewall, but _also_ have had some sort of employee authentication system.

I have no idea how this could be measured, but from my experience, this is a non-issue. If you allow anyone who has access to your network to have access to your intranet site, that means anyone could come into your physical location, use an open Ethernet port and take all of the data off of the intranet site... that's a huge security risk that most organizations are not going to take.

**Comment by annevk** [comment]
Your router doesn't have a site?

**Comment by annevk** [comment]
That's a fairly weak point as installing a native application is much more involved than visiting a site. Anyway, this debate has been had many times already and browsers have repeatedly pointed out they're not willing to compromise end user security here.

**Comment by davidbarratt** [comment]
Your argument is that, it's ok to sacrifice user experience, in favor a security issue that is effectively nonexistent. And that a user's web browser (a client application) is responsible for protecting a server on the local network.

And that's fine to argue that, but please let the browsers themselves make their own decision(s) instead of closing my issues.

**Comment by annevk** [comment]
Well, I don't think it's nonexistent. And yes, I do think that a browser is responsible for not regressing on its end-user security.

And furthermore, I can speak for Mozilla Firefox on this matter.

**Comment by davidbarratt** [comment]
Ah, I'm sorry, I didn't know of the association.

What I am saying, is that the odds are _greater_ that a security vulnerability is created by a server-administrator incorrectly implementing CORS, than they are of the security vulnerability of a completely open intranet site.

In my mind, you're choosing the greater vulnerability of the two. I understand that you don't agree with that, but I think it's worth considering that perhaps browsers have _already_ implemented a security regression and it would be better to _stop_ that regression.

**Comment by annevk** [comment]
I guess I should point out that `Access-Control-Allow-Origin: *` will fail for credentialed requests for the reasons you point out.

**Comment by annevk** [comment]
It sounds like you don't understand CORS. CORS only enables access, it doesn't restrict it. The same-origin policy restricts access.

**Comment by davidbarratt** [comment]
That's the discussion we are having, the default behavior is that access is _restricted_ and you have to _allow_ it with CORS.

I'm arguing that the default behavior ought to be _allowing_ the non-credentialed request, unless CORS has put a restrictions on that request. Or to put it another way: CORS would be used to _allow_ credentialed requests or _restrict_ non-credentialed requests. If you've set `Access-Control-Allow-Origin` to a fixed value of `example.com` then the change I'm proposing would not affect your site because I would not be allowed to access your domain, I would be _restricted_ by CORS. So while it's _currently_ not used as a restriction, there's nothing stopping it from being used this way.

Reversing the behavior would mean that non-credentialed public resources would become available to a web app, and that intranet sites would be responsible for their own security (as they ought to be).

**Comment by davidbarratt** [comment]
I completely understand why it is the way it is, and why you wouldn't want to change it. It makes 100% sense to me. I suppose I just don't agree with that, and that's ok. :)

I really appreciate @annevk & @sleevi taking the time to discuss this. That wasn't necessary at all, so it means a lot. I hope that my disagreement does not discourage you in the slightest. Keep up the good work. :)
