### ISSUE TITLE
It is possible to construct a Request with a used body

### ISSUE THREAD

**Issue by harrishancock** [whatwg/fetch#792]
Given some disturbed but unlocked ReadableStream `rs`, the following spec-conformant code will construct a Request object with a disturbed body:

```javascript
let rs = // a disturbed, unlocked ReadableStream
let request = new Request(url, { method: "POST", body: rs })
```

This works because Request's constructor, `Request(input, init)`, only throws if `input.body` is disturbed, but does not throw if `init.body` is disturbed.

This seems a little strange, because it means iteratively applying Request's constructor could throw upon the second invocation. An example would be in `fetch()`, which is required by the spec to pass its arguments to Request's constructor:

```javascript
// This will NOT throw, because fetch() invokes new Request(input, init).
await fetch(url, { method: "POST", body: rs })

// This WILL throw, because fetch() invokes new Request(input).
let request = new Request(url, { method: "POST", body: rs })
await fetch(request)
```

Should this be considered a bug?

**Comment by annevk** [comment]
Yeah, I think so. I wonder if we should throw when trying to extract from a disturbed/locked stream.

cc @yutakahirano

**Comment by yutakahirano** [comment]
Maybe 

> 38. If _inputBody_ is _body_ and _input_ is disturbed or locked, then throw a TypeError.

should be

> 38. If _body_ is non-null and _body_ is disturbed or locked, then throw a TypeError.


?

**Comment by harrishancock** [comment]
I think it depends on what the behavior of Response's constructor should be. Right now, it will also accept a disturbed but unlocked ReadableStream as its first parameter.

That's less of an issue, since there's no surprising case like `fetch()` for Responses. Nevertheless, if we put the check in the body extraction operation, we could remove step 38 from the Request constructor and "fix" both classes. By my reading, it shouldn't cause any problems elsewhere where a body is extracted.

I'll leave it to @yutakahirano. I'd be happy to make a PR with either solution.

**Comment by annevk** [comment]
@yutakahirano they do, both accept https://fetch.spec.whatwg.org/#bodyinit which takes a `ReadableStream`. (None of this is implemented since upload streams aren't a thing yet, but they will be at some point presumably.)

**Comment by yutakahirano** [comment]
https://fetch.spec.whatwg.org/#concept-http-redirect-fetch and https://fetch.spec.whatwg.org/#http-network-or-cache-fetch. They don't pass arguments causing exceptions, so there is no need to introduce special return values.

**Comment by annevk** [comment]
Thanks, I think I have an idea for how to solve this to your liking.
