### ISSUE TITLE
Solely matching `*`

### ISSUE THREAD

**Issue by gibson042** [whatwg/fetch#798]
https://fetch.spec.whatwg.org/commit-snapshots/3ca2ee5968a60883c9e302f296047d539337b6dd/#http-new-header-syntax

> For \`Access\-Control\-Expose\-Headers\`, \`Access\-Control\-Allow\-Methods\`, and \`Access\-Control\-Allow\-Headers\` response headers the value \`\*\` counts as a wildcard for requests without credentials\. For such requests there is no way to solely match a header name or method that is \`\*\`\.

I believe that, contrary to the quoted text, it is possible to solely match `*` values via repetition. For example:
```
Access-Control-Allow-Headers: *, *
```

**Comment by annevk** [comment]
That doesn't solely match `*` though? It matches all other names too.

**Comment by gibson042** [comment]
Ah, correct. I thought _standalone_ `*` was given special treatment as in e.g. [If-Match](https://tools.ietf.org/html/rfc7232#section-3.1), but that is not the case per https://fetch.spec.whatwg.org/#cors-preflight-fetch .
