### ISSUE TITLE
Provide more ergonomic way of setting request URL's query

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#799]
I stumbled across https://github.com/github/fetch/issues/256 today and it seems there's quite a bit of demand for a more ergonomic way of setting URL's query.

This would add some API surface, but otherwise be explained in terms of existing primitives. I'd expect we'd reuse the constructor argument from https://url.spec.whatwg.org/#interface-urlsearchparams (presumably abstract that with a typedef) and name the dictionary member `urlSearch` or `urlSearchParams`.

There's another question of what to do when the URL already has query parameters. Replacing would be somewhat more trivial to define I expect, but appending is probably what should happen.

cc @theefer @mislav

**Comment by annevk** [comment]
This is now https://github.com/whatwg/url/issues/413 based on feedback at https://twitter.com/annevk/status/1031824798312218624.

**Comment by jfirebaugh** [comment]
https://github.com/whatwg/url/issues/413 is now closed. Is this DOA? There's over 300 👍 s on https://github.com/github/fetch/issues/256#issuecomment-231558127. IMHO this is a rather glaring ergonomic issue.

**Comment by annevk** [comment]
@jfirebaugh how are libraries solving this?
```js
const url = new URL("https://geo.example.org/api");
const params = {lat:35.696233, long:139.570431};
Object.keys(params).forEach(key => url.searchParams.append(key, params[key]));
fetch(url).then(/* … */);
```
doesn't seem too bad (and got a number of updates too), but I could see you might want:
```js
fetch(new URL(url, { search: params })).then(/* … */);

// or

fetch(url, { urlSearch: params }).then(/* … */);
```
but then there would be less flexibility in how parameters get combined with those already present and we'd have to defend why query parameters get special treatment, but paths do not, etc.
