### ISSUE TITLE
"Set fallbackCredentials to "same-origin"."

### ISSUE THREAD

**Issue by aljopro** [whatwg/fetch#804]
There are two lines that seem to be at odds with each other.
By default a request should be using "omit" as the credentials mode  but in the Response Constructor, a fallback of "same-origin" should be used.

Should these two lines sync up to say the same thing?

https://fetch.spec.whatwg.org/commit-snapshots/4321ab66c7ecc73793229939eaaeb811333e6cab/#keep-alive-flag

> A request has an associated credentials mode, which is "omit", "same\-origin", or "include"\. Unless stated otherwise, it is "omit"\.

https://fetch.spec.whatwg.org/commit-snapshots/4321ab66c7ecc73793229939eaaeb811333e6cab/#request-class

> Set fallbackCredentials to "same\-origin"\.

**Comment by annevk** [comment]
Yeah, we should probably change this. The former only affects specifications that do not set credentials mode themselves, but most explicitly set it, and we've stopped using "omit" as a default for them.

**Comment by annevk** [comment]
Finally created a PR for this in #1153. Thanks @aljopro!
