### ISSUE TITLE
Add `Link` as a CORS-safelisted/simple response header?

### ISSUE THREAD

**Issue by ethanresnick** [whatwg/fetch#805]
I'm not sure if this is the right repo, or if I should be posting somewhere CORS-specifc. 

I'm also not familiar with all the history/rationale behind the current list of CORS simple response headers, so consider this a question as much as a suggestion.

But: would it make sense to have `Link` as a simple response header? I don't immediately see a security risk here, and I imagine any server sending a Link would want this data to be usable by browser clients.

**Comment by annevk** [comment]
Hi, you have found the correct place!

It should be trivial for any server to configure `Access-Control-Expose-Headers: link`, no?

I don't think we can change this, as servers that did want to keep those headers confidential, or store debug information in those headers, would end up with a security hole of sorts.

**Comment by ethanresnick** [comment]
> It should be trivial for any server to configure Access-Control-Expose-Headers: link, no?

Yes, it's reasonably trivial. And, as I think about this more, I realize the change I proposed doesn't really make sense, in that it doesn't make the platform as a whole any simpler.

I think my motivation for raising this was that having to add `Access-Control-Expose-Headers` is just one more thing for normal devs to have to know about and do as they're trying to accomplish something that seems like it should be simple/automatic. 

That's really a critique against CORS in general, though, and it's probably better solved in a more holistic way than patching some header whitelist (if it's even possible to solve at all given web compat constraints).

**Comment by annevk** [comment]
There is some hope that with https://github.com/WICG/origin-policy/ we can allow setting CORS for an entire site, so you don't have to do piecemeal configuration. You might want to follow that.
