### ISSUE TITLE
After update to 3.0.0 Webpack build is failing on line 72

### ISSUE THREAD

**Issue by belcherj** [whatwg/fetch#808]
Updating from 2.0.4 to 3.0.0 webpack is failing, see error below. I assume I need to use a different loader but wanted to raise the issue since a quick web search and perusing the issues here did not result in any others having the issue.  This method of including fetch via webpack is shared a lot in examples so there will probably be others.

In my webpack config I include fetch globally like this:

```
new webpack.ProvidePlugin( {
	fetch: 'imports-loader?this=>global!exports-loader?global.fetch!whatwg-fetch',
} ),
```

```
    ERROR in ./node_modules/whatwg-fetch/fetch.js (./node_modules/imports-loader?this=>global!./node_modules/exports-loader?global.fetch!./node_modules/whatwg-fetch/fetch.js) 72:0
    Module parse failed: 'import' and 'export' may only appear at the top level (72:0)
    You may need an appropriate loader to handle this file type.
    | }
    |
    > export function Headers(headers) {
    |   this.map = {};
    |
     @ ./plugins/wccom-plugins/geo-page-replace/assets/setup.js 1:0-79
```

**Comment by annevk** [comment]
This is not the repository you're looking for. Perthaps github/fetch? This repository defines the Fetch Standard.

**Comment by jakearchibald** [comment]
https://github.com/github/fetch is what you're looking for.

**Comment by belcherj** [comment]
Ohhh noooo, my bad.  Thanks!
