### ISSUE TITLE
Purpose of the Content-DPR hint is not entirely clear.

### ISSUE THREAD

**Issue by malchata** [whatwg/fetch#812]

**Comment by malchata** [comment]
I have personally had an especially difficult time tying the purpose and usefulness of the `Content-DPR` client hint to a specific use case, and I don't think I'm alone in this. While the spec at large is straightforward and reads well, I think `Content-DPR` could benefit from a concrete example of how it might be used by the client. Currently, the spec says the following of `Content-DPR` in [section 4](https://tools.ietf.org/html/draft-ietf-httpbis-client-hints-06#section-4):

> The client can use this information to perform additional processing on the resource - for example, calculate the appropriate intrinsic size of the image resource such that it is displayed at the correct resolution.

This seems a bit vague to me. Does Chrome act on this response header a specific way? Are implementing browsers _expected_ to? And what's a specific example where that may be the case? Does any suboptimal behavior result when DPR is _not_ confirmed with `Content-DPR`, and if so, what instances?

**Comment by eeeps** [comment]
I'll add one concrete example of this not being clear to server-implementers – my employer, Cloudinary, implemented (and still implements) `Content-DPR` incorrectly. We echo back the DPR of the client, no matter how the width of the returned resource matches up with the requested `Width`. The example in section 4 could use some fleshing-out!

Jeremey’s questions are all about describing how `Content-DPR` is actually used on the front end – I'll add that I think there should be more about how the server in the example calculated the `Content-DPR: 1` that it sends back. I assume that the resource it sent had a width of 160 pixels? That should be added to the example, along with a general formula that:

`Content-DPR` should = response resource width, in pixels ÷ ( request `Width` ÷ `request `DPR` )

**Comment by eeeps** [comment]
(also what should servers do, if they don't have both a `Width` and a `DPR`?)

**Comment by malchata** [comment]
To follow up, I'd be willing to provide documentation on how this should work, and would be willing to work with spec authors to document, should there be interest in that.

**Comment by malchata** [comment]
Closing this because the issue should be in httpwg/http-extensions, _not_ in this repo. My mistake.
