### ISSUE TITLE
clarify if internal fetch algorithm needs original URL with the fragment intact

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#84]
Currently the Request and Response .url getters are defined as:

  The url attribute's getter must return request's url, serialized with the exclude-fragment flag set. 

It would be nice to clarify that the spec doesn't actually need the fragment to be set on the Request internally either.  It may be easier for some implementations to just strip the fragment upfront.

**Comment by annevk** [comment]
Do you want the clarification for `Request` or request?

**Comment by wanderview** [comment]
uh, I guess I thought we might need it internally, so request
