### ISSUE TITLE
Remove "filesystem" URL scheme

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#846]
As far as I know there's only one implementation. Also need to add historical tests.

**Comment by M-ZubairAhmed** [comment]
hi @annevk can you please tell me more about this issue, i would like to give this a try. Thank you

**Comment by annevk** [comment]
This would require removing the three occurences of "filesystem" in the standard, along with corresponding text for the third instance.

(You can ignore "needs tests". I'm not sure how I imagined to test for this. I don't think that's actually possible.)

**Comment by M-ZubairAhmed** [comment]
thank you , will surely look into it this weekend. Also please go easy on me, i have very rarely collaborated in large public project :snail:

**Comment by domenic** [comment]
I think this could be tested, by creating a fetchable file using the Chrome-only filesystem APIs and then trying to fetch() it.

**Comment by annevk** [comment]
As a Chrome-only test? That doesn't seem like a good fit for wpt.

**Comment by domenic** [comment]
Well, we could make the test also pass if those Chrome-only APIs weren't present, I guess. Like, we'd have a historical test saying those Chrome-only APIs weren't present, then a second historical test saying "if they are present, filesystem URLs should not work".

**Comment by annevk** [comment]
Filed https://github.com/web-platform-tests/wpt/issues/15525 on that idea.
