### ISSUE TITLE
Integrate "subresource" integrity

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#85]
Now it's implemented all over, it's probably time to remove the Fetch monkey patching from SRI and make it a proper part of Fetch.

https://github.com/w3c/webappsec/issues/428 has a question for @fmarier and co that needs to be answered first. I suspect the answer is yes.

**Comment by wanderview** [comment]
gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1187335
