### ISSUE TITLE
Add support for stale-while-revalidate handling

### ISSUE THREAD

**Issue by dtapuska** [whatwg/fetch#852]
Add support for handling stale-while-revalidate handling.

Context is Chrome is wanting to [ship handling](
https://groups.google.com/a/chromium.org/d/msg/blink-dev/rspPrQHfFkI/rrhGyO4DBwAJ)

[RFC](https://tools.ietf.org/html/rfc5861)

**Comment by ziyunfei** [comment]
What about the must-revalidate directive handling, you didn't mention it in the PR. https://cs.chromium.org/chromium/src/net/http/http_response_headers.cc?type=cs&q=stale-while-revalidate&sq=package:chromium&g=0&l=1013

**Comment by annevk** [comment]
Do we have two implementers that want to add this?

cc @ddragana @youennf

**Comment by mnot** [comment]
SwR is triggered by a response `Cache-Control` directive. What's the motivation for triggering it from a fetch argument?

**Comment by dtapuska** [comment]
@ziyunfei I've added text for handling must-revalidate. Please take another look.

@mnot SwR handling is only triggered when a stale resource (which had a `Cache-Control` directive set on a previous response) is accessed and returned. So a subsequent request that accesses a stale resource needs to execute first and thus being triggered by a fetch.
