### ISSUE TITLE
Consider "extract a MIME type and compare its essence"

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#856]
I think this is an operation that many standards could use. Given a _headerList_ and a _mimeTypeEssence_:

1. Let _mimeType_ be the result of extracting a MIME type.
2. If _mimeType_ is failure, then return failure.
3. If _mimeType_'s essence is not _mimeTypeEssence_, then return failure.
4. Return _mimeType_.

E.g., https://github.com/WICG/webpackage/pull/359 by @jyasskin identifies two callers (they don't need the returned MIME type either, but some callers will need it to inspect parameters).

**Comment by jyasskin** [comment]
It's difficult to word this operation in a way that'll [=autolink=].

* If calls look like `Extract a MIME type from |headerList| and compare its essence to |essence|`, there's nowhere good to put the [==] brackets.
* If calls look like `[=Extract a MIME type and compare its essence=] from |headerList| to |essence|`, it's not very readable.

Maybe extend [Extract a MIME type](https://fetch.spec.whatwg.org/#concept-header-extract-mime-type) to take an optional "expected essence", and call it like `Let |mimeType| be the result of [=extracting a MIME type=] from |headerList| with expected essence <code>"application/essence"</code>`.

**Comment by annevk** [comment]
I'd be onboard with the extension to extract a MIME type (I'd say from X with Y, but makes sense overall).

**Comment by annevk** [comment]
I'm no longer convinced this is worth doing, especially as some callers want to allow a list of essences and such. And this is not exactly an error-prone algorithm I think.
