### ISSUE TITLE
EvalError refused to evaluate because CSP is defined to script-src set to 'self' 'unsafe-inline'

### ISSUE THREAD

**Issue by lopesdasilva** [whatwg/fetch#861]
Hi, 

I need a clarification on this:

I'm using whatwg-fetch polyfill on a server with 'strict' CSP's 
`
default-src 'none'; object-src 'self'; script-src 'self' 'unsafe-inline' ; connect-src 'self' ; img-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; frame-src 'self'`

Currently i'm getting an error loading the script (although it's a browser with fetch support)
`EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' `

![screenshot 2019-01-22 at 09 48 16](https://user-images.githubusercontent.com/1013126/51526941-5c270980-1e2b-11e9-94dc-424c9d60a4ee.png)

Thanks, 
Rui

**Comment by annevk** [comment]
Heya, you want https://github.com/github/fetch. This is the repository for the Fetch Standard.
