### ISSUE TITLE
Typo "If mimeType is falure"

### ISSUE THREAD

**Issue by alexistderking** [whatwg/fetch#866]
https://fetch.spec.whatwg.org/commit-snapshots/d219389264742ce9bb3411601f680f54a77e2f3a/#simple-header

> If mimeType is falure, then return false\. 

It should read "failure".

**Comment by annevk** [comment]
Thanks for noticing that, if signing https://participate.whatwg.org/agreement isn't a problem, then perhaps you'd like to fix it?
