### ISSUE TITLE
can body consuming be interrupted by response/body GC?

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#874]
Consider a case where we get a Response and start consuming its body in a function:

```
async function loadText(url) {
  let r = await fetch(url);
  return r.text();
}
```

This returns a promise without holding any explicit references to the response or its body.  If the body is particularly slow to load the response and body could be GC'd before it completes.

As a developer my expectation would be that the loading process would implicitly hold a strong reference to the body.  Looking at the steps here, though:

https://fetch.spec.whatwg.org/#concept-body-consume-body

I don't see where such a reference is maintained.  I'm just trying to understand the intended behavior.

**Comment by annevk** [comment]
https://fetch.spec.whatwg.org/#garbage-collection talks about some different aspects, but might help. 

But as far as I can tell, the fetch algorithm holds a reference to a response, which holds a reference to a body. How could it feed bytes into the body otherwise?

**Comment by wanderview** [comment]
Thanks.  That makes sense.
