### ISSUE TITLE
Consider allow Service Worker to pass-through the original referrer

### ISSUE THREAD

**Issue by mattto** [whatwg/fetch#89]
Filing a bug as recommended at https://github.com/slightlyoff/ServiceWorker/issues/404#issuecomment-89755099

Some SW users want to "pass-through" the original referrer, e.g., the following code wouldn't override the referrer of the original request: 
``onfetch = function(e) { e.respondWith(fetch(e.request)) }``

**Comment by annevk** [comment]
Did #80 not fix this somehow?

**Comment by mattto** [comment]
That looks perfect, I just didn't notice #80 

To be clear, the way this usecase would be solved is something like:
```javascript
onfetch = function(e) {
  r = e.request;
  e.respondWith(fetch(new Request(r.url, {method: r.method, headers: r.headers, ..., referrer: r.referrer, referrerPolicy: r.referrerPolicy));
}
```

right? And maybe copying of r.body if it exists.

**Comment by mattto** [comment]
Ah I'm wrong in the previous comment. Looks like 
```javascript
onfetch = function(e) { e.respondWith(fetch(e.request)) }
```
should just pass through the original referrer (based on https://w3c.github.io/webappsec/specs/referrer-policy/#determine-requests-referrer), unless the referrer policy is set to something that disallows that.

**Comment by annevk** [comment]
Yes, you don't need to do anything. The default copies the referrer, even for CORS CSS (where referrer would not be same-origin). However, if you have anything custom, the referrer will be "reset".
