### ISSUE TITLE
Cross-Origin-Resource-Policy shouldn't apply to browser-initiated requests (e.g. downloads)

### ISSUE THREAD

**Issue by anforowicz** [whatwg/fetch#896]
This bug is motivated by https://crbug.com/952834 where Chromium's implementation of the Cross-Origin-Resource-Policy has incorrectly applied to downloads triggered by Save-Link-As context menu.  IMO such downloads should be considered browser-initiated (since triggering them requires going through trusted browser UI [the context menu]).

Such download requests use [mode](https://fetch.spec.whatwg.org/#concept-request-mode) set to `no-cors` which makes them subject to CORP (FWIW, I don't think `navigate` mode should be used for downloads and I don't see a separate mode just for downloads).

I note that the concept of "browser-initiated" requests is not well defined in specs today (I think).  See also "[Directly User-Initiated Requests](https://mikewest.github.io/sec-metadata/#directly-user-initiated)" discussed for [`Sec-Fetch-Site: none`](https://mikewest.github.io/sec-metadata/#sec-fetch-site-header)

/cc @mikewest @annevk @youennf @johnwilander @csreis

**Comment by anforowicz** [comment]
FWIW, TIL that since Chrome 65 cross-origin <a download> are blocked (i.e. do not result in a download): https://bugs.chromium.org/p/chromium/issues/detail?id=714373

This means that (at least in Chrome?) there is no known scenario where a cross-origin download is triggered by a web initiator (other than a navigation to a `Content-Disposition: attachment` or non-renderable `Content-Type` and navigations are already exempt from CORP).  In other words, the problem indeed seems to be limited to browser-initiated downloads.

**Comment by annevk** [comment]
Why is `navigate` not the way to go? Pretty sure that's what is used for `<a download>` and such.

I agree that user-initiated downloads should not end up being restricted, as they do not end up within the attacker's reach.

**Comment by anforowicz** [comment]
Good point - thanks!  Using `navigate` also works.

Initially I wasn't sure if `navigate` should be applied to downloads / wasn't sure if downloads should be treated as navigations.  OTOH, I guess the thumbs up above indicate that this is the consensus.

I guess we can close this issue (as WontFix or something equivalent) unless anybody objects to using `navigate` mode here.
