### ISSUE TITLE
"The above steps prevent the following attack at..."

### ISSUE THREAD

**Issue by Ms2ger** [whatwg/fetch#921]
https://fetch.spec.whatwg.org/commit-snapshots/60a516da3c3c023da74a151d0970fdcb4735d94e/#main-fetch

> The above steps prevent the following attack attack

One "attack" too many.

**Comment by M-ZubairAhmed** [comment]
@annevk sorry for not informing here, but i submitted pull request for this issue here https://github.com/whatwg/fetch/pull/947
