### ISSUE TITLE
specify default accept header on cors preflight

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#922]
In https://crbug.com/995740 we have encountered a server that fails if the cors preflight options request does not have an accept header.  It seems, though, the spec does not include accept on those requests.

The default accept */* header is added in "perform a fetch" here:

https://fetch.spec.whatwg.org/#fetching

But cors preflight taps straight into "HTTP-network-or-cache fetch" further down the algorithm.

Is this intentional or an oversight in the spec?

**Comment by annevk** [comment]
Pretty sure it wasn't considered, though hard to say over a decade plus. Is the suggestion to always send `Accept: */*`?

**Comment by wanderview** [comment]
Yea, I was wondering if it should get the default of `Accept: */*`.

**Comment by annevk** [comment]
I think that's a reasonable change FWIW.

**Comment by wanderview** [comment]
This came up for chromium because we changed our CORS implementation recently.  It seems prior to M76 we sent an accept header, but starting in M76 stopped sending the accept header.

**Comment by wanderview** [comment]
Firefox Nightly seems to send `Accept: */*` on the cors preflight.

![image](https://user-images.githubusercontent.com/1256526/63435985-e2bdbc80-c3f5-11e9-90b3-a2dcace07cb9.png)

**Comment by wanderview** [comment]
Its hard to quickly check safari since it doesn't seem to expose preflights to devtools network panel.

**Comment by toyoshim** [comment]
Confirmed that Safari also send Accept: */* for the CORS preflight.
I will restore the original behavior to have the Accept in Chrome's new CORS.

**Comment by mnot** [comment]
So, browsers are going to send an extra header on every preflight, just because one server was erroneously counting on it? 

That seems like a path to bad things happening. `Accept` is completely optional in requests, and HTTP requires servers to be able to deal without it.

**Comment by toyoshim** [comment]
No. Sending the accept header was the original behavior of all UAs including chromium.

We'd just want to confirm the spec description if it reflects the actual UAs' implementation so that we can ship a brand new CORS implementaton as much compatible as possible.

Even if this is an optional one, we'd have an explit explanation to say so in the spec. Otherwise, we will receive bug reports from users continuously.

**Comment by domenic** [comment]
It's more like, browsers have always sent the header on every preflight, but until one of them tried to remove it, we didn't realize that the spec was not aligned with implementations in this regard. Now that we realize that, we're fixing the spec.

**Comment by annevk** [comment]
Not sending `Accept` in various places has been tried a couple times if I remember correctly and always ended up failing. I suspect that unfortunately servers use it as a high-level filter for clients.
