### ISSUE TITLE
Editorial: weird invocations of header list's append

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#942]
* Step 2 and step 4.2 of https://fetch.spec.whatwg.org/#cors-preflight-fetch-0
* Step 7 of https://fetch.spec.whatwg.org/#dom-response-redirect

These should all be updated to use the pair syntax we use elsewhere and not say that the header name is appended to its value in some list...

**Comment by rabbivalentino** [comment]
Rabbivalentino@gmail.com

**Comment by M-ZubairAhmed** [comment]
@annevk can i work on this one ?

**Comment by M-ZubairAhmed** [comment]
If yes, can you please tell what is pair syntax?

**Comment by annevk** [comment]
Please do. A pair is written as follows at the moment (see also the other invocations of this append):

> name/value

**Comment by annevk** [comment]
c9fa1fc68248d031e9937f79754e690a0a8909c1 and 4ad496d27170eb28b528f83f0582594c9ee6b120 fixed these.
