### ISSUE TITLE
It is hard read this section because of 4 "body"s and reassigning each other.

### ISSUE THREAD

**Issue by yoichio** [whatwg/fetch#954]
https://fetch.spec.whatwg.org/commit-snapshots/ae6435fdfd08f10833bbe65bd0ba559192baa330/#request-class

> Let inputBody be input’s request’s body if input is a Request object, and null otherwise\.
> 
> If either init\["body"\] exists and is non\-null or inputBody is non\-null, and request’s method is \`GET\` or \`HEAD\`, then throw a TypeError\.
> 
> Let body be inputBody\.
> 
> If init\["body"\] exists and is non\-null, then:​
> 
> Let Content\-Type be null\.
> 
> If init\["keepalive"\] exists and is true, then set body and Content\-Type to the result of extracting init\["body"\], with the keepalive flag set\.
> 
> Otherwise, set body and Content\-Type to the result of extracting init\["body"\]\.
> 
> If Content\-Type is non\-null and r’s headers’s header list does not contain \`Content\-Type\`, then append \`Content\-Type\`/Content\-Type to r’s headers\.
> 
> If body is non\-null and body’s source is null, then:​
> 
> If r’s request’s mode is neither "same\-origin" nor "cors", then throw a TypeError\.
> 
> Set r’s request’s use\-CORS\-preflight flag\.
> 
> If inputBody is body and input is disturbed or locked, then throw a TypeError\.
> 
> If inputBody is body and inputBody i\.\.\.

**Comment by yoichio** [comment]
How about introducing more constant variables?

**Comment by annevk** [comment]
I'm not opposed to a refactoring of this. Might also help #933.
