### ISSUE TITLE
"If init's status member is either not in the ra..."

### ISSUE THREAD

**Issue by srirama179** [whatwg/fetch#96]
https://fetch.spec.whatwg.org/#response-class

> If init's status member is either not in the range 200 to 599, inclusive, or is a null body status, throw a RangeError

Why are we not including 100-199 in valid status range (in HTTP there are 100 and 101 status codes defined)? If we include this, then we can simplify the condition and remove the "null body status" check here.

**Comment by annevk** [comment]
1xx has special semantics. It's not clear to me why we'd allow them. Also, it's not clear to me why we could remove the null body status check if we handled them.

**Comment by srirama179** [comment]
I am referring to the 2nd part of below condition
"If init's status member is either not in the range 200 to 599, inclusive, or is a null body status, throw a RangeError"
if we include 100 - 199 in valid range then we can just check if status is not in 100 - 599 range then throw RangeError.
And regarding 1xx special semantics, probably we don't need "101 - switching protocols" here but don't we need "100 - continue" incase of form submission with POST request? ofcourse this is just an additional feature where we can add "Expect" header in request and wait for server's "100 - continue" response before we actually send the request body to server. Probably this is irrelevant for this standard ?

**Comment by annevk** [comment]
Thank you for your report. I ended up fixing this in the wrong way last time and accidentally removed an important check.

I still don't think we should allow constructing responses with 1xx status codes. At least not until it's clear what the value of that would be.

Could you please check that I spelled your name correctly in the acknowledgments section?

**Comment by srirama179** [comment]
Thanks. I got it.
Name is correct.
