### ISSUE TITLE
Define Content-Type for ReadableStream.

### ISSUE THREAD

**Issue by yoichio** [whatwg/fetch#961]
https://fetch.spec.whatwg.org/commit-snapshots/7db8ac52245d6f0abaaeec6ae1cd96553c30b737/#body-mixin

> If the keepalive flag is set, then throw a TypeError\.
> 
> If object is disturbed or locked, then throw a TypeError\.
> 
> Set stream to object\.

**Comment by yutakahirano** [comment]
Can you explain your intention a bit more?

**Comment by yoichio** [comment]
W/o that, server doesn't know what's coming.

**Comment by yutakahirano** [comment]
We set _Content-Type_ only when it can be calculated from _object_. We don't set _Content-Type_ when _object_ is a BufferSource for example. Web developers are still able to specify the `content-type` request header through the request headers.

Are you suggesting to set `Content-Type` for all requests having non-null body?

**Comment by yoichio** [comment]
I see. Let me close this issue.
