### ISSUE TITLE
ResourceTiming integration question: how to handle iframes

### ISSUE THREAD

**Issue by npm1** [whatwg/fetch#968]
After https://github.com/whatwg/fetch/pull/955, we'll have integrated the TAO check with Fetch... somewhat. We noticed that iframes are fetched in navigation mode, so the CORS-specific flags (response tainting, tainted origin flag) will not be present when redirects occur. Any thoughts on how to deal with this problem? @yoavweiss @yutakahirano

**Comment by domfarolino** [comment]
It does seem that the response tainting will always be "basic" for requests with the "navigate" mode I think. But for A -> B -> !B requests, doesn't the tainted origin flag still get set regardless of the mode, or even response tainting? I think setting it only considers the request's origin, current URL, and location URL.

**Comment by annevk** [comment]
@npm1 what kind of information is exposed to the parent about frame navigations? Can you point me to the existing processing model?

**Comment by yoavweiss** [comment]
> @npm1 what kind of information is exposed to the parent about frame navigations?

Essentially, a ResourceTiming Entry. 
Assuming the frame was created by "process the {i,}frame attributes" and response doesn't include TAO, the following information is exposed:
* resolved URL (pre-redirect)
* workerStart
* startTime
* initiatorType
* fetchStart
* responseEnd

> Can you point me to the existing processing model?

https://w3c.github.io/resource-timing/#processing-model

**Comment by annevk** [comment]
So frame navigations are weird. I guess I'd expect some integration with HTML's navigate algorithm for this and it basically does the relevant security check and fill in the relevant details. I'm not entirely sure whether redirects are to be taken into account here. They're not always with navigations currently, but that is a weak point and not necessarily great precedent for new features.

**Comment by annevk** [comment]
I looked at this again and I think Fetch does all the right things here. @npm1 could you explain why you think those bits are not set for navigations?

**Comment by npm1** [comment]
Hmm I don't recall what was the problem we saw. From looking into this, I do see a problem with the `timing allow passed flag` that I added. It's only set on the main fetch in a place where it would never be set for iframe fetches. I think it should be moved to HTTP fetch, where the TAO check is called. Then it should be set even for iframe fetches, I think.

**Comment by annevk** [comment]
Why would it not be set for "iframe fetches" (i.e., navigations) though? They go through main fetch (sometimes from HTTP-redirect fetch, but they all go through there, afaik).

**Comment by npm1** [comment]
Don't they go into step 5 of main fetch, and directly go into scheme fetch because the request mode is "navigate"?

**Comment by npm1** [comment]
Ah never mind, I misread it.
