### ISSUE TITLE
206/304 handling broken?

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#97]
@mnot, at some point you mentioned the handling of 304 was broken. Presumably that also applies to 206, which is not really handled at all at the moment. Could you elaborate on that or point to where we discussed this?

**Comment by mnot** [comment]
Yep, deep underwater with other things right now, but this is still on my list. Will find it.

**Comment by annevk** [comment]
https://lists.w3.org/Archives/Public/public-webappsec/2015Apr/thread.html#msg74 has the discussion. https://code.google.com/p/chromium/issues/detail?id=520565 is a related(?) Chrome bug.

**Comment by annevk** [comment]
@mnot are you still planning on providing a PR for this or would it be better if I worked on this?

**Comment by mnot** [comment]
@annevk yeah. If I don't get to it by Japan, drinks are on me.
