### ISSUE TITLE
allow to pass a ReadableStream as Request Body

### ISSUE THREAD

**Issue by ccwienk** [whatwg/fetch#978]
# Motivation

I would like to be able to pass a stream as body to a HTTP request sent via fetch-API. In particular, I would like to send some metadata (serialised JSON), followed by some file contents (octet-stream) specified via `<input/>` in a single HTTP request.

# My Investigations so far

I found out by trial-and-error and reading documentation that it is possible to pass a file descriptor as returned from `<input/>`'s `files` attribute as request body. So I figured it should be possible to also pass a ReadableStream. If this were possible, one could construct a ReadableStream, that first returns chunks from e.g. the afforementioned file descriptor, followed by other contents.

However, when trying this (against a http server I setup for testing purposes), passing a ReadableStream would result in a string representation of the passed stream object's name (as opposed to its contents) would be sent.

# Proposal

Allow passing of ReadableStream objects. Maybe, support passing a list of streams, or a list of objects, which would then be concatenated.

**Comment by annevk** [comment]
This is mostly done already specification-wise, though there's some remaining issues (labeled with one or two of the streams labels).

**Comment by ccwienk** [comment]
@annevk : is there any way for me to tell when the implementation will arrive at, e.g. firefox(/spidermonkey) or chrome (/v8)?

**Comment by ricea** [comment]
@ccwienk You can star https://bugs.chromium.org/p/chromium/issues/detail?id=688906 to track the progress of implementation in Chrome.

For Firefox it looks like the correct issue is https://bugzilla.mozilla.org/show_bug.cgi?id=1387483.
