### ISSUE TITLE
Have CORP check rely on request's response tainting rather than request's mode

### ISSUE THREAD

**Issue by yutakahirano** [whatwg/fetch#985]
Brought up at https://chromium-review.googlesource.com/c/chromium/src/+/1971810, related with https://github.com/w3c/ServiceWorker/issues/1490.

We would like to run [the CORP check](https://fetch.spec.whatwg.org/#cross-origin-resource-policy-check) in CacheStorage for COEP (https://github.com/w3c/ServiceWorker/issues/1490), but currently the CORP check relies on the request mode which is not directly accessible there. [request's response tainting](https://fetch.spec.whatwg.org/#concept-request-response-tainting) is stored as [response type](https://fetch.spec.whatwg.org/#concept-response-type) and we can use it. What do you think about changing the first item as follows?

If _request_'s response tainting is not "opaque", then return __allowed__.

In the CacheStorage spec, we will restore a _request_ for the CORP check as follows:

 - Let _request_ be a new request.
 - Set _request_'s URL to the given URL.
 - Set _request_'s origin to the current realm's origin
 - Set _request_'s response tainting to 
   - "basic" if _response_'s type is "basic", "default" or "opaqueredirect"
   - "opaque" if _response_'s type is "opaque"
   - "cors" if _response_'s type is "cors"

@ArthurSonzogni @wanderview @annevk

**Comment by annevk** [comment]
Given the check the only caller does today is

> If httpRequest’s response tainting is not "cors"

per https://fetch.spec.whatwg.org/#ref-for-cross-origin-resource-policy-check perhaps that initial step

> If request’s mode is not "no-cors", then return allowed.

is even redundant?

I think we should investigate how this should change together with the change to enforce this for a service worker response.

**Comment by yutakahirano** [comment]
Yes, that is a possible approach. Do you think it's better?

Regarding the service worker response, [it](https://mikewest.github.io/corpp/#integration-sw) is now part of https://github.com/mikewest/corpp.

**Comment by annevk** [comment]
I think I would prefer putting all the checks in Fetch, if possible (Fetch gets the response from the service worker and can do it, after all), rather than putting security checks in Service Workers for this.

**Comment by yutakahirano** [comment]
I prefer running a CORP check in cache.match(https://github.com/w3c/ServiceWorker/issues/1490), which means calling it from the SW spec.

**Comment by annevk** [comment]
Fair, I guess that would be the exception, but I don't think we need it for `respondWith()`.

**Comment by wanderview** [comment]
Why not in `respondWith()`?  It seems like the loading page could require CORP while the service worker itself does not.  No?
