### ISSUE TITLE
fetch with request mode as no-cors is causing strict cross origin resource accessable

### ISSUE THREAD

**Issue by naveento** [whatwg/fetch#994]
i am using spring boot with cross origin configured for path "/getData" at "http://localhost:8080" as below
```
registry.addMapping("/getData")
	    .allowedOrigins("http://localhost:4000")
           .allowedHeaders("POST, GET, OPTIONS, DELETE");
```

if i try `fetch("http://localhost:8080/getData",{mode:'no-cors'}) ` from "http://localhost:9090".
i am able to access resources. is it intended behaviour or some issue?

**Comment by annevk** [comment]
Please define "access". What does `response.type` say?

**Comment by naveento** [comment]
![cors](https://user-images.githubusercontent.com/30177043/72659819-9b127f80-39eb-11ea-9a1f-f452ab14365e.png)

Response type="opaque"

**Comment by annevk** [comment]
Then it's working as designed. There shouldn't be a warning since it might be legitimate resource.
