### ISSUE TITLE
IE 11 vs preProcessedHeaders.split(/\r?\n/)

### ISSUE THREAD

**Issue by pierremanceaux** [whatwg/fetch#995]
Hello devs, and thank you for this great polyfill.

I am facing a strange bug in IE 11 (on Browserstack, no access to and old Windows system).

In short, the behaviour of [preProcessedHeaders.split(/\r?\n/).forEach(...)](https://github.com/github/fetch/blob/master/fetch.js#L373) seem to be inconsistent between for instance Chrome's last version (my reference point) and IE11 on Browserstack.

**IE 11** -> Incorrect
![image](https://user-images.githubusercontent.com/4114535/72547076-32f95780-388c-11ea-91a2-7bbba7578442.png)

**Chrome** -> Correct
![image](https://user-images.githubusercontent.com/4114535/72547173-66d47d00-388c-11ea-9415-e46c0d4842c4.png)

Meaning that the polyfill simply doesn't work for me on IE 11.

If you want to try yourself assuming you have an access to an IE 11 browser:
```
'preProcessedHeaders'.split(/\r?\n/)
'preProcessedHeaders\n'.split(/\r?\n/)
'preProcessedHeaders\r'.split(/\r?\n/)
'preProcessedHeaders\r\n'.split(/\r?\n/)
```

Is anyone able to reproduce this?

Thank you for your time in advance.

**Note**
Polyfill version: 3.0.0
Here is the IE11 build I tested with:
![image](https://user-images.githubusercontent.com/4114535/72547459-fda13980-388c-11ea-848a-d590a52f9a86.png)

**Comment by annevk** [comment]
Why did you move it from github/fetch? That's a polyfill, this is the Fetch Standard repository.

**Comment by pierremanceaux** [comment]
Friday, I think I'm a little tired. Just reopened the other one and closing that one. Really sorry for the noise here!
