### ISSUE TITLE
Cookies not sent across origins with credentials: 'include' and Content-Type: application/json

### ISSUE THREAD

**Issue by mshindal** [whatwg/fetch#997]
When I don't include the `Content-Type` header, cookies are sent:

```js
await fetch('https://localhost:44348/api/test', { credentials: 'include', method: 'POST' })
```

But when I specify the header, the cookies aren't sent:

```js
await fetch('https://localhost:44348/api/test', { credentials: 'include', method: 'POST', headers: { 'Content-Type': 'application/json' } })
```

Why is this?

**Comment by annevk** [comment]
Are you asking about the preflight or the actual request?

**Comment by mshindal** [comment]
I'm not seeing this happen anymore - I think I might have been looking at the preflight request. Closing.
